src/browser/installations.js, src/messages.js, src/reporters/index.js, src/runner/bootstrapper.js, src/runner/index.js, src/utils/fallback-default.js, test/server/.eslintrc, test/server/browser-connection-test.js, test/server/runner-test.js
/cc @churkin @AlexanderMoskovkin 
@VasilyStrelyaev Please, check spelling in strings.
=> Runner tests. Fix some edge cases with the browsers bootsrapping.

src/client/.eslintrc, test/server/.eslintrc
\cc @churkin @AlexanderMoskovkin
=> Remove unnecessary "extends" from the .eslintrc files

src/compiler/index.js, src/runner/bootstrapper.js
\cc @AlexanderMoskovkin @kirovboris
=> Get rid of await* (fixes #30)

src/browser-connection/commands.js, src/messages.js, src/runner/bootstrapper.js, src/runner/test-run/commands.js, test/server/runner-test.js
\cc @AlexanderMoskovkin @churkin
=> Fallback to the "spec" reporter if the reporter was not specified (fixes #20)

src/browser-connection/index.js, src/runner/browser-job.js, src/runner/task.js, src/utils/array.js, test/server/browser-connection-test.js
In general it's the implementation of the last proposal in the #33 with some simplification.
=> New task completion and abortion mechanism (fixes #33).

src/formatters/diffs/array.js, src/formatters/diffs/date.js, src/formatters/diffs/index.js, src/formatters/diffs/object.js, src/formatters/diffs/string.js, src/formatters/diffs/truncate-diff.js, test/server/diffs-test.js
=> Diff calculator for the formatter

.eslintrc, package.json, src/reporters/minimal.js, src/reporters/xunit.js, src/runner/browser-job.js
=> Switch to eslint 1.2.0 (closes #29)

package.json
=> Update babel-eslint (#43 follow up)

src/client/browser/idle-page/index.js, src/client/browser/index.js
After the #66 issue was closed I've found a problem on the idle-page script. I've fixed it here
/cc @inikulin @helen-dikareva
=> Stop requests to the server before redirect from the idle-page

src/client/browser/idle-page/index.js
According to the https://github.com/superroma/testcafe-phoenix/pull/73#issuecomment-142292434
=> Idle page script fixed

Gulpfile.js, package.json, test/report-design-viewer/.eslintrc, test/report-design-viewer/errors.js, test/report-design-viewer/index.js
according to #68
I added gulp task ```error-message-lister```.
\cc @inikulin @VasilyStrelyaev
=> Error message lister

Gulpfile.js, src/utils/word-wrap.js
=> Fix broken word wrapping in reporters in Windows TTY (closes #87)

src/browser-connection/index.js, src/browser-connection/local.js, src/reporters/base.js, src/reporters/minimal.js, src/reporters/xunit.js, src/runner/bootstrapper.js, test/server/browser-connection-test.js, test/server/runner-test.js
=> Get rid of class properties (closes #37)

src/browser-connection/gateway.js
=> Prevent caching of heartbeat and connection routes (closes #98)

src/reporters/errors/decorators/plain-text.js, src/reporters/errors/decorators/tty.js, src/reporters/errors/templates.js, src/reporters/list.js, src/reporters/minimal.js, src/reporters/spec.js, test/server/data/expected-reports/list, test/server/data/expected-reports/minimal, test/server/data/expected-reports/spec
\cc @AlexanderMoskovkin @kirovboris
=> Implement coloring for TTY reporter (closes #68 for now)

src/client/core/transport.js, src/client/runner/api/actions.js, src/runner/test-run/index.js
We have no unit tests for this but it will be tested in DXperience demos tests and in functional tests (https://github.com/superroma/testcafe-phoenix/issues/52, https://github.com/superroma/testcafe-phoenix/issues/76)
/cc @inikulin @helen-dikareva
=> Fix DXperience demos tests (according to #55)

src/browser-connection/local.js, src/runner/bootstrapper.js, src/runner/index.js, test/server/runner-test.js
=> Make TestRunner wait while browsers are not closed (closes #123)

src/client/runner/step-iterator.js
Regression functional test was added in minor version. We'll move it with others functional test.
=> check expected browser dialogs only before start new step (close #140)

src/client/runner/automation/playback/click.js, test/client/fixtures/runner/automation/regression-test.js
Mechanism implemented in testcafe hammerhead https://github.com/superroma/testcafe-hammerhead/pull/49
Bug fixed in IE and corresponding test added
=> Active window watching mechanism implemented (close #134)

src/client/core/utils/style.js, test/client/fixtures/runner/api/click-test.js
=> Document elements with overflow hidden are considered non-scrollable (close #144)

src/reporters/errors/decorators/plain-text.js, src/reporters/errors/decorators/tty.js, src/reporters/errors/templates.js, test/report-design-viewer/errors.js, test/server/data/expected-test-errors/empty-iframe-argument, test/server/data/expected-test-errors/iframe-argument-is-not-iframe, test/server/data/expected-test-errors/incorrect-iframe-argument, test/server/data/expected-test-errors/multiple-iframe-argument, test/server/data/expected-test-errors/wait-for-action-timeout-exceeded, test/server/error-formatter-test.js
/cc @inikulin @AlexanderMoskovkin 
Now it's looking:
=> Don't escape step code strings (closes #100)

src/client/core/utils/dom.js, src/client/runner/iframe-dispatcher.js, src/client/runner/runner-base.js, test/client/data/dom-utils/iframe.html, test/client/fixtures/core/dom-utils-test.js
=> Add isIFrameWindowInDOM function (closes #136)

src/client/core/utils/dom.js, test/client/fixtures/runner/api/assertions-test.js, test/client/fixtures/runner/api/click-test.js, test/client/fixtures/runner/automation/select-element-test.js
=> HTML content is escaped before it is sent to the server (close #127)

src/cli/argument-parser.js, src/cli/index.js, src/client/browser/index.js, test/server/cli-argument-parser-test.js
=> Minor changes to the CLI API. Implement correct comparison of URLs in client browser code (fixes #126)

README.md
=> Finish the repo transfer (closes #171)

src/client/core/utils/dom.js, src/client/runner/automation/playback/key-press-simulator.js, test/client/fixtures/runner/automation/tab-emulation-test.js
=> Fixed 'find next focusable' mechanism (closes #139)

src/client/core/utils/dom.js, src/client/runner/automation/playback/move.js, test/client/fixtures/runner/automation/regression-test.js
=> Save lastHoveredElement between move actions (closes #137)

test/server/runner-test.js
=> Improve mock for Task termination tests (closes #178)

src/client/test-run/index.js.mustache
=> Check if the progress panel exists when TEST_FAILED_EVENT fires (close #180)

Gulpfile.js, test/client/data/dom-utils/iframe.html, test/client/data/runner/iframe.html, test/client/fixtures/core/dom-utils-test.js
=> Fixed QUnit in IE9 (closes #111)

src/client/ui/styles.less
Discovered in [T310776](https://isc.devexpress.com/Thread/WorkplaceDetails/T310776).
=> Prevent cascading 'overflow' CSS for ShadowUI

src/client/runner/runner.js, test/client/fixtures/runner/runner-test.js
=> Step name is escaped before it is sent to server (close #160)

Gulpfile.js
=> Add OSX Firefox and Chrome to the build matrix

.travis.yml
=> Restore the nodejs "stable" version in the .travis.yml (closes #154)

package.json
=> Module name in package.json (closes #204)

package.json
/cc @inikulin @AlexanderMoskovkin 
For the installation testcafe as github dependency, we need have as well filled "version" field.
=> Module version in package.json

package.json
/cc @AlexanderMoskovkin  @inikulin
=> Move to testcafe-hammerhead v.3.x.x (close #209)

package.json, src/browser-connection/command.js, src/browser-connection/index.js, src/browser-connection/local.js, src/client/browser/idle-page/index.js, src/client/browser/index.js, src/runner/bootstrapper.js, src/runner/browser-set.js, src/runner/index.js, test/server/runner-test.js
=> Refactored monitoring of browser connections (closes #131)

src/compiler/index.js, src/compiler/legacy/ast.js, src/compiler/legacy/compiler.js, src/compiler/utils/read-source-file.js
=> Replace the BOM symbol when reading a file (closes #212)

Gulpfile.js, src/client/ui/select-element.js, test/client/fixtures/runner/api/wait-test.js, test/client/fixtures/runner/automation/regression-test.js, test/client/fixtures/runner/automation/select-element-test.js, test/client/fixtures/runner/xhr-test.js
=> Fixed QUnit on Android (closes #112)

test/server/browser-connection-test.js, test/server/cli-argument-parser-test.js, test/server/create-testcafe-test.js, test/server/legacy-compiler-adapter-test.js, test/server/runner-test.js
=> Refactor async server tests that uses Promises (closes #208)

src/browser-connection/index.js, src/browser-connection/local.js, src/runner/browser-set.js, src/runner/index.js, test/server/browser-connection-test.js, test/server/runner-test.js
=> Use Error objects when emitting events (closes #211)

src/client/runner/automation/playback/type.js
=> Fix Qunit tests for latest Google Chrome (close #217)

src/client/ui/progress-panel/index.js
after merge PR https://github.com/DevExpress/testcafe/pull/218 some ASPxperience tests was failed
this fix was tested on farm and it solved all problems
=> ASPxperience tests fixed

package.json, src/reporter/plugin-host.js
=> #231 follow up

src/client/ui/select-element.js, test/client/fixtures/runner/automation/select-element-test.js
=> Set selectedIndex before simulating 'change' in IE (closes #234)

Gulpfile.js, src/client/core/utils/dom.js, src/client/runner/automation/playback/click.js, src/client/runner/automation/playback/key-press-simulator.js, src/client/runner/automation/playback/move.js, test/client/fixtures/core/dom-utils-test.js, test/client/fixtures/runner/api/drag-test.js, test/client/fixtures/runner/automation/automation-test.js, test/client/fixtures/runner/automation/regression-test.js, test/client/fixtures/runner/automation/select-element-test.js, test/client/fixtures/runner/automation/submit-on-enter-test.js, test/client/fixtures/runner/content-editable/select-and-type-content-editable-test/index-test.js, test/client/fixtures/runner/detection-element-after-events-simulation-test.js
=> Fix QUnit tests in iOS browsers (close #113)

src/runner/browser-job.js
\CC @inikulin, @AlexanderMoskovkin
PR
=> Fixed problem with running in quarantine mode (closes#236)

Gulpfile.js, package.json, test/functional/.eslintrc, test/functional/config.js, test/functional/fixtures/runner/api/click/click-test.js, test/functional/fixtures/runner/api/click/click.test.js, test/functional/fixtures/runner/api/click/index.html, test/functional/fixtures/test_config.json, test/functional/get-test-error.js, test/functional/setup.js, test/functional/site/index.js, test/functional/site/server.js
=> Functional harness implemented (#52)

src/client/runner/automation/playback/scroll.js
=> fix unstable tests in IOS

src/browser-connection/index.js
=> Emit 'idle' on status request (closes #253)

Gulpfile.js, test/client/fixtures/runner/api/click-test.js
=> Disable strict mode for Babel transform (closes #258)

src/client/runner/api/actions.js, src/client/runner/automation/playback/click.js
=> Get rid of ERROR_TYPE dependency in the click automation

src/reporter/errors/category.js, src/reporter/errors/templates.js, test/server/data/expected-test-errors/empty-iframe-argument, test/server/data/expected-test-errors/iframe-argument-is-not-iframe, test/server/data/expected-test-errors/incorrect-iframe-argument, test/server/data/expected-test-errors/multiple-iframe-argument, test/server/error-formatter-test.js
=> Remove related source code from inIFrame errors (closes #255)

src/client/runner/step-iterator.js, src/reporter/errors/templates.js, src/reporter/errors/type.js, test/client/fixtures/runner/step-iterator-test.js, test/server/data/expected-test-errors/global-wait-for-action-timeout-exceed, test/server/data/expected-test-errors/incorrect-global-wait-for-action-event-argument, test/server/data/expected-test-errors/incorrect-global-wait-for-action-timeout-argument, test/server/error-formatter-test.js
\cc @inikulin, @AlexanderMoskovkin, @VasilyStrelyaev
PR
=> Added __waitFor action error types (closes #257)

src/runner/browser-set.js
\cc @inikulin, @AlexanderMoskovkin, @VasilyStrelyaev, @AndreyBelym 
PR
=> Fixed '_waitIdle' method for browser set (closes #271)

src/client/runner/step-iterator.js
=> Fix misprinted 'this' in StepIterator (closes #278)

src/runner/index.js, test/server/runner-test.js
\cc @AlexanderMoskovkin @kirovboris 
\cc @VasilyStrelyaev  - please, check comments and strings
=> Implement 'cancel' method for result of runner.run() (closes #270)

package.json, src/client/core/index.js, src/client/core/utils/dom.js, src/client/core/utils/position.js, src/client/runner/automation/cursor.js, src/client/runner/automation/iframe-behavior.js, src/client/runner/automation/playback/move.js, src/client/runner/automation/playback/scroll.js, src/client/runner/index.js, src/client/runner/runner-base.js, src/client/test-run/index.js.mustache, src/client/ui/index.js, src/runner/test-run/index.js, test/client/before-test.js, test/client/fixtures/runner/action-barrier-test.js, test/client/fixtures/runner/api/press-test.js, test/client/fixtures/runner/runner-base-test.js
=> Update hammerhead to v5.0.0

Gulpfile.js
=> Use writeFileSync in the 'update-greenkeeper' gulp task (closes #315)

package.json
=> Update version to 0.0.11

docs/articles/documentation/using-testcafe/common-concepts/browser-aliases.md, docs/articles/documentation/using-testcafe/common-concepts/index.md, docs/nav/nav-menu.yml
=> Docs: Browser Aliases topic added

src/cli/remotes-wizard.js
/cc @VasilyStrelyaev @inikulin
=> Wizard text changed

src/client/core/transport.js, src/client/runner/iframe-dispatcher.js, src/client/runner/iframe-runner.js, src/client/runner/runner-base.js, src/client/runner/runner.js, src/client/runner/test-context-storage.js, src/client/test-run/iframe.js.mustache, src/client/test-run/index.js.mustache, src/legacy/test-run/command.js, src/legacy/test-run/index.js, test/client/data/runner/iframe.html, test/client/fixtures/runner/cross-domain/in-iframe-test.js, test/client/fixtures/runner/cross-domain/run-test.js, test/client/fixtures/runner/runner-base-test.js
=> Use HTML5 Storage for test variables (closes  #279)

.markdownlint.json, docs/articles/documentation/index.md, docs/articles/documentation/using-testcafe/index.md, docs/articles/documentation/using-testcafe/programming-interface/BrowserConnection.md, docs/articles/documentation/using-testcafe/programming-interface/Runner.md, docs/articles/documentation/using-testcafe/programming-interface/TestCafe.md, docs/articles/documentation/using-testcafe/programming-interface/createTestCafe.md, docs/articles/documentation/using-testcafe/programming-interface/index.md, docs/nav/nav-menu.yml
fixes #286
\cc @DevExpress/testcafe
=> Docs: Introduce TestCafe programming interface reference (ex CI API)

docs/articles/documentation/using-testcafe/command-line-interface.md, docs/articles/documentation/using-testcafe/index.md, docs/nav/nav-menu.yml
/cc @VasilyStrelyaev  @inikulin
=> Docs: CLI topic added

src/client/runner/api/actions.js
=> Fixed upload method for correct displaying file names in error message (closes #336)

Gulpfile.js, src/client/runner/api/actions.js, src/client/runner/automation/automation.js, src/client/runner/automation/options/click.js, src/client/runner/automation/playback/click.js, src/client/runner/automation/playback/dblclick.js, src/client/runner/automation/playback/rclick.js, src/client/runner/automation/util.js, test/client/fixtures/runner/api/click-test.js, test/client/fixtures/runner/api/press-test.js, test/client/fixtures/runner/automation/out-of-bounds-test.js
/cc @AlexanderMoskovkin @AndreyBelym 
@MargaritaLoseva please help with comment: https://github.com/helen-dikareva/testcafe-phoenix/commit/3526257d02f8d3cbb520413fcfb9863570eaecb5#diff-5b7bb7364f1a533c7d2d73407a451457R352
=> RClick automation refactoring (#239)

.travis.yml
=> Tell Travis to do not build pushes in greenkeeper branches

Gulpfile.js, src/client/runner/api/actions.js, src/client/runner/automation/automation.js, src/client/runner/automation/playback/hover.js, test/client/fixtures/runner/automation/real-actions-blocker-test.js, test/client/fixtures/runner/automation/regression-test.js
=> Hover automation refactoring (#239)

src/client/runner/runner.js, src/client/runner/test-context-storage.js, test/functional/fixtures/.eslintrc, test/functional/fixtures/runner/browser-dialogs/before-unload-dialog-test.js, test/functional/fixtures/runner/browser-dialogs/before-unload-dialog.test.js, test/functional/fixtures/runner/browser-dialogs/index.html, test/functional/fixtures/runner/browser-dialogs/test_config.json
\cc @inikulin @AlexanderMoskovkin @georgiy-abbasov
=> Fix error handling on beforeunload (closes #329)

src/browser-connection/index.js, test/functional/.eslintrc, test/functional/fixtures/quarantine-mode/fails-by-request.html, test/functional/fixtures/quarantine-mode/index-test.js, test/functional/fixtures/quarantine-mode/index.test.js, test/functional/setup.js
=> Fix quarantine mode (closes #328)

package.json, src/client/runner/runner-base.js, src/client/runner/step-iterator.js, test/client/fixtures/runner/api/press-test.js
=> hammerhead version updated (closes #349)

test/functional/fixtures/.eslintrc, test/functional/fixtures/runner/using-shared-code/cross-domain.html, test/functional/fixtures/runner/using-shared-code/index.html, test/functional/fixtures/runner/using-shared-code/inline.html, test/functional/fixtures/runner/using-shared-code/mixin.js, test/functional/fixtures/runner/using-shared-code/module.js, test/functional/fixtures/runner/using-shared-code/same-domain.html, test/functional/fixtures/runner/using-shared-code/shared-code-test.js, test/functional/fixtures/runner/using-shared-code/shared-code.test.js, test/functional/fixtures/runner/using-shared-code/test_config.json
=> Functional tests for shared code use added (closes #294)

.markdownlint.json, docs/articles/documentation/using-testcafe/command-line-interface.md, docs/articles/documentation/using-testcafe/common-concepts/browser-aliases.md, docs/articles/documentation/using-testcafe/programming-interface/BrowserConnection.md, docs/articles/documentation/using-testcafe/programming-interface/Runner.md, docs/articles/documentation/using-testcafe/programming-interface/TestCafe.md
=> Docs: remove manually added anchors from headers (#312)

test/functional/fixtures/quarantine-mode/index-test.js, test/functional/fixtures/quarantine-mode/pages/page-failing-quarantine.html, test/functional/fixtures/quarantine-mode/pages/page-passing-quarantine.html, test/functional/fixtures/quarantine-mode/testcafe-fixtures/failing-quarantine.test.js, test/functional/fixtures/quarantine-mode/testcafe-fixtures/passing-quarantine.test.js, test/functional/quarantine-mode-tracker.js, test/functional/site/server.js
=> Refactored quarantine mode tests (closes #358)

src/client/runner/runner-base.js, src/legacy/test-run-error/templates.js, test/functional/fixtures/uncaught-js-errors/test.js, test/server/error-formatter-test.js
=> Fix destination URL in uncaught JS error reports (fixes #388)

src/client/runner/api/actions.js
For fix tests I just replaced (https://github.com/DevExpress/testcafe/pull/396/files#diff-27aea5773c389e89e84c3a8e9953640dR448)
```
new iframe.contentWindow[automation.AUTOMATION_RUNNERS].ClickAutomation(element, clickOptions) :
```
to
```
new iframe.contentWindow[AUTOMATIONS].ClickAutomation(element, clickOptions) :
```
I didn't refactor actions.js, but I added this file in 'lint-client' and fixed all ESlint error in it.
\cc @AlexanderMoskovkin
=> fix ASPxperienceDemos (close #395)

Gulpfile.js, src/client/runner/api/actions.js, src/client/runner/automation/automation.js, src/client/runner/automation/playback/dblclick.js, test/client/fixtures/runner/automation/automation-test.js, test/client/fixtures/runner/automation/out-of-bounds-test.js, test/client/fixtures/runner/automation/regression-test.js, test/client/fixtures/runner/automation/select-element-test.js
\cc @AlexanderMoskovkin @AndreyBelym 
Dbl click uses click automation, but click wait for new version of Hammerhead (coming soon). It'll not be a problem refactor click after this PR.
=> Dblclick automation refactoring (#239)

test/functional/fixtures/api/regression/gh-399/pages/iframe.html, test/functional/fixtures/api/regression/gh-399/pages/index.html, test/functional/fixtures/api/regression/gh-399/test.js, test/functional/fixtures/api/regression/gh-399/testcafe-fixtures/index.test.js, test/functional/fixtures/api/regression/gh-399/testcafe-fixtures/test_config.json
/cc @georgiy-abbasov @churkin @VasilyStrelyaev
=> gh-399 test added (closes #399)

package.json, src/legacy/test-run-error/templates.js, src/reporter/plugin-host.js
=> Use less colorful styles for errors. Bump version

docs/articles/documentation/using-testcafe/command-line-interface.md
=> -v option added

src/client/runner/automation/playback/move.js, src/client/runner/runner-base.js, test/functional/fixtures/regression/gh-414/pages/cross-domain.html, test/functional/fixtures/regression/gh-414/pages/first-page.html, test/functional/fixtures/regression/gh-414/pages/second-page.html, test/functional/fixtures/regression/gh-414/test.js, test/functional/fixtures/regression/gh-414/testcafe-fixtures/in-iframe.test.js, test/functional/fixtures/regression/gh-414/testcafe-fixtures/index.test.js, test/functional/fixtures/regression/gh-414/testcafe-fixtures/test_config.json, test/functional/fixtures/regression/gh-418/pages/cross-domain.html, test/functional/fixtures/regression/gh-418/pages/first-page.html, test/functional/fixtures/regression/gh-418/pages/second-page.html, test/functional/fixtures/regression/gh-418/test.js, test/functional/fixtures/regression/gh-418/testcafe-fixtures/index.test.js, test/functional/fixtures/regression/gh-418/testcafe-fixtures/test_config.json
\cc @AlexanderMoskovkin, @AndreyBelym
=> Fixed move automation and iframe step iterating (closes #414, closes #418)

src/client/runner/automation/playback/move.js, test/client/fixtures/runner/api/click-test.js, test/client/fixtures/runner/api/drag-test.js, test/client/fixtures/runner/api/press-test.js, test/client/fixtures/runner/api/select-test/index-test.js, test/client/fixtures/runner/content-editable/api-actions-content-editable-test/index-test.js
=> mousemove event sent to wrong element during dragging (close #372)

src/client/ui/styles.less
\cc @AlexanderMoskovkin, @inikulin
=> Fixed client UI styles - attribute "float" protected (closes #341)

src/client/runner/automation/playback/type/type-char.js, test/client/fixtures/runner/content-editable/api-actions-content-editable-test/index-test.js, test/client/fixtures/runner/content-editable/api-actions-content-editable-test/index.html
/cc @helen-dikareva @AndreyBelym
=> Raise 'input' event when typing into a content editable element (closes #436)

src/client/driver/command-executors/execute-action-command.js, src/test-run/commands/index.js, src/test-run/commands/type.js, test/functional/fixtures/api/raw/right-click/pages/index.html, test/functional/fixtures/api/raw/right-click/test.js, test/functional/fixtures/api/raw/right-click/testcafe-fixtures/right-click.testcafe
=> Right click command (#441)

src/client/driver/command-executors/execute-action-command.js, src/test-run/commands/index.js, src/test-run/commands/type.js, test/functional/fixtures/api/raw/double-click/pages/index.html, test/functional/fixtures/api/raw/double-click/test.js, test/functional/fixtures/api/raw/double-click/testcafe-fixtures/double-click.testcafe
=> Double click command (#441)

package.json, src/api/globals/test.js, src/errors/test-run/category.js, src/errors/test-run/formattable-adapter.js, src/errors/test-run/index.js, src/errors/test-run/templates.js, src/errors/test-run/type.js, test/functional/fixtures/api/es-next/generic-errors/pages/index.html, test/functional/fixtures/api/es-next/generic-errors/test.js, test/functional/fixtures/api/es-next/generic-errors/testcafe-fixtures/error-in-test-code-test.js, test/functional/fixtures/api/es-next/generic-errors/testcafe-fixtures/external-assertion-lib-errors-test.js, test/functional/fixtures/api/es-next/generic-errors/testcafe-fixtures/helpers.js, test/server/data/expected-test-run-errors/external-assertion-library-error, test/server/data/expected-test-run-errors/uncaught-js-error-in-test-code, test/server/data/expected-test-run-errors/uncaught-non-error-object-in-test-code, test/server/test-run-command-options-test.js, test/server/test-run-commands-test.js, test/server/test-run-error-formatting-test.js
\cc @AlexanderMoskovkin @helen-dikareva 
@VasilyStrelyaev please check test names
=> APIv2: Uncaught errors in test code. Externall assertion lib errors. (part of #374)

src/client/driver/command-executors/execute-action-command.js, src/test-run/commands/index.js, src/test-run/commands/type.js, test/functional/fixtures/api/raw/double-click/test.js, test/functional/fixtures/api/raw/hover/pages/index.html, test/functional/fixtures/api/raw/hover/test.js, test/functional/fixtures/api/raw/hover/testcafe-fixtures/hover.testcafe, test/functional/fixtures/api/raw/right-click/test.js
=> Hover command (#441)

src/client/runner/api/actions.js, src/errors/test-run/index.js, src/errors/test-run/templates.js, src/errors/test-run/type.js, src/test-run/commands/options.js, test/client/fixtures/runner/api/drag-test.js, test/functional/fixtures/api/es-next/click/test.js, test/functional/fixtures/api/raw/click/test.js, test/server/data/expected-test-run-errors/action-integer-option-error, test/server/data/expected-test-run-errors/action-positive-integer-option-error, test/server/test-run-command-options-test.js, test/server/test-run-commands-test.js, test/server/test-run-error-formatting-test.js
\cc @AlexanderMoskovkin, @helen-dikareva, @inikulin
=> Check for fractional offsets (closes #450, closes #439, closes #365)

src/api/test-controller.js, src/test-run/commands/index.js, test/functional/fixtures/api/es-next/right-click/pages/index.html, test/functional/fixtures/api/es-next/right-click/test.js, test/functional/fixtures/api/es-next/right-click/testcafe-fixtures/right-click-test.js
\cc @inikulin. @AlexanderMoskovkin 
@VasilyStrelyaev, check tests names, please.
=> Implement t.rightClick (part of #240)

src/api/test-controller.js, src/test-run/commands/index.js, test/functional/fixtures/api/es-next/double-click/pages/index.html, test/functional/fixtures/api/es-next/double-click/test.js, test/functional/fixtures/api/es-next/double-click/testcafe-fixtures/double-click-test.js
=> Implement t.doubleClick (part of #240)

src/client/runner/runner-base.js, test/functional/fixtures/regression/gh-399/pages/iframe.html, test/functional/fixtures/regression/gh-399/pages/index.html, test/functional/fixtures/regression/gh-399/testcafe-fixtures/index.test.js
\cc @AlexanderMoskovkin 
functional test added
=> A test gets stuck if iframe removes parent during step execution (close #433)

package.json, src/client/browser/idle-page/index.js, src/client/browser/index.js, src/client/core/sandboxed-jquery.js, src/client/driver/index.js, src/client/runner/runner.js, test/client/fixtures/runner/automation/regression-test.js
/cc @AlexanderMoskovkin @AndreyBelym @VasilyStrelyaev
=> Testcafe-Hammerhead updated to version 8.x.x (close #428)

src/client/core/utils/position.js, src/client/driver/command-executors/execute-action-command.js, src/client/runner/api/actions.js, src/client/runner/automation/automation.js, src/client/runner/automation/playback/drag/base.js, src/client/runner/automation/playback/drag/to-element.js, src/client/runner/automation/playback/drag/to-offset.js, src/client/runner/utils/mouse.js, src/errors/test-run/index.js, src/errors/test-run/templates.js, src/errors/test-run/type.js, src/test-run/commands/index.js, src/test-run/commands/options.js, src/test-run/commands/type.js, test/client/fixtures/runner/automation/automation-test.js, test/client/fixtures/runner/automation/out-of-bounds-test.js, test/functional/fixtures/api/es-next/click/test.js, test/functional/fixtures/api/es-next/double-click/test.js, test/functional/fixtures/api/es-next/right-click/test.js, test/functional/fixtures/api/raw/click/test.js, test/functional/fixtures/api/raw/drag/pages/index.html, test/functional/fixtures/api/raw/drag/test.js, test/functional/fixtures/api/raw/drag/testcafe-fixtures/drag.testcafe, test/server/data/expected-test-run-errors/drag-destination-is-invisible-error, test/server/data/expected-test-run-errors/drag-destination-not-found-error, test/server/data/expected-test-run-errors/drag-destination-selector-type-error, test/server/test-run-command-options-test.js, test/server/test-run-commands-test.js, test/server/test-run-error-formatting-test.js
/cc @inikulin @helen-dikareva @VasilyStrelyaev
=> Implement Drag commands (#441)

src/api/test-controller.js, src/test-run/commands/index.js, test/functional/fixtures/api/es-next/hover/pages/index.html, test/functional/fixtures/api/es-next/hover/test.js, test/functional/fixtures/api/es-next/hover/testcafe-fixtures/hover-test.js
=> Implement t.hover (part of #240)

.markdownlint.json, docs/articles/documentation/extending-testcafe/custom-reporter/helper-methods.md, docs/articles/documentation/extending-testcafe/custom-reporter/index.md, docs/articles/documentation/extending-testcafe/index.md, docs/articles/documentation/using-testcafe/command-line-interface.md, docs/articles/documentation/using-testcafe/common-concepts/index.md, docs/articles/documentation/using-testcafe/common-concepts/reporters.md, docs/articles/documentation/using-testcafe/programming-interface/Runner.md, docs/nav/nav-menu.yml
/cc @inikulin @VasilyStrelyaev 
Fixes #288
=> Docs Custom Reporter

src/client/driver/command-executors/execute-action-command.js, src/errors/test-run/index.js, src/errors/test-run/templates.js, src/errors/test-run/type.js, src/test-run/commands/index.js, src/test-run/commands/type.js, test/functional/fixtures/api/raw/type/pages/index.html, test/functional/fixtures/api/raw/type/test.js, test/functional/fixtures/api/raw/type/testcafe-fixtures/type.testcafe, test/server/data/expected-test-run-errors/action-string-argument-error, test/server/test-run-commands-test.js, test/server/test-run-error-formatting-test.js
/cc @AlexanderMoskovkin @AndreyBelym @VasilyStrelyaev
=> Type command (#441)

src/client/driver/command-executors/execute-action-command.js, src/client/driver/index.js, src/client/legacy/test-run/iframe.js.mustache, src/client/legacy/test-run/index.js.mustache, src/client/runner/api/actions.js, src/client/test-run/index.js.mustache, src/legacy/test-run/index.js, src/runner/index.js, src/test-run/index.js, test/client/before-test.js, test/functional/fixtures/api/raw/click/test.js, test/functional/fixtures/api/raw/click/testcafe-fixtures/click.testcafe, test/functional/fixtures/regression/gh-414/test.js, test/functional/fixtures/regression/gh-418/test.js, test/functional/fixtures/waiting-element-timeout/pages/index.html, test/functional/fixtures/waiting-element-timeout/test.js, test/functional/fixtures/waiting-element-timeout/testcafe-fixtures/waiting-element-timeout-test.js, test/functional/fixtures/waiting-element-timeout/testcafe-fixtures/waiting-element-timeout.test.js, test/functional/setup.js
=> Element availability timeout implemented (close #458)

src/api/test-controller.js, test/functional/fixtures/api/es-next/drag/pages/index.html, test/functional/fixtures/api/es-next/drag/test.js, test/functional/fixtures/api/es-next/drag/testcafe-fixtures/drag-test.js
=> Implement t.drag and t.dragToElement (part of #240)

package.json, src/client/.eslintrc
=> add use-hh-promise eslint rule

package.json, test/server/compiler-test.js, test/server/test-run-test.js
\cc @helen-dikareva @AlexanderMoskovkin
=> Fix server tests for Node 6

docs/articles/documentation/extending-testcafe/custom-reporter/helper-methods.md, docs/articles/documentation/using-testcafe/command-line-interface.md, docs/articles/documentation/using-testcafe/common-concepts/browser-aliases.md, docs/articles/documentation/using-testcafe/common-concepts/reporters.md, docs/articles/documentation/using-testcafe/programming-interface/BrowserConnection.md, docs/articles/documentation/using-testcafe/programming-interface/Runner.md, docs/articles/documentation/using-testcafe/programming-interface/TestCafe.md, docs/articles/documentation/using-testcafe/programming-interface/createTestCafe.md, docs/articles/documentation/using-testcafe/programming-interface/index.md, docs/articles/index.md
DevExpress/testcafe-gh-page-assets#3
=> Docs - Misc fixes that relate to the new design

src/api/common/hybrid/index.js, src/api/common/hybrid/test-run-tracker.js, src/api/globals/fixture.js, src/api/globals/test.js, src/api/globals/wrap-test-function.js, src/cli/index.js, src/compiler/es-next.js, src/errors/runtime/index.js, src/errors/runtime/message.js, test/functional/fixtures/api/es-next/double-click/test.js, test/functional/fixtures/api/es-next/hybrid-function/test.js, test/functional/fixtures/api/es-next/hybrid-function/testcafe-fixtures/hybrid-fn-test.js, test/server/compiler-test.js, test/server/data/test-suites/async-function-in-hybrid/testfile.js, test/server/data/test-suites/generator-in-hybrid/testfile.js, test/server/data/test-suites/hybrid-arg-is-not-a-function-as-ctor/testfile.js, test/server/data/test-suites/hybrid-arg-is-not-a-function/testfile.js, test/server/data/test-suites/hybrid-fn-cant-resolve-test-run/testfile.js
\cc @helen-dikareva @AlexanderMoskovkin 
@VasilyStrelyaev please, check strings
=> Implemented Hybrid function initialization errors (#241)

docs/articles/documentation/extending-testcafe/custom-reporter/helper-methods.md, docs/articles/documentation/extending-testcafe/custom-reporter/index.md, docs/articles/documentation/using-testcafe/command-line-interface.md, docs/articles/documentation/using-testcafe/common-concepts/reporters.md, docs/articles/documentation/using-testcafe/programming-interface/Runner.md
Broken links fixed.
Also, I've shortened long code lines in the code snippets.
=> Reporters: Broken links fixed

src/api/common/hybrid/index.js, src/api/common/hybrid/test-run-tracker.js, src/errors/runtime/message.js, test/functional/fixtures/api/es-next/hybrid-function/test.js, test/functional/fixtures/api/es-next/hybrid-function/testcafe-fixtures/hybrid-fn-test.js, test/server/data/hybrid-fn-test-run-tracking/in-function-after-await-with-error.js, test/server/data/hybrid-fn-test-run-tracking/in-helper-after-await.js, test/server/data/hybrid-fn-test-run-tracking/in-helper.js, test/server/data/hybrid-fn-test-run-tracking/in-next-tick.js, test/server/data/hybrid-fn-test-run-tracking/in-promise-catch.js, test/server/data/hybrid-fn-test-run-tracking/in-promise-ctor.js, test/server/data/hybrid-fn-test-run-tracking/in-promise-resolve.js, test/server/data/hybrid-fn-test-run-tracking/in-promise-then-second-handler.js, test/server/data/hybrid-fn-test-run-tracking/in-promise-then.js, test/server/data/hybrid-fn-test-run-tracking/in-set-immediate.js, test/server/data/hybrid-fn-test-run-tracking/in-set-interval.js, test/server/data/hybrid-fn-test-run-tracking/in-set-timeout.js, test/server/data/hybrid-fn-test-run-tracking/in-test-function-after-await.js, test/server/data/hybrid-fn-test-run-tracking/in-test-function.js
\cc @helen-dikareva @AlexanderMoskovkin 
@VasilyStrelyaev please, check strings
=> Implement hybrid function `bindTestRun` method  (#241)

src/errors/test-run/formattable-adapter.js, src/index.js, test/server/create-testcafe-test.js
=> Added internal method for the getting of the error markup before decorating

package.json
=> update version to 0.0.16

src/api/test-controller.js, test/functional/fixtures/api/es-next/type/pages/index.html, test/functional/fixtures/api/es-next/type/test.js, test/functional/fixtures/api/es-next/type/testcafe-fixtures/type-test.js
=> Implement t.typeText (part of #240)

src/cli/argument-parser.js, src/cli/index.js, src/errors/runtime/message.js, test/server/cli-argument-parser-test.js
=> element availability timeout added to cli (close #503)

src/api/common/hybrid/index.js, src/api/globals/fixture.js, src/api/globals/test.js, src/client/driver/command-executors/execute-hybrid-fn-command.js, src/compiler/es-next/compile-hybrid-function.js, src/compiler/es-next/index.js, src/compiler/es-next/load-babel-libs.js, src/errors/runtime/index.js, src/test-run/index.js, src/utils/node-version.js, test/functional/fixtures/api/es-next/hybrid-function/test.js, test/functional/fixtures/api/es-next/hybrid-function/testcafe-fixtures/hybrid-fn-test.js, test/server/compiler-test.js, test/server/data/hybrid-fn-compilation/basic/expected.js, test/server/data/hybrid-fn-compilation/basic/testfile.js, test/server/data/hybrid-fn-compilation/json-stringify/expected.js, test/server/data/hybrid-fn-compilation/json-stringify/testfile.js, test/server/data/hybrid-fn-compilation/object-keys/expected.js, test/server/data/hybrid-fn-compilation/object-keys/testfile.js, test/server/data/hybrid-fn-compilation/promises/expected.js, test/server/data/hybrid-fn-compilation/promises/testfile.js, test/server/data/hybrid-fn-compilation/typeof/expected-node10.js, test/server/data/hybrid-fn-compilation/typeof/expected.js, test/server/data/hybrid-fn-compilation/typeof/testfile.js
=> Hybrid functions: Promises support, polyfill Babel artifacts

src/client/driver/command-executors/execute-hybrid-fn-command.js, src/compiler/es-next/compile-hybrid-function.js, src/errors/test-run/index.js, src/errors/test-run/templates.js, src/errors/test-run/type.js, test/functional/fixtures/api/es-next/hybrid-function/test.js, test/functional/fixtures/api/es-next/hybrid-function/testcafe-fixtures/hybrid-fn-test.js, test/server/data/expected-test-run-errors/uncaught-error-in-client-executed-code, test/server/test-run-error-formatting-test.js
=> Hybrid function execution error (#241)

.travis-docs.yml, .travis.yml, Gulpfile.js, docs/articles/documentation/using-testcafe/common-concepts/browser-aliases.md, docs/articles/documentation/using-testcafe/common-concepts/reporters.md, docs/articles/documentation/using-testcafe/programming-interface/browserconnection.md, docs/articles/documentation/using-testcafe/programming-interface/createtestcafe.md, docs/articles/documentation/using-testcafe/programming-interface/index.md, docs/articles/documentation/using-testcafe/programming-interface/runner.md, docs/articles/documentation/using-testcafe/programming-interface/testcafe.md, docs/nav/nav-menu.yml, package.json
=> [docs] Add a website test for broken links

.travis-docs.yml, Gulpfile.js
=> [docs] Remove server tests from the documentation test bunch

docs/articles/documentation/using-testcafe/command-line-interface.md, docs/articles/documentation/using-testcafe/programming-interface/runner.md
=> [docs] Describe the elementAvailabilityTimeout option

src/api/common/hybrid/compiled-code-symbol.js, src/api/common/hybrid/index.js, src/compiler/es-next/compile-hybrid-function.js, src/errors/runtime/message.js, test/functional/fixtures/api/es-next/hybrid-function/pages/index.html, test/functional/fixtures/api/es-next/hybrid-function/test.js, test/functional/fixtures/api/es-next/hybrid-function/testcafe-fixtures/hybrid-fn-test.js, test/functional/setup.js, test/functional/site/index.js, test/server/compiler-test.js, test/server/data/test-suites/hybrid-dep-not-hybrid/testfile.js, test/server/data/test-suites/hybrid-deps-not-object/testfile.js
\cc @AlexanderMoskovkin @helen-dikareva 
@VasilyStrelyaev please, check comments and strings
=> Implement Hybrid dependencies (#241)

src/api/test-controller.js, test/functional/fixtures/api/es-next/select/pages/index.html, test/functional/fixtures/api/es-next/select/test.js, test/functional/fixtures/api/es-next/select/testcafe-fixtures/select-test.js
=> Implement select es-next api (part of #240)

src/api/test-controller.js, src/test-run/commands/index.js, test/functional/fixtures/api/es-next/press-key/pages/index.html, test/functional/fixtures/api/es-next/press-key/test.js, test/functional/fixtures/api/es-next/press-key/testcafe-fixtures/press-key-test.js
=> Implement t.pressKey (part of #240)

docs/articles/documentation/using-testcafe/programming-interface/index.md, docs/articles/documentation/using-testcafe/programming-interface/runner.md, docs/articles/documentation/using-testcafe/programming-interface/testcafe.md
plus a couple of fixes
fixes #520
=> [docs] Cancelling tasks through API

src/client/driver/command-executors/ensure-element-utils.js, src/client/driver/command-executors/execute-action-command.js, src/client/driver/command-executors/execute-wait-for-element-command.js, src/client/driver/index.js, src/test-run/commands/index.js, src/test-run/commands/type.js, src/test-run/index.js, test/functional/fixtures/api/raw/click/test.js, test/functional/fixtures/api/raw/wait-for-element/pages/index.html, test/functional/fixtures/api/raw/wait-for-element/pages/page-after-forwarding.html, test/functional/fixtures/api/raw/wait-for-element/pages/page-with-forwarding.html, test/functional/fixtures/api/raw/wait-for-element/test.js, test/functional/fixtures/api/raw/wait-for-element/testcafe-fixtures/page-with-forwarding.testcafe, test/functional/fixtures/api/raw/wait-for-element/testcafe-fixtures/wait-for-element.testcafe, test/functional/fixtures/api/raw/wait/pages/index.html, test/functional/fixtures/api/raw/wait/test.js, test/functional/fixtures/api/raw/wait/testcafe-fixtures/wait.testcafe, test/functional/fixtures/element-availability-timeout/pages/index.html, test/functional/fixtures/element-availability-timeout/test.js, test/functional/fixtures/element-availability-timeout/testcafe-fixtures/element-availability-timeout.js, test/functional/fixtures/element-availability-timeout/testcafe-fixtures/element-availability-timeout.test.js, test/server/test-run-commands-test.js
/cc @inikulin @AndreyBelym @VasilyStrelyaev
=> Wait and WaitForElement commands (part of #441)

src/client/driver/command-executors/execute-navigate-to-command.js, src/client/driver/index.js, src/errors/test-run/index.js, src/errors/test-run/templates.js, src/errors/test-run/type.js, src/test-run/commands/index.js, src/test-run/commands/type.js, test/client/fixtures/runner/api/navigate-to-test.js, test/functional/fixtures/api/raw/navigate-to/pages/index.html, test/functional/fixtures/api/raw/navigate-to/pages/navigation.html, test/functional/fixtures/api/raw/navigate-to/test.js, test/functional/fixtures/api/raw/navigate-to/testcafe-fixtures/navigate-to.testcafe, test/functional/fixtures/element-availability-timeout/pages/index.html, test/functional/fixtures/element-availability-timeout/test.js, test/functional/fixtures/element-availability-timeout/testcafe-fixtures/element-availability-timeout.js, test/functional/fixtures/element-availability-timeout/testcafe-fixtures/element-availability-timeout.test.js, test/functional/site/server.js, test/server/data/expected-test-run-errors/action-unsupported-url-protocol-error, test/server/test-run-commands-test.js, test/server/test-run-error-formatting-test.js
/cc @AlexanderMoskovkin @VasilyStrelyaev @AndreyBelym
=> NavigateTo command (part of #441)

src/api/test-controller.js, test/functional/fixtures/api/es-next/wait/pages/index.html, test/functional/fixtures/api/es-next/wait/test.js, test/functional/fixtures/api/es-next/wait/testcafe-fixtures/wait-test.js
=> Implement es-next wait actions (part of #240)

src/client/core/xhr-barrier.js
/cc @helen-dikareva @miherlosev
=> remove unused field and member in xhr-barrier (closes #532)

src/api/test-controller.js, src/errors/test-run/templates.js, test/functional/fixtures/api/es-next/navigate-to/pages/index.html, test/functional/fixtures/api/es-next/navigate-to/pages/navigation.html, test/functional/fixtures/api/es-next/navigate-to/test.js, test/functional/fixtures/api/es-next/navigate-to/testcafe-fixtures/navigate-to-test.js, test/server/data/expected-test-run-errors/action-unsupported-url-protocol-error
\cc @inikulin @AlexanderMoskovkin @VasilyStrelyaev
=> Implement t.navigateTo (part of #240)

src/client/driver/index.js, src/errors/test-run/index.js, src/errors/test-run/templates.js, src/errors/test-run/type.js, test/functional/fixtures/api/es-next/hybrid-function/test.js, test/functional/fixtures/api/es-next/hybrid-function/testcafe-fixtures/hybrid-fn-test.js, test/server/data/expected-test-run-errors/client-code-execution-interruption-error, test/server/test-run-error-formatting-test.js
=> Add HybridFnExecutionInterrupted error (closes #523)

test/client/before-test.js, test/client/fixtures/runner/api/select-test/index-test.js, test/client/fixtures/runner/content-editable/api-actions-content-editable-test/index-test.js
\cc @AlexanderMoskovkin, @helen-dikareva, @VasilyStrelyaev 
FPR (all previous remarks [here](https://github.com/DevExpress/testcafe/pull/539))
=> Fixed QUnit tests - api select and content-editable api-actions (part of #471)

src/api/test-controller.js, src/client/driver/command-executors/ensure-element-utils.js, src/errors/test-run/index.js, src/errors/test-run/type.js, test/functional/fixtures/api/es-next/upload/pages/index.html, test/functional/fixtures/api/es-next/upload/test-data/file1.txt, test/functional/fixtures/api/es-next/upload/test.js, test/functional/fixtures/api/es-next/upload/testcafe-fixtures/upload-test.js, test/server/test-run-error-formatting-test.js
\cc @inikulin @AlexanderMoskovkin @VasilyStrelyaev
=> Implement upload es-next api (part of #240)

test/client/fixtures/runner/cross-domain/in-iframe-test.js
=> Fixed QUnit tests - in-iframe (part of #471)

src/client/driver/index.js, src/test-run/index.js
/cc @inikulin @helen-dikareva @VasilyStrelyaev 
With this driver requests don't hang for more than 10 seconds
=> Add driver response timeout

test/functional/assertion-helper.js, test/functional/fixtures/api/es-next/take-screenshot/pages/index.html, test/functional/fixtures/api/es-next/take-screenshot/testcafe-fixtures/take-screenshot.js, test/functional/fixtures/screenshots-on-fails/test.js, test/functional/setup.js, test/server/test-run-commands-test.js
=> Fix problems after merge TakeScreenshotCommand PR

src/errors/stack-filter.js
=> Filter regenerator-runtime messages in error stack

src/client/driver/command-executors/prepare-browser-manipulation.js, src/client/driver/index.js, src/client/runner/runner.js, src/legacy/test-run/index.js, src/runner/screenshots/capturer.js, src/test-run/browser-manipulation-manager.js, src/test-run/index.js
\cc @inikulin, @AlexanderMoskovkin, @helen-dikareva
=> Fix windows handling for IE (closes #559)

Gulpfile.js, src/client/core/index.js, src/client/core/prevent-real-events.js, src/client/driver/index.js, src/client/runner/automation/automation.js, test/functional/fixtures/driver/pages/prevent-real-action.html, test/functional/fixtures/driver/test.js, test/functional/fixtures/driver/testcafe-fixtures/prevent-real-action-test.js
\cc @inikulin, @AlexanderMoskovkin, @helen-dikareva
=> Preventing real actions has been implemented in client driver (closes #549)

src/client/driver/command-executors/execute-action.js, src/test-run/commands/options.js, test/functional/fixtures/api/es-next/click/pages/index.html, test/functional/fixtures/api/es-next/click/test.js, test/functional/fixtures/api/es-next/click/testcafe-fixtures/click-test.js, test/server/test-run-command-options-test.js, test/server/test-run-commands-test.js
=> Use element center as default offset (closes #563)

src/api/test-controller.js, src/client/driver/command-executors/prepare-browser-manipulation.js, src/errors/test-run/index.js, src/errors/test-run/templates.js, src/errors/test-run/type.js, src/test-run/browser-manipulation-manager.js, src/test-run/commands/index.js, src/test-run/commands/type.js, src/test-run/index.js, test/functional/assertion-helper.js, test/functional/fixtures/api/es-next/resize-window/pages/index.html, test/functional/fixtures/api/es-next/resize-window/test.js, test/functional/fixtures/api/es-next/resize-window/testcafe-fixtures/resize-window-test.js, test/functional/fixtures/api/es-next/take-screenshot/test.js, test/functional/fixtures/screenshots-on-fails/test.js, test/functional/setup.js, test/server/data/expected-test-run-errors/action-boolean-argument-error, test/server/data/expected-test-run-errors/action-unsupported-device-type-error, test/server/test-run-commands-test.js, test/server/test-run-error-formatting-test.js
/cc @AlexanderMoskovkin @AndreyBelym @VasilyStrelyaev
=> ResizeWindow, ResizeWindowToFitDevice commands (part of #441, part of #240)

src/client/driver/command-executors/execute-action.js, src/client/runner/api/actions.js, src/client/runner/automation/errors.js, src/client/runner/automation/playback/click/index.js, src/client/runner/automation/playback/dblclick.js, src/client/runner/automation/playback/drag/base.js, src/client/runner/automation/playback/hover.js, src/client/runner/automation/playback/rclick.js, src/client/runner/automation/playback/select/base.js, test/client/fixtures/runner/api/click-test.js, test/functional/fixtures/api/legacy/click/test.js, test/functional/fixtures/api/legacy/click/testcafe-fixtures/click.test.js, test/functional/fixtures/api/raw/click/pages/index.html, test/functional/fixtures/api/raw/click/test.js, test/functional/fixtures/api/raw/click/testcafe-fixtures/click.testcafe, test/functional/fixtures/api/raw/hover/pages/index.html, test/functional/fixtures/api/raw/hover/test.js, test/functional/fixtures/api/raw/hover/testcafe-fixtures/hover.testcafe
/cc @inikulin @AlexanderMoskovkin @VasilyStrelyaev 
ASPxExperience tests successfully passed on farm with this fix
=> Logic for getting elementFromPoint changed for elements which located out of visible area (close #337)

src/errors/test-run/index.js, src/errors/test-run/templates.js, src/errors/test-run/type.js, src/test-run/index.js, test/functional/fixtures/page-error/pages/handled.html, test/functional/fixtures/page-error/pages/index.html, test/functional/fixtures/page-error/test.js, test/functional/fixtures/page-error/testcafe-fixtures/page-error-test.js, test/server/data/expected-test-run-errors/could-not-open-page-error, test/server/data/expected-test-run-errors/page-load-error, test/server/test-run-error-formatting-test.js
=> Handle page error (part of #374)

src/runner/screenshots/capturer.js, src/runner/screenshots/index.js, src/runner/screenshots/warning-messages.js, src/test-run/browser-manipulation-manager.js, test/functional/assertion-helper.js, test/functional/fixtures/api/es-next/take-screenshot/test.js, test/functional/fixtures/api/es-next/take-screenshot/testcafe-fixtures/take-screenshot.js, test/functional/fixtures/screenshots-on-fails/test.js
/cc @AlexanderMoskovkin @inikulin @VasilyStrelyaev
=> Path to screenshots changed for action takeScreenshot with custom path; screenshot warning added

package.json, src/test-run/browser-manipulation-manager.js, src/test-run/commands/service.js, src/test-run/commands/utils.js, src/test-run/index.js, test/functional/fixtures/api/es-next/resize-window/test.js, test/functional/fixtures/api/es-next/resize-window/testcafe-fixtures/resize-window-test.js
/cc @AlexanderMoskovkin  @AndreyBelym
=> Update testcafe-browser-natives to v0.13.0 (close #577)

src/api/test-controller.js, src/client/driver/command-executors/execute-action.js, src/test-run/commands/actions.js, src/test-run/commands/from-object.js, src/test-run/commands/type.js, test/functional/fixtures/api/es-next/upload/test.js, test/functional/fixtures/api/es-next/upload/testcafe-fixtures/upload-test.js, test/functional/fixtures/api/raw/upload/testcafe-fixtures/upload.testcafe, test/server/test-run-commands-test.js
\cc @AlexanderMoskovkin, @VasilyStrelyaev
=> t.uploadFile renamed to t.setFilesToUpload including server API (closes #595)

src/client/core/prevent-real-events.js, test/functional/fixtures/regression/gh-591/pages/index.html, test/functional/fixtures/regression/gh-591/test.js, test/functional/fixtures/regression/gh-591/testcafe-fixtures/index.test.js, test/functional/fixtures/regression/gh-591/testcafe-fixtures/test_config.json
\cc @AlexanderMoskovkin, @AndreyBelym
=> Fixed preventing from real actions (closes #591)

test/client/fixtures/runner/cross-domain/in-iframe-test.js, test/client/fixtures/runner/cross-domain/run-test.js
=> Fixed QUnit tests - cross-domain - run-test (part of #471)

docs/articles/documentation/extending-testcafe/custom-reporter/helper-methods.md, docs/articles/documentation/extending-testcafe/custom-reporter/index.md, docs/articles/documentation/extending-testcafe/index.md, docs/articles/documentation/using-testcafe/command-line-interface.md, docs/articles/documentation/using-testcafe/common-concepts/reporters.md
//cc @VasilyStrelyaev @inikulin @DevExpress/testcafe-docs
=> [docs] Topics checked by correctors

docs/articles/documentation/extending-testcafe/custom-reporter/helper-methods.md, docs/articles/documentation/extending-testcafe/custom-reporter/index.md, docs/articles/documentation/using-testcafe/command-line-interface.md
=> [docs] CLI - example for T and F options updated

package.json, src/cli/argument-parser.js, src/embedding-utils.js, src/index.js, src/reporter/plugin-host.js, src/utils/string.js
\cc @kirovboris @AlexanderMoskovkin
=> Fix error prefix length calculation. Expose test run errors via embedding utils for testing purposes. Bump version.

package.json, src/embedding-utils.js
\cc @kirovboris @AlexanderMoskovkin
=> Fix incorrect import in embedding utils. Bump version.

package.json, src/errors/test-run/templates.js, src/reporter/plugin-host.js
=> Correctly fix prefix length alignment. Remove colors in error subtitle. Bump version once again =/

package.json, src/index.js
=> Use IP address as the default hostname (closes #575)

package.json, test/functional/config.js, test/functional/fixtures/api/es-next/client-function/test.js, test/functional/fixtures/api/es-next/eval/test.js
=> Upgrade testcafe-browser-natives to 0.14.0

src/client/driver/driver.js, src/client/driver/iframe-driver.js, src/client/test-run/iframe.js.mustache, src/client/test-run/index.js.mustache, src/test-run/index.js, test/functional/fixtures/page-js-errors/test.js
=> Check the skipJsErrors option in the client driver (closes #609)

src/client/runner/automation/playback/press/parse-key-sequence.js, test/client/fixtures/runner/api/press-test.js
\cc @inikulin, @AlexanderMoskovkin, @VasilyStrelyaev
=>  Fixed argument validation for press automation

package.json, src/reporter/plugin-host.js
\cc @AndreyBelym @AlexanderMoskovkin
=> Expose `viewportWidth` to reporter plugins. Bump version.

docs/articles/documentation/getting-started/index.md, docs/articles/documentation/using-testcafe/index.md, docs/articles/documentation/using-testcafe/installing-testcafe.md, docs/articles/documentation/using-testcafe/programming-interface/index.md, docs/nav/nav-menu.yml
=> [docs] Installing TestCafe

.gitignore, package.json, src/errors/runtime/index.js, src/legacy/test-run/index.js, src/reporter/index.js, src/runner/screenshots/capturer.js, src/runner/screenshots/index.js, src/runner/screenshots/warning-messages.js, src/test-run/browser-manipulation-queue.js, src/test-run/index.js, src/utils/render-template.js, src/warnings/index.js, src/warnings/message.js, test/functional/fixtures/api/es-next/take-screenshot/test.js, test/functional/fixtures/screenshots-on-fails/test.js, test/functional/setup.js, test/server/reporter-test.js
\cc @AlexanderMoskovkin @helen-dikareva @VasilyStrelyaev
=> Implement test run warnings (#671 part2)

Gulpfile.js
\cc @AlexanderMoskovkin, @AndreyBelym 
Due to https://github.com/AlexanderMoskovkin/qunit-harness/issues/35#issuecomment-234875780
=> The latest firefox version has been set in the client test settings

src/client/runner/runner.js, test/client/fixtures/runner/runner-test.js
\cc @AlexanderMoskovkin, @inikulin, @VasilyStrelyaev
=> Fixed processing of errors on the client (legacy API, closes #660)

src/legacy/test-run/index.js, src/reporter/index.js, src/reporter/plugin-host.js, src/runner/browser-job.js, src/runner/task.js, src/test-run/browser-manipulation-queue.js, src/test-run/index.js, src/warnings/index.js, src/warnings/log.js, test/functional/setup.js, test/server/reporter-test.js
=> Make warnings global per task (part of #671)

src/runner/screenshots/capturer.js, test/functional/assertion-helper.js, test/functional/fixtures/api/es-next/take-screenshot/test.js, test/functional/fixtures/api/es-next/take-screenshot/testcafe-fixtures/take-screenshot.js
=> Add file name to path argument for takeScreenshot action (close #687)

Gulpfile.js, src/client/driver/command-executors/client-functions/selector-executor/sandboxed-node-properties.js, src/compiler/es-next/index.js, test/client/fixtures/automation/drag-test.js, test/server/runner-test.js
=> try to fix qunit test 'overlapped during dragging'

src/client/driver/native-dialog-tracker/iframe.js, src/client/driver/native-dialog-tracker/index.js, src/errors/test-run/index.js, src/errors/test-run/templates.js, test/functional/fixtures/native-dialogs-handling/errors.js, test/functional/fixtures/native-dialogs-handling/iframe/test.js, test/functional/fixtures/native-dialogs-handling/iframe/testcafe-fixtures/in-iframe-test.js, test/functional/fixtures/native-dialogs-handling/iframe/testcafe-fixtures/page-load-test.js, test/functional/fixtures/native-dialogs-handling/test.js, test/functional/fixtures/native-dialogs-handling/testcafe-fixtures/native-dialogs-test.js, test/functional/fixtures/native-dialogs-handling/testcafe-fixtures/page-load-test.js, test/server/data/expected-test-run-errors/native-dialog-not-handled-error, test/server/data/expected-test-run-errors/uncaught-error-in-native-dialog-handler, test/server/test-run-error-formatting-test.js
=> 'url' added to dialogInfo in dialog-tracker (closes #710)

docs/articles/documentation/extending-testcafe/custom-reporter/helpers.md, docs/articles/documentation/extending-testcafe/custom-reporter/index.md, docs/articles/documentation/extending-testcafe/custom-reporter/reporter-methods.md, docs/articles/documentation/using-testcafe/programming-interface/index.md, docs/articles/documentation/using-testcafe/programming-interface/runner.md, docs/articles/documentation/using-testcafe/programming-interface/testcafe.md, docs/nav/nav-menu.yml
Documentation updated due to these changes - https://github.com/DevExpress/testcafe/issues/671#issuecomment-235572817
=> [docs] Reporter methods with parameters described

test/server/runner-test.js
=> Properly disable resize hack in server tests (closes #719)

src/client/driver/command-executors/client-functions/selector-executor/index.js, src/client/driver/driver.js, src/client/ui/status-bar/iframe-status-bar.js, src/client/ui/status-bar/index.js, src/client/ui/status-bar/messages.js, src/client/ui/status-bar/progress-bar/determinate-indicator.js, src/client/ui/status-bar/progress-bar/index.js, src/client/ui/styles.less
/cc @inikulin @AlexanderMoskovkin 
The designer approved
=> Result of waiting for an element displayed in status bar

package.json, src/runner/browser-job.js, src/screenshots/capturer.js, src/screenshots/index.js, src/test-run/browser-manipulation-queue.js, test/functional/assertion-helper.js, test/functional/fixtures/api/es-next/take-screenshot/test.js, test/functional/fixtures/api/es-next/take-screenshot/testcafe-fixtures/take-screenshot.js, test/functional/fixtures/screenshots-on-fails/test.js, test/functional/fixtures/screenshots-on-fails/testcafe-fixtures/screenshots-on-fails.js
=> Screenshots paths made more user-friendly (closes #650)

test/functional/fixtures/api/raw/iframe-switching/pages/iframe.html, test/functional/fixtures/api/raw/iframe-switching/pages/index.html, test/functional/fixtures/api/raw/iframe-switching/pages/nested-iframe.html, test/functional/fixtures/api/raw/iframe-switching/test.js, test/functional/fixtures/api/raw/iframe-switching/testcafe-fixtures/iframe-switching.testcafe
/cc @AlexanderMoskovkin @georgiy-abbasov
=> RAW api iframe switching test added (closes #602)

src/cli/log.js
\сс @inikulin @AlexanderMoskovkin @VasilyStrelyaev
=> Disable spinner in CI environments (closes #733)

package.json, src/client/driver/driver.js, src/errors/test-run/index.js, src/errors/test-run/type.js, test/server/test-run-error-formatting-test.js
=> Creation of actionElementNotIframeError error fixed (closes #731)

package.json, src/browser/connection/index.js, src/browser/provider/built-in/base.js, src/browser/provider/built-in/locally-installed.js, src/browser/provider/built-in/path.js, src/browser/provider/built-in/remote.js, src/browser/provider/plugin-host.js, src/client/driver/command-executors/prepare-browser-manipulation.js, src/client/driver/driver.js, src/client/test-run/index.js.mustache, src/screenshots/capturer.js, src/test-run/browser-manipulation-queue.js, src/test-run/commands/validations/argument.js, src/test-run/index.js, src/warnings/message.js, test/functional/fixtures/api/es-next/resize-window/test.js, test/functional/fixtures/api/es-next/take-screenshot/test.js, test/functional/setup.js, test/server/browser-connection-test.js, test/server/runner-test.js
\cc @inikulin @VasilyStrelyaev
=> Refactor browser providers according to the docs review(related to #725)

package.json
/cc @inikulin @AlexanderMoskovkin 
We have breaking change in https://github.com/DevExpress/testcafe/issues/650
=> update testcafe version

.eslintrc, package.json, src/client/driver/command-executors/execute-action.js
=> Add import/export eslint rules

package.json, src/runner/browser-job.js, src/test-run/index.js, test/functional/fixtures/regression/gh-743/test.js, test/functional/fixtures/regression/gh-743/testcafe-fixtures/two-tests-in-a-fixture.js
=> Fix testRuns starting collision (fix #743). Bump version

src/runner/browser-job.js, src/screenshots/capturer.js, test/functional/assertion-helper.js, test/functional/fixtures/api/es-next/take-screenshot/test.js, test/functional/fixtures/api/es-next/take-screenshot/testcafe-fixtures/take-screenshot.js, test/functional/fixtures/screenshots-on-fails/test.js
/cc @inikulin  @AlexanderMoskovkin
=> Screenshots path in report fixed for tests in quarantine mode (closes #746)

src/test-run/index.js, test/functional/fixtures/regression/gh-754/pages/index.html, test/functional/fixtures/regression/gh-754/test.js, test/functional/fixtures/regression/gh-754/testcafe-fixtures/index-test.js
=> Fix the problem with several singlequotes in fixture and test names (fix #754)

.travis-docs.yml, docs/articles/index.html
A couple of things for DevExpress/testcafe-gh-page-assets#17
=> [docs] Website - SEO and Analytics

src/client/driver/command-executors/prepare-browser-manipulation.js, src/client/driver/driver.js, test/functional/fixtures/api/es-next/iframe-switching/test.js, test/functional/fixtures/api/raw/upload/test.js, test/functional/fixtures/api/raw/wait/test.js, test/functional/fixtures/native-dialogs-handling/test.js
waiting for passing tests on sauce labs
=> Bug with execution an action repeatedly fixed (close #663)

Gulpfile.js, test/functional/config.js
=> Move IE9, IE10 tests to separate tasks (closes #772)

src/client/automation/playback/click/index.js, src/client/core/utils/array.js, src/client/core/utils/dom.js, test/functional/fixtures/regression/gh-423/pages/index.html, test/functional/fixtures/regression/gh-423/test.js, test/functional/fixtures/regression/gh-423/testcafe-fixtures/index.test.js
\cc @inikulin, @AlexanderMoskovkin, @helen-dikareva, @VasilyStrelyaev
=> Fixed mouseup emulation for click automation (closes #423)

docs/articles/documentation/test-api/actions/action-options.md, docs/articles/documentation/test-api/actions/select-text.md, docs/articles/documentation/test-api/handling-native-dialogs.md, docs/articles/documentation/test-api/selecting-page-elements/dom-node-snapshots.md, docs/articles/documentation/test-api/selecting-page-elements/selectors.md
=> [docs] Corrections from #773 applied

package.json
\cc @VasilyStrelyaev @AlexanderMoskovkin
=> [docs] Add missing fields to package.json (closes #761)

src/client/core/page-unload-barrier.js
The problem reproduced on an asp-test. It reproduces on a slow virtual machine sometimes (it looks it depends on a machine productivity). We have functional tests for this already
/cc @AndreyBelym @helen-dikareva
=> Add missed flag set (#784)

src/client/automation/playback/select/utils.js
=> fix functional test in MSEdge

src/client/automation/cursor.js
/cc @helen-dikareva @AndreyBelym @VasilyStrelyaev 
I suppose there are no reason to write a test for this. I can write a test that hovers to point (50;50) but it is not a common case.
=> Move default cursor point outside of the page (closes #794)

examples/running-tests-using-travis-and-saucelabs/.travis.yml, examples/running-tests-using-travis-and-saucelabs/README.md, examples/running-tests-using-travis-and-saucelabs/index.html, examples/running-tests-using-travis-and-saucelabs/package.json, examples/running-tests-using-travis-and-saucelabs/server.js, examples/running-tests-using-travis-and-saucelabs/tests/index-test.js
=> [docs] Travis + Saucelabs example

test/functional/get-test-error.js
=> Include all browsers in test errors in functional tests (closes #799)

README.md
=> [docs] Add appveyor badge

README.md, docs/articles/index.html
=> [docs] install command with g flag

docs/articles/documentation/test-api/assertions.md
\cc @DevExpress/testcafe @miherlosev
=> [docs] assert module mentioned

.markdownlint-readme.json, README.md, docs/articles/index.html
=> [docs] Features added to landing page and readme (closes #763)

package.json, src/cli/index.js, src/runner/index.js, test/server/runner-test.js
=> Get rid of unhandled rejections in runner (fixes #825)

docs/articles/documentation/recipes/running-tests-using-travis-ci-and-sauce-labs.md
=> [docs] Armina corrections

examples/README.md
=> [docs] Readme for examples added

docs/articles/documentation/test-api/selecting-page-elements/dom-node-snapshots.md
/cc @inikulin @MargaritaLoseva 
closes #834
=> [docs] Add the domSnapshot.hasClass method description (closes #834)

src/client/driver/command-executors/client-functions/selector-executor/node-snapshots.js, test/functional/fixtures/api/es-next/selector/pages/index.html, test/functional/fixtures/api/es-next/selector/test.js, test/functional/fixtures/api/es-next/selector/testcafe-fixtures/selector-test.js
=> Add `selected` attribute to DOM Element snapshot (closes #839)

package.json, src/.babelrc, src/client/.babelrc, src/compiler/es-next/compile-client-function.js, src/compiler/es-next/load-babel-libs.js, test/functional/fixtures/api/es-next/before-after-each-hooks/test.js, test/functional/fixtures/api/es-next/before-after-each-hooks/testcafe-fixtures/fail-in-test.js, test/functional/fixtures/api/es-next/before-after-each-hooks/testcafe-fixtures/run-all.js
\cc @helen-dikareva @AndreyBelym
=> Fix bugs related to new Babel version

docs/README.md, docs/articles/documentation/test-api/A-Z.md, docs/articles/documentation/test-api/a-z-index.md, docs/articles/documentation/test-api/selecting-page-elements/dom-node-snapshots.md, docs/articles/documentation/test-api/test-code-structure.md, docs/nav/nav-menu.yml
=> [docs] Test API References

src/client/automation/playback/press/index.js, src/client/automation/playback/press/key-press-simulator.js, src/client/core/utils/dom.js, test/functional/fixtures/api/es-next/press-key/pages/iframe.html, test/functional/fixtures/api/es-next/press-key/pages/index.html, test/functional/fixtures/api/es-next/press-key/test.js, test/functional/fixtures/api/es-next/press-key/testcafe-fixtures/press-key-test.js
/cc @AlexanderMoskovkin @AndreyBelym 
need some change in testcafe-hammerhead
=> ASPxSpreadsheet tests're fixed in Chrome and IE

src/client/automation/playback/move.js, src/test-run/commands/options.js, test/functional/fixtures/api/es-next/iframe-switching/pages/index.html, test/functional/fixtures/api/es-next/iframe-switching/test.js, test/functional/fixtures/api/es-next/iframe-switching/testcafe-fixtures/iframe-switching-test.js, test/functional/fixtures/regression/gh-847/pages/iframe.html, test/functional/fixtures/regression/gh-847/pages/index.html, test/functional/fixtures/regression/gh-847/test.js, test/functional/fixtures/regression/gh-847/testcafe-fixtures/index-test.js, test/server/test-run-command-options-test.js
/cc @inikulin @georgiy-abbasov 
Sometimes the DOMContentLoaded event raises too late, as a result the iframe is empty when we are going to click inside it
=> Fix unstable functional test, closes #847

src/client/automation/playback/click/index.js, src/client/automation/playback/rclick.js, src/client/automation/utils/utils.js, test/functional/fixtures/regression/gh-770/pages/index.html, test/functional/fixtures/regression/gh-770/test.js, test/functional/fixtures/regression/gh-770/testcafe-fixtures/index.test.js
\cc @inikulin, @AlexanderMoskovkin, @helen-dikareva
=> Fixed focus behavior for click automation (closes #770)

.travis.yml, test/functional/legacy-fixtures/regression/legacy-gh-16/pages/iframe.html, test/functional/legacy-fixtures/regression/legacy-gh-16/pages/index.html, test/functional/legacy-fixtures/regression/legacy-gh-16/test.js, test/functional/legacy-fixtures/regression/legacy-gh-16/testcafe-fixtures/index.test.js, test/functional/legacy-fixtures/regression/legacy-gh-16/testcafe-fixtures/test_config.json
=> Added regression test for testcafe-legacy-api#16

README.md, docs/articles/documentation/extending-testcafe/browser-provider-plugin/browser-provider-methods.md, docs/articles/documentation/extending-testcafe/browser-provider-plugin/index.md, docs/articles/documentation/using-testcafe/common-concepts/browser-support.md, docs/articles/index.html
The text has been changed due to Armina comments.
@inikulin @VasilyStrelyaev Please, check if this new text is correct technically. Then I'll send it to Armina again.
=> [docs] Landing page modified

Gulpfile.js, docs/articles/blog/2016-10-5-introducing-testcafe-testing-framework.md, docs/articles/documentation/getting-started/index.md, docs/nav/top-menu-items.yml
A part of DevExpress/testcafe-gh-page-assets#19
=> [docs] Website: Introduce Blogging Platform

src/client/driver/driver.js, src/client/driver/iframe-driver.js, test/functional/fixtures/regression/gh-856/pages/first.html, test/functional/fixtures/regression/gh-856/pages/iframe.html, test/functional/fixtures/regression/gh-856/pages/second.html, test/functional/fixtures/regression/gh-856/pages/third.html, test/functional/fixtures/regression/gh-856/test.js, test/functional/fixtures/regression/gh-856/testcafe-fixtures/index-test.js
/cc @helen-dikareva @georgiy-abbasov 
The test name is reviewed by @VasilyStrelyaev
=> Update driver flags on start (closes #856)

src/client/automation/playback/move.js, src/client/automation/utils/get-line-rect-intersection.js, test/functional/fixtures/regression/gh-850/pages/iframe.html, test/functional/fixtures/regression/gh-850/pages/index.html, test/functional/fixtures/regression/gh-850/test.js, test/functional/fixtures/regression/gh-850/testcafe-fixtures/index.test.js
\cc @AlexanderMoskovkin, @helen-dikareva, @AndreyBelym
=> Fixed cursor behavior on moving out from iframe (closes #850)

src/client/core/page-unload-barrier.js, src/test-run/client-messages.js, src/test-run/index.js, test/client/fixtures/core/page-unload-barrier-test.js, test/functional/fixtures/regression/gh-845/pages/iframe.html, test/functional/fixtures/regression/gh-845/pages/index.html, test/functional/fixtures/regression/gh-845/test.js, test/functional/fixtures/regression/gh-845/testcafe-fixtures/index-test.js, test/functional/legacy-fixtures/regression/gh-845/pages/iframe.html, test/functional/legacy-fixtures/regression/gh-845/pages/index.html, test/functional/legacy-fixtures/regression/gh-845/test.js, test/functional/legacy-fixtures/regression/gh-845/testcafe-fixtures/index.test.js, test/functional/legacy-fixtures/regression/gh-845/testcafe-fixtures/test_config.json, test/functional/site/server.js
=> Logic to handle file downloading during test execution added (part of #845)

src/client/automation/playback/click/index.js, src/client/automation/playback/dblclick.js, src/client/core/utils/array.js, test/functional/fixtures/regression/gh-851/pages/index.html, test/functional/fixtures/regression/gh-851/test.js, test/functional/fixtures/regression/gh-851/testcafe-fixtures/index.test.js
\cc @inikulin, @AlexanderMoskovkin, @helen-dikareva
=> Fixed raising `click` and `dblclick` events in automations (closes #851)

CHANGELOG.md, Gulpfile.js
=> [docs] Add changelog file (#704)

src/client/automation/index.js, src/client/automation/settings.js, src/client/core/page-unload-barrier.js, src/client/core/request-barrier.js
=> Decrease timeouts (closes #863)

feed.xml, index.html, sitemap.xml
=> Fix protocol for DevExpress CDN content

README.md, docs/articles/blog/2016-10-17-introducing-testcafe-open-source-testing-framework.md, docs/articles/documentation/getting-started/index.md, docs/articles/documentation/using-testcafe/installing-testcafe.md, docs/articles/index.html
=> [docs] Add blog post and fix browser names in docs

README.md
=> [docs] Fix broken links in the Readme

src/browser/provider/built-in/locally-installed.js
\cc @AndreyBelym @AlexanderMoskovkin
=> Make browser alias name check case insensitive (fixes #890)

CONTRIBUTING.md, docs/articles/documentation/using-testcafe/common-concepts/browser-support.md
A couple of corrections by Julian and Armina.
=> [docs] A couple of corrections

src/client/automation/utils/utils.js, src/client/core/utils/dom.js, test/functional/fixtures/api/raw/click/pages/index.html, test/functional/fixtures/regression/gh-889/pages/index.html, test/functional/fixtures/regression/gh-889/test.js, test/functional/fixtures/regression/gh-889/testcafe-fixtures/index.test.js
/cc @AlexanderMoskovkin @georgiy-abbasov @VasilyStrelyaev
=> Focusing of non-focusable element fixed

.publishrc, package.json
=> Fix testcafe-hammerhead version (closes #886). Bump version.

package.json
=> Update version to 0.10.0-alpha

README.md
=> [docs] Use badges for build status

README.md
=> [docs] Fix gif's url

src/client/core/utils/position.js, test/functional/fixtures/regression/gh-883/pages/index.html, test/functional/fixtures/regression/gh-883/test.js, test/functional/fixtures/regression/gh-883/testcafe-fixtures/index-test.js
=> Use body.clientWidth/Height if document is in compat mode (closes #883)

package.json, test/server/data/client-fn-compilation/basic/expected-node10.js
=> Update hammerhead (10.0.2) and testcafe (0.10.0-alpha1) versions

README.md, docs/articles/documentation/getting-started/index.md, docs/articles/documentation/test-api/actions/click.md, docs/articles/documentation/test-api/actions/double-click.md, docs/articles/documentation/test-api/actions/drag-element.md, docs/articles/documentation/test-api/actions/hover.md, docs/articles/documentation/test-api/actions/index.md, docs/articles/documentation/test-api/actions/navigate.md, docs/articles/documentation/test-api/actions/press-key.md, docs/articles/documentation/test-api/actions/resize-window.md, docs/articles/documentation/test-api/actions/right-click.md, docs/articles/documentation/test-api/actions/select-text.md, docs/articles/documentation/test-api/actions/take-screenshot.md, docs/articles/documentation/test-api/actions/type-text.md, docs/articles/documentation/test-api/actions/upload.md, docs/articles/documentation/test-api/assertions.md, docs/articles/documentation/test-api/handling-native-dialogs.md, docs/articles/documentation/test-api/obtaining-data-from-the-client.md, docs/articles/documentation/test-api/pausing-the-test.md, docs/articles/documentation/test-api/selecting-page-elements/selector-options.md, docs/articles/documentation/test-api/selecting-page-elements/selectors.md, docs/articles/documentation/test-api/test-code-structure.md, docs/articles/documentation/test-api/working-with-iframes.md, docs/articles/index.html, examples/.eslintrc, examples/running-tests-using-travis-and-saucelabs/tests/index-test.js
\cc @DevExpress/testcafe-docs @VasilyStrelyaev
=> [docs] Update docs to use new snapshot property shorthand feature. Modify variable names and style to follow recommended code practices.

src/client/automation/playback/scroll.js, src/client/core/utils/position.js, test/functional/fixtures/regression/gh-882/pages/index.html, test/functional/fixtures/regression/gh-882/test.js, test/functional/fixtures/regression/gh-882/testcafe-fixtures/index-test.js
=> Round fractional scroll values in move and scroll (closes #882)

package.json, src/client/core/page-unload-barrier.js, src/client/driver/command-executors/execute-action.js, test/functional/fixtures/api/raw/click/pages/index.html
=> Improve pageUnloadBarrier waiting logic (closes #245)

package.json
=> Fix testcafe-browser-tools@1.1.2 as dep (closes #915)

package.json, src/cli/log.js
=> Use "is-ci" package for better CI environment determination.

.publishrc, package.json
=> Bump version to release

docs/articles/blog/2016-11-8-testcafe-v0-10-0-released.md
=> [docs] Add a blog post announcing v0.10.0

package.json, test/functional/fixtures/regression/gh-889/pages/index.html, test/functional/fixtures/regression/gh-889/test.js, test/functional/fixtures/regression/gh-889/testcafe-fixtures/index.test.js
due to https://github.com/DevExpress/testcafe-hammerhead/issues/901
/cc @AlexanderMoskovkin @georgiy-abbasov
=> Functional test 'Click on children of table' fixed

docs/articles/documentation/recipes/index.md, docs/articles/documentation/recipes/running-tests-locally.md
This PR adds one easy way to run your tests into a local server.
=> [docs] Add running locally recipe

src/test-run/commands/actions.js, test/functional/fixtures/regression/gh-963/pages/index.html, test/functional/fixtures/regression/gh-963/test-data/file1.txt, test/functional/fixtures/regression/gh-963/test.js, test/functional/fixtures/regression/gh-963/testcafe-fixtures/index-test.js, test/server/test-run-commands-test.js
/cc @inikulin @georgiy-abbasov @MarinaRukavitsyna
=> Ignore element visibility for upload actions (closes #963)

.publishrc, package.json
/cc @inikulin 
Let's wait for the tests before merging
=> Update hammerhead. Set alpha tag. Bump version.

src/compiler/es-next/compile-client-function.js, src/compiler/es-next/index.js, test/server/data/client-fn-compilation/typeof/expected-node10.js
=> Add workaround for broken re-export (closes #969)

docs/README.md, docs/articles/documentation/recipes/index.md, docs/articles/documentation/recipes/test-static-html-pages.md, docs/nav/nav-menu.yml
=> [docs] Add missed links to Testing static files receipe

src/client/automation/playback/scroll.js, test/functional/fixtures/regression/gh-973/pages/container.html, test/functional/fixtures/regression/gh-973/pages/index.html, test/functional/fixtures/regression/gh-973/test.js, test/functional/fixtures/regression/gh-973/testcafe-fixtures/container.test.js, test/functional/fixtures/regression/gh-973/testcafe-fixtures/index.test.js
=> Extra margin added to scroll automation (closes #973)

test/client/fixtures/automation/regression-test.js
=> QUnit regression test 'Wrong scroll' fixed

src/client-functions/selector-builder/snapshot-properties.js, test/functional/fixtures/api/es-next/selector/test.js, test/functional/fixtures/api/es-next/selector/testcafe-fixtures/selector-test.js
=> 'selectedIndex' property to ElementSnapshot added (closes #951)

src/client/automation/playback/scroll.js, test/functional/fixtures/regression/gh-987/pages/index.html, test/functional/fixtures/regression/gh-987/test.js, test/functional/fixtures/regression/gh-987/testcafe-fixtures/index.test.js
\cc @AlexanderMoskovkin, @helen-dikareva, @MarinaRukavitsyna
=> Fixed extra distance in scroll automation (closes #987)

src/client-functions/client-function-builder.js, src/client-functions/selector-builder/index.js
=> Fixed deprecated message for .with method

package.json, src/client/automation/playback/press/key-press-simulator.js, test/client/fixtures/automation/submit-on-enter-test.js
/cc @AlexanderMoskovkin 
Tests simulate real behavior, I've checked it.
=> Update testcafe-hammerhead. Bump version.

src/client-functions/selector-builder/add-api.js, test/functional/fixtures/api/es-next/selector/test.js, test/functional/fixtures/api/es-next/selector/testcafe-fixtures/selector-test.js
/cc @kirovboris @helen-dikareva
=> Fix number filter in selector methods (closes #1003)

src/client-functions/selector-builder/add-api.js, test/functional/fixtures/api/es-next/selector/pages/index.html, test/functional/fixtures/api/es-next/selector/test.js, test/functional/fixtures/api/es-next/selector/testcafe-fixtures/selector-test.js, test/server/compiler-test.js, test/server/data/test-suites/selector-filter-arg-is-not-a-function-or-string/testfile.js
/cc @inikulin @helen-dikareva @kirovboris
=> Add "filter" method for selectors (closes #990)

docs/articles/documentation/test-api/actions/right-click.md, docs/articles/documentation/test-api/actions/select-text.md, docs/articles/documentation/test-api/assertions.md, docs/articles/documentation/test-api/obtaining-data-from-the-client.md, examples/basic/test.js, examples/running-tests-using-travis-and-saucelabs/tests/index-test.js
=> [docs] Correct examples to not use deprecated API

README.md, docs/articles/index.html
=> [docs] Add a link to our roadmap to the landing page and Readme.md

docs/articles/documentation/test-api/selecting-page-elements/dom-node-snapshots.md, docs/articles/documentation/using-testcafe/command-line-interface.md
\cc @DevExpress/testcafe-docs, @lexkazakov
=> [docs] Added "Starting browser with arguments" paragraph

package.json, src/client/automation/playback/press/key-press-simulator.js, src/client/core/utils/key-maps.js, test/functional/fixtures/regression/gh-993/pages/index.html, test/functional/fixtures/regression/gh-993/test.js, test/functional/fixtures/regression/gh-993/testcafe-fixtures/index.test.js
\cc @AlexanderMoskovkin, @helen-dikareva, @MarinaRukavitsyna
=> Added 'event.key' and 'event.keyIdenfitifiers' properties to keypress simulator, updated hammerhead version (closes #993)

docs/articles/documentation/test-api/actions/index.md, docs/articles/documentation/test-api/actions/select-text.md, docs/articles/documentation/test-api/obtaining-data-from-the-client.md, docs/articles/index.html
\cc @DevExpress/testcafe-docs, @lexkazakov
=> [docs] Avoid using functions as Selector arguments

docs/articles/documentation/test-api/selecting-page-elements/dom-node-snapshots.md
\cc @DevExpress/testcafe-docs, @lexkazakov
=> [docs] dom-node-snapshots.md doc updated

README.md, docs/articles/index.html
README.MD updated according to Selector changes
/cc @helen-dikareva @inikulin
=> [docs] Update Readme.md according to selectors changes

README.md, docs/articles/documentation/extending-testcafe/browser-provider-plugin/browser-provider-methods.md, docs/articles/documentation/extending-testcafe/browser-provider-plugin/index.md, docs/articles/index.html
=> [docs] Add info about nightmare

README.md, docs/articles/documentation/test-api/actions/click.md, docs/articles/documentation/test-api/actions/double-click.md, docs/articles/documentation/test-api/actions/drag-element.md, docs/articles/documentation/test-api/actions/hover.md, docs/articles/documentation/test-api/actions/press-key.md, docs/articles/documentation/test-api/actions/resize-window.md, docs/articles/documentation/test-api/actions/select-text.md, docs/articles/documentation/test-api/actions/type-text.md, docs/articles/documentation/test-api/actions/upload.md, docs/articles/documentation/test-api/handling-native-dialogs.md, docs/articles/documentation/test-api/obtaining-data-from-the-client.md, docs/articles/documentation/test-api/pausing-the-test.md, docs/articles/documentation/test-api/test-code-structure.md, docs/articles/index.html, examples/running-tests-using-travis-and-saucelabs/tests/index-test.js
Waits for https://github.com/DevExpress/testcafe/pull/997
=> [docs] Correct examples to use build-in assertions

.publishrc, docs/articles/blog/2016-11-8-testcafe-v0-10-0-released.md, package.json
=> [docs] Bump version. Set 'latest' tag.

docs/articles/documentation/test-api/assertions/assertion-api.md
=> [docs] Fix contains and notContains assertions description

appveyor.yml, test/client/legacy-fixtures/api/press-test.js, test/functional/fixtures/regression/gh-889/test.js
\cc @AlexanderMoskovkin, @LavrovArtem
=> corrected options for regression test gh-889, fixed client legacy press test

src/client-functions/selector-builder/add-api.js, test/functional/fixtures/api/es-next/selector/pages/index.html, test/functional/fixtures/api/es-next/selector/test.js, test/functional/fixtures/api/es-next/selector/testcafe-fixtures/selector-test.js
=> Add 'dependencies' parameter and `index` argument to the filter method (closes #1025)

.publishrc, package.json
=> Bump version. Set 'alpha' tag

package.json, src/api/globals/fixture.js, src/errors/runtime/message.js, src/test-run/index.js, test/functional/config.js, test/functional/fixtures/auth/test.js, test/functional/fixtures/auth/testcafe-fixtures/basic-auth-with-correct-credentials-test.js, test/functional/fixtures/auth/testcafe-fixtures/basic-auth-with-wrong-credentials-test.js, test/functional/fixtures/auth/testcafe-fixtures/ntlm-auth-check-username-test.js, test/functional/legacy-fixtures/auth/test.js, test/functional/legacy-fixtures/auth/testcafe-fixtures/basic-auth-with-correct-credentials.test.js, test/functional/legacy-fixtures/auth/testcafe-fixtures/basic-auth-with-wrong-credentials.test.js, test/functional/legacy-fixtures/auth/testcafe-fixtures/ntlm-auth-check-username.test.js, test/functional/setup.js, test/functional/site/basic-auth-server.js, test/functional/site/index.js, test/functional/site/ntlm-auth-server.js, test/server/compiler-test.js, test/server/data/test-suites/httpAuth/domain-is-not-a-string.js, test/server/data/test-suites/httpAuth/pass-is-empty.js, test/server/data/test-suites/httpAuth/username-is-not-a-string.js
\сс @AlexanderMoskovkin @helen-dikareva @MarinaRukavitsyna
=> Add NTLM and Basic authentication support (close #955)

src/client/automation/playback/type/index.js, test/functional/fixtures/regression/gh-1054/pages/index.html, test/functional/fixtures/regression/gh-1054/test.js, test/functional/fixtures/regression/gh-1054/testcafe-fixtures/index.test.js
\cc @AlexanderMoskovkin, @helen-dikareva,  @lexkazakov
=> Type automation fixed (closes #1054)

src/api/assertion.js, test/functional/fixtures/api/es-next/assertions/test.js, test/functional/fixtures/api/es-next/assertions/testcafe-fixtures/assertions-test.js
=> Implement .match() assertion (closes #1038)

src/client/automation/utils/offsets.js, src/errors/test-run/index.js, src/errors/test-run/templates.js, src/errors/test-run/type.js, src/test-run/commands/options.js, test/client/fixtures/automation/click-test.js, test/client/legacy-fixtures/api/click-test.js, test/functional/fixtures/api/es-next/click/test.js, test/functional/fixtures/api/es-next/click/testcafe-fixtures/click-test.js, test/functional/fixtures/api/es-next/double-click/test.js, test/functional/fixtures/api/es-next/drag/test.js, test/functional/fixtures/api/es-next/hover/test.js, test/functional/fixtures/api/es-next/right-click/test.js, test/functional/fixtures/api/es-next/right-click/testcafe-fixtures/right-click-test.js, test/functional/fixtures/api/raw/click/test.js, test/server/data/expected-test-run-errors/action-integer-option-error, test/server/test-run-command-options-test.js, test/server/test-run-commands-test.js, test/server/test-run-error-formatting-test.js
/cc @AlexanderMoskovkin @georgiy-abbasov
=> Negative offset options are allowed for actions (closes #981)

CHANGELOG.md, docs/articles/documentation/test-api/actions/action-options.md
/cc @VasilyStrelyaev @AlexanderMoskovkin
=> [docs] Information about negative offsets added

CHANGELOG.md, docs/articles/documentation/test-api/a-z-index.md, docs/articles/documentation/test-api/test-code-structure.md, docs/nav/nav-menu.yml
=> [docs] Http Authentication

CHANGELOG.md, docs/articles/documentation/recipes/index.md, docs/articles/documentation/recipes/using-page-model.md, docs/articles/index.html, docs/nav/nav-menu.yml
Text may need to be polished here and there - so just \cc if the approach is right and everything is technically correct.
=> [docs] Add the Page Model recipe

src/runner/index.js
=> Remove unecessary line in Runner (#1047 follow up)

docs/articles/documentation/using-testcafe/command-line-interface.md, docs/articles/documentation/using-testcafe/programming-interface/runner.md
https://github.com/DevExpress/testcafe/issues/1047
=> [docs] Describe the 'app-command' option

docs/articles/documentation/test-api/assertions/assertion-api.md
https://github.com/DevExpress/testcafe/issues/1038
=> [docs] Describe the match and notMatch assertions

src/compiler/index.js
=> Split sources into chunks during compiling (closes #1090)

src/runner/browser-set.js, test/server/runner-test.js
/cc @inikulin @georgiy-abbasov
=> Increase remote browser connection waiting timeout (closes #1078)

test/website/test.js
=> [docs] Fix false broken links

docs/README.md, docs/articles/documentation/recipes/using-testcafe-with-gulp.md, docs/nav/nav-menu.yml
=> [docs] Add recipe - using TestCafe with Gulp.js

docs/articles/documentation/test-api/index.md, docs/articles/documentation/test-api/test-code-structure.md
A note for https://github.com/DevExpress/testcafe/issues/1083
=> [docs] Add a note about a eslint plugin

docs/articles/index.html
http://strelyaev-w8:8080/testcafe/
=> [docs] New section on the landing page

docs/articles/documentation/test-api/selecting-page-elements/selectors.md
=> [docs] Add info that selector methods can take a negative index

docs/articles/documentation/recipes/using-page-model.md, docs/articles/documentation/recipes/using-testcafe-with-gulp.md
=> [docs] Armina's corrections to recipes

src/api/assertion.js, src/client-functions/client-function-builder.js, src/client-functions/result-promise.js, src/client-functions/selector-builder/add-api.js, src/client-functions/selector-builder/index.js, test/functional/fixtures/api/es-next/assertions/pages/index.html, test/functional/fixtures/api/es-next/assertions/test.js, test/functional/fixtures/api/es-next/assertions/testcafe-fixtures/assertions-test.js, test/functional/fixtures/api/es-next/client-function/test.js, test/functional/fixtures/api/es-next/client-function/testcafe-fixtures/client-fn-test.js, test/server/compiler-test.js, test/server/data/test-suites/client-fn-cant-resolve-test-run/testfile.js
\cc @AlexanderMoskovkin @helen-dikareva @georgiy-abbasov
=> Implement assertion smart query mechanism for ClientFunctions (closes #1009)

package.json
=> Bump version to 0.12.0-alpha3

package.json
=> Update hammerhead, bump version to 0.12.0-alpha4

Gulpfile.js, package.json, src/client/driver/command-executors/execute-action.js, src/client/driver/index.js, src/client/driver/script-execution-barrier.js, test/client/config-qunit-server-app.js, test/client/fixtures/driver/script-execution-barrier-test.js, test/functional/fixtures/driver/script-execution-barrier/pages/index.html, test/functional/fixtures/driver/script-execution-barrier/pages/script.js, test/functional/fixtures/driver/script-execution-barrier/test.js, test/functional/fixtures/driver/script-execution-barrier/testcafe-fixtures/index-test.js
=> Implement scriptExecutionBarrier (closes #1072)

docs/articles/documentation/recipes/running-tests-in-firefox-and-chrome-using-travis-ci.md, docs/articles/documentation/recipes/running-tests-using-travis-ci-and-sauce-labs.md, docs/articles/documentation/recipes/test-static-html-pages.md, examples/basic/package.json, examples/running-tests-in-firefox-and-chrome-using-travis-ci/.travis.yml, examples/running-tests-in-firefox-and-chrome-using-travis-ci/README.md, examples/running-tests-in-firefox-and-chrome-using-travis-ci/index.html, examples/running-tests-in-firefox-and-chrome-using-travis-ci/package.json, examples/running-tests-in-firefox-and-chrome-using-travis-ci/server.js, examples/running-tests-in-firefox-and-chrome-using-travis-ci/tests/index-test.js, examples/running-tests-using-travis-and-saucelabs/.travis.yml, examples/running-tests-using-travis-and-saucelabs/package.json
Running example: https://travis-ci.org/AndreyBelym/testcafe-example-travis-local/builds/184244319
Requires https://github.com/DevExpress/testcafe/pull/1068
=> [docs] Provide recipe for running Chrome and Firefox with Travis

docs/README.md, docs/articles/documentation/recipes/index.md, docs/articles/documentation/recipes/running-tests-in-firefox-and-chrome-using-travis-ci.md, docs/articles/documentation/test-api/selecting-page-elements/selectors.md, docs/nav/nav-menu.yml
=> [docs] Add missed links to new recipes

src/client/core/page-unload-barrier.js
Form submission handling is obsolete in page-unload-barrier since it's handled in testcafe-hammerhead (page-navigation-watch)
/cc @helen-dikareva @miherlosev
=> Remove obsolete form submit handling from page unload barrier (closes #1115)

package.json
=> Update hammerhead and browser-tools versions, bump testcafe version to 0.12.0-alpha5

docs/articles/documentation/test-api/actions/resize-window.md, docs/articles/documentation/test-api/actions/take-screenshot.md, docs/articles/documentation/using-testcafe/command-line-interface.md, docs/articles/documentation/using-testcafe/programming-interface/runner.md
=> [docs] Remove notes about unsupported Linux from docs (part of #1117)

src/browser/provider/index.js, src/screenshots/capturer.js, src/warnings/message.js, test/functional/fixtures/api/es-next/resize-window/test.js, test/functional/fixtures/api/es-next/take-screenshot/test.js
=> Remove warnings about Linux (closes #1117)

src/client/automation/utils/offsets.js, test/functional/fixtures/regression/gh-1136/pages/index.html, test/functional/fixtures/regression/gh-1136/test.js, test/functional/fixtures/regression/gh-1136/testcafe-fixtures/index.test.js
\cc @AlexanderMoskovkin, @AndreyBelym, @VasilyStrelyaev
=> Round element fractional width\height while calculating automation offset options (closes #1136)

docs/articles/documentation/test-api/a-z-index.md, docs/articles/documentation/test-api/selecting-page-elements/selectors.md
by @VasilyStrelyaev 
/cc @kirovboris @lexkazakov @DevExpress/testcafe-docs
=> [docs] Describe "Adding Custom Properties to Element State" (#749)

docs/articles/documentation/test-api/selecting-page-elements/selectors.md
=> [docs] Fix a typo in examples (extra parenthesis)

docs/articles/blog/2017-1-19-testcafe-v0-12-0-released.md
=> [docs] v0.12.0 announcement post

.publishrc, package.json
/cc @AlexanderMoskovkin @VasilyStrelyaev
=> Bump version 0.12.0

CHANGELOG.md
=> [docs] Changelog for v0.12.1

src/client/automation/playback/move.js, test/functional/fixtures/regression/gh-1161/pages/index.html, test/functional/fixtures/regression/gh-1161/test.js, test/functional/fixtures/regression/gh-1161/testcafe-fixtures/index.test.js
\cc @AlexanderMoskovkin, @AndreyBelym, @VasilyStrelyaev
=> Fixed event emulation in move automation (closes #1161)

docs/articles/documentation/using-testcafe/programming-interface/browserconnection.md, docs/articles/documentation/using-testcafe/programming-interface/createtestcafe.md, docs/articles/documentation/using-testcafe/programming-interface/index.md, docs/articles/documentation/using-testcafe/programming-interface/runner.md, docs/articles/documentation/using-testcafe/programming-interface/testcafe.md
=> [docs] Remove async/await from Programming Interface examples

README.md
=> [docs] Add ecosystem section to README

docs/articles/index.html
=> [docs] Add a point about ecosystem to the landing page

.publishrc, package.json
=> Update testcafe-hammerhead (10.3.2). Bump version.

src/client/core/prevent-real-events.js
/cc @georgiy-abbasov @AndreyBelym
=> Allow to open DevTools on mac (closes #1193)

src/client/browser/index.js
=> Fix sending an 'init-script' request from the idle page

.travis.yml
This reverts commit d34f5d29f11a558e60d9686fea645970d83a0e49.
=> Revert "Disable some travis tasks"

package.json, src/api/globals/testing-unit.js
=> Use hammerhead@10.3.3; Enable file protocol in TestingUnit (closes #1213)

src/.eslintrc, src/api/globals/fixture.js, src/api/test-controller/index.js, src/browser/connection/gateway.js, src/browser/connection/index.js, src/errors/test-run/templates.js, src/runner/browser-job.js, src/runner/fixture-hook-controller.js, src/runner/task.js, src/test-run/index.js, src/test-run/state.js, test/functional/fixtures/api/es-next/hooks/test.js, test/functional/fixtures/api/es-next/hooks/testcafe-fixtures/fixture-before-fail.js, test/functional/fixtures/api/es-next/hooks/testcafe-fixtures/fixture-ctx.js, test/functional/fixtures/api/es-next/hooks/testcafe-fixtures/fixture-hooks-seq.js, test/functional/fixtures/api/es-next/hooks/testcafe-fixtures/fixture-hooks.js, test/functional/setup.js, test/server/compiler-test.js, test/server/data/test-suites/fixture-after-is-not-a-function/testfile.js, test/server/data/test-suites/fixture-before-is-not-a-function/testfile.js, test/server/runner-test.js
\cc @AlexanderMoskovkin @georgiy-abbasov @AndreyBelym
=> Implement fixture.before and fixture.after hooks (closes #903)

src/client-functions/selector-builder/add-api.js, test/functional/fixtures/api/es-next/selector/test.js, test/functional/fixtures/api/es-next/selector/testcafe-fixtures/selector-test.js, test/server/compiler-test.js, test/server/data/test-suites/selector-next-sibling-incorrect-arg-type/testfile.js, test/server/data/test-suites/selector-prev-sibling-incorrect-arg-type/testfile.js
\cc @AlexanderMoskovkin @georgiy-abbasov @miherlosev
=> Add Selector.nextSibling, Selector.prevSibling methods (closes #1218)

docs/articles/documentation/recipes/debugging-tests.md
=> [docs] Debugging recipe - Remove the part about client debugging

docs/articles/documentation/test-api/actions/action-options.md
=> [docs] Add documentation for `paste` TypeOption

docs/articles/documentation/test-api/a-z-index.md, docs/articles/documentation/test-api/selecting-page-elements/selector-options.md, docs/articles/documentation/test-api/selecting-page-elements/selectors.md
=> [docs] Remove documentation for deprecated API

docs/articles/documentation/test-api/selecting-page-elements/selectors.md
=> [docs] Selector - Add a note that indexes are zero-based

docs/articles/documentation/test-api/test-code-structure.md
=> [docs] Add description for test controller import

docs/articles/documentation/index.md
=> [docs] Add Recipes to index.md

package.json
=> Versions is updated

docs/README.md, docs/articles/documentation/test-api/a-z-index.md, docs/articles/documentation/test-api/actions/action-options.md, docs/articles/documentation/test-api/actions/press-key.md, docs/articles/documentation/test-api/actions/select-text.md, docs/articles/documentation/test-api/test-code-structure.md, docs/articles/documentation/using-testcafe/command-line-interface.md, docs/articles/documentation/using-testcafe/programming-interface/runner.md, docs/nav/nav-menu.yml
=> [docs] Describe the action speed option

CHANGELOG.md
=> [docs] Add changelog for v0.13.0

docs/articles/blog/2017-2-16-testcafe-v0-13-0-released.md, docs/articles/documentation/test-api/actions/action-options.md, docs/articles/documentation/test-api/test-code-structure.md
=> [docs] Add announcement post for v0.13.0

CHANGELOG.md, docs/articles/documentation/test-api/actions/action-options.md, docs/articles/documentation/test-api/test-code-structure.md
=> [docs] Add info about IDE plugins to changelog

docs/articles/documentation/test-api/a-z-index.md
=> [docs] Add fixture hooks to a-z index

.publishrc, package.json
=> Bump version

test/functional/fixtures/api/es-next/speed/test.js
=> Fix an unstable test (closes #1253)

src/client/automation/index.js, src/client/driver/command-executors/prepare-browser-manipulation.js
=> Hide cursor when a browser manipulation is in execution (closes #1245)

src/client-functions/selector-builder/add-api.js, test/functional/fixtures/regression/gh-1240/pages/index.html, test/functional/fixtures/regression/gh-1240/test.js, test/functional/fixtures/regression/gh-1240/testcafe-fixtures/index-test.js
=> Fix filtering by index (when the result is empty) (closes #1240)

package.json, src/client/core/prevent-real-events.js, test/functional/fixtures/regression/gh-1275/pages/index.html, test/functional/fixtures/regression/gh-1275/test.js, test/functional/fixtures/regression/gh-1275/testcafe-fixtures/index-test.js
/cc @AndreyBelym @helen-dikareva
=> Fix native blur event preventing (fixes #1275)

docs/README.md, docs/articles/documentation/test-api/index.md, docs/articles/documentation/test-api/waiting-for-page-elements-to-appear.md, docs/nav/nav-menu.yml
=> [docs] Describe autowait mechanism

src/browser/provider/index.js, test/server/browser-provider-test.js
=> Catch provider init errors (closes #1282)

src/client/automation/playback/scroll.js, src/client/core/utils/style.js, test/functional/fixtures/regression/gh-1057/pages/index.html, test/functional/fixtures/regression/gh-1057/test.js, test/functional/fixtures/regression/gh-1057/testcafe-fixtures/index-test.js
=> Adaptive scroll margins to avoid fixed elements (closes #1057)

src/client/ui/status-bar/index.js
=> Status bar grabbed focus problem fixed (closes #1200)

docs/articles/blog/2016-12-8-testcafe-v0-11-0-released.md, docs/articles/blog/2017-2-16-testcafe-v0-13-0-released.md, docs/articles/documentation/using-testcafe/common-concepts/browser-support.md
=> [docs] Add the BrowserStack plugin to the list

src/client/driver/driver.js, src/client/driver/statuses/driver.js, src/test-run/commands/utils.js, src/test-run/index.js
=> Debugger stops on assertions during test running step-by-step (closes #1288)

src/compiler/index.js, src/compiler/raw-file.js, test/server/compiler-test.js, test/server/data/test-suites/raw/invalid2.testcafe
=> Add comprehensive message for RAW data compiler errors (closes #1302)

src/client/automation/playback/click/select-child.js, test/functional/fixtures/regression/gh-1311/pages/index.html, test/functional/fixtures/regression/gh-1311/test.js, test/functional/fixtures/regression/gh-1311/testcafe-fixtures/index.test.js
=> SelectChildClickAutomation fixed (closes #1311)

src/client-functions/selectors/add-api.js, src/client-functions/selectors/selector-builder.js, test/functional/fixtures/api/es-next/selector/test.js, test/functional/fixtures/api/es-next/selector/testcafe-fixtures/selector-test.js, test/server/compiler-test.js, test/server/data/test-suites/selector-add-custom-dom-properties-incorrect-arg-type/testfile.js, test/server/data/test-suites/selector-add-custom-methods-incorrect-arg-type/testfile.js, test/server/data/test-suites/selector-custom-dom-method-incorrect-arg-type/testfile.js, test/server/data/test-suites/selector-custom-dom-property-incorrect-arg-type/testfile.js
=> Added .addCustomMethods method (closes #1212)

docs/articles/documentation/recipes/running-tests-in-firefox-and-chrome-using-travis-ci.md, docs/articles/documentation/test-api/actions/resize-window.md, docs/articles/documentation/test-api/actions/take-screenshot.md, examples/running-tests-in-firefox-and-chrome-using-travis-ci/.travis.yml
=> [docs] Add info about window managers on Linux (closes #1171)

README.md
\cc @AlexanderMoskovkin @inikulin
=> [docs] Add a BrowserStack logo to Readme

src/client/driver/command-executors/client-functions/client-function-executor.js, src/client/driver/command-executors/execute-action.js, src/client/driver/command-executors/execute-navigate-to.js, src/client/driver/command-executors/prepare-browser-manipulation.js, src/client/driver/driver-link/child.js, src/client/driver/driver.js, src/client/driver/iframe-driver.js, src/client/driver/status.js, src/client/driver/statuses/assertion-retries.js, src/test-run/client-messages.js, src/test-run/commands/service.js, src/test-run/commands/type.js, src/test-run/commands/utils.js, src/test-run/index.js, test/server/compiler-test.js
=> debuggin logic unified

package.json, test/server/compiler-test.js
=> Fix linter error

docs/articles/documentation/using-testcafe/programming-interface/browserconnection.md, docs/articles/documentation/using-testcafe/programming-interface/runner.md, docs/articles/documentation/using-testcafe/programming-interface/testcafe.md
=> [docs] Promote the testcafe.close() function

README.md, docs/articles/index.html
=> [docs] Remove mentions of ES2016 from feature descriptions

docs/articles/blog/2017-3-28-testcafe-v0-14-0-released.md
=> [docs] Add v0.14.0 announcement blog post

src/role/index.js, src/test-run/index.js
=> Do not set breakpoints during switching to role (closes #1359)

docs/articles/documentation/recipes/test-static-html-pages.md
\cc @DevExpress/testcafe-docs @miherlosev 
fixes #1394
=> [docs] Add info about relative paths to the recipe

src/client/ui/status-bar/index.js
=> We prevent execution of page elements' handlers which binded with capturing after click on status panel (closes #1389)

src/client/automation/playback/press/shortcuts.js, test/functional/fixtures/regression/gh-1388/pages/index.html, test/functional/fixtures/regression/gh-1388/test.js, test/functional/fixtures/regression/gh-1388/testcafe-fixtures/index-test.js
/cc @helen-dikareva @georgiy-abbasov
=> Fix actions order during pressKey execution for shortcuts (fixes #1388)

src/cli/argument-parser.js, src/runner/index.js, src/test-run/index.js
=> CLI option for debugging is implemented (closes #1347)

docs/README.md, docs/articles/documentation/recipes/README.md, docs/articles/documentation/recipes/using-testcafe-with-grunt.md, docs/nav/nav-menu.yml
=> [docs] Add a recipe about using TestCafe with Grunt

src/client/core/index.js, src/client/core/prevent-real-events.js, test/client/fixtures/automation/automations-test.js, test/client/fixtures/automation/click-test.js, test/client/fixtures/automation/content-editable/api-actions-content-editable-test/index-test.js, test/client/fixtures/automation/content-editable/regression-test/index-test.js, test/client/fixtures/automation/content-editable/select-and-type-content-editable-test/index-test.js, test/client/fixtures/automation/dblclick-test.js, test/client/fixtures/automation/detection-element-after-events-simulation-test.js, test/client/fixtures/automation/drag-test.js, test/client/fixtures/automation/focus-blur-change-test.js, test/client/fixtures/automation/hover-test.js, test/client/fixtures/automation/key-press-simulation-test.js, test/client/fixtures/automation/out-of-bounds-test.js, test/client/fixtures/automation/press-shortcuts-test.js, test/client/fixtures/automation/press-test.js, test/client/fixtures/automation/rclick-test.js, test/client/fixtures/automation/real-actions-blocker-test.js, test/client/fixtures/automation/regression-test.js, test/client/fixtures/automation/select-element-test.js, test/client/fixtures/automation/select-test/index-test.js, test/client/fixtures/automation/submit-on-enter-test.js, test/client/fixtures/automation/tab-emulation-test.js, test/client/fixtures/automation/type-test.js
=> Add ability to turn off user events prevention (close #1399)

src/api/exportable-lib.js, src/role/index.js, src/test-run/bookmark.js, src/test-run/index.js, test/functional/fixtures/api/es-next/roles/pages/preserved-page.html, test/functional/fixtures/api/es-next/roles/test.js, test/functional/fixtures/api/es-next/roles/testcafe-fixtures/preserve-url-test.js, test/server/api-test.js, test/server/data/test-suites/role-options-is-not-an-object/testfile.js, test/server/data/test-suites/role-preserve-url-option-is-not-a-boolean/testfile.js
=> Implement Role preserveUrl option (closes #1339)

src/client/driver/driver.js, src/client/test-run/index.js.mustache
@AlexanderMoskovkin @helen-dikareva
=> Add ability to set custom command handler for the 'ClientDriver' (close #1400)

package.json, src/client/driver/command-executors/client-functions/selector-executor/sandboxed-node-properties.js, test/functional/fixtures/api/es-next/roles/test.js, test/functional/fixtures/api/es-next/roles/testcafe-fixtures/preserve-url-test.js, test/functional/fixtures/api/es-next/selector/test.js, test/functional/fixtures/api/es-next/selector/testcafe-fixtures/selector-test.js
=> Hammerhead updated to 10.6.5 version

docs/articles/documentation/using-testcafe/installing-testcafe.md
\cc @DevExpress/testcafe-docs @AndreyBelym
=> [docs] Describe how to work with the Docker image

docs/articles/documentation/test-api/selecting-page-elements/dom-node-state.md
=> [docs] Describe the DOM Node State hasAttribute method

src/client-functions/selectors/add-api.js, src/client-functions/selectors/selector-builder.js, src/client/driver/command-executors/client-functions/selector-executor/filter.js, src/utils/make-reg-exp.js, test/functional/fixtures/api/es-next/selector/pages/index.html, test/functional/fixtures/api/es-next/selector/test.js, test/functional/fixtures/api/es-next/selector/testcafe-fixtures/selector-error-test.js, test/functional/fixtures/api/es-next/selector/testcafe-fixtures/selector-test.js, test/server/api-test.js, test/server/data/test-suites/selector-with-attr-arg-is-not-regexp-or-string/attrName.js, test/server/data/test-suites/selector-with-attr-arg-is-not-regexp-or-string/attrValue.js
=> withAttr implemented (closes #1346)

src/client/automation/playback/press/key-press-simulator.js, src/client/core/utils/dom.js, test/functional/fixtures/regression/gh-1424/pages/index.html, test/functional/fixtures/regression/gh-1424/test.js, test/functional/fixtures/regression/gh-1424/testcafe-fixtures/index-test.js
/cc @helen-dikareva @georgiy-abbasov
=> Raise 'click' if 'enter' is pressed on a button (fixes #1424)

docs/articles/documentation/test-api/authentication/user-roles.md
=> [docs] Describe the preserveUrl role option

docs/articles/documentation/test-api/a-z-index.md, docs/articles/documentation/test-api/selecting-page-elements/selectors.md
=> [docs] Describe the withAttr method

docs/articles/documentation/test-api/debugging.md, docs/articles/documentation/using-testcafe/command-line-interface.md
\cc @DevExpress/testcafe-docs @helen-dikareva
=> [docs] Describe the debugging cli option

test/client/fixtures/driver/script-execution-barrier-test.js, test/functional/fixtures/driver/script-execution-barrier/pages/index.html, test/functional/setup.js
=> Fix launch old and legacy functional tests

docs/articles/documentation/using-testcafe/command-line-interface.md, docs/articles/documentation/using-testcafe/programming-interface/runner.md
=> [docs] Describe the proxy option

src/embedding-utils.js
=> Add few classes to embedding utils

src/client-functions/selectors/add-api.js, test/functional/fixtures/api/es-next/selector/test.js, test/functional/fixtures/api/es-next/selector/testcafe-fixtures/selector-test.js, test/server/api-test.js, test/server/data/test-suites/selector-with-attr-arg-is-not-regexp-or-string/attrName.js, test/server/data/test-suites/selector-with-attr-arg-is-not-regexp-or-string/attrValue.js
=> withAttr method renamed withAttribute

docs/articles/blog/2017-4-26-testcafe-v0-15-0-released.md
=> [docs] Add an announcement blog post for v0.15.0

package.json
This will help to solve https://github.com/DevExpress/testcafe/issues/1448
=> Hammerhead updated to 10.6.7 version

docs/articles/documentation/test-api/assertions/assertion-api.md
=> [docs] Assertions' swapped arguments are fixed (closes #1462)

src/browser/connection/index.js, src/browser/provider/index.js, src/browser/provider/plugin-host.js, src/runner/browser-job-result.js, src/runner/browser-job.js, src/runner/task.js, test/functional/.eslintrc, test/functional/fixtures/browser-provider/job-reporting/pages/index.html, test/functional/fixtures/browser-provider/job-reporting/test.js, test/functional/fixtures/browser-provider/job-reporting/testcafe-fixtures/index-test.js, test/functional/fixtures/browser-provider/job-reporting/testcafe-fixtures/long-test.js, test/functional/setup.js
=> Implement task status reporting in providers (closes #1320)

src/utils/get-viewport-width.js
=> Add lower limit for the viewport width (closes #1469)

.publishrc, package.json, src/client/automation/playback/press/key-press-simulator.js
Waiting for https://github.com/DevExpress/testcafe-hammerhead/pull/1119
=> Fix regression test for GH-1424

src/client/driver/command-executors/prepare-browser-manipulation.js
/cc @georgiy-abbasov @helen-dikareva
=> Hide UI when taking screenshots (closes #1357)

src/client-functions/selectors/add-api.js, src/client-functions/selectors/selector-attribute-filter.js, src/client-functions/selectors/selector-text-filter.js, src/client/automation/playback/click/select-child.js, src/client/core/index.js, src/client/core/utils/dom.js, src/client/ui/select-element.js
https://github.com/DevExpress/testcafe-studio/issues/791
/cc @AlexanderMoskovkin
=> Some changes required to SelectorGenerator in Studio

src/client/automation/playback/press/shortcuts.js, test/client/fixtures/automation/press-shortcuts-test.js
=> Fix press action shortcuts (closes #1499)

src/client/automation/playback/move/event-sequence/base.js, src/client/automation/playback/move/event-sequence/index.js, src/client/automation/playback/move/index.js, src/client/core/utils/dom.js, test/functional/fixtures/api/es-next/hover/pages/index.html, test/functional/fixtures/api/es-next/hover/test.js, test/functional/fixtures/api/es-next/hover/testcafe-fixtures/hover-test.js
[will be refactored when #1490 is merged]
=> Raise 'mouseenter' and 'mouseleave' events during moving (closes #1426)

package.json, src/compiler/load-babel-libs.js, src/compiler/test-file/formats/es-next.js, test/server/compiler-test.js, test/server/data/test-suites/flow-type-declarations/flower-marker.js, test/server/data/test-suites/flow-type-declarations/no-flow-marker.js, test/server/data/test-suites/flow-type-declarations/rocket-launch.js, test/server/data/test-suites/flow-type-declarations/rocket.js, test/server/data/test-suites/flow-type-declarations/testfile.js
=> Strip Flow type declarations from the compiled test files (closes #1329)

Gulpfile.js, test/functional/fixtures/api/es-next/generic-errors/test.js
=> Workaround for gulp-git on node 8

src/client/automation/playback/drag/base.js, test/functional/fixtures/api/es-next/drag/pages/drag-and-drop.html
=> Don't raise click after drag and drop (closes #1516)

test/server/data/test-suites/typescript-basic/testfile1.ts, test/server/data/test-suites/typescript-basic/testfile2.ts, test/server/data/test-suites/typescript-defs/client-functions.ts, test/server/data/test-suites/typescript-defs/roles.ts, test/server/data/test-suites/typescript-defs/selectors.ts, test/server/data/test-suites/typescript-exportable-lib-dep/testfile.ts, test/server/data/test-suites/typescript-mixed-dep/testfile.ts, ts-defs/index.d.ts
=> Allow usage of fixture and page as template tags in TypeScript

package.json, src/browser/provider/built-in/chrome/cdp.js, src/browser/provider/built-in/chrome/config.js, src/browser/provider/built-in/chrome/index.js, src/browser/provider/built-in/chrome/local-chrome.js, test/server/chrome-provider-config-test.js
\cc @AlexanderMoskovkin @helen-dikareva 
* Fix a problem when the specific Chrome version can't be started by
path;
* Fix path mode syntax
* Fix default emulated width/height for detailed emulation config
* Fix ugly looking emulation window by resizing browser to the emulation
viewport
=> Fix problems in Chrome provider

README.md, docs/articles/documentation/getting-started/README.md, docs/articles/documentation/test-api/README.md, docs/articles/index.html
=> [docs] Add info about TypeScript support in README

README.md, docs/articles/blog/2017-1-19-testcafe-v0-12-0-released.md, docs/articles/documentation/using-testcafe/common-concepts/browser-support.md, docs/articles/index.html
Reviewed by @lexkazakov and @helen-dikareva
=> [docs] Some changes in docs about Chrome device emulation mode

CHANGELOG.md
=> [docs] Update changelog for v0.16.0

README.md
=> [docs] add info about axe integration

package.json
@AlexanderMoskovkin @AndreyBelym
=> Update hammerhead, bump version (close #1502)

CHANGELOG.md, README.md, docs/articles/blog/2017-6-13-testcafe-v0-16-0-released.md, docs/articles/documentation/getting-started/README.md, docs/articles/documentation/test-api/typescript-support.md, docs/articles/index.html
=> [docs] Fix a mistake with 'using of'

package.json
=> Make tmp a dependency (closes #1547)

docs/articles/blog/2017-6-13-testcafe-v0-16-0-released.md
=> [docs] Note about Canary build added to blog post

docker/Dockerfile, package.json
=> Fix screenshots on Docker (closes #1540)

package.json, src/client/automation/playback/press/shortcuts.js, src/client/automation/playback/type/type-text.js, src/client/automation/utils/utils.js, test/client/fixtures/automation/press-test.js, test/client/fixtures/automation/type-test.js
=> fix `t.typeText() not working with React's new version (15.6.1)` (close #1558)

CHANGELOG.md
=> [docs] Add a changelog for v0.16.2

src/client-functions/selectors/add-api.js, src/client-functions/selectors/selector-attribute-filter.js, test/functional/fixtures/api/es-next/selector/testcafe-fixtures/selector-test.js
=> `withAttribute` method filter attribute by strict name match when string argument is provided (closes #1548)

docs/articles/documentation/test-api/selecting-page-elements/selectors.md
=> [docs] Selectors - Add info about string arguments to withText and withAttribute methods

docs/articles/documentation/test-api/actions/take-screenshot.md
=> [docs] Fix the description of t.takeScreenshot's path parameter

docs/README.md, docs/articles/documentation/recipes/README.md, docs/articles/documentation/recipes/testing-select-elements.md, docs/nav/nav-menu.yml
=> [docs] Add the select elements recipe

docs/articles/documentation/test-api/selecting-page-elements/selectors.md
=> [docs] Fix snapshot example

src/client/driver/driver.js, src/role/index.js, src/test-run/commands/service.js, src/test-run/commands/type.js, src/test-run/index.js, test/functional/fixtures/api/es-next/roles/pages/index.html, test/functional/fixtures/api/es-next/roles/pages/login-page.html, test/functional/fixtures/api/es-next/roles/testcafe-fixtures/anonymous-role-test.js, test/functional/fixtures/api/es-next/roles/testcafe-fixtures/use-role-test.js
=> Implement backup/restore storages functionality for useRole (close #1454)

src/test-run/commands/actions.js, src/test-run/execute-js-expression.js, test/functional/fixtures/api/raw/click/testcafe-fixtures/click.testcafe, test/server/test-run-commands-test.js
=> Fix Selectors in RAW API (follow up #1466)

docs/articles/documentation/test-api/actions/press-key.md
fixes #1636
@DevExpress/testcafe-docs
=> [docs] Add remarks about meta and alt keys

src/client/automation/playback/visible-element-automation.js, test/functional/fixtures/regression/gh-1521/pages/fixed-element.html, test/functional/fixtures/regression/gh-1521/test.js, test/functional/fixtures/regression/gh-1521/testcafe-fixtures/index-test.js
=> Avoid waiting for a fixed element (follow up #1521)

src/compiler/test-file/parse-es-next.js, test/server/data/test-suites/tests-fixtures-in-iife/testfile.js, test/server/parse-fixture-test.js
=> Fixed parsing tests and fixtures in IIFE (closes #1652)

src/compiler/test-file/parse-es-next.js, src/embedding-utils.js, test/server/parse-fixture-test.js
=> Added the possibility to parse esnext code (close #1653)

package.json, src/browser/connection/gateway.js, src/browser/connection/index.js, src/browser/connection/status.js, src/cli/index.js, src/cli/log.js, src/client/browser/index.js, src/index.js, src/notifications/debug-logger.js, src/testcafe.js
=> revert bff4a699 commit

package.json, src/client/automation/errors.js, src/client/automation/index.js, src/client/automation/playback/click/index.js, src/client/automation/playback/dblclick.js, src/client/automation/playback/drag/base.js, src/client/automation/playback/hover.js, src/client/automation/playback/rclick.js, src/client/automation/playback/select/select-text.js, src/client/automation/playback/type/index.js, src/client/automation/playback/visible-element-automation.js, src/client/driver/command-executors/client-functions/selector-executor/index.js, src/client/driver/command-executors/execute-action.js, src/client/driver/command-executors/execute-selector.js, src/client/driver/driver.js, test/client/legacy-fixtures/api/click-test.js, test/functional/fixtures/regression/gh-1521/pages/changing-element.html, test/functional/fixtures/regression/gh-1521/test.js, test/functional/fixtures/regression/gh-1521/testcafe-fixtures/index-test.js
=> Handle case when element is changing during automation waiting

README.md, docs/articles/documentation/using-testcafe/common-concepts/reporters.md
=> [docs] Add info about new custom reporters

CHANGELOG.md
=> [docs] Introduce changelog for v0.17.0

package.json, src/runner/test-run-controller.js, test/functional/fixtures/api/es-next/click/test.js, test/functional/legacy-fixtures/page-js-errors/test.js, test/functional/legacy-fixtures/page-js-errors/testcafe-fixtures/unreachable-page.test.js
waiting for 3.1.1 version of testcafe-lagacy-api
=> incorrect testing time calculation for xunit and json reporters fixed (сloses #1674)

src/compiler/test-file/formats/typescript.js
=> Fix TypeScript on MacOS (fixes #1696)

src/browser/provider/built-in/chrome/cdp.js
=> Workaround for the latest Canary (closes #1685)

src/client/automation/playback/hover.js, src/client/automation/playback/visible-element-automation.js, test/functional/fixtures/regression/gh-1521/pages/hover-element.html, test/functional/fixtures/regression/gh-1521/test.js, test/functional/fixtures/regression/gh-1521/testcafe-fixtures/index-test.js, test/functional/fixtures/regression/gh-1679/pages/index.html, test/functional/fixtures/regression/gh-1679/test.js, test/functional/fixtures/regression/gh-1679/testcafe-fixtures/index-test.js
/cc @helen-dikareva @AndreyBelym
=> Improve visible-element-automation (fixes #1679)

CHANGELOG.md
=> [docs] Add changelog for v0.17.1

src/client-functions/selectors/add-api.js, src/test-run/execute-js-expression.js, test/functional/fixtures/api/raw/selector/pages/index.html, test/functional/fixtures/api/raw/selector/test.js, test/functional/fixtures/api/raw/selector/testcafe-fixtures/test.testcafe
=> Support all types of selectors in raw api

src/errors/test-run/index.js, src/errors/test-run/templates.js, src/errors/test-run/type.js, src/test-run/commands/actions.js, src/test-run/commands/assertion.js, src/test-run/commands/utils.js, src/test-run/execute-js-expression.js, test/functional/fixtures/api/raw/assertions/test.js, test/functional/fixtures/api/raw/assertions/testcafe-fixtures/assertions.testcafe, test/server/data/expected-test-run-errors/assertion-executable-argument-error, test/server/test-run-commands-test.js, test/server/test-run-error-formatting-test.js
@VasilyStrelyaev Check error message pls.
=> Add js-expr assertion parameters support (close #1715)

.md-lint/faq.json, Gulpfile.js, docs/articles/faq/README.md, docs/nav/top-menu-items.yml
\cc @DevExpress/testcafe-docs @Nuarat 
Preview at http://strelyaev-w8:8080/testcafe/faq/
=> [docs] Add the FAQ section

package.json, src/browser/provider/index.js, src/client/driver/command-executors/prepare-browser-manipulation.js, src/client/driver/driver.js, src/client/driver/iframe-driver.js, src/client/test-run/iframe.js.mustache, src/client/test-run/index.js.mustache, test/functional/fixtures/api/es-next/resize-window/test.js
Fixes: 
* #1732 
* #1551 
* #1625 ?
=> Improve browser manipulations mechanism. Update testcafe-browser-tools (fixes #1732, fixes #1551)

docker/testcafe-docker.sh
=> Use exposed Docker ports (closes #1728)

.gitattributes
=> Fix EOL in TS files

test/server/data/test-suites/typescript-defs/client-functions.ts, test/server/data/test-suites/typescript-defs/selectors.ts, ts-defs/index.d.ts
=> Fix ClientFunction.dependencies TS definitions (closes #1713)

CHANGELOG.md
/cc @DevExpress/testcafe-docs @lexkazakov
=> [docs] Add changelog v0.17.2

docs/articles/documentation/test-api/working-with-iframes.md
\cc @helen-dikareva @AlexanderMoskovkin
=> [docs] Improve the example in the Iframes topic

docs/articles/blog/2017-6-13-testcafe-v0-16-0-released.md, docs/articles/documentation/using-testcafe/common-concepts/browser-support.md
@DevExpress/testcafe-docs 
fixes #1694
=> [docs] Get rid of notes about Chrome Canary

docs/articles/documentation/test-api/assertions/assertion-api.md
=> [docs] Add info about passing objects to contains and notContains assertions

src/compiler/test-file/formats/es-next/get-test-list.js, test/server/data/test-suites/regression-gh-1771/testfile.js, test/server/parse-fixture-test.js
=> Fixed test parser (closes #1771)

Gulpfile.js, src/client/automation/playback/drag/base.js, src/client/automation/playback/drag/to-element.js, src/client/automation/playback/drag/to-offset.js, src/test-run/commands/actions.js, src/test-run/commands/options.js, test/functional/fixtures/api/es-next/drag/pages/index.html, test/functional/fixtures/api/es-next/drag/test.js, test/functional/fixtures/api/es-next/drag/testcafe-fixtures/drag-test.js, test/server/data/test-suites/typescript-defs/test-controller.ts, test/server/test-run-command-options-test.js, test/server/test-run-commands-test.js, ts-defs/index.d.ts
/cc @AndreyBelym @helen-dikareva @VasilyStrelyaev
=> Add destination offset options to dragToElement (closes #982)

README.md
Committing @Nuarat 's text to README.md
=> [docs] New Readme

package.json, src/client/core/utils/text-selection.js, test/client/fixtures/automation/content-editable/api-actions-content-editable-test/index-test.js, test/client/fixtures/automation/content-editable/api-actions-content-editable-test/index.html, test/functional/fixtures/api/es-next/select-text/pages/index.html, test/functional/fixtures/api/es-next/select-text/test.js, test/functional/fixtures/api/es-next/select-text/testcafe-fixtures/select-text-test.js
see comment [here](https://github.com/DevExpress/testcafe/pull/1768#issuecomment-327791998)
=> Qunit tests for inverse selection of contenteditable elements fixed

docs/README.md, docs/articles/documentation/recipes/README.md, docs/articles/documentation/recipes/finding-code-issues-with-flow-type-checker.md, docs/articles/index.html, docs/nav/nav-menu.yml
\cc @DevExpress/testcafe-docs @AndreyBelym 
fixes #1553
=> [docs] Add a recipe about using Flow with TestCafe

src/cli/argument-parser.js, src/client/driver/driver.js, src/client/ui/status-bar/index.js, src/notifications/debug-logger.js, src/runner/index.js, src/test-run/commands/service.js, src/test-run/index.js, test/server/cli-argument-parser-test.js
Here is how does it look now: https://www.screencast.com/t/kDkx9J5sj
/cc @helen-dikareva @AndreyBelym @VasilyStrelyaev @DevExpress/testcafe
=> Add the debugOnFail option (closes #1608)

docs/articles/documentation/using-testcafe/command-line-interface.md, docs/articles/documentation/using-testcafe/common-concepts/reporters.md, docs/articles/documentation/using-testcafe/programming-interface/runner.md
\cc @DevExpress/testcafe-docs @AlexanderMoskovkin
=> [docs] Mention using multiple reporters

src/client/ui/status-bar/index.js
for https://github.com/DevExpress/testcafe-studio/issues/1031
=> status bar hiding and showing behavior changed (fix for TestCafe Studio)

docs/articles/documentation/test-api/actions/action-options.md, docs/articles/documentation/test-api/actions/drag-element.md
\cc @DevExpress/testcafe-docs @AlexanderMoskovkin
=> [docs] Action options - describe destination point for drag action

docs/articles/documentation/test-api/obtaining-data-from-the-client.md
\cc @DevExpress/testcafe-docs @AlexanderMoskovkin
=> [docs] Describe creating client functions that run async client code

src/browser/provider/built-in/chrome/index.js, src/browser/provider/built-in/chrome/local-chrome.js, src/browser/provider/built-in/chrome/runtime-info.js, src/browser/provider/built-in/firefox/config.js, src/browser/provider/built-in/firefox/index.js, src/browser/provider/built-in/firefox/local-firefox.js, src/browser/provider/built-in/firefox/marionette-client.js, src/browser/provider/built-in/firefox/runtime-info.js, src/browser/provider/built-in/remote.js, src/browser/provider/index.js, src/browser/provider/plugin-host.js, src/browser/provider/utils/kill-browser-process.js, test/server/firefox-provider-config-test.js
It's done, but requires #1792.
The actual changes are in the second commit.
=> Firefox headless (closes #1742)

docs/articles/blog/2017-9-29-testcafe-v0-18-0-alpha1-released.md
=> [docs] Add a v0.18.0-alpha1 announcement

src/browser/provider/utils/kill-browser-process.js, src/utils/promisified-functions.js
\cc @AlexanderMoskovkin @kirovboris
=> Fix Headless Chrome termination (closes #1826)

src/browser/provider/built-in/chrome/index.js, src/browser/provider/built-in/firefox/marionette-client.js, src/browser/provider/built-in/firefox/runtime-info.js, src/browser/provider/index.js, src/browser/provider/utils/client-functions.js
\cc @LavrovArtem @helen-dikareva
=> Fix Headless Firefox resize (closes #1825)

docs/nav/top-menu-items.yml, docs/publications/publications.json
=> [docs] Add publication list

src/browser/provider/built-in/firefox/marionette-client.js
\cc @AlexanderMoskovkin @churkin
=> Increase number of connection attempts for Marionette (closes #1824)

docs/articles/documentation/getting-started/README.md
Changed "theirs state" to "their state".
=> [docs] Fix typo in README.md

src/client/ui/status-bar/index.js, test/functional/fixtures/regression/gh-1846/pages/index.html, test/functional/fixtures/regression/gh-1846/test.js, test/functional/fixtures/regression/gh-1846/testcafe-fixtures/index-test.js
=> Fix Status panel (fixes #1846)

docs/README.md, docs/articles/documentation/test-api/README.md, docs/articles/documentation/test-api/a-z-index.md, docs/articles/documentation/test-api/accessing-console-messages.md, docs/nav/nav-menu.yml
@DevExpress/testcafe-docs @AlexanderMoskovkin
=> [docs] Describe accessing console messages

docs/articles/blog/2017-10-9-testcafe-v0-18-0-released.md
=> [docs] Add an announcement blog post

Gulpfile.js
=> [docs] Update the Gulpfile.js

CHANGELOG.md
=> [docs] Add changelog for v0.18.1

CHANGELOG.md
\cc @VasilyStrelyaev @DevExpress/testcafe-docs
=> [docs] Update changelog about #1874

package.json, src/client-functions/selectors/add-api.js, test/functional/fixtures/regression/gh-1907/pages/index.html, test/functional/fixtures/regression/gh-1907/test.js, test/functional/fixtures/regression/gh-1907/testcafe-fixtures/index-test.js
=> Pass options to derivative selectors (fixes #1907)

src/client/driver/driver-link/child.js, src/client/driver/driver.js, src/client/driver/iframe-driver.js, test/functional/fixtures/regression/gh-1842/pages/iframe.html, test/functional/fixtures/regression/gh-1842/pages/index.html, test/functional/fixtures/regression/gh-1842/pages/reloading-iframe.html, test/functional/fixtures/regression/gh-1842/test.js, test/functional/fixtures/regression/gh-1842/testcafe-fixtures/index-test.js, test/functional/fixtures/regression/gh-1875/pages/iframe.html, test/functional/fixtures/regression/gh-1875/pages/index.html, test/functional/fixtures/regression/gh-1875/test.js, test/functional/fixtures/regression/gh-1875/testcafe-fixtures/index-test.js
/cc @helen-dikareva @AndreyBelym
=> Iframe driver fixes (closes #1842, closes #1875)

package.json, src/client/core/utils/dom.js
@AlexanderMoskovkin @AndreyBelym
=> update hammerhead (close #1895)

.publishrc, CHANGELOG.md, package.json
/cc @AndreyBelym @miherlosev @lexkazakov
=> Bump version. Update Changelog (0.18.2)

CHANGELOG.md, package.json, test/client/fixtures/automation/click-test.js, test/client/fixtures/automation/hover-test.js
@AlexanderMoskovkin @AndreyBelym @lexkazakov
=> Bump version. Update changelog (0.18.3)(close #1920)

.publishrc, package.json
=> prepared dev version to publish

docs/articles/documentation/test-api/obtaining-data-from-the-client.md
Without eslint it would be tough to find where you fail if you copy this doc example
=> [docs] Fix non-ASCII char in docs

docs/articles/documentation/test-api/assertions/assertion-api.md
=> [docs] Fix redundant quotation marks

docs/articles/documentation/using-testcafe/command-line-interface.md, docs/articles/documentation/using-testcafe/programming-interface/runner.md
=> [docs] Fix a mistake and add details on how to run portable browsers
