.publishrc, CHANGELOG.md, package.json
=> updated hammerhead, bumped testcafe version (close #1912, #1922)

CHANGELOG.md
=> [docs] Fix lint errors

CHANGELOG.md
=> [docs] Add changelog for v0.18.5

docs/articles/documentation/test-api/obtaining-data-from-the-client.md, docs/articles/documentation/using-testcafe/command-line-interface.md
=> [docs] A couple of small fixes

docs/publications/publications.json
\cc @AlexanderMoskovkin @Nuarat
=> [docs] Add info about two new publications

package.json, src/client/automation/playback/scroll.js, src/client/core/utils/style.js, test/functional/fixtures/regression/gh-1940/pages/body-scroll.html, test/functional/fixtures/regression/gh-1940/pages/document-and-body-have-scroll.html, test/functional/fixtures/regression/gh-1940/pages/document-scroll.html, test/functional/fixtures/regression/gh-1940/test.js, test/functional/fixtures/regression/gh-1940/testcafe-fixtures/index.js
waiting for  https://github.com/DevExpress/testcafe-hammerhead/pull/1377
=> TestCafe scrolls page when body has scroll

docs/articles/documentation/test-api/selecting-page-elements/selectors.md
=> [docs] Fix selector's dependency param description

.publishrc, Gulpfile.js, package.json
=> 0.18.6-dev20171129

package.json
=> 0.18.6-dev20171201

docs/publications/publications.json
=> [docs] Add a publication

package.json
=> 0.18.6-dev20171207

docs/articles/faq/README.md
=> [docs] Update the FAQ topic with window resize actions

package.json
=> 0.18.6-dev20171211

src/browser/provider/built-in/chrome/runtime-info.js
=> Disable password bubble (closes #1913)

docs/articles/documentation/test-api/actions/type-text.md
\cc @helen-dikareva @AlexanderMoskovkin
=> [docs] Describe typing formats for specific inputs

src/browser/provider/built-in/firefox/runtime-info.js
=> Skip default browser check (closes #1926)

src/client/driver/command-executors/client-functions/selector-executor/index.js, test/functional/fixtures/regression/gh-1994/pages/index.html, test/functional/fixtures/regression/gh-1994/test.js, test/functional/fixtures/regression/gh-1994/testcafe-fixtures/index.js
The element that matches the specified selector is not visible
=> Fix click behavior if  element was firstly hidden and then recreated on timeout (closes #1994)

src/browser/provider/built-in/chrome/local-chrome.js
=> Add delay when starting multiple Chrome instances on Mac (closes #2035)

package.json
@AlexanderMoskovkin @AndreyBelym
=> 0.18.7-dev20180117 (close #1897)

docs/articles/documentation/using-testcafe/command-line-interface.md, docs/publications/publications.json
=> [docs] Change single quotes to double quotes in Command Line Interface

README.md
Fix browser support page link.
=> [docs] Fix link in README.md

docs/articles/index.html
and [removed a popup](https://github.com/DevExpress/testcafe-gh-page-assets/pull/45) (since now we have links)
https://1667b6e1.ngrok.io/testcafe/
=> [docs] Added links to the landing page

docs/articles/documentation/test-api/a-z-index.md, docs/articles/documentation/test-api/actions/resize-window.md
=> [docs] Add maximizeWindow to A-Z index

src/cli/argument-parser.js
\cc @AlexanderMoskovkin \cc @churkin 
Related to https://testcafe-discuss.devexpress.com/t/tests-executed-several-times-via-cli/811
Supersedes #1247
=> Fix default test folders on macOS

docs/articles/documentation/test-api/a-z-index.md, docs/articles/documentation/test-api/selecting-page-elements/dom-node-state.md, docs/articles/documentation/test-api/selecting-page-elements/selectors/functional-style-selectors.md, docs/articles/documentation/test-api/selecting-page-elements/selectors/selector-options.md, docs/articles/documentation/test-api/waiting-for-page-elements-to-appear.md
=> [docs] Describe the filterVisible and filterHidden selector methods

docs/README.md, docs/articles/documentation/test-api/selecting-page-elements/README.md, docs/articles/documentation/test-api/selecting-page-elements/examples-of-working-with-dom-elements.md, docs/articles/documentation/test-api/selecting-page-elements/examples-of-working-with-page-dom.md, docs/nav/nav-menu.yml
=> [docs] Add an example topic for working with page dom

docs/articles/documentation/test-api/a-z-index.md, docs/articles/documentation/test-api/selecting-page-elements/selectors/functional-style-selectors.md
=> [docs] Describe selector's withExactText method

Gulpfile.js
@AlexanderMoskovkin @AndreyBelym 
See https://github.com/gulpjs/gulp/blob/master/docs/API.md#optionsread
=> speed up 'test-server' task

docs/publications/publications.json
=> [docs] Add recent publications

src/client/ui/screenshot-mark.js, src/screenshots/constants.js, src/screenshots/crop.js, src/screenshots/generate-mark.js
=> Make screenshot mark black'n'white (closes #2145)

src/errors/stack-cleaning-hook.js
=> Import stack-chain only when it's necessary (closes #2166)

src/client/ui/screenshot-mark.js, src/screenshots/constants.js, src/screenshots/crop.js, src/screenshots/generate-mark.js, test/server/test-run-commands-test.js
=> Fix screenshot cropping on Mac Retina(closes #2159)

src/client/driver/command-executors/browser-manipulation/ensure-crop-options.js, test/functional/fixtures/api/es-next/take-screenshot/test.js, test/functional/fixtures/api/es-next/take-screenshot/testcafe-fixtures/take-element-screenshot.js
=> Fix scroll target error message when cropping bounds are invalid

package.json, src/cli/cli.js, src/cli/index.js, src/cli/termination-handler.js, src/compiler/test-file/api-based.js, src/errors/stack-cleaning-hook.js
=> Finally fix stack-chain issue (closes #2166)

CHANGELOG.md
=> [docs] Add changelog for v0.19.1

docs/articles/index.html
=> [docs] Update the landing page description

.gitignore
=> add .vscode folder to gitignore

src/screenshots/capturer.js, test/functional/fixtures/api/legacy/smoke/test.js, test/functional/fixtures/api/legacy/smoke/testcafe-fixtures/screenshots.test.js, test/functional/setup.js
=> Restore screenshot capturer backward compatibility (closes #2235)

package.json, src/utils/promisified-functions.js
=> Use graceful-fs (closes #1702)

src/browser/provider/built-in/chrome/cdp.js
=> Use new touch emulation method (closes #2268)

README.md
TestCafe Live
CloudBrowserTesting
=> [docs] Added two plugins

Gulpfile.js, package.json
=> Added test-client-local task

CHANGELOG.md, docs/articles/documentation/getting-started/README.md, docs/articles/documentation/using-testcafe/common-concepts/browsers/browser-support.md
=> [docs] Minor changes

src/api/test-controller/assertion.js, src/assertions/executor.js, src/errors/test-run/index.js, src/errors/test-run/templates.js, src/errors/test-run/type.js, src/test-run/commands/options.js, src/utils/thennable.js, test/functional/config.js, test/functional/fixtures/api/es-next/assertions/test.js, test/functional/fixtures/api/es-next/assertions/testcafe-fixtures/assertions-test.js, test/server/data/expected-test-run-errors/assertion-unawaited-promise-error, test/server/test-run-command-options-test.js, test/server/test-run-commands-test.js, test/server/test-run-error-formatting-test.js, ts-defs/index.d.ts
Fixes #2207 
I expect you all will have feedback on the message language and the new error class I introduced, `AssertionUnawaitedPromiseError`, as there are still some pending questions from me in #2207.
=> Throw error when running assertion on unawaited Promises

Gulpfile.js, appveyor.yml, test/functional/config.js, test/functional/setup.js
=> Run legacy api functional tests on push

src/api/request-hooks/hook.js, src/api/request-hooks/request-mock.js, test/server/request-hooks-test.js
=> Request mock should handle only specified requests (part of #2336)

src/browser/provider/built-in/firefox/runtime-info.js
=> Disable session recovery bubble in Firefox

src/api/request-hooks/request-logger.js, test/server/request-hooks-test.js
=> Fix request logger error for delayed response

CODE_OF_CONDUCT.md
=> [docs] update code_of_conduct

docs/articles/documentation/test-api/intercepting-http-requests/mocking-http-responses.md
=> [docs] filter parameter is required

CHANGELOG.md, docs/articles/documentation/test-api/assertions/README.md
//cc @DevExpress/testcafe-docs @miherlosev 
Review only _CHANGELOG.md_, _assertions/README.md_ was added to another pull request
=> [docs] Changelog v20

.publishrc, .travis.yml, package.json
=> Bump version (release); require Node.js>=6.0.0

docs/articles/blog/2018-05-15-testcafe-v0-20-0-released.md
=> [docs] release notes corrected

CHANGELOG.md, docs/articles/blog/2018-05-15-testcafe-v0-20-0-released.md
=> [docs] fix broken link

CHANGELOG.md, docs/articles/blog/2018-05-15-testcafe-v0-20-0-released.md
=> [docs] absolute links specified

blog/testcafe-v0-20-0-released.html, feed.xml
=> absolute links specified in release notes

src/browser/provider/built-in/firefox/runtime-info.js
=> Add a pref into Firefox temp profile for disabling SHIELD

Gulpfile.js, src/browser/provider/built-in/index.js, src/compiler/compile-client-function.js, src/compiler/load-babel-libs.js, src/utils/node-version.js, test/server/compiler-test.js
=> Remove node v4 artefacts

CONTRIBUTING.md, README.md, docs/articles/blog/2016-10-17-introducing-testcafe-open-source-testing-framework.md, docs/articles/documentation/test-api/selecting-page-elements/examples-of-working-with-dom-elements.md, docs/nav/top-menu-items.yml
\cc @kirovboris @MargaritaLoseva @Nuarat 
I left one link in the FAQ topic because it points to a specific thread (Why not Selenium) and we didn't come up with a good way to move it to SC.
=> [docs] Remove forum links

docs/tweets/tweets.json
\cc @kirovboris 
Replace a tweet for which @Nuarat could not find user consent.
=> [docs] Replace a tweet

.dockerignore
=> Add TS definitions to the Docker image

test/functional/fixtures/api/es-next/take-screenshot/test.js
=> Fix the test for screenshot rewriting warning on *nix

package.json, src/client/driver/driver.js
=> Update hammerhead (close #2469)

src/browser/provider/built-in/chrome/cdp.js, test/functional/fixtures/browser-provider/chrome-emulation/test.js, test/functional/fixtures/browser-provider/chrome-emulation/testcafe-fixtures/index-test.js
=> Fix touch emulation in the recent Chrome (closes #2448)

test/functional/config.js, test/functional/setup.js
=> Fix legacy functional tests on master

CHANGELOG.md, docs/articles/documentation/using-testcafe/command-line-interface.md
\cc @MargaritaLoseva @helen-dikareva @MarinaRukavitsyna
=> [docs] Replace vague phrasing

CHANGELOG.md, docs/README.md, docs/articles/documentation/using-testcafe/README.md, docs/articles/documentation/using-testcafe/installing-testcafe.md, docs/articles/documentation/using-testcafe/using-testcafe-docker-image.md, docs/nav/nav-menu.yml
\cc @DevExpress/testcafe-docs  @AndreyBelym 
Refactored the Docker section into a separate topic and added a note about testing heavy websites.
=> [docs] Docker - Add a note about allocating resources

CHANGELOG.md, docs/articles/documentation/using-testcafe/using-testcafe-docker-image.md
=> [docs] Add a note about sharing win folders with docker

CHANGELOG.md, docs/articles/documentation/test-api/actions/README.md
\cc @DevExpress/testcafe-docs @AndreyBelym 
closes #2389
=> [docs] Add a note about underlying elements

CHANGELOG.md, docs/articles/documentation/test-api/intercepting-http-requests/logging-http-requests.md
\cc @DevExpress/testcafe-docs @miherlosev
=> [docs] Fix a request logger example

CHANGELOG.md, docs/articles/documentation/test-api/selecting-page-elements/selectors/functional-style-selectors.md
https://twitter.com/Mo_Glz/status/1008853799673344001
=> [docs] Add example for withAttribute method

CONTRIBUTING.md, README.md, docs/articles/blog/2016-10-17-introducing-testcafe-open-source-testing-framework.md, docs/articles/documentation/test-api/selecting-page-elements/examples-of-working-with-dom-elements.md, docs/nav/top-menu-items.yml
=> [docs] Move to StackOverflow

docs/articles/documentation/using-testcafe/using-testcafe-docker-image.md
\cc @kirovboris @helen-dikareva @AndreyBelym 
closes #1880
=> [docs] Add info about running remote browsers from Docker

docs/README.md, docs/articles/blog/2017-4-26-testcafe-v0-15-0-released.md, docs/articles/documentation/test-api/README.md, docs/articles/documentation/test-api/actions/navigate.md, docs/articles/documentation/test-api/built-in-waiting-mechanism.md, docs/articles/documentation/test-api/built-in-waiting-mechanisms.md, docs/articles/documentation/test-api/selecting-page-elements/selectors/selector-options.md, docs/nav/nav-menu.yml
=> [docs] Add info about waiting for redirect

README.md
=> [docs] Update README.md for the Studio Release

docs/articles/documentation/extending-testcafe/reporter-plugin/reporter-methods.md, docs/articles/documentation/using-testcafe/command-line-interface.md, docs/articles/documentation/using-testcafe/programming-interface/runner.md
=> [docs] describe new properties of testRunInfo

src/cli/argument-parser.js
\cc @MargaritaLoseva @miherlosev
=> [docs] Correctors checked the --dev option description

docs/articles/documentation/test-api/actions/take-screenshot.md, docs/articles/documentation/using-testcafe/command-line-interface.md, docs/articles/documentation/using-testcafe/programming-interface/runner.md
Waits for Dirk's review
@dirk-pieterse
=> [docs] corrections - screenshotpathpattern

CHANGELOG.md
\cc @DevExpress/testcafe-docs @miherlosev 
Changelog for v0.21.0
=> [docs] Changelog for v0.21.0

.publishrc, package.json
=> Bump version (v0.21.0-alpha.1)

src/client/core/utils/style.js, test/client/fixtures/core/style-utils-test.js
@LavrovArtem @AndreyBelym @AlexKamaev
=> fix wrong 'hasScroll' result for some IE specific case (part of #2511)

docs/articles/faq/README.md
http://strelyaev-w8:8080/testcafe/faq/
=> [docs] Update the FAQ part about TestCafe versions

docs/articles/faq/README.md
\cc @MargaritaLoseva 
When it's just the release dates, it's not quite clear what they mean. One can even think that they are the latest release dates ('Your products are so old?').
=> FAQ - Add explanations about release years

README.md
Added the part of FAQ about differences between the paid, open-source TestCafe and TestCafe Studio.
=> [docs] Add diffs between TestCafe versions

src/cli/argument-parser.js, src/cli/cli.js, src/runner/bootstrapper.js, src/runner/index.js, src/utils/parse-file-list.js, test/server/cli-argument-parser-test.js, test/server/runner-test.js, test/server/util-test.js
@kirovboris @AndreyBelym @churkin
=> Implemented glob pattern support for 'runner.src' method (close #980)

docs/articles/documentation/using-testcafe/programming-interface/runner.md
=> [docs] [WIP] Describe using globs in runner.src

Gulpfile.js
=> remove 'test-client-old-browsers-travis' task

docs/articles/documentation/test-api/intercepting-http-requests/attaching-hooks-to-tests-and-fixtures.md, docs/articles/documentation/test-api/intercepting-http-requests/specifying-which-requests-are-handled-by-the-hook.md
=> [docs] Fix two mistakes in the Request Hooks docs

docs/articles/documentation/test-api/actions/resize-window.md, docs/articles/documentation/test-api/actions/take-screenshot.md
\cc @miherlosev @kirovboris 
Fixes https://github.com/DevExpress/testcafe/issues/2712
=> [docs] Add a note about .NET requirements for browser actions

ts-defs/index.d.ts
=> Update the hooks parameter in TS definitions

package.json
=> update hammerhead (close #2639, close #2670)

CHANGELOG.md
The part about enhancements is ready, bug fixes are on the way.
=> [docs] Introduce changelog for v0.22.0

package.json, src/utils/temp-directory/cleanup-process/index.js, src/utils/temp-directory/cleanup-process/worker.js, test/dependency-licenses-checker.js
=> Add missing module; Improve temp dir logs; Bump version (v0.22.0-alpha.2)

docs/articles/documentation/using-testcafe/command-line-interface.md, docs/articles/documentation/using-testcafe/programming-interface/runner.md
=> [docs] describe stopOnFirstFail option

src/api/test-controller/index.js, src/api/wrap-test-function.js, src/browser/provider/built-in/locally-installed.js, src/browser/provider/built-in/path.js, src/browser/provider/built-in/remote.js, src/browser/provider/utils/argument-parsing.js, src/errors/error-list.js, test/functional/fixtures/api/es-next/test-controller/test.js, test/functional/fixtures/api/es-next/test-controller/testcafe-fixtures/test-controller-test.js
=> Don't track unawaited promises if uncaught error is occured (close #2557)

src/api/request-hooks/hook.js, src/client/automation/playback/dblclick.js, src/test-run/index.js, test/server/request-hooks-test.js
=> fix 'Request hook added multiple times when using filter rule ' (close #2650)

docs/articles/documentation/using-testcafe/programming-interface/runner.md
Please check but don't merge - we need Dirk here.
Fixes #2752
=> [docs] Add details to the quarantine mode description

docs/articles/documentation/README.md, docs/articles/documentation/getting-started/README.md
=> [docs] Add a redirect from the docs root page

src/compiler/test-file/formats/es-next/get-test-list.js, src/compiler/test-file/formats/typescript/get-test-list.js, src/compiler/test-file/test-file-parser-base.js, test/server/data/test-suites/basic/testfile3.js, test/server/parse-fixture-test.js, test/server/runner-test.js
for PR in Studio https://github.com/DevExpress/testcafe-studio/pull/1818
=> Test compiler fixed

docs/articles/blog/2016-11-8-testcafe-v0-10-0-released.md, docs/articles/blog/2016-12-8-testcafe-v0-11-0-released.md, docs/articles/blog/2017-1-19-testcafe-v0-12-0-released.md, docs/articles/blog/2017-2-16-testcafe-v0-13-0-released.md, docs/articles/blog/2017-3-28-testcafe-v0-14-0-released.md, docs/articles/blog/2017-4-26-testcafe-v0-15-0-released.md, docs/articles/documentation/recipes/README.md, docs/articles/documentation/recipes/debug-in-chrome-dev-tools.md, docs/articles/documentation/recipes/debug-in-visual-studio-code.md, docs/articles/documentation/test-api/built-in-waiting-mechanisms.md, docs/articles/documentation/test-api/selecting-page-elements/selectors/README.md, docs/articles/documentation/test-api/selecting-page-elements/selectors/selector-options.md
=> [docs] Add a redirect from the old Selectors topic

docs/articles/documentation/using-testcafe/using-testcafe-docker-image.md
Remove a phrase that seems to be incorrect (https://github.com/DevExpress/testcafe/issues/2946)
=> [docs] Remove a questionable phrase from the Docker topic

docs/articles/documentation/test-api/actions/resize-window.md, docs/articles/documentation/test-api/actions/take-screenshot.md, docs/articles/documentation/using-testcafe/common-concepts/browsers/browser-support.md
=> [docs] Add notes about screenshot and window resize actions (closes #2966)

docs/articles/documentation/using-testcafe/command-line-interface.md, docs/articles/documentation/using-testcafe/programming-interface/runner.md
\cc @AndreyBelym @AlexKamaev @kirovboris 
https://github.com/DevExpress/testcafe/issues/1815
=> [docs] Add a note about what we do if a browser hangs

docs/articles/documentation/test-api/selecting-page-elements/framework-specific-selectors.md
\cc @kirovboris @miherlosev 
closes #2754
=> [docs] Get rid of Angular 2+ notation

docs/articles/faq/README.md
=> [docs] Edit FAQ according to Helen's remarks

docs/articles/documentation/test-api/selecting-page-elements/selectors/functional-style-selectors.md
\cc @kirovboris @helen-dikareva 
closes #2538
=> [docs] Add small examples to the Functional-Style Selectors topic

docs/articles/documentation/test-api/authentication/user-roles.md
\cc @AndreyBelym @kirovboris
closes #2815
=> [docs] Add an example for role's options.preserveUrl

docs/articles/documentation/test-api/obtaining-data-from-the-client.md
\cc @kirovboris @AndreyBelym 
closes #2346
=> [docs] Add an example about importing CF dependencies

docs/articles/documentation/recipes/using-page-model.md
=> [docs] Add actions to the page model

README.md, docs/articles/faq/README.md
=> [docs] Add info that TestCafe Studio is a Preview

docs/articles/documentation/using-testcafe/command-line-interface.md, docs/articles/documentation/using-testcafe/programming-interface/runner.md
Documentation for PR #2841 (issue #2527 )
=> [docs] Add "group" metadata to define which tests will be run

README.md
1. Moved stackoverflow questions to the 'community' section
2. Updated links for bug reports and feature requests
3. Updated the contributing descrtiption, added a 'thank you note' for contributors. Now we can just add a list to the end of this section.
4. Moved the 'badge' section to the end.
=> [docs] Update issues, questions and contributing

CHANGELOG.md
\cc @DevExpress/testcafe-docs @miherlosev
=> [docs] Introduce a changelog for v0.23.1

docs/articles/blog/2018-11-7-testcafe-v0-23-1-released.md
=> [docs] Add an announcement for v0.23.1

CHANGELOG.md, docs/articles/blog/2018-11-7-testcafe-v0-23-1-released.md, docs/articles/documentation/using-testcafe/command-line-interface.md, docs/articles/documentation/using-testcafe/programming-interface/runner.md
=> [docs] Merge documentation for v0.23.1

CONTRIBUTING.md
\cc @DevExpress/testcafe-docs @Nuarat @miherlosev 
Updated the contribution guide with details on how to contribute to documentation.
=> [docs] Update the contribution guide to reflect changes in the docs workflow

CHANGELOG.md, docs/articles/blog/2018-11-7-testcafe-v0-23-1-released.md, docs/articles/documentation/using-testcafe/command-line-interface.md, docs/articles/documentation/using-testcafe/programming-interface/runner.md
No review is required - I'll just wait for tests to pass.
=> [docs] Apply Dirk's corrections

docs/articles/documentation/recipes/debug-in-visual-studio-code.md, docs/articles/documentation/recipes/integrating-testcafe-with-ci-systems/circleci.md
=> [docs] Fix x.y.z in the CircleCI topic

src/runner/bootstrapper.js
=> fix can use parallel condition check

package.json, test/functional/legacy-fixtures/regression/legacy-gh-42/pages/index.html, test/functional/legacy-fixtures/regression/legacy-gh-42/test.js, test/functional/legacy-fixtures/regression/legacy-gh-42/testcafe-fixtures/index.test.js, test/functional/legacy-fixtures/regression/legacy-gh-42/testcafe-fixtures/test_config.json
https://github.com/DevExpress/testcafe-legacy-api/pull/42
=> Update testcafe-legacy-api version

CHANGELOG.md
=> [docs] Add changelog for v0.23.3

docs/articles/documentation/using-testcafe/using-testcafe-docker-image.md
\cc @kirovboris @AndreyBelym 
fixes #3249
=> [docs] Fix the description about using Docker for remote testing

LICENSE
=> [docs] Update year in the license

docs/articles/documentation/using-testcafe/using-testcafe-docker-image.md
\cc @miherlosev @AndreyBelym 
Fixes #3226
=> [docs] Docker - Add a note about where referenced files should be located

src/cli/argument-parser.js, src/configuration/index.js, src/runner/bootstrapper.js, src/runner/index.js, src/utils/prepare-reporters.js, test/server/cli-argument-parser-test.js, test/server/configuration-test.js, test/server/util-test.js
See https://github.com/DevExpress/testcafe/pull/3291#issuecomment-452750646
@VasilyStrelyaev @AndreyBelym
=> Rename 'reporter.outStream' parameter to 'reporter.file'

src/errors/runtime/message.js, src/notifications/warning-message.js, test/server/configuration-test.js, test/server/runner-test.js, test/server/util-test.js
=> Corrected user messages

src/client/browser/idle-page/index.html.mustache
@AndreyBelym 
https://github.com/DevExpress/testcafe/blob/e7eedd5fcf025831139b1daa5b27ec2a1c7b318c/src/testcafe.js#L50
=> Fixed favicon

src/configuration/default-values.js, src/configuration/index.js, src/configuration/option-names.js, src/runner/bootstrapper.js, src/runner/index.js, test/server/configuration-test.js, test/server/helpers/console-wrapper.js, test/server/runner-test.js
=> Fixed wrong overriden options warnings

docs/articles/documentation/test-api/intercepting-http-requests/creating-a-custom-http-request-hook.md
I'm not sure if it's everything that should be updated because of https://github.com/DevExpress/testcafe/pull/3236/
Is it just about `async`?
=> [docs] Add async to onRequest and onResponse methods

documentation/continuous-integration/azure-devops.html, documentation/continuous-integration/circleci.html, documentation/continuous-integration/gitlab.html, documentation/recipes/debug-tests/webstorm.html, documentation/test-api/selecting-page-elements/selectors/using-selectors.html, documentation/using-testcafe/using-testcafe-docker-image.html, feed.xml, sitemap.xml
Mainly, fixes a mistake in the `npm install` command in new recipes.
=> [docs] Update the website 1/25/2019

docs/README.md, docs/articles/blog/2016-12-8-testcafe-v0-11-0-released.md, docs/articles/blog/2017-2-16-testcafe-v0-13-0-released.md, docs/articles/documentation/test-api/obtaining-data-from-the-client/README.md, docs/articles/documentation/using-testcafe/README.md, docs/articles/documentation/using-testcafe/command-line-interface.md, docs/articles/documentation/using-testcafe/common-concepts/concurrent-test-execution.md, docs/articles/documentation/using-testcafe/configuration-file.md, docs/articles/documentation/using-testcafe/programming-interface/createtestcafe.md, docs/articles/documentation/using-testcafe/programming-interface/runner.md, docs/nav/nav-menu.yml, examples/.testcaferc.json
You can already look at this, but it's WIP at least until I ensure that everything works as decribed
=> [docs] Describe the configuration file

docs/articles/blog/2016-12-8-testcafe-v0-11-0-released.md, docs/articles/blog/2017-2-16-testcafe-v0-13-0-released.md, docs/articles/documentation/extending-testcafe/reporter-plugin/README.md, docs/articles/documentation/extending-testcafe/reporter-plugin/helpers.md, docs/articles/documentation/extending-testcafe/reporter-plugin/reporter-methods.md, docs/articles/documentation/test-api/obtaining-data-from-the-client/README.md
\cc @AndreyBelym 
Please check the examples in `README.md`, `helpers.md` and `reporter-methods.md`. If possible, not only the ones that I've changed but also the rest of them.
They were very inconsistent - even used different versions of the API.
=> [docs] Describe changes to reporter API

CHANGELOG.md, docs/articles/documentation/using-testcafe/command-line-interface.md, docs/articles/documentation/using-testcafe/common-concepts/reporters.md, docs/articles/documentation/using-testcafe/configuration-file.md, docs/articles/documentation/using-testcafe/programming-interface/runner.md, examples/.testcaferc.json
=> [docs] API and Configuration File: Rename outStream, file -> output

docs/articles/blog/2019-2-7-migration-from-testcafe-v0-x-y-to-v1-0-0.md
=> [docs] Update Migration Guide according to Andrey's suggestion

CHANGELOG.md
A small thing, but it got me confused at first thinking I was on the wrong repo 😅
=> [docs] Fix year in changelog

package.json
=> Upgraded Typescript to 3.x version (close #3401)

src/client/ui/status-bar/index.js, ts-defs/index.d.ts
according to https://github.com/DevExpress/testcafe-studio/issues/1446
Little changes in docs are required
=> StatusPanel's buttons renaming

src/.eslintrc, src/compiler/index.js, src/compiler/test-file/api-based.js, src/compiler/test-file/base.js, src/compiler/test-file/formats/raw.js, src/compiler/test-file/formats/typescript/compiler.js, src/errors/stack-cleaning-hook.js
=> Fix TS compilation performance (closes #3475)

docs/articles/faq/README.md, docs/articles/index.html, docs/nav/top-menu-items.yml
Updated links to TestCafe Studio, as Bogdan requested.
http://strelyaev-w8:8080/testcafe/
\cc @helen-dikareva @kirovboris
=> [docs] Update FAQ and TestCafe Studio links

test/server/data/test-suites/typescript-defs/assertions.ts, ts-defs/index.d.ts
=> Fix TS defs for the contains assertion (closes #3537)

src/runner/index.js, test/server/data/test-suites/live/test-external-unexisting-module.js, test/server/live-test.js
=> stop spinner in LiveMode if bootstrapping failed (closes #3451)

package.json, src/browser/provider/built-in/chrome/build-chrome-args.js, src/browser/provider/built-in/chrome/local-chrome.js, src/browser/provider/built-in/chrome/runtime-info.js, test/server/util-test.js
=> Added necessary Google Chrome flags for running in the docker (close #3531)

package.json, src/browser/provider/built-in/dedicated/base.js, src/browser/provider/built-in/dedicated/chrome/cdp.js, src/browser/provider/built-in/dedicated/chrome/index.js, src/browser/provider/built-in/dedicated/firefox/index.js, src/browser/provider/built-in/dedicated/firefox/marionette-client/index.js, src/screenshots/capturer.js, src/screenshots/crop.js, src/screenshots/utils.js, src/utils/promisified-functions.js, test/functional/assertion-helper.js, test/functional/fixtures/api/es-next/take-screenshot/testcafe-fixtures/take-screenshot.js
It will fix failing functional tests, and also (I guess) #3541.
=> Fix scrollbar cropping in Firefox 66

docs/articles/documentation/continuous-integration/bitbucket-pipelines.md, docs/articles/documentation/using-testcafe/using-testcafe-docker-image.md, examples/running-tests-in-chrome-using-bitbucket-pipelines-ci/package.json
Closes #3605 
\cc @kirovboris @miherlosev
=> [docs] Remove info about no-sandbox and shm flags for Docker

package.json, test/server/cli-correct-browsers-and-sources-test.js, test/server/live-test.js
Allow to run server tests when Chrome is not installed.
=> Fix tests in Docker

docs/articles/faq/README.md
=> [docs] Update FAQ with network troubleshooting information

src/errors/test-run/index.js, src/errors/test-run/templates.js, src/test-run/index.js, test/functional/fixtures/page-error/test.js, test/server/data/expected-test-run-errors/page-load-error, test/server/data/expected-test-run-errors/uncaught-js-error-on-page, test/server/test-run-error-formatting-test.js
=> Improve page load error (closes #3492)

CHANGELOG.md
=> [docs] Changelog for v1.1.2

docs/articles/documentation/using-testcafe/command-line-interface.md, docs/articles/documentation/using-testcafe/configuration-file.md, docs/articles/documentation/using-testcafe/programming-interface/runner.md
=> [docs] Add info about running Studio tests

docs/articles/faq/README.md
\cc @helen-dikareva @kirovboris
=> [docs] FAQ - Remove info about Studio Preview

src/screenshots/crop.js, test/server/crop-test.js
=> Fix t.takeElementScreenshots for color corrected Displays

docs/articles/documentation/test-api/a-z-index.md, docs/articles/documentation/test-api/selecting-page-elements/selectors/creating-selectors.md, docs/articles/documentation/test-api/selecting-page-elements/selectors/selector-options.md
closes https://github.com/DevExpress/testcafe/issues/3349
\cc @AndreyBelym
=> [docs] Add the selector's options.dependencies description

Gulpfile.js, src/cli/cli.js, src/marketing/data-file.js, src/marketing/index.js, src/marketing/messages.js, src/notifications/warning-message.js, src/runner/bootstrapper.js, src/runner/index.js, test/server/marketing-test.js
The new message with link to TestCafe Studio is displayed in the CLI interface after each 20 runs.
Now, there are 3 such messages.
The texts will be reviewed by Rey. But we check them now and apply the changes later if it will be necessary.
=> Added 3 messages with links to TestCafe Studio

CHANGELOG.md
=> [docs] Changelog v1.1.4

docs/README.md, docs/articles/documentation/recipes/README.md, docs/articles/documentation/recipes/create-a-data-driven-test-case.md, docs/nav/nav-menu.yml
=> [docs] Create a recipe about data-driven testing

docs/articles/documentation/test-api/built-in-waiting-mechanisms.md, docs/articles/documentation/test-api/selecting-page-elements/selectors/selector-options.md
fixes https://github.com/DevExpress/testcafe/issues/3659
=> [docs] Describe waiting for requests

docs/articles/documentation/recipes/extract-reusable-test-code/README.md, docs/articles/documentation/recipes/extract-reusable-test-code/create-helpers.md
=> [docs] Remove single-item bullet lists

CHANGELOG.md
=> [docs] Changelog for v1.2.0

docs/articles/documentation/using-testcafe/common-concepts/browsers/using-chrome-device-emulation.md
fixes https://github.com/DevExpress/testcafe/issues/3116
=> [docs] Describe user agent substitution

docs/articles/roadmap/README.md
Update two features' statuses in the Roadmap.
=> [docs] Update the roadmap

.github/ISSUE_TEMPLATE/bug-report.md
Add the 'Your complete configuration file' section
=> [docs] Add the Config File Request section

docs/articles/documentation/test-api/authentication/user-roles.md
fixes https://github.com/DevExpress/testcafe/issues/1968
=> [docs] Describe role benefits

package.json, src/client/automation/playback/click/click-command.js, src/client/automation/utils/utils.js, src/client/core/utils/dom.js, test/client/before-test.js, test/client/fixtures/automation/click-test.js, test/functional/fixtures/regression/gh-1057/pages/hiddenByFixedParent.html, test/functional/fixtures/regression/gh-1353/pages/index.html, test/functional/fixtures/regression/gh-3501/pages/index.html, test/functional/fixtures/regression/gh-3501/test.js, test/functional/fixtures/regression/gh-3501/testcafe-fixtures/index.js, test/functional/fixtures/regression/gh-883/pages/index.html, test/functional/fixtures/regression/gh-973/pages/index.html
then please review this one https://github.com/DevExpress/testcafe-hammerhead/pull/2054
=> label with attribute tabIndex should be focused (closes #3501)

docs/articles/documentation/using-testcafe/common-concepts/browsers/browser-support.md
fixes https://github.com/DevExpress/testcafe/issues/3952
=> [docs] Browser Support: "Android browser" -> "Google Chrome mobile"

blog/testcafe-v1-3-0-released.html, documentation/test-api/typescript-support.html, documentation/using-testcafe/common-concepts/browsers/browser-support.html, documentation/using-testcafe/configuration-file.html, feed.xml, sitemap.xml
New:
* [Compiler Options](http://vasilystrelyaev.github.io/testcafe/documentation/test-api/typescript-support.html#customize-compiler-options)
* a corresponding [main config option](http://vasilystrelyaev.github.io/testcafe/documentation/using-testcafe/configuration-file.html#tsconfigpath)
* [Release notes](http://vasilystrelyaev.github.io/testcafe/blog/testcafe-v1-3-0-released.html)
* Changed `Android browser` to `Chrome mobile` in [supported browsers](http://vasilystrelyaev.github.io/testcafe/documentation/using-testcafe/common-concepts/browsers/browser-support.html#officially-supported-browsers)
=> [docs] Update the website 7/2/2019

src/configuration/configuration-base.js, src/configuration/typescript-configuration.js, test/server/configuration-test.js
=> remove default tsconfig processing (closes #3979)

blog/index.html, blog/testcafe-v1-3-1-released.html, documentation/test-api/typescript-support.html, documentation/using-testcafe/command-line-interface.html, documentation/using-testcafe/configuration-file.html, documentation/using-testcafe/programming-interface/runner.html, feed.xml, sitemap.xml
* [1.3.1 release notes](http://vasilystrelyaev.github.io/testcafe/blog/testcafe-v1-3-1-released.html)
Updated
* [1.3.0 release notes](http://vasilystrelyaev.github.io/testcafe/blog/testcafe-v1-3-0-released.html)
* [TypeScript Support](http://vasilystrelyaev.github.io/testcafe/documentation/test-api/typescript-support.html#customize-compiler-options)
* [CLI](http://vasilystrelyaev.github.io/testcafe/documentation/using-testcafe/command-line-interface.html#--ts-config-path-path)
* [runner](http://vasilystrelyaev.github.io/testcafe/documentation/using-testcafe/programming-interface/runner.html#tsconfigpath)
* [config](http://vasilystrelyaev.github.io/testcafe/documentation/using-testcafe/configuration-file.htm …
=> [docs] Update the website 7/5/2019

CHANGELOG.md, docs/articles/blog/2019-2-7-migration-from-testcafe-v0-x-y-to-v1-0-0.md, docs/articles/blog/2019-2-7-testcafe-v1-0-0-released.md, docs/articles/documentation/extending-testcafe/reporter-plugin/helpers.md, docs/articles/documentation/extending-testcafe/reporter-plugin/reporter-methods.md, docs/articles/documentation/using-testcafe/command-line-interface.md, docs/articles/documentation/using-testcafe/common-concepts/screenshots-and-videos.md, docs/articles/documentation/using-testcafe/configuration-file.md, docs/articles/faq/README.md
Merge as soon as tests pass - no review needed.
=> [docs] Corrections 7/9/2019

package.json
=> Update lodash (closes #3995)

blog/index.html, blog/migration-from-testcafe-v0-x-y-to-v1-0-0.html, blog/testcafe-v1-0-0-released.html, documentation/continuous-integration/jenkins.html, documentation/extending-testcafe/reporter-plugin/helpers.html, documentation/extending-testcafe/reporter-plugin/index.html, documentation/extending-testcafe/reporter-plugin/reporter-methods.html, documentation/recipes/extract-reusable-test-code/create-helpers.html, documentation/test-api/intercepting-http-requests/select-requests-to-be-handled-by-the-hook.html, documentation/test-api/obtaining-data-from-the-client/index.html, documentation/test-api/test-code-structure.html, documentation/using-testcafe/command-line-interface.html, documentation/using-testcafe/common-concepts/screenshots-and-videos.html, documentation/using-testcafe/common-concepts/test-https-and-http2-websites.html, documentation/using-testcafe/configuration-file.html, documentation/using-testcafe/programming-interface/createtestcafe.html, documentation/using-testcafe/programming-interface/livemoderunner.html, faq/index.html, feed.xml, sitemap.xml
Applied corrections and fixed one example.
=> [docs] Update the website 7/18/2019

src/errors/test-run/index.js, src/errors/test-run/templates.js, src/errors/types.js, src/test-run/commands/actions.js, src/test-run/commands/assertion.js, src/test-run/commands/from-object.js, src/test-run/commands/type.js, src/test-run/commands/utils.js, src/test-run/commands/validations/initializers.js, src/test-run/execute-js-expression.js, src/test-run/index.js, test/functional/fixtures/api/raw/code-steps/pages/index.html, test/functional/fixtures/api/raw/code-steps/test.js, test/functional/fixtures/api/raw/code-steps/testcafe-fixtures/code-steps.testcafe, test/functional/fixtures/api/raw/code-steps/testcafe-fixtures/module.js, test/functional/fixtures/api/raw/execute-expression/test.js, test/functional/fixtures/api/raw/execute-expression/testcafe-fixtures/shared-context.testcafe, test/functional/fixtures/test-run/testcafe-fixtures/get-real-queue-length.js, test/server/data/expected-test-run-errors/execute-js-expression-error, test/server/execute-async-expression-test.js, test/server/test-run-commands-test.js, test/server/test-run-error-formatting-test.js
Testing plan:
1. async/await
2. promises
3. require absolute/relative modules
4. error handling and error stack with correct lines/columns
5. shared `t.ctx` between code steps
6. all available global variables and functions are working (setTimeout, new Array, everything)
7. __dirname, __filename
8. Capability to execute Selector/ClientFunction, Roles, RequestHook without `require` inside a code step
9. Ensure that global variables defined in code step are not shared between test runs (global scope should not be spoiled by code steps)
10. console.log should work
11. api methods: click, typeText, etc
=> code-steps for RAW format (closes #3954)

README.md
Updated docs for cloud browser plugin support LambdaTest
Here already opened an issue at TestCafe #3896
=> [docs] Added new cloud browser plugin LambdaTest

docs/articles/documentation/test-api/actions/upload.md, docs/articles/documentation/test-api/obtaining-data-from-the-client/examples-of-using-client-functions.md, docs/articles/documentation/test-api/selecting-page-elements/examples-of-working-with-dom-elements.md, docs/articles/documentation/test-api/selecting-page-elements/selectors/functional-style-selectors.md
according to @helen-dikareva's feedback
=> [docs] Fix selector and client function examples

docs/articles/documentation/using-testcafe/common-concepts/inject-scripts-into-tested-pages.md
According to @helen-dikareva's feedback
=> [docs] Enhancements for client scripts

CHANGELOG.md
You've already checked the content here:
https://github.com/DevExpress/testcafe/pull/4088
Just merge when we release.
=> [docs] Add changelog for v1.4.0

src/api/structure/test.js, test/functional/fixtures/api/es-next/custom-client-scripts/test.js, test/functional/fixtures/api/es-next/custom-client-scripts/testcafe-fixtures/i4122.js, test/functional/fixtures/api/es-next/request-hooks/test.js, test/functional/fixtures/api/es-next/request-hooks/testcafe-fixtures/i4122.js
=> fix 'Client scripts: test's client scripts rewrite fixture's client scripts' (close #4122)

docs/articles/blog/2019-7-2-testcafe-v1-3-0-released.md, docs/articles/documentation/test-api/typescript-support.md
=> [docs] Fix info about TS config's unsupported settings

src/utils/async-event-emitter.js
=> Use the reqular emitter class instead of legacy one

src/cli/cli.js, src/cli/log.js
=> Change 'logUpdater' stream from 'strerr' to 'stdout' (close #3873)

src/custom-client-scripts/client-script.js, src/custom-client-scripts/utils.js, test/server/custom-client-scripts-test.js
=> fix " Wrong duplicated scripts calculation'' (close #4116)

blog/testcafe-v1-3-0-released.html, documentation/test-api/typescript-support.html, feed.xml, sitemap.xml
* Removed the `paths` TS config option mentions. Added info that you can't override the `moduleResolution` option: http://vasilystrelyaev.github.io/testcafe/documentation/test-api/typescript-support.html#customize-compiler-options
* Removed `paths` from the Release Notes: http://vasilystrelyaev.github.io/testcafe/blog/testcafe-v1-3-0-released.html#customize-typescript-compiler-options-1845
=> [docs] Update the website 8/16/2019

docs/articles/documentation/continuous-integration/bitbucket-pipelines.md, docs/articles/documentation/continuous-integration/travis-and-sauce-labs.md, docs/articles/documentation/continuous-integration/travis.md, docs/articles/documentation/recipes/test-static-html-pages.md, docs/articles/documentation/test-api/typescript-support.md, docs/articles/documentation/using-testcafe/installing-testcafe.md
fixes https://github.com/DevExpress/testcafe/pull/4200
=> [docs] Enhance the installation topic

docs/articles/documentation/continuous-integration/circleci.md
=> [docs] Type: CircelCI should be CircleCI

blog/testcafe-v1-4-0-released.html, documentation/using-testcafe/common-concepts/inject-scripts-into-tested-pages.html, feed.xml, sitemap.xml
Removes `=` from script injection examples:
http://vasilystrelyaev.github.io/testcafe/documentation/using-testcafe/common-concepts/inject-scripts-into-tested-pages.html#add-client-scripts-to-all-tests
=> [docs] Update the website 9/9/2019

documentation/test-api/actions/click.html, feed.xml, sitemap.xml
Fixes the `t.pressKey` method name in a `t.click` example:
http://vasilystrelyaev.github.io/testcafe/documentation/test-api/actions/click.html
=> [docs] Update the website 9/10/2019

docs/articles/documentation/using-testcafe/common-concepts/browsers/using-chrome-device-emulation.md
fixes https://github.com/DevExpress/testcafe/issues/4259
=> [docs] Fix the default CDP port value

documentation/test-api/intercepting-http-requests/creating-a-custom-http-request-hook.html, documentation/using-testcafe/common-concepts/browsers/using-chrome-device-emulation.html, feed.xml, roadmap/index.html, sitemap.xml
* Updated the roadmap: http://vasilystrelyaev.github.io/testcafe/roadmap/
* Small fix for the `cdpPort` parameter: http://vasilystrelyaev.github.io/testcafe/documentation/using-testcafe/common-concepts/browsers/using-chrome-device-emulation.html#emulator-parameters
UPD:
* Added `export` to a custom request hook example: http://vasilystrelyaev.github.io/testcafe/documentation/test-api/intercepting-http-requests/creating-a-custom-http-request-hook.html
=> Update the website 9/23/2019

src/cli/argument-parser.ts, src/cli/cli.js, src/configuration/screenshot-option-names.ts, src/utils/get-options/base.ts, src/utils/get-options/index.ts, src/utils/get-options/screenshot.ts, test/server/cli-argument-parser-test.js
=> Implement compound --screenshots argument (closes #4324)

@types/promisify-event/index.d.ts, @types/qrcode-terminal/index.d.ts, package.json, src/assertions/get-fn.js, src/cli/argument-parser.ts, src/cli/remotes-wizard.ts, src/configuration/allow-multiple-windows-option.ts, src/configuration/interfaces.ts, src/configuration/option-names.js, src/configuration/run-option-names.ts, src/configuration/testcafe-configuration.ts, src/test-run/index.js, src/test-run/session-controller.js, test/functional/setup.js, test/server/cli-argument-parser-test.js
Changes:
* add `--allow-multiple-windows` option
* rewrite `src/cli/remotes-wizard.ts` to TypeScript
=> Add `--allow-multiple-windows` option

test/server/compiler-test.js, test/server/data/test-suites/typescript-test-redeclared-in-types/node_modules/@types/jest/index.d.ts, test/server/data/test-suites/typescript-test-redeclared-in-types/testfile.ts, ts-defs-src/helpers/test-api-globals.d.ts, ts-defs-src/index.d.ts.mustache
=> Fix a conflict with Jest type definitions (closes #4405)

src/test-run/commands/actions.js, src/test-run/commands/validations/argument.js, src/test-run/execute-js-expression.js, test/server/test-run-commands-test.js
the reason https://github.com/DevExpress/testcafe-studio/issues/2813
=> ExecuteAsyncExpressionCommand can have an empty expression

documentation/test-api/a-z.html, feed.xml, sitemap.xml
Updated the A-Z topic: http://vasilystrelyaev.github.io/testcafe/documentation/test-api/a-z.html
=> [docs] Update the website 11/5/2019

Gulpfile.js, test/functional/config.js
=> Remove outdated tasks

Gulpfile.js, package.json
https://docs.npmjs.com/misc/scripts
```
npm install AndreyBelym/testcafe#prepare-script
```
```
npm install AndreyBelym/testcafe#8523bb6b72ef22835ddad26412996ebc50f64137
```
=> Allow installing TestCafe directly from Git

src/client/driver/driver.js, src/test-run/commands/actions.js, src/test-run/commands/from-object.js, src/test-run/commands/type.js, src/test-run/commands/utils.js, test/server/test-run-commands-test.js
+ allow passing a function as `executeInTopWindowOnly` parameter in Driver's setCustomCommandHandlers method.
=> Add recorder command type and treat is as a service one

src/api/request-hooks/request-logger.js, test/server/request-hooks-test.js
=> add 'timestamp' for the logged request (close #3738)

documentation/continuous-integration/bitbucket-pipelines.html, documentation/test-api/assertions/assertion-api.html, documentation/using-testcafe/command-line-interface.html, documentation/using-testcafe/configuration-file.html, documentation/using-testcafe/using-testcafe-docker-image.html, feed.xml, sitemap.xml
* The `Troubleshooting` section in the Docker topic: http://vasilystrelyaev.github.io/testcafe/documentation/using-testcafe/using-testcafe-docker-image.html#troubleshooting
* A note that links to this section in the `BitBucket` topic: http://vasilystrelyaev.github.io/testcafe/documentation/continuous-integration/bitbucket-pipelines.html#step-3---trigger-a-bitbucket-pipelines-ci-build
=> [docs] Update the website 11/26/2019

docs/articles/documentation/continuous-integration/azure-devops.md, docs/articles/documentation/test-api/authentication/user-roles.md
**This pull request fixes code styling in examples for User Roles**
Also:
- Fixed link in azure-devops.md
=> [docs] Fixed code styling in examples for User Roles

README.md
**This pull request adds new contributors to README.md**
=> [docs] Add new contributors to README.md

LICENSE
Site footers will be updated automatically when republished.
=> [docs] Update the year in the license

docs/articles/documentation/test-api/built-in-waiting-mechanisms.md
Fixes https://github.com/DevExpress/testcafe/issues/4619
=> [docs] Fix a wrong example in 'Wait mechanisms'

.gitattributes
Added SVG, JSON and YAML to `.gitattributes`
Trying to heal the line ending hell on Mac.
=> Add new file types to git attributes

docs/articles/documentation/test-api/intercepting-http-requests/mocking-http-requests.md
Fixes https://github.com/DevExpress/testcafe/issues/4720
=> [docs] Add info about async mock response functions

docs/articles/documentation/test-api/actions/resize-window.md
Fixes https://github.com/DevExpress/testcafe/issues/4764
=> [docs] Add a link to the device list for t.resizeWindowToFitDevice

.gitignore, docs/articles/documentation/continuous-integration/github-actions.md, docs/articles/documentation/extending-testcafe/reporter-plugin/README.md, docs/articles/documentation/using-testcafe/programming-interface/runner.md
Fixes https://github.com/DevExpress/testcafe/issues/4723
=> [docs] Describe passing the reporter object through the API

.gitignore, documentation/continuous-integration/github-actions.html, documentation/extending-testcafe/reporter-plugin/index.html, documentation/recipes/create-data-driven-tests.html, documentation/recipes/extract-reusable-test-code/create-helpers.html, documentation/recipes/extract-reusable-test-code/use-page-model.html, documentation/recipes/import-third-party-modules.html, documentation/recipes/test-select-elements.html, documentation/test-api/actions/resize-window.html, documentation/test-api/intercepting-http-requests/mocking-http-requests.html, documentation/test-api/selecting-page-elements/examples-of-working-with-dom-elements.html, documentation/using-testcafe/programming-interface/runner.html, feed.xml, sitemap.xml
* Custom reporter as object described: https://vasilystrelyaev.github.io/testcafe/documentation/using-testcafe/programming-interface/runner.html#specifying-a-custom-reporter
* Links to the `testcafe-examples` repo added to the Recipes topics
* The new list of devices linked: https://vasilystrelyaev.github.io/testcafe/documentation/test-api/actions/resize-window.html#fitting-the-window-into-a-particular-device
* Async response function in HTTP request mocker described: https://vasilystrelyaev.github.io/testcafe/documentation/test-api/intercepting-http-requests/mocking-http-requests.html#a-custom-response-function
* Some wording and links fixed
=> [docs] Update the website 2/18/2020

docs/articles/documentation/using-testcafe/common-concepts/browsers/browser-support.md
=> [docs] Document support for testing in edge legacy

test/server/data/test-suites/typescript-defs/structure.ts, ts-defs-src/test-api/structure.d.ts
Adds missing type definitions on FixtureFN and TestFN for 
- disablePageCaching
- disablePageReloads
=> Add missing typescript type definitions

.publishrc, package.json
=> Bump version (v1.8.3)

docs/community-content/community-content.json, docs/courses/courses.json
This addresses @andnaz's remarks
See: https://github.com/DevExpress/testcafe-gh-page-assets/pull/85/
=> [docs] Add links to source home pages

.publishrc, package.json
=> Bump version (v1.8.4-rc.1); Bump hammerhead (v16.2.3)

docs/articles/documentation/guides/advanced-guides/screenshots-and-videos.md
=> [docs] Refactor 'Screenshots and Videos'

.publishrc, package.json
- testcafe-browser-tools@2.0.11
=> Bump version (v1.8.5-alpha.1); Bump browser tools

src/client/core/utils/key-maps.js
Studio's PR - https://github.com/DevExpress/testcafe-studio/pull/3122
1) Space key property updated for IE
2) `reversedKeyProperty` added
=> Some changes in KEY_MAPS for Studio

.publishrc, package.json
=> Bump version (v1.8.5)

src/browser/connection/gateway.ts, src/browser/connection/index.ts, src/browser/connection/status.js, src/browser/connection/status.ts, src/browser/provider/plugin-host.js, src/runner/browser-set.ts, test/functional/setup.js, test/server/browser-connection-test.js
I've created a new PR, because there are a few problems with rebasing https://github.com/DevExpress/testcafe/pull/5063 PR.
=> Refactor browser connection statuses

package.json, src/client/automation/playback/type/type-text.js, src/client/core/utils/content-editable.js, src/client/core/utils/dom.js, src/client/driver/command-executors/client-functions/selector-executor/node-snapshots.js
https://github.com/DevExpress/testcafe-hammerhead/issues/2236
=> Use the native "childNodes" getter in client code. Bump eslint-plugin-hammerhead (v0.3.1), testcafe-hammerhead (v17.1.1)

.publishrc, package.json
=> Bump version (v1.8.6)

docs/articles/documentation/guides/extend-testcafe/reporter-plugin.md, docs/articles/documentation/reference/plugin-api/reporter.md
=> [docs] Fix plugin examples

Gulpfile.js
This code left over from development the 'Rerun failed tests on CI' task.
=> Remove dev artifacts

docs/articles/documentation/guides/concepts/browsers.md
We forgot to mention that we start Chromium-based Edge with a new empty temp profile each test session.
=> [docs]Mention MS Edge in the temp profiles section

docs/articles/documentation/guides/basic-guides/select-page-elements.md
=> Fix minor typo in a link wording

docs/articles/documentation/recipes/integrations/use-testing-library-api.md
just a minor update to the example code in the testing library docs page
=> docs: update example code for testing library

docs/articles/documentation/reference/test-api/testcontroller/setnativedialoghandler.md
Fix link to client function's options.
=> Fix link in setnativedialoghandler.md

src/browser/connection/index.ts, src/browser/interfaces.ts, src/browser/provider/built-in/dedicated/chrome/index.js, src/browser/provider/index.ts, src/browser/provider/utils/client-functions.ts, src/runner/browser-job.ts, src/utils/async-event-emitter.ts, test/functional/fixtures/api/es-next/take-screenshot/test.js, test/functional/fixtures/browser-provider/browser-reconnect/test.js, test/functional/fixtures/browser-provider/chrome-emulation/test.js, test/functional/fixtures/concurrency/test.js, test/functional/fixtures/regression/gh-3835/test.js, test/functional/fixtures/regression/gh-4675/test.js, test/functional/fixtures/regression/gh-4725/test.js, test/functional/fixtures/regression/gh-4787/test.js, test/functional/utils/reporter.js, test/functional/utils/stream.js, test/server/reporter-test.js
Changes:
* some TypeScript rewrites
* introduce the `createReporter` util function
* etc.
=> Enhancements from #5162 PR

package.json, test/functional/fixtures/regression/hammerhead/gh-2350/pages/empty-value.html, test/functional/fixtures/regression/hammerhead/gh-2350/pages/initial-value.html, test/functional/fixtures/regression/hammerhead/gh-2350/test.js, test/functional/fixtures/regression/hammerhead/gh-2350/testcafe-fixtures/index.js
I moved tests for the fixed case in TestCafe because it's complicated check it in context of QUnit test.
The linked PR in hammerhead - https://github.com/DevExpress/testcafe-hammerhead/pull/2352
=> Tests for hammerhead/#2350

docs/articles/documentation/guides/basic-guides/run-tests.md, docs/articles/documentation/guides/basic-guides/select-page-elements.md
fixes https://github.com/DevExpress/testcafe/issues/4998
=> [docs] Prohibit opening front-end devtools

CHANGELOG.md, docs/articles/blog/2019-2-7-testcafe-v1-0-0-released.md, docs/articles/documentation/guides/advanced-guides/test-https-features-and-http2-websites.md, docs/articles/documentation/guides/basic-guides/run-tests.md, docs/articles/documentation/reference/testcafe-api/browserconnection/README.md, docs/articles/documentation/reference/testcafe-api/global/createtestcafe.md, docs/articles/documentation/reference/testcafe-api/livemoderunner.md, docs/articles/documentation/reference/testcafe-api/runner/README.md, docs/articles/documentation/reference/testcafe-api/runner/browsers.md, docs/articles/documentation/reference/testcafe-api/runner/run.md, docs/articles/documentation/reference/testcafe-api/testcafe/close.md, docs/articles/documentation/reference/testcafe-api/testcafe/createbrowserconnection.md, docs/articles/documentation/reference/testcafe-api/testcafe/createlivemoderunner.md, docs/articles/documentation/reference/testcafe-api/testcafe/createrunner.md
fixes https://github.com/DevExpress/testcafe/issues/5165
=> [docs] Handle testcafe.close promise

.publishrc, package.json
=> Bump version (v1.8.7)

src/notifications/warning-message.js, test/functional/fixtures/api/es-next/assertions/test.js
Needed to fix warning messages after merging #5211
=> Fix warning messages

src/api/test-controller/index.js, src/reporter/index.js, src/utils/get-browser.ts, src/utils/parse-user-agent.ts, test/server/reporter-test.js
1. Added test ID to `testStartInfo` parameter of the `reportTestStart` method
2. Added test ID and test run IDs` to `testRunInfo` parameter of the `reportTestDone` method
=> Provide test ID to reportTestStart/reportTestDone and test run IDs to reportTestDone (closed #5010)

CHANGELOG.md
Highlighted changes from `testcafe` and `testcafe-hammerhead` repositories.
=> [docs] Add changelog for v1.8.8

.publishrc, package.json
=> Bump version (v1.8.8)

package.json, test/functional/fixtures/regression/hammerhead/gh-2350/pages/text-property-getters-of-title-element.html, test/functional/fixtures/regression/hammerhead/gh-2350/test.js, test/functional/fixtures/regression/hammerhead/gh-2350/testcafe-fixtures/index.js
https://github.com/DevExpress/testcafe-hammerhead/pull/2378
=> Tests for hammerhead/#2374

.publishrc, package.json
=> Bump version (v1.9.0-alpha.1)

docs/articles/documentation/guides/basic-guides/select-page-elements.md
fixes https://github.com/DevExpress/testcafe/issues/5197
=> [docs] Select timeout example

docs/README.md, docs/articles/documentation/guides/README.md, docs/articles/documentation/guides/continuous-integration/README.md, docs/articles/documentation/guides/continuous-integration/github-actions-and-browserstack.md, docs/articles/documentation/guides/continuous-integration/github-actions.md, docs/nav/nav-menu.yml
=> [docs] Added GitHub actions+browserstack guide

.publishrc, package.json
=> Bump version (v1.9.0)

docs/articles/documentation/guides/advanced-guides/multiple-browser-windows.md, docs/articles/documentation/reference/test-api/testcontroller/openwindow.md, docs/articles/documentation/reference/test-api/testcontroller/switchtowindow.md
See https://github.com/DevExpress/testcafe/pull/5400
=> [docs] Edits to the multi-window mode docs requested by @miherlosev

test/functional/fixtures/api/es-next/assertions/data/expected-missing-await-on-snapshot-callsite, test/functional/fixtures/api/es-next/assertions/data/expected-selector-property-awaited-callsite, test/functional/fixtures/api/es-next/assertions/test.js, test/functional/fixtures/api/es-next/assertions/testcafe-fixtures/assertions-test.js, test/server/data/test-suites/typescript-defs/assertions.ts, test/server/data/test-suites/typescript-defs/test-controller.ts, test/server/data/test-suites/typescript-testcafe-scripts-defs/test-controller.ts, ts-defs-src/test-api/assertions.d.ts
Add tests for the fixed type definitions
#5456
=> Add type definition tests for typeOf and notTypeOf assertions

CHANGELOG.md, docs/articles/blog/2016-12-8-testcafe-v0-11-0-released.md, docs/articles/documentation/guides/basic-guides/assert.md, docs/articles/documentation/guides/basic-guides/interact-with-the-page.md, docs/articles/documentation/guides/basic-guides/obtain-client-side-info.md, docs/articles/documentation/guides/basic-guides/select-page-elements.md, docs/articles/documentation/guides/continuous-integration/github-actions-and-browserstack.md, docs/articles/documentation/guides/continuous-integration/github-actions.md, docs/articles/documentation/reference/test-api/selector/withexacttext.md, docs/articles/documentation/reference/test-api/selector/withtext.md, docs/articles/documentation/reference/test-api/testcontroller/README.md, docs/articles/documentation/reference/test-api/testcontroller/navigateto.md, docs/articles/documentation/reference/test-api/testcontroller/setnativedialoghandler.md, docs/articles/templates/actions/selector-parameter.md
=> [docs] Gh #5196 describe current limitations

ts-defs-src/test-api/action-options.d.ts, ts-defs-src/test-api/client-function.d.ts, ts-defs-src/test-api/test-controller.d.ts
=> Fix missing semicolons in d.ts

package.json
=> Bump version (v1.9.2-rc.2); Bump hammerhead (v17.1.15)

@types/chrome-remote-interface/index.d.ts, package.json, test/functional/fixtures/browser-provider/browser-reconnect/test.js, test/functional/fixtures/browser-provider/chrome-emulation/test.js, test/functional/fixtures/live/test.js, test/functional/fixtures/multiple-windows/pages/debug-synchronization/child.html, test/functional/fixtures/multiple-windows/testcafe-fixtures/debug-synchronization.js, test/functional/fixtures/regression/gh-3049/test.js, test/functional/fixtures/regression/hammerhead/gh-2350/pages/inital-value-script-only-in-body.html, test/functional/fixtures/regression/hammerhead/gh-2350/test.js, test/functional/fixtures/regression/hammerhead/gh-2350/testcafe-fixtures/index.js
See the [video](https://monosnap.com/file/rqzNlnw3cbJUyXy33mdptJ53wmJkiH) on how it looks now.
Changes:
* set unique ids for tabs (done in hammerhead)
* small refactoring and code style changes
=> Set unique title for browser tabs

src/browser/connection/index.ts, src/browser/provider/built-in/dedicated/chrome/cdp.ts, src/browser/provider/built-in/dedicated/firefox/index.js, src/client/driver/driver.js, test/functional/fixtures/multiple-windows/testcafe-fixtures/debug-synchronization.js, test/functional/fixtures/regression/gh-3049/test.js, test/functional/fixtures/regression/hammerhead/gh-2350/pages/inital-value-script-only-in-body.html
Formatting, extracting methods, fix typos.
=> Small refactoring

docs/articles/blog/2020-09-24-the-fastest-way-to-your-next-test-qa.md, docs/articles/documentation/guides/advanced-guides/test-https-features-and-http2-websites.md
This PR adds a Q&A post following the sept 8th webinar
=> [docs] Add a Q&A post following the sept 8th webinar

.publishrc, package.json
=> Bump version (v1.9.4)

docs/articles/documentation/guides/basic-guides/obtain-client-side-info.md, docs/articles/documentation/reference/test-api/testcontroller/switchtoiframe.md
Transfer examples from https://github.com/DevExpress/testcafe-examples/pull/22
=> [docs] Transfer examples from testcafe-examples

ts-defs-src/runner-api/runner-api.d.ts
=> Fix typing tooltip

src/notifications/warning-message.js, src/test-run/index.js, src/utils/string.js, test/functional/fixtures/api/es-next/custom-client-scripts/test.js, test/server/configuration-test.js, test/server/runner-test.js, test/server/util-test.js, test/server/video-recorder-test.js
Before:
```js
1 item
1, 2 items
1, 2, 3 items
```
After:
```js
1 item
1 and 2 items
1, 2, and 3 items.
```
=> Change list items formatting in messages

.publishrc, .travis.yml, package.json, test/functional/fixtures/hammerhead/gh-2418/pages/index.html, test/functional/fixtures/hammerhead/gh-2418/pages/script.js, test/functional/fixtures/hammerhead/gh-2418/test.js, test/functional/fixtures/hammerhead/gh-2418/testcafe-fixtures/index.js
https://github.com/DevExpress/testcafe-hammerhead/pull/2454
https://github.com/DevExpress/testcafe-hammerhead/issues/2418
=> Add a test for testcafe-hammerhead/pull/2454. Bump version (v1.9.5-rc.1)

package.json
Fixing tree-kill dependence vulnerability
Updating package version for 1.2.2
https://hackerone.com/reports/701183
- [] Write tests for your proposed changes
=> Fix tree-kill vulnerability from old version.

docker/Dockerfile
=> add tzdata package in the docker image  (close #5572)

docs/articles/documentation/examples/README.md, examples/README.md
=> [docs] Put in new examples

docs/articles/documentation/guides/basic-guides/select-page-elements.md, docs/articles/templates/intercept-http-requests/requestoptions-object.md, ts-defs-src/test-api/request-hook.d.ts
=> [docs] Describe requestOptions.isAjax

docs/articles/documentation/guides/concepts/typescript-and-coffeescript.md, docs/articles/documentation/reference/README.md, docs/articles/documentation/reference/command-line-interface.md, docs/articles/documentation/reference/configuration-file.md, docs/articles/documentation/reference/testcafe-api/runner/README.md, docs/articles/documentation/reference/testcafe-api/runner/compileroptions.md, docs/articles/documentation/reference/testcafe-api/runner/tsconfigpath.md
=> [docs] Update the TypeScript guide, describe the 'compiler options' feature

package.json
=> Bump version (v1.10.0-rc.7), bump testcafe-hammerhead (v17.1.26)

docs/articles/faq/README.md
=> [docs] FAQ update (React Native)

blog/v1-10-0-new-compiler-options-api-resize-and-screenshot-support-for-child-windows.html, faq/index.html, feed.xml, media/team-blog/index.html, release-notes/index.html, sitemap.xml
* Published the [release notes](https://vasilystrelyaev.github.io/testcafe/blog/v1-10-0-new-compiler-options-api-resize-and-screenshot-support-for-child-windows.html)
* Added a [small FAQ entry](https://vasilystrelyaev.github.io/testcafe/faq/#can-i-use-testcafe-to-test-react-native-apps)
=> [docs] Update the website 12/15/2020

documentation/guides/advanced-guides/multiple-browser-windows.html, feed.xml, sitemap.xml
* updated beta notes in [Multiple Browser Windows](https://vasilystrelyaev.github.io/testcafe/documentation/guides/advanced-guides/multiple-browser-windows.html) to reflect some limitations being lifted
=> [docs] Update beta notes in Multiple Browser Windows

.publishrc, package.json
```
* fix 'Error: [BABEL] unknown: Preset' (closes #5808) (#5819)
* Add service worker to make multiple requests for the test page (closes #5239) (#5738)
* fix 'Script that worked in version 1.5.0 but no longer works in 1.9.4. (closes #5600) (#5781)
```
=> Bump version (v1.10.1)

package.json
=> Fix 'debug' vulnerability

docs/articles/documentation/guides/basic-guides/run-tests.md, docs/articles/documentation/guides/continuous-integration/github-actions-and-browserstack.md
=> [docs] Add more details about concurrency on remote devices

src/errors/runtime/templates.js, src/errors/types.js, src/test-run/index.js, test/functional/fixtures/browser-provider/browser-reconnect/run-log-error-on-disconnect-test.js, test/functional/fixtures/browser-provider/browser-reconnect/test.js, test/functional/fixtures/browser-provider/browser-reconnect/testcafe-fixtures/index-test.js
here is original approved PR https://github.com/DevExpress/testcafe/pull/5840
=> Reject with error (it's duplicate since I had a problem with npm cache in the my previous PR)

src/configuration/default-values.ts, src/configuration/interfaces.ts, src/configuration/testcafe-configuration.ts
=> Remove outdated code for the old 'retry test pages' feature implementation

docs/articles/documentation/guides/advanced-guides/intercept-http-requests.md
Changing some `var` to `const` inside the code examples
=> [docs] Switch var to const

docs/articles/documentation/guides/advanced-guides/multiple-browser-windows.md
=> [Docs] Describe multiple browser windows mode limitations 

docs/articles/documentation/guides/advanced-guides/intercept-http-requests.md, docs/articles/documentation/guides/advanced-guides/multiple-browser-windows.md
=> [docs] Remove beta mentions for multiple browser windows

src/client/driver/driver.js, test/functional/fixtures/multiple-windows/pages/frame/frame.html, test/functional/fixtures/multiple-windows/test.js, test/functional/fixtures/multiple-windows/testcafe-fixtures/iframe.js
Prevent duplicating child link if the child window is opened and reloaded in iframe
=> fix child window reloading, when child window is opened from iframe (closes #5930)

docs/articles/templates/intercept-http-requests/request-filter.md
Describe the possibility to use async functions in the predicate of a requestLogger and requestHook constructor.
=> [docs] describe async predicate in requesthook and requestlogger

docs/articles/documentation/reference/command-line-interface.md
=> [docs] Update `command-line-interface.md` to new guidelines [2]

documentation/reference/command-line-interface.html, feed.xml, roadmap/index.html, sitemap.xml
=> [docs] Publish website 25.02 - 2021 roadmap

blog/testcafe-v1-11-0-released.html, blog/testcafe-v1-12-0-released.html, documentation/reference/command-line-interface.html, documentation/reference/configuration-file.html, documentation/reference/testcafe-api/global/createtestcafe.html, documentation/reference/testcafe-api/runner/run.html, feed.xml, sitemap.xml
=> Publish website 05.03 

docs/articles/documentation/guides/basic-guides/select-page-elements.md, docs/articles/documentation/reference/test-api/selector/README.md, docs/articles/templates/selectors/selector-members.md
=> [docs] Add template for Selector options

docs/articles/documentation/reference/README.md, docs/articles/documentation/reference/configuration-file.md, docs/articles/documentation/reference/test-api/test/timeouts.md, docs/articles/documentation/reference/test-api/testcontroller/setpageloadtimeout.md, docs/nav/nav-menu.yml
=> [docs] Describe test.timeouts

docs/articles/documentation/guides/concepts/typescript-and-coffeescript.md
=> [docs] Describe type-casting HTML elements in client side TypeScript code

docs/articles/documentation/guides/advanced-guides/multiple-browser-windows.md
=> [docs] Add note about multiple windows in custom browsers

docs/articles/documentation/reference/test-api/requesthook/README.md, docs/articles/documentation/reference/test-api/requesthook/onresponse.md, docs/articles/templates/notes-warnings/requesthook-onresponse-no-stub-headers.md
=> [docs] Describe how to mock part of response headers

security.md
Added the `security.md` files to reference DevExpress rules for submitting security vulnerabilities.
Links:
1. The actual shared `security.md` document: [DevExpress/Shared/security/policy](https://github.com/DevExpress/Shared/security/policy)
2. The thread in MS Teams with discussion: [Security Guild](https://teams.microsoft.com/l/message/19:afa53234eac94199b6ff8f43570501bc@thread.skype/1617953576213?tenantId=e4d60396-9352-4ae8-b84c-e69244584fa4&groupId=df7be995-3e54-4587-af18-0330a780c32b&parentMessageId=1617185793348&teamName=Security%20Guild&channelName=General&createdTime=1617953576213)
=> [docs] docs: add security vulnerability reporting instructions

docs/articles/roadmap/README.md
=> [docs] Add mouse actions to roadmap

src/services/compiler/host.ts
=> Fix deprecation warning

test/functional/fixtures/regression/gh-3904/test.js
add a note as was asked here: https://github.com/DevExpress/testcafe/pull/6188#discussion_r625704564
=> add a note about 6201

test/functional/fixtures/api/es-next/scroll/pages/event-properties.html, test/functional/fixtures/api/es-next/scroll/test.js, test/functional/fixtures/api/es-next/scroll/testcafe-fixtures/event-properties.js
I ran the test 7 times and it was green all times.
Changes:
* simplify selectors.
* remove unnecessary communication between client and server.
=> Fix scroll test

README.md, package.json
Today is the end of life of Nodejs v10.
Update minimal required Nodejs version in readme.
[https://github.com/nodejs/Release#release-schedule](https://github.com/nodejs/Release#release-schedule)
=> chore: Update minimal required Nodejs version

.publishrc, package.json, test/functional/legacy-fixtures/page-js-errors/test.js
=> release: v1.15.0-alpha.3, bump replicator@1.0.5, bump testcafe-legacy-api@5.0.1

.github/workflows/test-client-desktop.yml, .github/workflows/test-client-mobile.yml, .github/workflows/test-functional-docker.yml, .github/workflows/test-functional-local-chrome.yml, .github/workflows/test-functional-local-compiler-service.yml, .github/workflows/test-functional-local-firefox.yml, .github/workflows/test-functional-local-ie.yml, .github/workflows/test-functional-local-legacy.yml, .github/workflows/test-functional-local-multiple-windows.yml, .github/workflows/test-functional-remote-macos.yml, .github/workflows/test-functional-remote-mobile.yml, .github/workflows/test-server-docker.yml, .github/workflows/test-server-lts.yml
=> ci: upgrade minimal Node version

src/client-functions/selectors/add-api.js, src/client-functions/selectors/selector-builder.js
https://github.com/DevExpress/testcafe/issues/5642
=> [WIP] fix: Selector evaluates with correct callsite (closes #5642)

package.json
=> release: bump version (v1.15.0-alpha.4); use testcafe-legacy-api@5.0.2

package.json, src/services/compiler/host.ts, src/services/serialization/replicator/create-replicator.ts, src/services/serialization/replicator/transforms/request-hook-event-data-transform.ts, test/functional/fixtures/api/es-next/request-hooks/test.js, test/functional/fixtures/api/es-next/request-hooks/testcafe-fixtures/api/request-hook-events.js
Changes:
* update `testcafe-hammerhead` module
* add `RequestHookEventDataTransform` transform
=> refactor (compiler service): improve serialization (RequestHookEventData)

src/test-run/index.ts
Close https://github.com/DevExpress/testcafe/issues/6373
=> do not show warning when debugging in headless mode using the compiler service (close #6373)

src/cli/argument-parser.ts, src/cli/cli.js, src/runner/index.js, src/test-run/debug-log.js, src/utils/log-entry.ts, test/server/debug-log-test.js
Log passed command-line arguments, parsed parameters and result option before test run.
=> refactor: add more logging

.publishrc, package.json
=> release: v1.15.1

.publishrc, package.json
=> release: v1.15.2

package.json, src/cli/argument-parser.ts, src/configuration/default-values.ts, src/configuration/option-names.ts, src/configuration/testcafe-configuration.ts, src/index.js, test/server/api-test.js, test/server/cli-argument-parser-test.js, test/server/configuration-test.js, test/server/data/test-suites/typescript-runner/runner.ts, ts-defs-src/helpers/runner-api-types.d.ts, ts-defs-src/index.d.ts.mustache, ts-defs-src/runner-api/configuration.d.ts, ts-defs-src/runner-api/options.d.ts, ts-defs-src/runner-api/runner-api.d.ts, ts-defs-src/test-api/request-hook.d.ts
* deps: update testcafe-hammerhead@24.5.1
* fix: allow disabling http2 with --disable-http2
* fix: allow objects as an argument of setBody (closes  #5180)
=> release: 1.15.3-rc.1

.publishrc, package.json
=> release: v1.16.0

src/client/automation/playback/type/type-text.js, test/client/fixtures/automation/type-test.js
Add support for the `beforeinput` event in FF.
=> support beforeInput event in Firefox (closes #6504)

.publishrc, package.json
=> release: v1.16.1

src/client-functions/client-function-builder.js, src/client/driver/command-executors/client-functions/selector-executor/check-element-delay.ts, src/client/driver/command-executors/client-functions/selector-executor/index.ts, test/functional/fixtures/compiler-service/test.js, test/functional/fixtures/compiler-service/testcafe-fixtures/synchronous-selectors.js
=> chore: fix selector timeout in debug mode (close #6575)

.publishrc, CHANGELOG.md, package.json, test/functional/fixtures/api/raw/execute-expression/test.js
=> release: v1.17.0

.github/workflows/deploy-to-artifacts.yml, .github/workflows/test-cdp.yml, Gulpfile.js, src/browser/provider/built-in/dedicated/chrome/cdp-client/execution-context.ts, src/browser/provider/built-in/dedicated/chrome/cdp-client/utils.ts, test/cdp/.eslintrc, test/cdp/position-utils-test-iframe.html, test/cdp/position-utils-test-page.html, test/cdp/position-utils-test.js
=> Position utils

.github/workflows/deploy-to-artifacts.yml
Fix problem when installing the npm
Add a flag `--legacy-peer-deps`
=> build: added flag `--legacy-peer-deps` for `npm i` in the `deploy to artifacts`

.publishrc, package.json
=> release: v1.18.0

.publishrc, package.json
=> release: v1.18.3

CONTRIBUTING.md
=> [docs] Add info about contribution to docs

package.json, src/client/core/utils/shared/scroll.ts, src/client/core/utils/shared/types.d.ts, test/functional/config.js, test/functional/fixtures/api/es-next/iframe-switching/test.js, test/functional/fixtures/api/es-next/iframe-switching/testcafe-fixtures/iframe-switching-test.js, test/functional/fixtures/api/es-next/native-dialogs-handling/test.js, test/functional/fixtures/regression/gh-1327/testcafe-fixtures/index.test.js, test/functional/fixtures/run-options/disable-page-caching/test.js
Changes:
* update browsers on MacOS platform to latest versions
* update devices with Safari browser
=> test: update Safari in functional tests

.publishrc, package.json, src/screenshots/utils.js, test/server/util-test.js
Closes https://github.com/DevExpress/testcafe/issues/6887
Regression - https://github.com/DevExpress/testcafe/commit/d46a0b92df22fcf2729d52c70b90a17772ee8979#diff-7919d38364837dcdee8bf136aa3523c6cb3f2db275394995a4443556b7a4a8e7R20
=> fix 'Showing a warning as unable to take screenshots when running the test in Lambda Test' (close #6887)

.publishrc, package.json
=> release: v1.18.5

.github/workflows/label-actions.yml
=> ci: fixed label-actions.yml

package.json
Update browser tools to fix https://github.com/DevExpress/testcafe-browser-tools/issues/222
=> chore: bump testcafe-browser-tools@2.0.23

package.json
update the `async` module to fix https://github.com/advisories/GHSA-fwr7-v2mv-hh25
=> chore: update legacy api

.publishrc, package.json
=> release: v1.18.6

package.json
=> build: updated testcafe-hammerhead

src/dashboard/formatting.ts, src/dashboard/index.ts, src/dashboard/messages.ts, src/reporter/interfaces.ts, src/reporter/plugin-host.ts, src/reporter/symbols.ts, test/server/cli-dashboard-integration-test.js
See how it looks now: https://www.figma.com/file/ZKDQGuznawilTV24qTR5GY/Terminal-appearance?node-id=0%3A1
=> Change text formatting for the 'testcafe dashboard' command

src/dashboard/config-storage.ts, src/dashboard/index.ts, src/dashboard/messages.ts, test/server/cli-dashboard-integration-test.js
Logic and texts were discussed with @helen-dikareva and @titerman .
=> Run the 'testcafe dashboard on|off' command in case of non-existing token

package.json, src/compiler/compile-client-function.js, test/dependency-licenses-checker.js
=> release: fix publishing issues

.publishrc, package.json
=> release: publish v1.19.0

src/compiler/test-file/formats/raw.js, src/utils/raw-command-callsite-record.ts, test/functional/fixtures/api/raw/test-controller/test.js, test/functional/fixtures/api/raw/test-controller/testcafe-fixtures/test-controller-test.testcafe
[closes DevExpress/testcafe#7089]
Enhance showing information about assertion commands.
1. Add raw test
2. Show additional information about assertions
https://github.com/DevExpress/testcafe/issues/7089
=> feat: modified raw-command-callsite-record for the assertions

.publishrc, package.json
=> release: publish v1.20.0

README.md
_Added Tesults reporter to Custom Reporter section to README.md._
_Documentation/example update._
_N/A_
- [N/A] Write tests for your proposed changes
- [x ] Make sure that existing tests do not fail
=> Added Tesults to Custom Reporters in README.md

package.json, src/client/core/utils/position.ts, test/client/fixtures/automation/click-test.js, test/client/fixtures/core/page-unload-barrier-test.js, test/functional/fixtures/api/es-next/request-hooks/test.js, test/functional/fixtures/api/es-next/request-hooks/testcafe-fixtures/request-mock/500-status-code.js
These utilities use only in TestCafe Studio.
=> fix: revert utilites

package.json
=> build: updated testcafe-browser-provider-browserstack

.publishrc, CHANGELOG.md, package.json
=> release: publish v2.0.1

.github/workflows/test-functional-remote-macos.yml, test/client/fixtures/automation/select-test/index-test.js
temporary skip test and increase task time
=> Skip Safari test and increase Remote MacOS task time

src/compiler/test-file/formats/dev-tools/commands/click.ts, src/compiler/test-file/formats/dev-tools/commands/factory.ts, src/compiler/test-file/formats/dev-tools/commands/hover.ts, src/compiler/test-file/formats/dev-tools/compiler.ts, src/compiler/test-file/formats/dev-tools/types.ts, src/errors/runtime/templates.js, src/errors/types.js, test/functional/fixtures/api/json/pages/index.html, test/functional/fixtures/api/json/test.js, test/functional/fixtures/api/json/testcafe-fixtures/dblclick-test.json, test/functional/fixtures/api/json/testcafe-fixtures/hover-test.json, test/functional/fixtures/api/json/testcafe-fixtures/invalid-test.json, test/functional/fixtures/api/json/testcafe-fixtures/rclick-test.json
Closes DevExpress/testcafe-private#24
=> support hover/dblclick/rclick in google dev tools recorder

src/client/automation/playback/press/shortcuts.js
=> fix: fixed pressKey handler for radio button

.publishrc, package.json
=> release: publish v2.0.2

src/errors/process-test-fn-error.js, src/errors/test-run/index.js, src/test-run/index.ts, test/functional/fixtures/api/es-next/generic-errors/test.js, test/functional/fixtures/api/es-next/generic-errors/testcafe-fixtures/error-in-test-code-test.js
[closes #6936]
Render correct error text for internal uncaught errors
=> feat: rendered correct error text for internal uncaught errors

package.json
Fix for uuid package installation warning (https://github.com/DevExpress/testcafe-reporter-dashboard/issues/111)
=> deps: update testcafe-reporter-dashboard v0.2.7

src/proxyless/request-pipeline/index.ts, src/proxyless/resource-injector.ts
Connected with https://github.com/DevExpress/testcafe/issues/7334.
=> proxyless: add custom status text

.publishrc, CHANGELOG.md, package.json
=> release: publish v2.2.0

.eslintrc, src/proxyless/api-base.ts, src/proxyless/api.ts, src/proxyless/console-messages/formatter.ts, src/proxyless/console-messages/index.ts, src/proxyless/console-messages/types.ts, src/proxyless/index.ts, src/test-run/index.ts, test/functional/fixtures/api/es-next/roles/test.js
Closes DevExpress/testcafe-private#61.
=> proxyless getBrowserConsoleMessages

package.json
```
json5  <2.2.2
Severity: high
Prototype Pollution in JSON5 via Parse Method - https://github.com/advisories/GHSA-9c47-m6qq-7p4h
fix available via `npm audit fix --force`
Will install babel-plugin-module-resolver@2.2.0, which is a breaking change
node_modules/find-babel-config/node_modules/json5
find-babel-config  *
Depends on vulnerable versions of json5
node_modules/find-babel-config
babel-plugin-module-resolver  >=2.3.0
Depends on vulnerable versions of find-babel-config
node_modules/babel-plugin-module-resolver
```
https://github.com/DevExpress/testcafe/actions/runs/3801428590/jobs/6465887126
_Describe how your changes address the issue or implement the desired functionality in as much detail as …
=> deps: fix CVE GHSA-9c47-m6qq-7p4h

package.json
=> build: updated testcafe-browser-provider-browserstack version

package.json
babel-plugin-module-resolver version updated to fix npm audit
=> build: update babel-plugin-module-resolver

test/functional/fixtures/regression/gh-2546/test.js
=> test: skipped test "uncaught promise rejection"

.publishrc, package.json
=> release: publish v2.3.0-rc.1

package.json, test/server/chrome-provider-config-test.js
=> release: publish v2.3.0-rc.2, updated HH

.publishrc, CHANGELOG.md, package.json
=> release: publish v2.3.0

package.json, src/client/automation/playback/click/index.ts, src/client/automation/types.d.ts, src/client/automation/visible-element-automation.ts, src/client/core/utils/style.js, src/client/driver/command-executors/action-executor/actions-initializer.ts, src/client/driver/command-executors/action-executor/index.ts, src/client/driver/driver-link/iframe/child.js, src/client/driver/driver-link/messages.js, src/client/driver/driver.js, src/client/driver/iframe-driver.js, src/client/ui/cursor/iframe-cursor.js, src/client/ui/cursor/index.js, src/proxyless/client/event-simulator.ts
We pass the left top corner of iframe element to calculate the screen coordinates.
=> proxyless: perform 'click' using CDP (iframes support)

src/api/structure/fixture.ts, src/api/structure/test.ts, src/api/structure/testing-unit.ts, src/compiler/test-file/add-export-api.ts, test/functional/fixtures/regression/gh-7482/test.js, test/functional/fixtures/regression/gh-7482/testcafe-fixtures/index.js
[closes #7482]
https://github.com/DevExpress/testcafe/issues/7482
=> fix: fixed regression with using tests and fixture methods

.publishrc, package.json, src/compiler/test-file/formats/es-next/compiler.js
=> release: publish 2.3.1-rc.1

package.json
=> release: bump version (2.3.1-rc.2)

.publishrc, CHANGELOG.md, package.json
=> release: publish 2.3.1

.github/workflows/deploy-to-artifacts.yml
Fix for this:
https://github.com/DevExpress/testcafe/pull/7530
https://github.com/DevExpress/testcafe/pull/7530
=> fix: add headed task to tasks queue

.publishrc, package.json
=> release: publish 2.4.0-rc.1

.github/workflows/deploy-to-artifacts.yml, .github/workflows/set-status.yml, .github/workflows/test-client.yml, .github/workflows/test-functional.yml, .github/workflows/test-server.yml, test/functional/assertion-helper.js, test/functional/fixtures/api/es-next/take-screenshot/test.js, test/functional/fixtures/proxy/test.js, test/functional/fixtures/regression/gh-3456/test.js, test/functional/fixtures/regression/hammerhead/gh-2350/test.js, test/functional/fixtures/request-pipeline/redirects/test.js, test/functional/fixtures/request-pipeline/redirects/testcafe-fixtures/redirects.js
[closes DevExpress/testcafe-private#110]
[closes DevExpress/testcafe-private#82]
Improve workflows
1. Update actions
2. Remove duplication
3. Parallelize functional tests to increase execution speed
=> refactor: optimized workflow actions

src/index.js, src/proxyless/request-pipeline/index.ts, src/proxyless/resource-injector.ts, test/functional/fixtures/page-js-errors/test.js, test/functional/fixtures/proxy/test.js, test/server/runner-test.js
Changes:
* fixed typos
* refactored `ResourceInjector` options.
* others
=> proxyless: refactoring 2

package.json, test/functional/fixtures/regression/gh-7575/pages/index.html, test/functional/fixtures/regression/gh-7575/test.js, test/functional/fixtures/regression/gh-7575/testcafe-fixtures/index.js
=> test for `do not modify authorization header in proxyless mode` PR in hh

bin/testcafe-with-v8-flag-filter.js, src/cli/argument-parser/index.ts, src/cli/cli.js, src/compiler/babel/load-libs.js, src/compiler/compilers.js, src/compiler/index.js, src/compiler/interfaces.ts, src/compiler/test-file/api-based.js, src/compiler/test-file/formats/es-next/compiler.js, src/compiler/test-file/formats/typescript/compiler.ts, src/compiler/test-file/get-exportable-lib-path.ts, src/configuration/option-names.ts, src/errors/runtime/templates.js, src/runner/bootstrapper.ts, src/services/compiler/service.ts, test/functional/config.js, test/functional/fixtures/esm/test.js, test/functional/fixtures/live/test.js, test/functional/setup.js, test/server/cli-argument-parser-test.js
[closes DevExpress/testcafe-private#135]
Move esm mode from experimental
Remove all `experimental*`  prefixes for ESM mode
=> feat: moved esm mode from experimental

src/runner/task/index.ts, src/test-run/index.ts
Lodash types added from callsite-record dependency have been updated with breaking changes
=> fix lodash type errors

ts-defs-src/test-api/test-controller.d.ts
https://github.com/DevExpress/testcafe/pull/7562
=> fix: t.report method description

ts-defs-src/runner-api/options.d.ts
Fix typings for: https://github.com/DevExpress/testcafe/pull/7608
=> nativeAutomation: fix typings

.github/workflows/deploy-to-artifacts.yml, .github/workflows/test-functional-local-native-automation.yml, Gulpfile.js
rename all the proxyless API to nativeAutomation. step 3
=> nativeAutomation: rename task

package.json
We've introduced a new t.report action which requires a v2.2.0 spec reporter.
=> fix: update spec-reporter dependency

.github/workflows/test-functional-local-debug-1.yml, .github/workflows/test-functional-local-debug-2.yml
=> build: increase timeout for debug tests

.github/ISSUE_TEMPLATE/bug_report.yaml
=> A note about Native Automation Mode added into the bug report template

.publishrc, package.json
https://github.com/DevExpress/testcafe-private/issues/168
=> release: publish 2.6.0-rc.1

.publishrc, package.json
=> release: publish 2.6.0

.github/workflows/test-functional-remote-macos.yml, .github/workflows/test-functional-remote-mobile.yml
[closes DevExpress/testcafe-private#177]
=> build: change timeouts for remote tests

src/client/browser/index.js, src/client/driver/driver.js, test/functional/fixtures/driver/test.js, test/functional/fixtures/driver/testcafe-fixtures/page-url-with-hash.js
[closes #7652]
Fix hanging
Force page reloading page between tests in NA if URL has a hash.
https://github.com/DevExpress/testcafe/issues/7652
=> fix: fixed hanging in NA if url has hash

.github/workflows/deploy-to-artifacts.yml, .github/workflows/test-functional-remote-macos.yml, .github/workflows/test-functional-remote-mobile.yml, .github/workflows/test-functional.yml
[closes DevExpress/testcafe-private#180]
Increase the speed of test execution.
1. Run middleware jobs on Ubuntu.
2. Removed limitation for a parallel count of jobs
=> github-actions: upgraded remote workflows

src/browser/connection/gateway/index.ts, src/errors/runtime/templates.js, src/errors/types.js, test/server/browser-connection-gateway-test.js, test/server/helpers/mocks.js, test/server/runner-test.js
=> fix 'Error creating multiple test runnres at the same time' close (#7711)

.publishrc, package.json
=> release: publish 2.6.1-rc.1

.publishrc, CHANGELOG.md, package.json, test/server/compiler-test.js
[closes DevExpress/testcafe-private#182]
=> release: publish 2.6.1

.publishrc, package.json
=> release: updated version (2.6.2-rc.1) and HH

.publishrc, package.json
=> release: updated version (2.6.2)

src/client-functions/client-function-builder.js
Closes https://github.com/DevExpress/testcafe/issues/7707
=> fix 'Testcafe crashes if driver status result is null'

.github/workflows/deploy-to-artifacts.yml, .github/workflows/test-functional-local-edge.yml, .github/workflows/test-functional.yml, Gulpfile.js, test/functional/config.js, test/functional/fixtures/api/es-next/take-screenshot/test.js
[closes DevExpress/testcafe-private#193]
=> github-actions: moved testing on the edge to the github-host

.publishrc, package.json
=> release: updated version (3.0.0-rc.1)

package.json, test/functional/fixtures/browser-provider/browser-reconnect/test.js
=> build: updated HH

src/api/structure/interfaces.ts, src/reporter/index.ts, ts-defs-src/test-api/structure.d.ts, ts-defs-src/test-api/test-info.d.ts
=> fix: meta typings regression

.publishrc, package.json
=> release: publish (3.0.0)

src/notifications/warning-message.ts, src/video-recorder/recorder.js, test/functional/fixtures/video-recording/test.js, test/server/video-recorder-test.js
Need to add info about singleFile option for users to be able to identify the cause of the issue
Update warning message
#7256
=> fix: add more info to the video recording pattern warning message(closes #7256)

src/cli/argument-parser/index.ts, src/configuration/option-names.ts, src/configuration/testcafe-configuration.ts, src/errors/runtime/templates.js, src/errors/types.js, src/reporter/index.ts, src/runner/index.js, src/utils/debug-loggers.ts, src/utils/get-options/index.ts, test/server/configuration-test.js, test/server/reporter-test.js
Changes:
* add logging for the `Reporting` subsystem
* remove the `dashboard` subsystem leftovers
=> add logging for reporting, remove dashboard leftovers

.publishrc, package.json
=> release: updated version (3.0.1-rc.1)

.publishrc, CHANGELOG.md, package.json
=> release: updated version (3.0.1)

src/api/structure/interfaces.ts, src/api/structure/testing-unit.ts
https://github.com/DevExpress/testcafe-private/issues/208
Remove extra type
https://github.com/DevExpress/testcafe-private/issues/208
=> fix: remove extra metadata type

package.json, test/functional/fixtures/api/es-next/upload/pages/7832.html, test/functional/fixtures/api/es-next/upload/test.js, test/functional/fixtures/api/es-next/upload/testcafe-fixtures/7832.js
Changes:
* fix incorrect `HTMLFileInput.value` value
=> partial fix for the GH-7832 issue

test/client/fixtures/automation/click-test.js, test/client/fixtures/automation/content-editable/api-actions-content-editable-test/index-test.js, test/client/fixtures/automation/drag-test.js, test/client/fixtures/automation/regression-test.js
[closes DevExpress/testcafe-private#218]
=> test: fixed tests for mobile safari

src/native-automation/client/event-descriptor.ts, test/functional/fixtures/api/es-next/click/pages/index.html, test/functional/fixtures/api/es-next/click/test.js, test/functional/fixtures/api/es-next/click/testcafe-fixtures/click-test.js
[closes #7867]
Fix issue `Some clicks don't work in native automation mode`
1. Find out the reason why click doesn't work correctly in NA
2. Add a test
3. Fix issue
https://github.com/DevExpress/testcafe/issues/7867
=> fix: added pressure for click in NA

package.json
New hh version contains vulnerability fix
=> fix: bump hammerhead version to 31.4.11

.publishrc, package.json
=> release: updated release (v3.1.0-rc.1)

package.json
=> release: updated version (3.1.0-rc.2)

src/native-automation/request-pipeline/index.ts, src/native-automation/request-pipeline/safe-api.ts
The second part of https://github.com/DevExpress/testcafe/pull/7875
We handled the Request error, but we have an unsafe code in targetAttached handler.
Use try-catch 
https://github.com/DevExpress/testcafe/pull/7875
=> fix: Session with given id not found(closes #7865, #7810)

.publishrc, package.json
[closes DevExpress/testcafe-private#229]
=> release: update version 3.1.0

test/client/fixtures/automation/content-editable/api-actions-content-editable-test/index-test.js, test/client/fixtures/automation/content-editable/regression-test/index-test.js, test/client/fixtures/automation/content-editable/select-and-type-content-editable-test/index-test.js
=> refactor: removed IE leftovers in test\client\fixtures\automation\content-editable

test/client/fixtures/automation/automations-test.js, test/client/fixtures/automation/click-test.js, test/client/fixtures/automation/detection-element-after-events-simulation-test.js, test/client/fixtures/automation/drag-test.js, test/client/fixtures/automation/focus-blur-change-test.js, test/client/fixtures/automation/hover-test.js, test/client/fixtures/automation/out-of-bounds-test.js, test/client/fixtures/automation/press-test.js, test/client/fixtures/automation/select-test/index-test.js
=> refactor: removed IE leftovers from test\client\fixtures\automation (part1)

package-lock.json, test/client/fixtures/automation/rclick-test.js, test/client/fixtures/automation/regression-test.js, test/client/fixtures/automation/select-element-test.js, test/client/fixtures/automation/submit-on-enter-test.js, test/client/fixtures/automation/tab-emulation-test.js, test/client/fixtures/automation/utils-test.js
=> refactor: removed IE leftovers from test\client\fixtures\automation (part 2)

.github/workflows/deploy-to-artifacts.yml, .github/workflows/test-functional-docker.yml, .github/workflows/test-functional-local-chrome.yml, .github/workflows/test-functional-local-edge.yml, .github/workflows/test-functional-local-esm.yml, .github/workflows/test-functional-local-firefox.yml, .github/workflows/test-functional-local-headed-browsers.yml, .github/workflows/test-functional-local-legacy.yml, .github/workflows/test-functional-local-multiple-windows.yml, .github/workflows/test-functional-local-native-automation.yml, .github/workflows/test-functional-local-safari.yml, .github/workflows/test-functional-remote-mobile.yml, .github/workflows/test-functional.yml
[closes DevExpress/testcafe-private#232]
=> github-actions: added saving debug logs by default for all functional tests

.publishrc, package.json
=> release: updated release (v3.2.0-rc.1)

package-lock.json
=> build: updated package-lock

.publishrc, package-lock.json, package.json
=> release: updated version (v3.2.0)

CHANGELOG.md
=> release: updated changelog

src/client-functions/selectors/selector-builder.js, src/utils/escape-unsafe-chars.ts
=> fix: fixed codeql vulnerability 19

package-lock.json, package.json, test/functional/fixtures/regression/gh-7599/pages/disable-multiple-windows/_child-page.html, test/functional/fixtures/regression/gh-7599/pages/disable-multiple-windows/click-on-link.html, test/functional/fixtures/regression/gh-7599/pages/disable-multiple-windows/form-submit.html, test/functional/fixtures/regression/gh-7599/pages/disable-multiple-windows/window-open.html, test/functional/fixtures/regression/gh-7599/test.js, test/functional/fixtures/regression/gh-7599/testcafe-fixtures/disable-multiple-windows.js, test/functional/utils/skip-in.js
Connected PR - https://github.com/DevExpress/testcafe-hammerhead/pull/2957
Closes https://github.com/DevExpress/testcafe/issues/7916
=> native automation: disableMultipleWindows

legacy.test.js, src/errors/runtime/templates.js, src/errors/types.js, src/runner/bootstrapper.ts, test/functional/fixtures/regression/gh-7942/test.js, test/functional/fixtures/regression/gh-7942/testcafe-fixtures/legacy.test.js
=> fix 'legacy test running with the native automation mode'

test/client/legacy-fixtures/api-actions-content-editable-test/index-test.js, test/client/legacy-fixtures/regression-test.js, test/client/legacy-fixtures/runner-test.js, test/client/legacy-fixtures/select-element-test.js
=> refactor: removed IE leftovers from test\client\legacy-fixtures

test/client/before-test.js, test/client/fixtures/automation/automations-test.js, test/client/fixtures/automation/press-shortcuts-test.js, test/client/fixtures/automation/regression-test.js, test/client/fixtures/automation/select-test/index-test.js
=> refactor: removed IE leftovers from test\client

.publishrc, package-lock.json, package.json
=> publish: v3.3.0-rc.1

package.json
=> release: updated version

package-lock.json
=> release: fix package-lock

.github/workflows/test-functional.yml, test/functional/fixtures/browser-provider/browser-reconnect/run-log-error-on-disconnect-test.js, test/functional/fixtures/browser-provider/browser-reconnect/test.js, test/functional/fixtures/live/test.js
[closes DevExpress/testcafe-private#282]
=> fix: safari tests

test/functional/fixtures/api/es-next/client-function/test.js, test/functional/fixtures/api/es-next/dispatch-event/test.js, test/functional/fixtures/api/es-next/eval/test.js, test/functional/fixtures/api/es-next/hooks/test.js, test/functional/fixtures/api/es-next/iframe-switching/pages/index.html, test/functional/fixtures/api/es-next/iframe-switching/test.js, test/functional/fixtures/api/es-next/roles/test.js, test/functional/fixtures/api/es-next/select-text/testcafe-fixtures/select-text-test.js, test/functional/fixtures/api/es-next/selector/test.js, test/functional/fixtures/api/es-next/selector/testcafe-fixtures/selector-test.js, test/functional/fixtures/api/es-next/take-screenshot/testcafe-fixtures/take-screenshot.js
=> refactor: removed IE leftovers fromtest\functional\fixtures\api\es-next

test/server/cli-argument-parser-test.js, test/server/configuration-test.js, test/server/data/test-suites/typescript-defs/selectors.ts, test/server/data/test-suites/typescript-selectors-defs/selector.ts, test/server/data/test-suites/typescript-testcafe-scripts-defs/selector.ts
=> refactor: removed IE leftovers from test\server

.github/workflows/handle-stale.yml
some issues was not proccess for some reasons, so I change the settings of stale bot temporary to fix process missing issues
+ decrease time of inactive period
=> change stale-bot settings

test/functional/assertion-helper.js, test/functional/config.js
=> refactor: removed IE leftovers from test\functional

src/client/automation/playback/click/browser-click-strategy.ts, src/client/automation/playback/click/select-child.js, src/client/automation/playback/move/event-sequence/base.js, src/client/automation/playback/press/key-press-simulator.js, src/client/automation/playback/press/shortcuts.js
=> refactor: removed IE leftovers from src\client\automation (part 1)

src/client/automation/get-element.ts, src/client/automation/move.ts, src/client/automation/playback/dblclick.js, src/client/automation/playback/rclick.js, src/client/automation/playback/select/base.js, src/client/automation/playback/select/utils.js, src/client/automation/playback/type/type-text.js
=> refactor: removed IE leftovers from src\client\automation (part 2)

src/client/core/utils/key-maps.js, src/client/core/utils/position.ts, src/client/core/utils/scroll.ts, src/client/core/utils/text-selection.js
=> refactor: removed IE leftovers from src\client\core\utils (part 2)

src/client/core/prevent-real-events.js, src/client/core/utils/dom.js
=> refactor: removed IE leftovers from src\client\core

src/client/browser/idle-page/index.html.mustache, src/client/driver/command-executors/client-functions/selector-executor/node-snapshots.ts, src/client/test-run/index.js.mustache, src/client/ui/cursor/iframe-cursor.js, src/client/ui/cursor/index.js, src/client/ui/select-element.js
=> refactor: removed IE leftovers from src\client

src/cli/argument-parser/index.ts, src/client-functions/selectors/selector-text-filter.js, src/client/browser/index.js
=> refactor: removed IE leftovers from src\others

src/client/ui/selector-inspector-panel/descriptors.js, src/client/ui/selector-inspector-panel/hide-button.js, src/client/ui/selector-inspector-panel/index.js, src/client/ui/selector-inspector-panel/main-container.js, src/client/ui/styles.less, test/functional/fixtures/ui/test.js, test/functional/fixtures/ui/testcafe-fixtures/selector-inspector-test.js, test/functional/fixtures/ui/utils/selector-inspector.js
Added button for debugger selector panel which hide and show panel. It's trial version without design.
=> [WIP] add hide/show btn for debugger selector panel

gulp/constants/client-test-settings.js
=> build: fix desktop client test

.publishrc, package-lock.json, package.json
=> release: v3.5.0-rc.1

.publishrc, CHANGELOG.md, package-lock.json, package.json
=> release: v3.5.0

package-lock.json
=> testing: new build of qunit-harness (#8131)

package-lock.json, package.json
fixed: https://github.com/DevExpress/testcafe/security/dependabot/45
=> build: bump gulp-babel

package-lock.json, package.json
=> Build: overrides minimatch  and glob

package-lock.json, package.json
=> release: v3.6.0-rc.1

package-lock.json, package.json
=> bump: testcafe-legacy-api

.publishrc, CHANGELOG.md, package-lock.json, package.json
=> version 3.6.1 latest

.github/workflows/deploy-to-artifacts.yml, .github/workflows/license-check.yml, test/dependency-licenses-checker.js
Add a workflow to check production dependencies licenses.
Create a new workflow file and add it in artifacts deploy
Correct licenses run: https://github.com/Testing-and-Learning/testcafe/actions/runs/9413544636
Incorrect licenses run: https://github.com/Testing-and-Learning/testcafe/actions/runs/9413057523/job/25929056940
=> license check workflow added

.publishrc, package-lock.json, package.json
=> release: version updated to 3.6.2-rc.1

test/dependency-licenses-checker.js
=> fix: license checker fixed for publishing

.publishrc, CHANGELOG.md, package-lock.json, package.json
=> 3.6.2 latest release

ts-defs-src/test-api/test-info.d.ts
=> update: change Metadata from type to interface

package-lock.json
=> upd package-lock

src/native-automation/request-pipeline/safe-api.ts
closes https://github.com/DevExpress/testcafe/issues/8258
=> testing: fix promise rejection error

src/client/automation/playback/move/event-sequence/base.js, test/functional/fixtures/regression/gh-8264/pages/index.html, test/functional/fixtures/regression/gh-8264/test.js, test/functional/fixtures/regression/gh-8264/testcafe-fixtures/index.js
=> fix: add check prev element

.publishrc, package-lock.json, package.json
=> release: 3.7.0-rc.1

package-lock.json
=> release: upd package-lock

src/browser/provider/built-in/dedicated/chrome/build-chrome-args.js
=> fix: add --disable-component-extensions-with-background-pages flag to default arguments 

package-lock.json, package.json
=> fix: devtools package moved from dev to prod packages

.github/workflows/publish.yml, package-lock.json, package.json, test/docker/Dockerfile
=> fix: docker server-test run fail fixed

examples/running-tests-in-chrome-using-bitbucket-pipelines-ci/bitbucket-pipelines.yml
=> update: example with bitbucket

.publishrc, CHANGELOG.md, package-lock.json, package.json
=> release: v3.7.1

gulp/docker/run-functional-test-via-command-line.js, src/browser/provider/built-in/dedicated/chrome/build-chrome-args.js
=> Stabilize docker tests

.github/workflows/test-server-latest.yml, .github/workflows/test-server.yml
=> Server tests workflow updated to pass node-options as input

.github/workflows/test-functional.yml
=> fix: functional remote mobile workflow fixed to not upload artifacts

docker/Dockerfile
closes https://github.com/DevExpress/testcafe/issues/8362
=> add: package chromium-lang added to dockerfile

.publishrc, package-lock.json, package.json
=> release: 3.7.2-rc.1

.publishrc, CHANGELOG.md, package-lock.json, package.json
=> release: 3.7.2 latest
