src/reporters/json.js
src/reporters/xunit.js
test/server/reporters-test.js

`xunit` and `json` reporters always use plain-text decorator (closes #86)

---

Gulpfile.js

Fix is the same like in hammerhead

Don't allow es6-promise pollute `window` in client scripts (close #78)

---

src/runner/index.js

Now we send send to the `Reporter` constructor `null` as `outStream` and `errorDecorator` parameters by default. But reporter falls back them to default values it they are `undefined`.
For fix we can write 
```js
reporter (reporter, outStream = void 0, errorDecorator = void 0) {
```
but it makes no sense because a default argument is applied if the argument is `undefined`.
/cc @inikulin

Set outStream to process.stdout if it's not specified (closed #114)

---

.babelrc
bin/testcafe
package.json
src/browser-connection/index.js
src/cli/.eslintrc
src/cli/argument-parser.js
src/cli/index.js
src/client/runner/runner-base.js
src/client/test-run/iframe.js.mustache
src/client/test-run/index.js.mustache
src/index.js
src/messages.js
src/reporters/base.js
src/reporters/json.js
src/reporters/spec.js
src/reporters/xunit.js
src/runner/index.js
src/runner/test-run/index.js
src/utils/get-viewport-width.js
test/client/fixtures/runner/automation/tab-emulation-test.js
test/server/browser-connection-test.js
test/server/cli-argument-parser-test.js
test/server/create-testcafe-test.js
test/server/runner-test.js

You can try it locally (please try it) by running in the shell:
```sh
mkdir test-cli && cd ./test-cli && \
git clone https://github.com/inikulin/testcafe-phoenix && \ 
cd ./testcafe-phoenix && git checkout cli && \
npm install && gulp build
```
Then to run CLI:
```
node bin/testcafe <args>
```
\cc @churkin @AlexanderMoskovkin @kirovboris 
@VasilyStrelyaev check texts and test names, please

Implement CLI (closes #105)

---

src/client/runner/action-barrier/xhr.js
test/client/fixtures/runner/xhr-test.js

\cc @inikulin @AlexanderMoskovkin @helen-dikareva

Make TestRunner don't wait for aborted XHR's (closes #132)

---

test/client/fixtures/runner/automation/select-element-test.js

Bug was fixed after refactoring in testcafe-phoenix. Just test fixed for checking this scenario.

Event 'change'  raising fixed for select elements with option groups (close #133)

---

package.json
src/messages.js
src/runner/bootstrapper.js
test/server/runner-test.js

Runner.browser() now accepts browser path (fixes #128)

---

src/runner/browser-job.js

\cc @AlexanderMoskovkin @churkin 
Unfortunately there is no way to test it :cry:  Because currently reporting testing involves having mocking and functional test are not ready yet.

Add 'test-run-start' event to the BrowserJob (fixes #186)

---

src/client/runner/runner-base.js

This is an afterfix for the #161 issue. Here is fixed the following scenario:
```
- start a step in an iframe
- start waiting for the element for the action (progress panel is shown)
- iframe reloading (it's maybe document.location changing on timeout) -- here we should close the panel
- start the next step 
```
We have the functional test for this
/cc @inikulin @helen-dikareva

"Wait for element" progress bar is not shown (#161) afterfix

---

src/compiler/legacy/get_err_msg.js

Add missing error message for the legacy compiler (fixes #195)

---

package.json
src/reporter/plugin-host.js
test/server/error-formatter-test.js

\сс @kirovboris @AlexanderMoskovkin

Make word wrapping optional in `formatError` (fixes #228). Bump version.

---

src/client/core/utils/event.js
src/client/runner/api/actions.js
src/client/runner/iframe-dispatcher.js
src/client/runner/runner-base.js
src/client/ui/modal-background.js
src/client/ui/progress-panel/index.js

This PR'll close item "Get rid of jquery binding for 'ready' and 'load' events" from https://github.com/DevExpress/testcafe/issues/56 checklist
Wait for all qunit tests

Binding to document.ready event implemented without jQuery (partial of #56)

---

.travis.yml

/cc @georgiy-abbasov It's necessary right now to stable qunit tests in opened pull requests

Switch 'test-client-travis' gulp task to 'stable' nodejs version

---

package.json
src/errors/test-run/formattable-adapter.js
src/legacy/test-run-error/formattable-adapter.js
src/legacy/test-run-error/templates.js
src/legacy/test-run/index.js
src/reporter/plugin-host.js
test/server/data/expected-legacy-test-run-errors/empty-first-argument
test/server/data/expected-legacy-test-run-errors/empty-type-action-argument
test/server/data/expected-legacy-test-run-errors/eq-assertion
test/server/data/expected-legacy-test-run-errors/incorrect-dragging-second-argument
test/server/data/expected-legacy-test-run-errors/incorrect-press-action-argument
test/server/data/expected-legacy-test-run-errors/incorrect-select-action-arguments
test/server/data/expected-legacy-test-run-errors/incorrect-wait-action-milliseconds-arguments
test/server/data/expected-legacy-test-run-errors/incorrect-wait-for-action-event-argument
test/server/data/expected-legacy-test-run-errors/incorrect-wait-for-action-timeout-argument
test/server/data/expected-legacy-test-run-errors/invisible-action-element
test/server/data/expected-legacy-test-run-errors/not-eq-assertion
test/server/data/expected-legacy-test-run-errors/not-ok-assertion
test/server/data/expected-legacy-test-run-errors/ok-assertion
test/server/data/expected-legacy-test-run-errors/upload-can-not-find-file-to-upload
test/server/data/expected-legacy-test-run-errors/upload-element-is-not-file-input
test/server/data/expected-legacy-test-run-errors/upload-invalid-file-path-argument
test/server/data/expected-legacy-test-run-errors/wait-for-action-timeout-exceeded
test/server/legacy-test-run-error-formatting-test.js

\cc @kirovboris @churkin 
@kirovboris note that `errorDecorator` has been changed. I've bumped the version already, so once we've done with this PR you will be able to update it for the studio.

Redesign error decorator, so it fits needs of both API versions (#374 part5)

---

Gulpfile.js
package.json

\cc @AlexanderMoskovkin 
This breaks `gulp publish` because we always have uncommitted changes in the working tree.

Don't modify package.json if we don't have greenkeeper ignore changes.

---

.markdownlint.json
docs/articles/documentation/index.md
docs/articles/documentation/using-testcafe/command-line-interface.md
docs/articles/documentation/using-testcafe/common-concepts/browser-aliases.md
docs/articles/documentation/using-testcafe/common-concepts/index.md
docs/articles/documentation/using-testcafe/index.md
docs/articles/documentation/using-testcafe/programming-interface/BrowserConnection.md
docs/articles/documentation/using-testcafe/programming-interface/Runner.md
docs/articles/documentation/using-testcafe/programming-interface/TestCafe.md
docs/articles/documentation/using-testcafe/programming-interface/createTestCafe.md
docs/articles/documentation/using-testcafe/programming-interface/index.md
docs/nav/nav-menu.yml

Docs - Introduce links that are navigable when browsing the repo

---

test/functional/assertion-helper.js
test/functional/fixtures/api/es-next/before-after-each-hooks/test.js
test/functional/fixtures/api/es-next/click/test.js
test/functional/fixtures/api/es-next/double-click/test.js
test/functional/fixtures/api/es-next/generic-errors/test.js
test/functional/fixtures/api/es-next/right-click/test.js
test/functional/fixtures/api/es-next/test-controller/test.js
test/functional/fixtures/api/es-next/test-controller/testcafe-fixtures/test-controller-test.js
test/functional/fixtures/api/legacy/click/test.js
test/functional/fixtures/api/legacy/click/testcafe-fixtures/click.test.js
test/functional/fixtures/api/raw/before-after-each-hooks/test.js
test/functional/fixtures/api/raw/click/test.js
test/functional/fixtures/api/raw/double-click/test.js
test/functional/fixtures/api/raw/hover/test.js
test/functional/fixtures/api/raw/right-click/test.js
test/functional/fixtures/before-unload-handling/test.js
test/functional/fixtures/native-dialogs-handling/test.js
test/functional/fixtures/quarantine-mode/test.js
test/functional/fixtures/regression/gh-414/test.js
test/functional/fixtures/regression/t200501/test.js
test/functional/fixtures/uncaught-js-errors/test.js
test/functional/fixtures/upload/test.js
test/functional/get-test-error.js
test/functional/setup.js

Fixed behavior for functional tests with attributes 'SKIP' and 'ONLY' (closes #444)

---

.travis.yml
Gulpfile.js

We do it to have an ability to restart client tests on mobile devices only while we are fixing unstable tests

Move client tests on mobile browsers to the separate task

---

src/cli/argument-parser.js
src/runner/bootstrapper.js
test/server/cli-argument-parser-test.js
test/server/runner-test.js

\cc @inikulin. @AlexanderMoskovkin, @VasilyStrelyaev (changed error message, test names)

Implemented 'path:' prefix for browser paths (closes #468, closes #466)

---

src/client/core/utils/dom.js
src/client/runner/automation/get-element.js
test/client/fixtures/runner/automation/tab-emulation-test.js

Usage of "browserUtils.isOpera" dropped (closes #497)

---

src/api/common/hybrid/index.js
src/api/common/index.js
src/api/test-controller.js
src/compiler/es-next/compile-hybrid-function.js
src/test-run/commands/type.js
test/functional/fixtures/api/es-next/eval/pages/index.html
test/functional/fixtures/api/es-next/eval/test.js
test/functional/fixtures/api/es-next/eval/testcafe-fixtures/eval-test.js
test/server/compiler-test.js
test/server/create-testcafe-test.js

\cc @AlexanderMoskovkin @helen-dikareva @AndreyBelym 
Note that I've changed the way we define API methods to avoid code duplication.
@VasilyStrelyaev pls, check strings

Refactor TestController. Implement t.eval() (#241)

---

.travis-docs.yml
Gulpfile.js
docs/articles/documentation/extending-testcafe/custom-reporter/helper-methods.md

The broken link checker seems to wrongly mark links as "leading to the same page".
That's why it's missing some broken links unless the `excludeLinksToSamePage` option is disabled.

[docs] Work around a bug in the broken link checker

---

src/client/core/utils/dom.js
test/client/fixtures/core/dom-utils-test.js
test/client/fixtures/core/sandboxed-jquery-test/index-test.js

about the `isIFrameWindowInDOM` test - the functionality was broken for cross-domain iframes.
about the `sandboxed-jquery` test - I've discussed with test creator, here should be same-domain iframe
/cc @helen-dikareva @georgiy-abbasov

isIFrameWindowInDOM behavior fixed. sandboxed-jquery client test corrected

---

src/errors/test-run/templates.js
src/reporter/plugin-host.js

* Add decorator for error subtitles
* Wrap null, undefined number, etc. with \<code\> in messages
/cc @inikulin

Refactor report errors for the APIv2 (part of #374)

---

src/errors/process-test-fn-error.js
src/errors/test-run/formattable-adapter.js
src/errors/test-run/templates.js
test/functional/fixtures/api/es-next/generic-errors/test.js
test/functional/fixtures/api/es-next/generic-errors/testcafe-fixtures/external-assertion-lib-errors-test.js
test/server/data/expected-test-run-errors/external-assertion-library-error

* Callsites for assertion errors (filter node_modules and internal callsites)

Refactor report errors for the APIv2 (closes #374)

---

.gitignore
Gulpfile.js
docs/articles/documentation/getting-started/index.md
docs/articles/documentation/test-api/actions.md
docs/articles/documentation/test-api/executing-client-code/index.md
docs/articles/documentation/test-api/index.md
docs/articles/documentation/test-api/test-code-structure.md
docs/articles/documentation/using-testcafe/programming-interface/browserconnection.md
docs/articles/documentation/using-testcafe/programming-interface/runner.md
package.json
test/website/test.js

/cc @DevExpress/testcafe-docs 
Added a thing that, when checking for broken links, parses the referenced documents to check that an element with a particular name/id exists.
Is it too crappy?

[docs] Add testing for invalid hashes

---

package.json
src/api/test-controller.js
src/client/driver/command-executors/client-functions/selector-executor.js
src/client/driver/command-executors/execute-action.js
src/client/driver/driver.js
test/functional/fixtures/api/es-next/select/pages/index.html
test/functional/fixtures/api/es-next/select/test.js
test/functional/fixtures/api/es-next/select/testcafe-fixtures/select-test.js
test/functional/fixtures/api/es-next/selector/pages/index.html
test/functional/fixtures/api/es-next/selector/pages/new-page-element.html
test/functional/fixtures/api/es-next/selector/test.js
test/functional/fixtures/api/es-next/selector/testcafe-fixtures/selector-test.js

In this final part:
- Cross-page behavior
- `t.select`
\cc @helen-dikareva @AlexanderMoskovkin @VasilyStrelyaev

Implement `Selector` (part7, closes #574)

---

docs/articles/documentation/using-testcafe/command-line-interface.md
docs/articles/documentation/using-testcafe/programming-interface/runner.md

/cc @DevExpress/testcafe-docs 
That phrase has already been checked so I leave the `checked: true` flag in these topics.

[docs] Renamed 'element timeout' to 'selector timeout'

---

test/functional/config.js
test/functional/setup.js

It was a mistake that has broken local functional tests running (via gulp-task too)
/cc @inikulin

Fix functional tests running

---

test/server/compiler-test.js
test/server/data/test-suites/regression-gh-599/testfile.js

Module `babel-preset-es2015-loose` uses the latest version of `babel-plugin-transform-regenerator` module, so we have the fix already

Added regression test for GH-599 (closes #599)

---

docs/articles/index.html

Part of https://github.com/DevExpress/testcafe-gh-page-assets/issues/13
Landing page doesn't actually need a head - it should be in the layout.

[docs] Move the landing page head to assets

---

.eslintignore
Gulpfile.js
package.json
src/browser/provider/built-in/saucelabs.js
src/client-functions/client-function-builder.js
src/client-functions/selector-builder.js
src/client/core/index.js
src/client/driver/iframe-driver.js
test/functional/fixtures/api/es-next/selector/test.js
test/functional/fixtures/api/es-next/selector/testcafe-fixtures/selector-test.js

Fix `ReferenceError: selector is not defined` if selector promise is passed to `t.select` (fixes #716). Fix linting and related errors. Bump version.

---

docs/articles/documentation/using-testcafe/programming-interface/browserconnection.md
docs/articles/documentation/using-testcafe/programming-interface/createtestcafe.md
docs/articles/documentation/using-testcafe/programming-interface/index.md
docs/articles/documentation/using-testcafe/programming-interface/runner.md
docs/articles/documentation/using-testcafe/programming-interface/testcafe.md

\cc @DevExpress/testcafe-docs @AndreyBelym 
I've also changed the synopsis for async methods from
`methodName(param1, param2) → Promise<Type>`
to
`async methodName(param1, param2) → Type`
it reads better IMHO

[docs] createBrowserConnection is async now

---

README.md

/cc @inikulin @VasilyStrelyaev 
I've added info from the landing page and create common sections: license, contributing... 
I haven't added info from Getting Started, there will be a link to the Getting Started section from the documentation.
Some notes:
1. Do we need some introduction about TestCafe or "Modern functional testing framework" is enough?
2. Do we need the **Modules** section?
3. In the **Documentation** section, there will be links to the main sections on gh-pages. They do not work yet.
4. The image for the **Descriptive Reports** section isn't ready.

[docs] Readme updated

---

src/client/core/page-unload-barrier.js
src/client/driver/driver.js
src/client/driver/iframe-driver.js
test/functional/fixtures/regression/gh-664/pages/index.html
test/functional/fixtures/regression/gh-664/test.js
test/functional/fixtures/regression/gh-664/testcafe-fixtures/index-test.js

/cc @inikulin @helen-dikareva @georgiy-abbasov @VasilyStrelyaev 
We fix the situation when the `beforeunload` event is raised but the page is not unloading (it occurs if it was click on a download link or in the situation described in #664).
So, with this fix we resumes the test if the page is not unloaded after 15 seconds after the `beforeunload` event.
In usual case it can be delay between `beforeunload` and `unload` events if the server responses with some timeout (it can be hard work on the server or a query to a database or smthg else).
We were planning to use the [hammerhead feature](https://github.com/DevExpress/testcafe-hammerhead/issues/667) to fix this, but it takes to much time to implement it. So I think we should add this temporary fix as a workaround for now to have not this …

Resolve page-unload-barrier waiting after a timeout (workaround for #437, #664)

---

src/client-functions/selector-builder.js
src/client/driver/command-executors/client-functions/selector-executor/index.js
test/functional/fixtures/api/es-next/selector/test.js
test/functional/fixtures/api/es-next/selector/testcafe-fixtures/selector-test.js
test/server/compiler-test.js
test/server/data/test-suites/selector-text-filter-is-not-regexp-or-string/testfile.js

\cc @VasilyStrelyaev @AlexanderMoskovkin

Rename selector `textFilter` property to `text` (closes #765)

---

docs/articles/documentation/test-api/selecting-page-elements/selector-options.md
docs/articles/documentation/test-api/selecting-page-elements/selectors.md

[docs] Rename `textFilter` to `text` (#765-related changes)

---

Gulpfile.js

Fix test-functional-travis-old-browsers

---

Gulpfile.js
src/cli/argument-parser.js

[docs] Remove ES6 syntax from Gulpfile. Fix link to website in CLI (fixes #780)

---

src/client/automation/playback/click/select-child.js

/cc @AlexanderMoskovkin @AndreyBelym 
Now we should raise `'change'` event after click on `option` in `select` with size more than one in Chrome

Fix qunit tests in Chrome

---

src/client/test-run/iframe.js.mustache
src/client/test-run/index.js.mustache
src/test-run/index.js
test/functional/fixtures/regression/gh-754/testcafe-fixtures/index-test.js

\cc @kirovboris @AlexanderMoskovkin

Always use escaped strings for templates (fixes #814)

---

src/client-functions/selector-builder.js
test/functional/fixtures/regression/gh-754/test.js
test/functional/fixtures/regression/gh-814/test.js
test/functional/fixtures/regression/gh-814/testcafe-fixtures/index-test.js
test/functional/fixtures/regression/gh-822/pages/index.html
test/functional/fixtures/regression/gh-822/test.js
test/functional/fixtures/regression/gh-822/testcafe-fixtures/index-test.js

\cc @helen-dikareva @AndreyBelym

Use single browser for about:blank regression tests. Escape string selector code (fixes #822).

---

src/client/core/page-unload-barrier.js
test/functional/fixtures/regression/gh-608/pages/index.html
test/functional/fixtures/regression/gh-608/test.js
test/functional/fixtures/regression/gh-608/testcafe-fixtures/index-test.js

\cc @AlexanderMoskovkin, @inikulin

Check for e.isFakeIEEvent has been deleted from page-unload-barrier (closes #608)

---

README.md

**A question:** should we also change all the links from this Readme to GitHub Pages from `http` to `https` or it doesn't matter?

[docs] Readme - add links to blog and twitter

---

test/functional/fixtures/api/es-next/iframe-switching/pages/iframe.html
test/functional/fixtures/api/es-next/iframe-switching/pages/index.html
test/functional/fixtures/api/es-next/iframe-switching/test.js
test/functional/fixtures/api/es-next/iframe-switching/testcafe-fixtures/iframe-switching-test.js

For this test: https://travis-ci.org/testcafe-build-bot/testcafe/jobs/166387072#L1797
It seems the problem occurs because the `beforeUnload` event is raised a little bit later than we are expecting in the test.

Fix unstable iframe-switching test in safari

---

Gulpfile.js
src/client/driver/command-executors/client-functions/selector-executor/index.js
test/functional/fixtures/api/es-next/selector/test.js
test/functional/fixtures/api/es-next/selector/testcafe-fixtures/selector-test.js

\cc @AndreyBelym @helen-dikareva @VasilyStrelyaev

Fallback to `textContent` for `<option>` element text selectors in Firefox (fixes #861)

---

.github/ISSUE_TEMPLATE.md
CODE_OF_CONDUCT.md
CONTRIBUTING.md

Not checked yet so just take a look.
fixes #703

[docs] Added a contribution guide, code of conduct and issue template (closes #703)

---

test/server/compiler-test.js

We have failed server tests after [changes in babylon](https://github.com/babel/babylon/pull/150). It was released in [v6.11.5](https://github.com/babel/babylon/blob/c300230a59ff80f524be609c12bc158cada1ead5/CHANGELOG.md#v6115-2016-10-12) several hours ago
/cc @inikulin

Fix server compiler test after babylon@6.11.6 update

---

package.json
test/functional/config.js

Updating `testcafe-legacy-api` is related with https://github.com/DevExpress/testcafe/pull/869 and https://github.com/DevExpress/testcafe-legacy-api/pull/20
/cc @inikulin

Update testcafe-legacy-api. Downgrade MSEdge version for functional tests (workaround for #872)

---

src/client/driver/command-executors/client-functions/selector-executor/index.js

Fix selector text filter for `document` nodes in MSEdge 14 (closes #875)

---

.eslintrc
.gitignore
examples/basic/test.js
src/api/test-controller.js
src/client-functions/client-function-builder.js
src/client-functions/selector-builder/create-snapshot-property-shorthands.js
src/client-functions/selector-builder/index.js
src/client-functions/selector-builder/node-snapshot-properties.js
src/client/driver/command-executors/client-functions/selector-executor/filter.js
src/client/driver/command-executors/client-functions/selector-executor/index.js
src/client/driver/command-executors/client-functions/selector-executor/node-snapshots.js
src/errors/callsite.js
src/errors/process-test-fn-error.js
src/errors/runtime/index.js
src/errors/test-run/index.js
src/errors/test-run/templates.js
src/errors/test-run/type.js
test/functional/fixtures/api/es-next/selector/test.js
test/functional/fixtures/api/es-next/selector/testcafe-fixtures/selector-test.js
test/server/data/expected-test-run-errors/cant-obtain-info-for-element-specified-by-selector-error
test/server/test-run-error-formatting-test.js

\cc @AlexanderMoskovkin @helen-dikareva 
@VasilyStrelyaev please, check error messages and comments. Feature summary for documentation is here in the OP post: https://github.com/DevExpress/testcafe/issues/771

Node snapshot properties shorthands for Selector (closes #771)

---

src/client/automation/utils/utils.js
test/functional/fixtures/regression/gh-913/pages/index.html
test/functional/fixtures/regression/gh-913/test.js
test/functional/fixtures/regression/gh-913/testcafe-fixtures/index-test.js

\cc @inikulin, @AlexanderMoskovkin, @AndreyBelym

Fixed focus for click automation (closes #913)

---

appveyor.yml
package.json
src/browser/provider/built-in/locally-installed.js
src/browser/provider/built-in/path.js
src/cli/argument-parser.js
src/utils/string.js
test/server/browser-provider-test.js
test/server/cli-argument-parser-test.js

\cc @inikulin @AlexanderMoskovkin 
Allow to pass command line arguments for a browser starting through CLI. Example:
```
testcafe 'path:/usr/bin/chrome-browser --start-fullscreen' test.js 
testcafe 'path:`C:\Program Files (x86)\Google\Chrome\Application\chrome.exe` --start-fullscreen' test.js
testcafe 'chrome --start-fullscreen' test.js
```

Allow specifying browser arguments (closes #905)

---

src/client-functions/selector-builder/add-api.js
test/functional/fixtures/api/es-next/selector/test.js
test/functional/fixtures/api/es-next/selector/testcafe-fixtures/selector-test.js

Filter methods for `.find`, `.child`, '.parent`, '.sibling` now accepts third `origin` argument. Origin is the element in the left hand side selector matching set by which derivative node is produced, e.g.:
```js
Selector('.someClass').find((el, idx, originNode) => ...});
```
here `originNode` will be an element of `someClass` in which `el` was found. 
Another example:
```js
Selector('.someChild').parent((el, idx, originNode) => ... });
```
here `originNode` will be an element of `someClass` whose parent is `el`
\cc @VasilyStrelyaev @AlexanderMoskovkin @helen-dikareva

Add origin argument to selector fitler methods (closes #1065)

---

src/client-functions/selector-builder/add-api.js
src/client-functions/selector-builder/index.js
src/client/driver/command-executors/client-functions/client-function-executor.js
src/client/driver/command-executors/client-functions/replicator.js
src/client/driver/command-executors/client-functions/selector-executor/index.js
src/errors/runtime/message.js
src/errors/test-run/index.js
src/errors/test-run/templates.js
src/errors/test-run/type.js
test/functional/fixtures/api/es-next/selector/test.js
test/functional/fixtures/api/es-next/selector/testcafe-fixtures/selector-test.js
test/server/data/expected-test-run-errors/uncaught-error-in-add-custom-dom-properties-code
test/server/data/expected-test-run-errors/uncaught-error-in-snapshot-extension-code
test/server/test-run-error-formatting-test.js

\cc @inikulin @AlexanderMoskovkin @VasilyStrelyaev

Implemented DOM Node extensions mechanism (closes #749)

---

src/client/automation/playback/move.js
test/functional/fixtures/regression/gh-1140/pages/iframe.html
test/functional/fixtures/regression/gh-1140/pages/index.html
test/functional/fixtures/regression/gh-1140/test.js
test/functional/fixtures/regression/gh-1140/testcafe-fixtures/index.test.js

\cc @AlexanderMoskovkin, @AndreyBelym, @VasilyStrelyaev

Fixed cursor moving out from iframe in move automation (closes #1140)

---

src/client/ui/styles.less
test/functional/fixtures/regression/gh-1138/pages/index.html
test/functional/fixtures/regression/gh-1138/test.js
test/functional/fixtures/regression/gh-1138/testcafe-fixtures/index.test.js

\cc @AlexanderMoskovkin @helen-dikareva @VasilyStrelyaev

Avoid scrollbars in ShadowUI (closes #1138)

---

package.json
src/client/ui/cursor/index.js
src/client/ui/styles.less
test/functional/fixtures/regression/gh-1138/test.js

Repair cursor (closes #1156)

---

src/client/automation/playback/type/index.js
src/test-run/commands/options.js
test/client/fixtures/automation/regression-test.js
test/client/fixtures/automation/type-test.js
test/functional/fixtures/api/es-next/type/test.js
test/functional/fixtures/api/es-next/type/testcafe-fixtures/type-test.js
test/functional/fixtures/api/raw/type/pages/index.html
test/functional/fixtures/api/raw/type/test.js
test/functional/fixtures/api/raw/type/testcafe-fixtures/type.testcafe
test/server/test-run-command-options-test.js
test/server/test-run-commands-test.js

Resolves #1230.
There is currently no way to enter a block of text in a single keystroke with the [Test API](http://devexpress.github.io/testcafe/documentation/test-api/actions/action-options.html#typing-action-options).  This will allow optionally inserting a block of text with one keystroke instead of typing each character individually.
This could be useful in a number of situations, such as:
* Speeding up test playback where individual keystrokes are not important to the result
* Testing a large block of text entry in a WYSIWYG editor
* Testing form validation and submission on a form with 100+ fields
Documentation and tests have been updated.

Add `paste` option to TypeOptions

---

src/compiler/es-next/compile-client-function.js
src/compiler/es-next/index.js
test/server/compiler-test.js
test/server/data/client-fn-compilation/typeof/expected-node10.js
test/server/data/test-suites/regression-gh-1226/helper.js
test/server/data/test-suites/regression-gh-1226/testfile.js
test/server/data/test-suites/regression-gh-969/helpers/consts.js
test/server/data/test-suites/regression-gh-969/helpers/module.js
test/server/data/test-suites/regression-gh-969/testfile.js

Changed babel options to avoid extra lines in report (closes #1226)

---

src/compiler/es-next/compile-client-function.js
test/server/compiler-test.js
test/server/data/client-fn-compilation/gh1279/expected.js
test/server/data/client-fn-compilation/gh1279/testfile.js

\cc @kirovboris @AndreyBelym @AlexanderMoskovkin

Fix fails on ES6 method syntax in ClientFunction arguments (closes #1279)

---

package.json
src/client/core/utils/position.js
test/functional/fixtures/regression/gh-1312/pages/index.html
test/functional/fixtures/regression/gh-1312/test.js
test/functional/fixtures/regression/gh-1312/testcafe-fixtures/index-test.js

\cc @inikulin @AlexanderMoskovkin 
Requires https://github.com/DevExpress/testcafe-hammerhead/pull/1061

Handle target elements that are inside Shadow DOM (closes #1312)

---

bin/testcafe-with-v8-flag-filter.js
bin/testcafe.js
package.json

\cc @helen-dikareva @churkin @VasilyStrelyaev

Use V8 flag filters only in CLI. Helps avoid confusion when bin/testcafe.js is used for debugging from IDE

---

docs/articles/documentation/recipes/test-static-html-pages.md
docs/articles/documentation/test-api/actions/navigate.md
docs/articles/documentation/test-api/test-code-structure.md

[docs] Add info about the file:// protocol to a recipe

---

docs/articles/blog/2017-1-19-testcafe-v0-12-0-released.md
docs/articles/documentation/test-api/actions/README.md

[docs] Add a note about touch devices

---

src/compiler/es-next/compile-client-function.js
src/compiler/es-next/index.js

We have found, that `source-map-support` still not working while we are debugging server-side test code in `vs code` or `chrome dev-tools`, so @inikulin and me decided to re-enable option.

Re-enable "retainLines" compiler option

---

src/.eslintrc
src/api/test-controller/index.js
src/api/wrap-test-function.js
src/errors/error-list.js
src/errors/process-test-fn-error.js
src/test-run/index.js
test/functional/fixtures/api/es-next/test-controller/test.js
test/functional/fixtures/api/es-next/test-controller/testcafe-fixtures/test-controller-test.js
test/server/compiler-test.js

Improve missing await tracking (closes #1285)

---

.dockerignore
.gitattributes
.publishrc
Gulpfile.js
docker/Dockerfile
docker/testcafe-docker.sh

\cc @inikulin @AlexanderMoskovkin 
Hub for our images: https://hub.docker.com/r/testcafe/testcafe/
Container comes with Chromium and Firefox preinstalled with Xvfb, so it allows headless testing out-of-the-box.
Get the [Docker Toolbox](https://github.com/docker/toolbox/releases) and install it.
Open Docker Quickstart Terminal and navigate to the TestCafe repository.
Do `gulp docker-build` or `gulp docker-publish`. If you are planning to publish the image, do `docker login` with TestCafe credentials before running `gulp docker-publish`.
Image will be published with the dist tag specified in the `.publishrc`.
`docker pull testcafe/testcafe:alpha`
`docker run -v ${TEST_FOLDER}:/tests -it testcafe/testcafe:alpha 'chromium --no-sandbox,firefox' /tests/test.js`, e. g.
`docker run -v …

Implement builds of Docker images (closes #1141)

---

docs/articles/documentation/recipes/debugging-with-visual-studio-code.md

[docs] Debug recipe for visual studio code updated (#1375)

---

src/client-functions/selectors/add-api.js
src/client-functions/selectors/create-snapshot-methods.js
test/functional/fixtures/api/es-next/selector/test.js
test/functional/fixtures/api/es-next/selector/testcafe-fixtures/selector-test.js

\cc @helen-dikareva @AlexanderMoskovkin

Add selector hasAttribute method (closes #1045)

---

test/functional/fixtures/regression/gh-1385/pages/index.html
test/functional/fixtures/regression/gh-1385/test.js
test/functional/fixtures/regression/gh-1385/testcafe-fixtures/index-test.js

It was fixed in `testcafe-hammerhead` but it's impossible to create a complete test there, so I've added a functional test
/cc @helen-dikareva @georgiy-abbasov

Add test for caretRangeFromPoint and caretPositionFromPoint usage (closes #1385)

---

docs/articles/documentation/test-api/a-z-index.md
docs/articles/documentation/test-api/selecting-page-elements/selectors.md
docs/articles/documentation/using-testcafe/programming-interface/runner.md

\cc @DevExpress/testcafe-docs  @helen-dikareva 
1. `withAttr` renamed to `withAttribute`
2, Added the runner's `debugMode` option

[docs] Last corrections

---

README.md

[docs] add link for testcafe-vue-selectors in 'TestCafe Ecosystem' section

---

src/browser/connection/gateway.js
src/browser/connection/remotes-queue.js
src/cli/remotes-wizard.js

Implement uniform URL for connecting remote browsers (closes #1476)

---

package.json
src/client/automation/playback/move/index.js

Avoid HTML5 Drag'n'Drop if a browser doesn't support it (closes #1522)

---

.travis-docs.yml
docs/articles/documentation/using-testcafe/command-line-interface.md
docs/articles/documentation/using-testcafe/common-concepts/browser-support.md
docs/articles/documentation/using-testcafe/programming-interface/runner.md

/cc @lexkazakov @DevExpress/testcafe

[docs] Add info about Chrome-specific features

---

test/functional/setup.js
test/server/data/test-suites/typescript-defs/roles.ts
ts-defs/index.d.ts

Fix typo in TS defs (closes #1541)

---

Gulpfile.js
src/compiler/test-file/formats/typescript.js

\cc @AlexanderMoskovkin 
Tested on https://github.com/caseyWebb/testcafe-slow-typescript-example. I'm going to run it on Travis CI for demonstration, and will post a link after it will be done.

Fix TypeScript compilation performance (closes #1591)

---

package.json
src/client/.eslintrc
src/client/automation/index.js
src/client/browser/index.js
src/client/core/index.js
src/client/core/utils/array.js
src/client/driver/command-executors/client-functions/replicator.js
src/client/driver/command-executors/client-functions/selector-executor/filter.js
src/client/driver/driver.js
src/client/driver/index.js
src/client/ui/index.js
test/functional/fixtures/page-js-errors/pages/unhandled-promise-rejection-test.html
test/functional/fixtures/page-js-errors/test.js
test/functional/fixtures/page-js-errors/testcafe-fixtures/unhandled-promise-rejection-test.js

@AlexanderMoskovkin @helen-dikareva

update hammerhead version (close #930, #1473)

---

test/server/data/test-suites/typescript-defs/test-controller.ts
ts-defs/index.d.ts

Change `selectText()` required parameters to match documentation.  In the documentation ([see here](https://devexpress.github.io/testcafe/documentation/test-api/actions/select-text.html)), it states that only the first parameter is required which seems to make sense since you wouldn't want to give all three parameters in all situations. 
If the `startPos` and `endPos` are not made optional, then a build error occurs.
fixes #1697

Change `selectText()` to match documentation (fixes #1697)

---

CHANGELOG.md
docs/articles/documentation/using-testcafe/common-concepts/browser-support.md
package.json

\cc @AlexanderMoskovkin @VasilyStrelyaev

Use `chrome-canary` alias for Chrome Canary (closes #1711)

---

src/compiler/test-file/formats/typescript/compiler.js

See details here: https://github.com/DevExpress/testcafe/issues/1537#issuecomment-321242185
/cc @AndreyBelym

Add the `skipLibCheck` option to TypeScript compiler settings (closes #1537)

---

src/cli/argument-parser.js
src/cli/index.js
src/errors/runtime/message.js
src/runner/bootstrapper.js
src/runner/index.js
test/functional/fixtures/reporter/pages/index.html
test/functional/fixtures/reporter/test.js
test/functional/fixtures/reporter/testcafe-fixtures/index-test.js
test/functional/setup.js
test/server/cli-argument-parser-test.js
test/server/runner-test.js

When using the TestCafé runner programmatically, calling `.reporter()` multiple times only uses the last reporter.
This PR allows calling `.reporter()` multiple times, however throws an error if multiple reporters are configured to use stdout.
This allows usage such that test runs can output json to a `.json` file, verbose output to a log file, and minimal output to the TTY (for example).
Also potentially serves as groundwork for #1412.
**NOTE**: I wasn't able to figure out how to run the tests, so those are not implemented.

Allow Multiple Reporters (closes #1412)

---

docs/articles/documentation/using-testcafe/command-line-interface.md

\cc @DevExpress/testcafe-docs @AndreyBelym  
The docs part for https://github.com/DevExpress/testcafe/issues/1640

[docs] Running portable browsers with parameters on *nix systems

---

src/client/automation/playback/move/index.js

The issue is reproduced only with a specific OS and browser settings (it's about floats instead of numbers again), so I haven't added new tests for this.
/cc @helen-dikareva

Floor endPoint values in move automation

---

test/client/fixtures/automation/tab-emulation-test.js

PR is waiting for fix https://github.com/DevExpress/testcafe-hammerhead/issues/1318

Link without href but with tabIndex included in nextFocusable method's logic (closes #1803)

---

src/browser/provider/built-in/chrome/config.js
src/browser/provider/built-in/chrome/index.js
src/browser/provider/built-in/chrome/local-chrome.js
src/browser/provider/built-in/firefox/config.js
src/browser/provider/built-in/firefox/index.js
src/browser/provider/built-in/firefox/local-firefox.js
src/browser/provider/built-in/firefox/runtime-info.js
src/browser/provider/built-in/index.js
src/browser/provider/pool.js
src/browser/provider/utils/argument-parsing.js
test/server/chrome-provider-config-test.js
test/server/firefox-provider-config-test.js

Start browsers with clean profile by default

---

src/client/core/utils/position.js

`elementFromPoint` part of DocumentOrShadowRoot interface is not fully supported by all browsers. If you are using a polyfill for ShadowDOM, it is likely that 'elementFromPoint' will not be available. Adding a check to ensure that it doesn't result in NPE.
https://developer.mozilla.org/en-US/docs/Web/API/DocumentOrShadowRoot/elementFromPoint

Fix potential NPE in getElementFromPoint

---

src/api/test-controller/index.js
src/client/driver/driver.js
src/client/driver/status.js
src/test-run/bookmark.js
src/test-run/browser-console-messages.js
src/test-run/commands/actions.js
src/test-run/commands/type.js
src/test-run/index.js
test/functional/fixtures/api/es-next/console/pages/empty.html
test/functional/fixtures/api/es-next/console/pages/index.html
test/functional/fixtures/api/es-next/console/test.js
test/functional/fixtures/api/es-next/console/testcafe-fixtures/console-test.js
test/functional/fixtures/api/es-next/roles/test.js
test/functional/fixtures/api/es-next/roles/testcafe-fixtures/configuration-test.js
test/server/data/test-suites/typescript-defs/test-controller.ts
ts-defs/index.d.ts

```js
const consoleMessages = await t.getBrowserConsoleMessages();
// returns arrays of messages in the browser console for...
// ...console.log()
const logs = consoleMessages.log;         // -> ['some log message 1', 'some log message 2']
// ...console.error()
const errors = consoleMessages.error;   // -> ['some error message'] 
// ...console.warn()
const warnings = consoleMessages.warn;   // -> ['some warning message'] 
// ...console.info()
const info = consoleMessages.info;   // -> ['some info message'] 
```
Some browsers can write messages to the console with a little bit different formatting. We just call `toString()` for arguments that were passed to the console methods (see an example in the [test](https://github.com/DevExpress/testcafe/compare/master...AlexanderMoskovkin:gh-1738?ex …

Add the capability to get browser console messages (closes #1738)

---

src/client/automation/index.js
src/client/core/index.js
src/client/driver/command-executors/client-functions/selector-executor/filter.js
src/client/driver/index.js
src/client/test-run/iframe.js.mustache
src/client/test-run/index.js.mustache
src/client/ui/index.js
test/functional/fixtures/regression/gh-1999/pages/index.html
test/functional/fixtures/regression/gh-1999/test.js
test/functional/fixtures/regression/gh-1999/testcafe-fixtures/index.js

Additionally Define the "testcafeDriverInstance" client global var in iframes.
/cc @AndreyBelym @miherlosev

Fix the "Cannot redefine property" error (closes #1996).

---

.publishrc
package.json
src/api/test-run-tracker.js
test/server/test-run-tracker-test.js

@AlexanderMoskovkin @AndreyBelym @helen-dikareva 
Now, `testRunId` does not contain the '-' symbol.

update hammerhead and remove unnecessary util methods

---

src/compiler/test-file/formats/typescript/compiler.js
test/server/compiler-test.js
test/server/data/test-suites/typescript-basic/testfile1.ts
test/server/data/test-suites/typescript-compile-errors/testfile.ts

fixes #2117
> 325 passing (20s)
>
> [05:42:04] Finished 'test-server' after 21 s
fails for me with "TypeError: Cannot read property 'path' of null" in `before all` hook
just hangs - "QUnit server listens on http://localhost:2000" displayed message forever
Same happens in `master`so i donth  think this is related to my changes.
Can you please suggest how to properly configure my local environment to be able to run all required tests so this small change could be merged into your app? Or maybe you could ran test in your environment and approve suggested changes. Decorators are quite useful and it would be great to be able to use them to have a clean and nice test scenarios...
P.S.: Im using same patch locally for a few weeks and found no issues with decorators enabled.

Allow decorators to be used in typescript code (#2117)

---

src/screenshots/crop.js
src/test-run/commands/utils.js
src/utils/promisified-functions.js
test/functional/fixtures/api/es-next/take-screenshot/test.js

Fix browser manipulation issues (closes #2150, closes #2146)

---

src/client/driver/command-executors/browser-manipulation/ensure-crop-options.js
src/errors/test-run/index.js
src/errors/test-run/templates.js
src/errors/test-run/type.js
src/screenshots/crop.js
test/functional/assertion-helper.js
test/functional/fixtures/api/es-next/take-screenshot/test.js
test/functional/fixtures/api/es-next/take-screenshot/testcafe-fixtures/take-element-screenshot.js
test/server/data/expected-test-run-errors/action-invalid-scroll-target-error
test/server/test-run-error-formatting-test.js

\cc @helen-dikareva @kirovboris

Fix scrolling for negative scroll target coordinates(closes #2148)

---

src/browser/provider/built-in/chrome/local-chrome.js
src/browser/provider/built-in/firefox/local-firefox.js
src/browser/provider/built-in/firefox/runtime-info.js
src/browser/provider/utils/browser-starter.js

Avoid password saving bubble in Firefox
Fix concurrency mode for Firefox on macOS

Fix some issues in Firefox (closes #2035, closes #2180)

---

docker/Dockerfile

@AlexanderMoskovkin  @AndreyBelym 
For fresh npm version (I have `5.6.0`) need to specify `--force` flag for `npm cache clean` command.
See https://docs.npmjs.com/cli/cache#details.

add --force flag for npm cache clean command

---

Gulpfile.js

@AlexanderMoskovkin @AndreyBelym 
Changes
* Fix timeout for mocha debug mode. In new nodejs versions (6.x and later) `v8debug` global object was removed (https://github.com/nodejs/node/pull/6599).
* remove mocha config properties with default values: `ui`, `reporter`.

fix mocha timeout in debug mode

---

src/client/automation/playback/type/type-text.js
src/client/core/utils/content-editable.js
src/client/core/utils/style.js
src/client/core/utils/text-selection.js
test/functional/fixtures/regression/gh-2205/pages/index.html
test/functional/fixtures/regression/gh-2205/test.js
test/functional/fixtures/regression/gh-2205/testcafe-fixtures/index.js

Should type in contenteditable div even if it has invisible child with contenteditable=false (#2205)

---

docs/articles/documentation/test-api/assertions/README.md

\cc @DevExpress/testcafe-docs @AndreyBelym

[docs] Describe the allowUnawaitedPromise assertion option

---

docs/articles/documentation/using-testcafe/command-line-interface.md
docs/articles/documentation/using-testcafe/programming-interface/runner.md

\cc @DevExpress/testcafe-docs @AlexKamaev

[docs] Describe bypassing the proxy

---

docs/articles/documentation/extending-testcafe/reporter-plugin/reporter-methods.md
docs/articles/documentation/test-api/test-code-structure.md
docs/nav/nav-menu.yml

[docs] Docs Metadata 

---

test/server/compiler-test.js
test/server/data/test-suites/typescript-defs/meta.ts
test/server/data/test-suites/typescript-defs/request-hooks.ts
ts-defs/index.d.ts

@AndreyBelym @MargaritaLoseva 
Changes:
* change var to const in header of `test/server/compiler-test.js`
* `resolve` -> `path.resolve`
* rewrite `Should provide API definitions` using `fs.readDirSync`
* add typescript definitions for `meta` and `Request Hook` features.

add typescript defs for new features (close #2428)

---

src/screenshots/crop.js
src/screenshots/generate-mark.js

@AndreyBelym 
The message `(node:3052) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.` is displayed during functional tests.
[appveyor test log](https://ci.appveyor.com/project/testcafe-build-bot/testcafe/build/%232986)

remove deprecated Buffer constructor usage

---

package.json
src/cli/argument-parser.js
src/cli/cli.js
src/cli/parse-ssl-options.js
src/index.js
src/testcafe.js
test/server/cli-argument-parser-test.js
test/server/create-testcafe-test.js

Implement a possibility to run TestCafe over https (close #1985)

---

README.md

Instead of "TestCafe" selected "questions with the TestCafe tag", because it is precisely what one will see when clicks the link.

[docs] Updated the link to StackOverflow

---

docs/articles/documentation/test-api/intercepting-http-requests/logging-http-requests.md

According to https://github.com/DevExpress/testcafe/issues/2555, added information about trying to stringify the request/response body that is not logged.

[docs] Correct docs according to #2555

---

docs/tweets/tweets.json

\cc @kirovboris 
The previous tweet was rendered too high to fit the designated area on the landing page.

[docs] Replace a long tweet with a shorter one

---

src/.babelrc
src/api/exportable-lib/index.js
src/errors/stack-cleaning-hook.js
src/utils/delegated-api.js

https://github.com/DevExpress/testcafe-hammerhead/issues/1651
1. Update node version to 6 (src/.babelrc)
2. Clean `Generator.next` error stack entries (Fix "Compiler > Error" tests)
3. Rewrite src/api/exportable-lib/index.js (Fix `new ClientFunction` tests, etc)
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/Method_definitions#Method_definitions_are_not_constructable
>  All method definitions are not constructors and will throw a TypeError if you try to instantiate them.
> ```js
> var obj = { 
>   method() {}
> };
> new obj.method; // TypeError: obj.method is not a constructor
> 
> var obj = { 
>   * g() {} 
> };
> new obj.g; // TypeError: obj.g is not a constructor (changed in ES2016)
> ```

fix `Update babel-preset-env target to node 6`

---

src/api/request-hooks/request-logger.js
test/server/request-hooks-test.js

fix 'Should not raise an error if during a long running request the "clear" method will be called' (close #2688)

---

package.json
src/compiler/index.js
src/compiler/test-file/formats/coffeescript/compiler.js
src/compiler/test-file/formats/coffeescript/get-test-list.js
src/compiler/test-file/formats/es-next/get-test-list.js
src/compiler/test-file/test-file-parser-base.js
src/embedding-utils.js
test/functional/fixtures/api/coffeescript/smoke/test.js
test/functional/fixtures/api/coffeescript/smoke/testcafe-fixtures/callsite-test.coffee
test/functional/fixtures/api/coffeescript/smoke/testcafe-fixtures/non-trivial-test.coffee
test/server/compiler-test.js
test/server/data/test-suites/coffeescript-basic/dep1.coffee
test/server/data/test-suites/coffeescript-basic/dep2.coffee
test/server/data/test-suites/coffeescript-basic/testfile1.coffee
test/server/data/test-suites/coffeescript-basic/testfile2.coffee
test/server/data/test-suites/coffeescript-parser-smoke/testfile1.coffee
test/server/data/test-suites/coffeescript-parser-smoke/testfile2.coffee
test/server/parse-fixture-test.js

Closes #1556. Adds support for CoffeeScript test files, similar to the existing TypeScript support.

CoffeeScript support (close #1556)

---

src/api/request-hooks/request-logger.js
test/server/request-hooks-test.js

fix 'Should not fail when logger logs and stringifies a response body and it equals null' (close #2718)

---

docs/nav/top-menu-items.yml

\cc @kirovboris 
Per @Nuarat 's request, added a `TestCafe Studio` link to the top menu instead of `Publications`

[docs] Add a TestCafe Studio top-level link

---

Gulpfile.js

Initialially in the source maps was absolute path of the source-file, because source map resolver could not process relative path correcly (in path we need 'src' but not 'lib'). But absolute path leads to incorrect root folder name, so the right way to use relative path, even with incorrect src folder name.
`[incorrect_root_path]\src\testcafe.js` => `[correct_root_path]\`**lib**`\testcafe.js`
UPD. fixed in normal way `[correct_root_path]\src\testcafe.js`

fix absolute paths for source maps (fix bug for #2546)

---

src/api/structure/testing-unit.js
src/api/test-controller/assertion.js
src/api/test-controller/index.js
src/api/test-controller/proxy.js
src/api/test-page-url.js
src/api/test-run-tracker.js
src/api/wrap-test-function.js
src/assertions/executor.js
src/screenshots/crop.js
src/screenshots/generate-mark.js
src/screenshots/path-pattern.js
test/server/path-pattern-test.js

@AndreyBelym 
Review only two files:
* `test/server/path-pattern-test.js`
*  `src/screenshots/path-pattern.js`

fix '${BROWSER} resolves to undefined in screenshot pattern' (close #2742)

---

Gulpfile.js
src/browser/connection/index.js
src/runner/browser-job.js
src/runner/test-run-controller.js
src/test-run/index.js
test/functional/fixtures/browser-provider/browser-reconnect/pages/index.html
test/functional/fixtures/browser-provider/browser-reconnect/test.js
test/functional/fixtures/browser-provider/browser-reconnect/testcafe-fixtures/index-test.js
test/server/browser-connection-test.js

I've accidentally closed previous pull request https://github.com/DevExpress/testcafe/pull/2746

Restart browser if it became unresponsive (closes #1815)

---

package.json
src/client/automation/playback/rclick.js
src/client/automation/utils/get-key-code.js
src/client/automation/utils/get-line-rect-intersection.js
src/client/automation/utils/next-tick.js
src/screenshots/capturer.js
src/screenshots/index.js
src/screenshots/path-pattern.js
src/utils/get-common-path.js
test/functional/fixtures/api/es-next/take-screenshot/test.js
test/functional/fixtures/api/legacy/smoke/test.js
test/server/util-test.js

fix 'incorrect screenshot path in report output ' (close #2726)

---

CHANGELOG.md
docs/articles/blog/2018-08-02-testcafe-v0-21-0-released.md
docs/articles/documentation/using-testcafe/command-line-interface.md

[docs] Change screenshot path pattern command line syntax to single quotes

---

docs/articles/documentation/test-api/selecting-page-elements/selectors/using-selectors.md

[docs] Fix an example in 'Using Selectors' with innerText

---

src/notifications/warning-message.js
test/functional/fixtures/regression/gh-2846/test.js

Edit a warning message displayed when a user tries to debug in headless mode

---

docs/articles/blog/2018-10-25-testcafe-v0-23-0-released.md

Announcement blog post - the same text as in the changelog except for the first line.

[docs] Add an announcement blog post for v0.23.0

---

docs/articles/documentation/using-testcafe/command-line-interface.md

I found document's typos about `FILE_INDEX `.
Please merge and fix them.

[docs] Fix doc's typo.

---

docs/articles/documentation/using-testcafe/command-line-interface.md
docs/articles/documentation/using-testcafe/programming-interface/runner.md

Reverts DevExpress/testcafe#2954
Reasons can be found here: https://github.com/DevExpress/testcafe/pull/2954#issuecomment-433978514
@kirovboris @miherlosev

[docs] Revert "[docs] Add "group" metadata to define which tests will be run"

---

docs/articles/documentation/using-testcafe/command-line-interface.md
docs/articles/documentation/using-testcafe/programming-interface/runner.md

Pull requesting user's content from https://github.com/DevExpress/testcafe/pull/2954 to the right branch (with my minor changes).

[docs] Add docs for the --test-meta and --fixture-meta flags

---

docs/nav/top-menu-items.yml

Edited the main menu: removed `Issues` and `Q&A`; added `Support`. Need to confirm we leave `FAQ`. 
Main PR: https://github.com/DevExpress/testcafe-gh-page-assets/pull/68

[docs] Edit the main menu in light of the new support page

---

docs/articles/documentation/using-testcafe/command-line-interface.md
docs/articles/documentation/using-testcafe/programming-interface/runner.md

\cc @DevExpress/testcafe-docs @AlexKamaev

[docs] Describe the --disable-test-syntax-validation option

---

docs/articles/documentation/using-testcafe/command-line-interface.md

[docs] Fix a bug in a --disable-test-syntax-validation example

---

blog/testcafe-v0-23-1-released.html
css/support-page.mobile.css
documentation/using-testcafe/command-line-interface.html
documentation/using-testcafe/programming-interface/runner.html
feed.xml
sitemap.xml

\cc @AndreyBelym @AlexSkorkin 
Pay attention to:
Release notes
https://vasilystrelyaev.github.io/testcafe/blog/
https://vasilystrelyaev.github.io/testcafe/blog/testcafe-v0-23-1-released.html
New docs:
https://vasilystrelyaev.github.io/testcafe/documentation/using-testcafe/command-line-interface.html#--test-meta-keyvaluekey2value2
https://vasilystrelyaev.github.io/testcafe/documentation/using-testcafe/command-line-interface.html#--disable-test-syntax-validation
https://vasilystrelyaev.github.io/testcafe/documentation/using-testcafe/programming-interface/runner.html#filter

[docs] Update website 11/7/2018

---

docs/articles/documentation/using-testcafe/command-line-interface.md
docs/articles/documentation/using-testcafe/common-concepts/browsers/testing-in-headless-mode.md
docs/articles/documentation/using-testcafe/common-concepts/browsers/user-profiles.md
docs/articles/documentation/using-testcafe/common-concepts/browsers/using-chrome-device-emulation.md
docs/articles/documentation/using-testcafe/programming-interface/runner.md

\cc @kirovboris @AndreyBelym 
fixes #3216

[docs] Emphasize that postfixes for browser aliases do not work with 'path:'

---

src/notifications/warning-log.js
src/reporter/index.js
src/test-run/index.js
test/server/reporter-test.js
test/server/warning-log-test.js

Part of #2753
Sum up changes in APIs:
Now `testRunInfo` has the following structure:
Property            | Type             | Description
------------------- | ---------------- | --------------------------------------------------------
`errs`              | Array of Strings | An array of errors that occurred during the test run.
**`warnings`**     | **Array of Strings** | **An array of warnings that occurred during the test run.**
`durationMs`        | Number           | The time spent on test execution (in milliseconds).
`unstable`          | Boolean          | Specifies if the test is marked as unstable.
`screenshotPath`    | String           | The path where screenshots are saved.
`screenshots`       | Array of Objects | An array of [screenshot](#screenshots-object) objects. …

Modify Reporter API to handle additional info

---

docs/articles/documentation/continuous-integration/azure-devops.md
docs/articles/documentation/continuous-integration/circleci.md
docs/articles/documentation/continuous-integration/gitlab.md
docs/articles/documentation/recipes/debug-tests/webstorm.md

This PR fixes incorrect npm install instructions:
~npm --save-dev~ --> `npm install --save-dev`
---
Hi all,
Nice work with testcafe 🚀 While looking through the documentation, I noticed that the command to install testcafe as a devDependency was incorrect. Hence, this PR fixes it. I read through the [contributing guidelines](https://github.com/DevExpress/testcafe/blob/master/CONTRIBUTING.md#contribute-to-documentation), but did not open any issue as this PR is so minor.
Cheers

[docs] correct npm install instructions

---

src/client/ui/status-bar/index.js
src/client/ui/styles.less

Don't hide fixture info in the status panel

---

src/cli/argument-parser.js
src/runner/bootstrapper.js
src/runner/index.js
src/utils/prepare-reporters.js
test/functional/fixtures/reporter/test.js
test/functional/fixtures/run-options/stop-on-first-fail/test.js
test/server/cli-argument-parser-test.js
test/server/util-test.js

Renamed the '.reporter' method parameter from 'outStream' to 'output'

---

docs/articles/documentation/using-testcafe/command-line-interface.md
docs/articles/documentation/using-testcafe/programming-interface/createtestcafe.md
docs/articles/documentation/using-testcafe/programming-interface/runner.md

\cc @DevExpress/testcafe-docs @miherlosev 
Since users are not always able to actually override a configuration file property (like in boolean flags), I thinks we'd not better write `overrides` everywhere. Changed to `related`.
What do you think?

[docs] Configuration file notes: Overrides property -> Related property

---

package.json
test/server/compiler-test.js
test/server/data/test-suites/typescript-runner/runner.ts
ts-defs/index.d.ts

Fixes #3341 
Adds missing typings for TestCafe, Runner, BrowserConnection classes by adding a callable signature to an exported module.

 Add TestCafe Class typings

---

CHANGELOG.md
docs/articles/blog/2018-11-7-testcafe-v0-23-1-released.md
docs/articles/documentation/using-testcafe/command-line-interface.md
docs/articles/documentation/using-testcafe/configuration-file.md
docs/articles/documentation/using-testcafe/programming-interface/runner.md
examples/.testcaferc.json

\cc @kirovboris @AlexKamaev 
Here I just remove the `Disable Syntax Validation` option.

[docs] Remove the Disable Syntax Validation option

---

docs/articles/documentation/using-testcafe/configuration-file.md

\cc @kirovboris 
Just adding a link to the config example we've created.
BTW, this link is broken so far because it points to the `master` branch.

[docs] Add a link to the configuration file example

---

CHANGELOG.md
docs/articles/blog/2018-08-02-testcafe-v0-21-0-released.md
docs/articles/documentation/test-api/actions/take-screenshot.md
docs/articles/documentation/using-testcafe/command-line-interface.md
docs/articles/documentation/using-testcafe/common-concepts/README.md
docs/articles/documentation/using-testcafe/common-concepts/screenshots-and-videos.md
docs/articles/documentation/using-testcafe/configuration-file.md
docs/articles/documentation/using-testcafe/programming-interface/runner.md
docs/nav/nav-menu.yml
examples/.testcaferc.json

It's awfully cross-linked (even between screenshots and video stuff), so ideally I should separate a `Screenshots and Videos` topic to gather it all.
And I haven't described the new `${GENERIC_TEST_NAME}` and `${GENERIC_RUN_NAME}` path patterns yet. Their description will fit well only when we create the `Screenshots and Videos` topic. As I've discussed with @AndreyBelym , the only good reason for customers to use them is if they want a configuration file setting that would work for both enabled and disabled quarantine mode. IDK how important this is.

[docs] Describe video recording

---

.md-lint/blog.json
Gulpfile.js
docs/articles/blog/2019-2-7-migration-from-testcafe-v0-x-y-to-v1-0-0.md

Added a migration guide aka breaking changes report.
Have I missed anything?

[docs] Add a migration guide for v0.x.y -> v1.0.0

---

src/cli/argument-parser.js
test/server/cli-argument-parser-test.js

Make CLI video options undefined if they're not specified (closes #3415)

---

docs/articles/documentation/extending-testcafe/reporter-plugin/README.md

Per @helen-dikareva request, wrapped custom reporter methods in
```js
export default function () {
return {
};
}
```
The idea was that Yeoman generator will generate the wrapping and we show only the part of the reporter that should be changed, but, yeah, I agree that without wrapping these examples may look strange (like, "why all these commas?").
\cc @helen-dikareva @kirovboris

[docs] Add "export" wrapping to custom reporter methods

---

docs/README.md
docs/articles/documentation/continuous-integration/README.md
docs/articles/documentation/continuous-integration/bitbucket-pipelines.md
docs/nav/nav-menu.yml
examples/running-tests-in-chrome-using-bitbucket-pipelines-ci/README.md
examples/running-tests-in-chrome-using-bitbucket-pipelines-ci/bitbucket-pipelines.yml
examples/running-tests-in-chrome-using-bitbucket-pipelines-ci/index.html
examples/running-tests-in-chrome-using-bitbucket-pipelines-ci/package.json
examples/running-tests-in-chrome-using-bitbucket-pipelines-ci/server.js
examples/running-tests-in-chrome-using-bitbucket-pipelines-ci/tests/index-test.js

This PR adds some documentation on how to setup Testcafe in a new continuous integration as the Bitbucket Pipelines .
The Travis CI documentation and example have been used as baseline for this documentation.
Let me know if I need to change any formality or anything else in here.

[docs] Bitbucket Pipelines CI documentation

---

src/configuration/index.js
src/notifications/warning-message.js
src/runner/task.js
src/utils/get-concatenated-values-string.js
src/utils/path-pattern.js
src/utils/string.js
src/video-recorder/index.js
test/functional/fixtures/video-recording/test.js
test/server/util-test.js
test/server/video-recorder-test.js

@AndreyBelym @AlexKamaev @VasilyStrelyaev

Fixed "${TEST_INDEX} is initialized to 'null' for video recording path pattern"  (close #3455)

---

Gulpfile.js
test/server/data/test-suites/typescript-defs/client-functions.ts
test/server/data/test-suites/typescript-defs/test-controller.ts
ts-defs/index.d.ts

No breaking changes. Generic default type is `any`

Feat: clientFunction better definition

---

docs/articles/documentation/using-testcafe/using-testcafe-docker-image.md

\cc @kirovboris @AndreyBelym 
closes #3413, closes #3479 
The purpose of the latter is to add a note that we do not take into account the container's proxy settings (let's ensure once again that it's not a bug).

[docs] Docker - Add a note about proxy settings + misc

---

docs/articles/roadmap/README.md
docs/nav/top-menu-items.yml

\cc @DevExpress/testcafe-docs @miherlosev 
http://strelyaev-w8:8080/testcafe/roadmap/
WIP because we still need to provide meaningful titles and descriptions to all these features on GitHub.

[docs] Add a roadmap

---

src/client/automation/playback/press/key-press-simulator.js
src/client/automation/playback/type/index.js
test/client/fixtures/automation/detection-element-after-events-simulation-test.js
test/client/fixtures/automation/key-press-simulation-test.js
test/client/fixtures/automation/press-test.js
test/client/fixtures/automation/regression-test.js
test/client/fixtures/automation/submit-on-enter-test.js
test/client/fixtures/automation/type-test.js

`Keypress` event should not raise on Android. I checked both Firefox and Chrome

keypress should not raise on Android (closes #2236)

---

.github/lock.yml

This bot will lock any closed threads (bugs, enhancements, questions) after 10 days of inactivity. 
Pull requests are ignored. We can lock them too if necessary.
We can configure the bot later according to our requirements. 
I will enable the bot when the config file is merged into master.

[docs] Add the Lock bot configuration file

---

test/functional/fixtures/api/coffeescript/smoke/test.js
test/functional/fixtures/api/es-next/roles/test.js
test/functional/fixtures/api/typescript/smoke/test.js
test/functional/fixtures/regression/gh-2015/test.js
test/functional/fixtures/regression/gh-2282/test.js

I want to disable these tests for Azure because fixing them can take an indefinite amount of time. The disabled tests still run on Appveyor and Travis. I will fix them in a separate PR.

Disable tests with Roles for Azure tasks

---

documentation/continuous-integration/bitbucket-pipelines.html
documentation/using-testcafe/using-testcafe-docker-image.html
faq/index.html
feed.xml
sitemap.xml

Preview at http://vasilystrelyaev.github.io/testcafe/.
Highlights:
* updated FAQ: http://vasilystrelyaev.github.io/testcafe/faq/#testcafe-reports-that-a-request-has-failed-what-are-the-possible-reasons
* removed info about `shm` from the Docker topic: http://vasilystrelyaev.github.io/testcafe/documentation/using-testcafe/using-testcafe-docker-image.html
* removed info about the `--no-sandbox` flag from the Docker and CI integration topics

[docs] Update the website 4/1/2019

---

package.json
src/client/automation/playback/click/click-command.js

@AlexKamaev 
All inputs' native dialogs are prevented in hammerhead repository:
* https://github.com/DevExpress/testcafe-hammerhead/blob/8e5430e0b5a9d4b3f990e49959fadc67d060e3a1/src/client/sandbox/event/index.ts#L150
* https://github.com/DevExpress/testcafe-hammerhead/blob/3a9e84adb47a65037ff3259332b311f417985f64/src/client/sandbox/upload/index.ts#L79

Updated xammerhead

---

README.md
docs/articles/faq/README.md
docs/articles/index.html

`[WIP]` because links to the article are not yet finalized.
So, here I:
* add links to an article to FAQ and ~the GitHub README.md~
* update texts (corrected by Vova)
* change the GitHub README.md 'Different versions' section - replaced lists with a table, like on the website
* update the Studio animation on GitHub README.md

[docs] Get ready for the TestCafe Studio official release

---

package.json
src/api/structure/fixture.js
src/api/test-page-url.js
src/client/driver/command-executors/execute-navigate-to.js
src/role/index.js
src/test-run/bookmark.js
src/test-run/commands/actions.js
src/test-run/index.js
src/test-run/session-controller.js
test/functional/fixtures/api/es-next/roles/pages/page-with-hash-navigation.html
test/functional/fixtures/api/es-next/roles/test.js
test/functional/fixtures/api/es-next/roles/testcafe-fixtures/hash-based-navigation-test.js
test/functional/fixtures/api/es-next/roles/testcafe-fixtures/same-url-test.js
test/functional/fixtures/api/es-next/roles/testcafe-fixtures/utils.js
test/server/test-run-commands-test.js
test/server/util-test.js

Changes:
* force reload if role's login url is different with fixture's url only in hash
* remove getting snapshot delay (https://github.com/DevExpress/testcafe/pull/3625/files#diff-7583ad80662fdf889e6e058fbf571d42L40). It's necessary, because at present we don't use service messages for cookie synchronization.
* use `StateSnapshot.empty()` instead of `null`.
* export special pages(`about:blank`, `about:error`) from hammerhead and use them as constants.
At first review this PR, next - [this](https://github.com/DevExpress/testcafe-hammerhead/pull/1974) in the hammerhead repository.

Allow to use roles for pages with hash-based havigation (close #2195)

---

src/reporter/index.js
src/reporter/plugin-host.js
src/runner/browser-job.js
src/runner/task.js
src/runner/test-run-controller.js
test/functional/fixtures/api/es-next/page-load-timeout/testcafe-fixtures/index-test.js
test/server/reporter-test.js

To work correctly with such reporters as Allure and have ability to add something to report during current test execution process I added reportTestStart method to reporting system 
Related feature request: https://github.com/DevExpress/testcafe/issues/3715

Add reportTestStart method to reporting system (close #3715)

---

ts-defs/index.d.ts

@AndreyBelym 
I renamed `Request` interface to `LoggedRequest` because it intercepts with standard NodeJs `Request` interface from `node_modules/typescript/lib/lib.dom.d.ts`.

Updated ts-defs (close #3829)

---

package.json
src/api/request-hooks/hook.js
src/errors/test-run/index.js
src/errors/test-run/templates.js
src/errors/types.js
src/test-run/index.js
test/functional/fixtures/api/es-next/request-hooks/test.js
test/functional/fixtures/api/es-next/request-hooks/testcafe-fixtures/api/handle-errors.js
test/server/data/expected-test-run-errors/request-hook-method-not-implemented-error
test/server/data/expected-test-run-errors/request-hook-unhandled-error
test/server/test-run-error-formatting-test.js

@AndreyBelym @AlexKamaev @LavrovArtem 
First - this PR, next - https://github.com/DevExpress/testcafe-hammerhead/pull/2036
@VasilyStrelyaev check please messages in the error templates

Handle errors inside the request hook methods (close #3786)

---

package.json
src/utils/parse-file-list.js

Closes #3918. Luckily I found a function that allowed me to avoid rewriting half of the `globby` code. Can't write a test for the fixed even with `proxyquire`, because the issue was caused by the internals of `node-glob`.

Fix test file scanning for Windows (closes #3918)

---

src/client/core/utils/style.js
test/functional/fixtures/regression/gh-2601/pages/index.html
test/functional/fixtures/regression/gh-2601/test.js
test/functional/fixtures/regression/gh-2601/testcafe-fixtures/index.js

The problem appears if:
1. Body has overflow: auto (here it implicitly has overflow-y auto)
2. Body has defined height
3. Body has a child with negative margin
This markup leads to incorrect calculations of html scrollHeight

fix scrolling when page has negative margins (#2601)

---

src/configuration/configuration-base.js
src/configuration/default-values.js
src/configuration/typescript-configuration.js
test/server/configuration-test.js

Closes #3970. Closes #3976.
1. `moduleResolution` is hardcoded in our TS config.
2. Override warning for hardcoded options is not shown if the user's config sets the same values as hardcoded values.
3. TypeScript target set to ES2016. Node 8 support of ES2016 is 100% - https://node.green/#ES2016.

Fix TypeScript compiler for configurations with moduleResolution (closes #3970, #3976)

---

docs/articles/documentation/test-api/typescript-support.md

We now say about specifying the location at the beginning: https://github.com/DevExpress/testcafe/pull/4098/files#diff-faffa7cb8471bb25963ec2306a99c62aR48.
This paragraph is obsolete (as it says about the root project directory).

[docs] Remove an obsolete paragraph about TS config

---

src/live/file-watcher/modules-graph.js
test/server/data/test-suites/live/commonjs-module.js
test/server/data/test-suites/live/multiple-tests.js
test/server/data/test-suites/live/test-external-module-rerun.js
test/server/data/test-suites/live/test-external-module.js
test/server/data/test-suites/live/test-external-unexisting-module.js
test/server/data/test-suites/live/test-with-syntax-error.js
test/server/data/test-suites/live/test.js
test/server/live-test.js

the cause is here https://github.com/nodejs/node/blob/master/lib/internal/modules/cjs/loader.js#L617
and the pull is here https://github.com/nodejs/node/commit/0f190a5bed14bf9f7392af889f3f83306bedae97

fix module cache clearing in live mode for Node 12 (closes #4052)

---

ts-defs/index.d.ts

The documentation shows that clientScripts can be ran on fixture and test but the typescript definitions do not take this into account. This updates the definitions to allow for these functions to be called.

update ts-defs clientscripts

---

src/api/test-controller/index.js
src/browser/provider/built-in/dedicated/base.js
src/browser/provider/built-in/dedicated/chrome/cdp.ts
src/browser/provider/built-in/dedicated/firefox/marionette-client/index.js
src/browser/provider/index.js
src/cli/argument-parser.ts
src/cli/cli.js
src/configuration/option-names.js
src/configuration/testcafe-configuration.ts
src/notifications/warning-message.js
src/runner/index.js
src/runner/task.js
src/screenshots/capturer.js
src/screenshots/index.js
src/test-run/browser-manipulation-queue.js
src/test-run/commands/browser-manipulation.js
test/functional/assertion-helper.js
test/functional/fixtures/api/es-next/take-screenshot/pages/full-page.html
test/functional/fixtures/api/es-next/take-screenshot/test.js
test/functional/fixtures/api/es-next/take-screenshot/testcafe-fixtures/take-full-page-screenshot.js
test/functional/setup.js
test/server/browser-provider-test.js
test/server/cli-argument-parser-test.js
test/server/configuration-test.js
test/server/runner-test.js
test/server/test-run-commands-test.js
ts-defs/index.d.ts

I found some issues while researching cdp and marionette.
Chrome headless works great
Chrome non-headless adds some paddings sometimes. Not great, but not terrible.
Firefox cuts screenshots sometimes, especially if there are positioned elements on the page.

allow taking full page screenshots (closes #1520)

---

src/cli/argument-parser.ts
src/cli/cli.js
test/server/cli-argument-parser-test.js

https://github.com/DevExpress/testcafe/issues/4294
1. Set the default "locally-installed" provider name in the `CliArgumentParser.parse` function.

Fix '`testcafe -b` returns the "The specified "true" browser provider was not found" error'

---

src/configuration/option-names.js
src/runner/index.js
src/test-run/index.js
test/server/execute-async-expression-test.js
test/server/runner-test.js

This PR is needed for https://github.com/DevExpress/testcafe-studio/issues/2729 to hide console output in coded steps with debug action.

Debug logger is able to be overriden

---

test/server/runner-test.js

Currently if you want to do smth like this `.mergeOptions({ debugLogger: customLogger });` the configuration will **merge** the target object, but not rewrite it. Fortunately, this error only in test code, since @Dmitry-Ostashev  in TestCafe merges `debugLogger` with 'null'. The 'null' !== object, so configuration will not merge, but just reset the debugLogger value. Thus everything should work as expected, excepting the test code.
In the test it's enough just to reset the debugLogger value to null, as happens in real code.

fix `debugLogger` server test

---

.publishrc
package.json

1. Move `mime-db` from `devDependencies` to `dependencies`.
2. Bump version.

Bump version (v1.6.0)

---

src/utils/detect-ffmpeg.js

A change in TestCafe 1.4.2 (possibly #4147) broke FFmpeg detection in `PATH`, resulting in an `Unable to locate the FFmpeg executable required to record videos` error when not using the `FFMPEG_PATH` environment variable, `ffmpegPath` video option or `@ffmpeg-installer/ffmpeg` package.
The issue happens on the following lines:
https://github.com/DevExpress/testcafe/blob/070540f89457e93a9bd351211e06e4d4b16fca40/src/utils/detect-ffmpeg.js#L11-L13
While `ffmpegPath` was previously a string, now it's an object like
```js
{ stdout: '/usr/local/bin/ffmpeg\n', stderr: '' }
```
meaning `ffmpegPath.trim()` results in `TypeError: ffmpegPath.trim is not a function`. Since everything is inside a try/catch, TestCafe itself doesn't break, but FFmpeg is not found.
This PR does the `trim` on …

Fix FFmpeg detection in PATH

---

ts-defs-src/runner-api/runner-api.d.ts

Closes https://github.com/DevExpress/testcafe/issues/4387.
I've added the definition based on https://devexpress.github.io/testcafe/documentation/using-testcafe/programming-interface/runner.html#tsconfigpath.

Add tsConfigPath definition to Runner interface

---

src/client/driver/driver.js
src/client/driver/iframe-driver.js
test/functional/fixtures/regression/gh-4360/pages/frame.html
test/functional/fixtures/regression/gh-4360/pages/index.html
test/functional/fixtures/regression/gh-4360/test.js
test/functional/fixtures/regression/gh-4360/testcafe-fixtures/index.js

The details of the requirement and the occurrence are contained in Issue #4360. This fix has been tested against the issue noted there and fixes it.
Simple addition to prevent use of contextStorage if not initialised. This is a valid check as it can't be already sent (therefore the flag check isn't required) if the storage isn't even initialised.
Other holes may exist with the same pattern but only the form submit is handled here. The other likely candidate is `_onJsError()` if the error is triggered prior to the driver start.

Protect form submit from pre-init use (close 4360)

---

test/server/compiler-test.js
test/server/data/test-suites/typescript-nodejs-globals/testfile.ts
ts-defs-src/index.d.ts.mustache
ts-defs-src/runner-api/runner-api.d.ts

Allow again using Node.js globals in TypeScript tests (closes #4437)

---

src/browser/provider/index.ts
src/utils/promisified-functions.js
test/server/browser-provider-test.js
test/server/capturer-test.js
test/server/crop-test.js

I reverted the fix of https://github.com/DevExpress/testcafe/issues/4303
Since it leaded to failure in custom browser provers
Now the dir will be created for all plugins but not for local browser.
For local browser the dir is created by `browser-tools`

create screenshot dir if plugin is used (closes #4477)

---

Gulpfile.js

A new `env` object without parent's `process.env` was passed to Jekyll and overrode its environment.
The build somehow worked on Windows all these years, but not on macOS.
This PR fixes it.

Gulpfile - Fix website build on macOS

---

docs/articles/documentation/test-api/assertions/assertion-api.md
docs/articles/documentation/test-api/intercepting-http-requests/logging-http-requests.md

And one unrelated formatting change.

[docs] Add description for request's timestamp parameters

---

src/client/automation/playback/type/type-text.js
test/client/fixtures/automation/type-test.js

https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/beforeinput_event
The `beforeInput` events fires only in Chrome and Safari.
However, the order of events is different.
In Chrome the order is `beforeinput - textInput - input`
In Safari - `textInput - beforeinput - input`
Any preceding event can prevent the next one. This behavior is shown in tests.
The `beforeinput` event handler has an argument of `InputEvent`. IE/Edge does not support `InputEvent`. Firefox supports `InputEvent` but does no support `beforeinput`

fire `beforeInput` (closes #4486 after hh is published)

---

src/errors/error-list.js
src/services/utils/ipc/interfaces.ts
src/services/utils/ipc/io.ts
src/services/utils/ipc/proxy.ts
src/services/utils/ipc/transport.ts
src/utils/prerender-callsite.js
src/utils/render-callsite-sync.js

What's changed:
- Improved `TestCafeErrorList` deserialization (by the `TestCafeErrorList` error name) for passing `TestCafeErrorList`'s between the host and compiler service processes
- Allow prerendered callsites in TestCafe errors. V8 stack frames (which are used to render callsites) don't serialize well, so it's easier to render a whole callsite to a string before transferring it from the compiler service to the host process.

Improve error handling in IPC utils

---

docs/articles/documentation/test-api/selecting-page-elements/selectors/functional-style-selectors.md

From https://github.com/DevExpress/testcafe/issues/4610
> Current documentation for filterHidden uses filterVisible in the example code:
https://devexpress.github.io/testcafe/documentation/test-api/selecting-page-elements/selectors/functional-style-selectors.html#filterhidden

[docs] Fix `filterHidden` docs example

---

.travis-docs.yml
README.md
package.json

**This pull request adds my TestCafe Cucumber steps plugin to the community plugins list**
Associated issue: https://github.com/DevExpress/testcafe/issues/4674

[docs] Add my TestCafe Cucumber steps plugin

---

test/server/data/test-suites/typescript-runner/runner.ts
ts-defs-src/runner-api/runner-api.d.ts

add missing video declaration and interfaces for runner

add missing video declaration for runner

---

src/runner/browser-job.js
test/functional/fixtures/regression/gh-4725/pages/index.html
test/functional/fixtures/regression/gh-4725/test.js
test/functional/fixtures/regression/gh-4725/testcafe-fixtures/index.js
test/server/browser-job-test.js

Accidentally I duplicated the assign to the `test-run-start` event. Test will prevent this

Should ensure AsyncEventEmitter from additional event subscriptions (closes #4725)

---

.publishrc
package.json

We updated browser tool to run chrome with the following flags:
`--disable-background-networking`
`--disable-ipc-flooding-protection`

Update browser tools (v2.0.9), bump version (v1.8.3-rc.1)

---

CODEOWNERS

1. @VasilyStrelyaev is no longer a code owner of `docs` and related `*.md` files since @anthophobiac can handle this too.
2. @kirovboris is no longer a code owner of `package.json` since most changes there are very minor and only increase the number of clutter mentions.

[docs] Exclude most scopes from CODEOWNERS

---

.travis.yml
Gulpfile.js
package.json
src/api/structure/base-unit.ts
src/api/structure/fixture.js
src/api/structure/interfaces.ts
src/api/structure/test-file.js
src/api/structure/test.js
src/api/structure/testing-unit.js
src/api/structure/unit-types.ts
src/api/test-run-tracker.d.ts
src/compiler/interfaces.ts
src/runner/bootstrapper.ts
src/runner/index.js
src/services/compiler/host.ts
src/services/compiler/io.ts
src/services/compiler/protocol.ts
src/services/compiler/service.ts
src/services/compiler/test-run-proxy.ts
src/services/compiler/test-structure.ts
src/testcafe.js
test/functional/config.js
test/functional/fixtures/compiler-service/test.js
test/functional/fixtures/compiler-service/testcafe-fixtures/basic-test.js
test/functional/fixtures/compiler-service/testcafe-fixtures/error-test.js
test/functional/setup.js

- Implemented the compiler service (`/src/services/compiler`) - a process that starts alongside the main TestCafe process and compiles & runs tests. Commands to compile and run specific tests are passed via inter-process messages handled by the IPC Proxy (`/src/services/utils/ipc`).
- Added IDs to test file objects (IDs for fixture and test objects were done in another PR) to simplify serializing and deserializing test structure (test, fixture, test file) objects.
- Added the "unitTypeName" property to test file objects and refactored it to use named constants for test and fixture objects.
- Added and enabled on Travis a new test task dedicated to the compiler service that will be used until we can run all existing functional tests with the compiler service enabled.
- Moved the hack that …

Implement compiler service

---

package.json
src/browser/provider/built-in/dedicated/firefox/create-temp-profile.ts

Fix testing page freezing when Firefox window is hidden behind another window.
Decrease `dom.min_background_timeout_value` and `dom.timeout.throttling_delay` options to 4ms in a Firefox profile. The default values are 10s and 30s respectively.

Disable background tabs timer throttling

---

docs/articles/documentation/how-it-works/README.md

**This pull request fixes a typo in 'Isolated Test Runs' section of 'How It Works'**

[docs] Fix a typo in 'How It Works'

---

src/client/automation/playback/visible-element-automation.js
src/client/core/utils/dom.js
test/client/fixtures/automation/click-test.js
test/client/fixtures/core/dom-utils-test.js

`contains` is not supported in IE11 for `svg` elements

fix IE11 `contains` usage (closes #4709)

---

src/reporter/index.js
src/runner/browser-job.js
test/functional/fixtures/regression/gh-4787/pages/index.html
test/functional/fixtures/regression/gh-4787/test.js
test/functional/fixtures/regression/gh-4787/testcafe-fixtures/index.js

The issue:
In general next test starts when the previous test executed the test body. The next test does not wait until the reporter of previous one is completed.
This leads to inconsistency, because the test from new fixture can start before the `reportTestDone` of previous test is completed. So, the new test emits the `test-run-start` event before the `fixture-start` event is raised.

wait until reporter of last test in fixture is completed before new fixture starts (closes #4787)

---

src/reporter/index.js
src/runner/task.js
test/server/reporter-test.js

I propose the following format for testStructure:
```JS
fixture: {
id:      'fixtureId',
name:    'fixtureName',
pageUrl: 'pageUrl',
path:    'path',
tests:   [{
id:      'testId',
name:    'testName',
pageUrl: 'pageUrl',
skip:    true/false
},
{ ... }, 
{ ... }
]
}
```
@aleks-pro please check if it fulfills your requirements.
At this moment in this PR the `testStructure` arg is the last argument of `reportTaskStart` method to prevent BC. However, I don't really like this approach. I think we can make one `options` object, or, at least, merge the `testCount` argument and `testStructure` argument, since both of the are about tests.
@miherlosev @AndreyBelym if you are agree with API please review this PR

Provide all structure objects info in reportTaskStart (closes #4807)

---

src/reporter/index.js
test/server/reporter-test.js

The current signature of the `reportTestStart` method is following:
```JS
async reportTestStart (name, meta)
```
and the signature of the `reportTestDone` method is following: 
```JS
async reportTestDone (name, testRunInfo, meta)
```
I propose to make a BC and add the second argument to the `reportTestStart` method. It will be consistent to `reportTestDone`. We can call this argument as `testRunInfo` as well, because it will contain ids of all testRun which will be executed during the test execution.
```JS
async reportTestStart (name, testRunInfo, meta)
```
The `testRunInfo` object after this PR will look like the following:
```JS
{
testRunIds: ['id1', 'id2']
}
```
We cannot name this field `ids` since it will be not clear enough, so it is `testRunIds`

Provide test run IDs to reportTestStart (closes #4808)

---

src/browser/connection/index.ts
src/browser/provider/built-in/dedicated/base.js
src/browser/provider/built-in/dedicated/chrome/index.js
src/browser/provider/built-in/dedicated/firefox/index.js
src/browser/provider/built-in/locally-installed.js
src/browser/provider/index.ts
src/browser/provider/plugin-host.js
test/functional/fixtures/regression/gh-1875/pages/index.html
test/functional/fixtures/run-options/allow-multiple-windows/pages/headless/child.html
test/functional/fixtures/run-options/allow-multiple-windows/pages/headless/index.html
test/functional/fixtures/run-options/allow-multiple-windows/test.js
test/functional/fixtures/run-options/allow-multiple-windows/testcafe-fixtures/headless.js

I need to know the possibility of using the `allowMultipleWindows` option before running tests.
If this option is not supported for the used browser, we show a clear error message.
https://github.com/DevExpress/testcafe/blob/5b4979d60ced70c54e7e331847c60d90ec8be3cb/src/runner/index.js#L337
I'm forced to move calculation of the `windowId` parameter to the `plugin.openBrowser` method because of this parameter is calculated for headless browsers only after validation procedure.
I've run tests for `allowMultipleWindow` option with chrome, chrome:headless, firefox, firefox:headless, edge, edge:headless, ie, safari and all works fine.

Add capability to use 'allowMultipleWindows' option in headless browsers (close #4770)

---

.publishrc
package.json
test/functional/fixtures/api/es-next/resize-window/test.js
test/functional/fixtures/api/es-next/resize-window/testcafe-fixtures/resize-window-test.js

Firefox 74 cannot set its width less than ~450px in both the headless and non-headless modes:

Fix the Firefox 74 "resizeWindowToFitDevice" (portrait orientation) test. Bump version (v1.8.3-rc.1)

---

docs/articles/documentation/continuous-integration/travis.md

xvfb docs are outdated; I tried the recommended docs but got errors; this config worked (https://github.com/internetarchive/bookreader/pull/208). Update to the recommended setup described in the [travis docs](https://docs.travis-ci.com/user/gui-and-headless-browsers/#using-xvfb-to-run-tests-that-require-a-gui).
- Use the xvfb service and chrome addon instead of manual install, as described in https://docs.travis-ci.com/user/gui-and-headless-browsers/#using-xvfb-to-run-tests-that-require-a-gui
- Make .travis.yml snippet complete for optimal copypasta
NA
- [NA] Write tests for your proposed changes

[docs] Update Xvfb docs to latest Travis recommendation

---

src/browser/provider/pool.js
test/functional/config.js
test/server/browser-provider-test.js

Fixes https://github.com/DevExpress/testcafe/issues/4522 and https://github.com/DevExpress/testcafe/issues/4673.
First uses `require.resolve`, which will only throw an error if the provider module itself doesn't exist. If it does exist, we then use `require` to load the module, not catching errors. That way, any errors caused by a 3rd party dependency will show up.

Only catch error if provider module itself does not exist

---

src/reporter/index.js
src/test-run/index.js
test/functional/fixtures/reporter/reporter.js
test/functional/fixtures/reporter/test.js
test/functional/fixtures/reporter/testcafe-fixtures/index-test.js
test/server/test-controller-events-test.js

This is the third attempt to write clean code for adapters.
In this version logic in more linear than in the first one.
The important moment is that we create a separate adapter for the `action-done` methods. Thus `testRunInfo.errs[0]` from `test-run-done` !== `err` from 'action-done'.
I think it does not really matter, since adapter is only service wrapper above the real error.
In addition,  the `errors` array param on `action-done` became just `err` param, because action should have only one error.

The `onActionDone` method should take TestRunErrorFormattableAdapter instance instead of Error (closes #4867)

---

test/functional/fixtures/run-options/stop-on-first-fail/test.js
test/functional/setup.js

ISSUE 1
we need to add beforeEach mocha hook to get the current executing test
ISSUE 2
after mocha is updated to `^7.1.1` the `afterEach` hook is called if the test is skipped/pending before the update the `afterEach` hook was not called. When we run the test not in `chrome` the file will not exist, since we have the { only: 'chrome' } option, so we cannot unlink it.

fix mocha for functional tests

---

src/client/driver/driver.js
src/client/driver/status.js
src/test-run/index.js
test/functional/fixtures/run-options/allow-multiple-windows/pages/i4855/child.html
test/functional/fixtures/run-options/allow-multiple-windows/pages/i4855/index.html
test/functional/fixtures/run-options/allow-multiple-windows/test.js
test/functional/fixtures/run-options/allow-multiple-windows/testcafe-fixtures/i4855.js
test/functional/site/server.js

The problem is reproduced only for the following unstable scenario:
- 'ExecuteSelectorCommand' is queried on the child page.
- the child page is closed. At that moment, the result of the 'ExecuteSelectorCommand' was not sent to the server.
- the parent page became a 'master' page and starts processing commands.
- the initial command processing request on the new 'master' is interpreted as the 'ExecuteSelectorCommand'.
This causes the crash down in the 'replicator' module.
To create a stable reproducible example I am forced to guarantee that the result of the 'ExecuteSelectorCommand' isn't sent to the server.

fix 'Should not finalize the "ExecuteSelectorCommand" command on driver starting' (close #4855) 

---

src/client/automation/index.js
src/client/ui/index.js
test/client/fixtures/automation/automations-test.js
test/client/fixtures/automation/click-test.js
test/client/fixtures/automation/content-editable/api-actions-content-editable-test/index-test.js
test/client/fixtures/automation/content-editable/regression-test/index-test.js
test/client/fixtures/automation/content-editable/select-and-type-content-editable-test/index-test.js
test/client/fixtures/automation/dblclick-test.js
test/client/fixtures/automation/detection-element-after-events-simulation-test.js
test/client/fixtures/automation/drag-test.js
test/client/fixtures/automation/focus-blur-change-test.js
test/client/fixtures/automation/get-element-test.js
test/client/fixtures/automation/hover-test.js
test/client/fixtures/automation/key-press-simulation-test.js
test/client/fixtures/automation/out-of-bounds-test.js
test/client/fixtures/automation/press-shortcuts-test.js
test/client/fixtures/automation/press-test.js
test/client/fixtures/automation/rclick-test.js
test/client/fixtures/automation/real-actions-blocker-test.js
test/client/fixtures/automation/regression-test.js
test/client/fixtures/automation/select-element-test.js
test/client/fixtures/automation/select-test/index-test.js
test/client/fixtures/automation/submit-on-enter-test.js
test/client/fixtures/automation/tab-emulation-test.js
test/client/fixtures/automation/type-test.js
test/client/fixtures/core/dom-utils-test.js
test/client/fixtures/core/style-utils-test.js

Make client tests do not rely on the internal structures of client bundles. Tests have to use only exported symbols, since Rollup doesn't preserve the submodule structure inside a bundle.

Fix imports in client scripts

---

src/client/automation/playback/press/utils.js
test/client/fixtures/automation/press-test.js

The `getActiveElement` method from `hammerhead` contains required code to work with shadowRoot

Make pressKey to work for elements within shadowDOM (closes #2432)

---

docs/articles/blog/2017-1-19-testcafe-v0-12-0-released.md
docs/articles/documentation/test-api/intercepting-http-requests/creating-a-custom-http-request-hook.md

There is a small typo in docs/articles/blog/2017-1-19-testcafe-v0-12-0-released.md, docs/articles/documentation/test-api/intercepting-http-requests/creating-a-custom-http-request-hook.md.
Should read `overridden` rather than `overriden`.

docs: Fix simple typo, overriden -> overridden

---

src/reporter/command/command-formatter.ts
src/reporter/command/interfaces.ts
src/utils/diff.ts
test/functional/fixtures/reporter/test.js
test/functional/fixtures/reporter/testcafe-fixtures/index-test.js
test/functional/fixtures/reporter/testcafe-fixtures/snapshots-test.js
test/server/data/test-controller-reporter-expected/index.js
test/server/test-controller-events-test.js
test/server/util-test.js

We pass the `command` object to the `action-start(done)` methods.
Some commands have `options`.
Options have default values.
User can pass options to action.
I.e. ClickCommand has ClickOptions:
```JS
{
modifiers: {
ctrl: Boolean,
alt: Boolean,
shift: Boolean,
meta: Boolean
},
offsetX: Number,
offsetY: Number,
caretPos: Number,
speed: Number
}
```
User executes action: `await t.click('#target'), { offsetX: 1, modifiers: { ctrl: true, alt: false } }`
The options will be the following:
```JS
{
speed: null
offsetX: 1
offsetY: null
modifiers: {
ctrl: true
alt: false
shift: false
meta: false
}
caretPos: null
}
```
We need to pass to reporter only NOT DEFAULT VALUES: `{ offsetX: 1, modifiers: { ctrl: true  } }`.
**P.S.**
I added the missing `timeout` option for selectors

report only modified options in reportActionDone(closes #4926)

---

src/runner/browser-job.js
test/functional/fixtures/regression/gh-4787/test.js

If we have multiple fixtures and every fixture contains small number of tests, the synchronization occurs too often. This leads to the situation when concurrent browsers wait for last test in fixture is done.
I remove the syncronization when the concurrency mode is enabled

Do not wait for reporter is executed when concurrency is enabled (closes #4894)

---

src/test-run/index.js
test/functional/fixtures/run-options/allow-multiple-windows/test.js
test/functional/fixtures/run-options/allow-multiple-windows/testcafe-fixtures/i4855.js
test/functional/site/server.js

This change fixed the following multi-window case - https://github.com/DevExpress/testcafe/issues/4927#issuecomment-607723547.
See the case description here - https://github.com/DevExpress/testcafe/blob/master/test/functional/fixtures/run-options/allow-multiple-windows/pages/i4855/index.html#L9

Fix one more case for i4855 issue

---

src/compiler/test-file/api-based.js
test/server/compiler-test.js

If you try to start test run for a folder that contains testcafe's test file and a typescript declaration file you get an error:
Try it yourself - [surveyjsio-site-tests.zip](https://github.com/DevExpress/testcafe/files/4450681/surveyjsio-site-tests.zip)
TypeScript compiler should not execute such files because they are don't produce any code.

Compiler doesn't execute typescript declaration files anymore

---

Gulpfile.js

It's enough to pull the image immediately after publishing.
The `pull` command sends request to the server even when you have local image with same name and tag. If the image exists on server the `image is up to date` message will appear in console, otherwise, the `manifest` not found error will break the task execution.

pull published image immediately after push (closes #4979)

---

src/test-run/index.js
test/functional/fixtures/run-options/allow-multiple-windows/pages/debug-synchronization/child.html
test/functional/fixtures/run-options/allow-multiple-windows/pages/debug-synchronization/parent.html
test/functional/fixtures/run-options/allow-multiple-windows/test.js
test/functional/fixtures/run-options/allow-multiple-windows/testcafe-fixtures/debug-synchronization.js

Fixes a problem when TestCafe starts debugging in a child window, child window closes and test execution continues. If a child windows closes, we should reexecute the SetBreakpointCommand if it is the current command in the execution queue.
Includes a test that uses Chrome Devtools protocol to control the browser during debugging.

Continue debugging when a child window closes (closes #4990)

---

src/client-functions/selectors/add-api.js
src/client/driver/command-executors/client-functions/selector-executor/filter.js
src/client/driver/command-executors/client-functions/selector-executor/index.js
test/functional/fixtures/api/es-next/selector/pages/visible.html
test/functional/fixtures/api/es-next/selector/testcafe-fixtures/selector-visible-test.js

In https://github.com/DevExpress/testcafe/commit/90e7b04aac9316c9416cc8fd08791c688b92948a we allowed to execute `Selector.visible` even if the target element does not exist. It was done by calculating visibility at the element filtration stage in contrast to calculating a DOM snapshot stage after filtration and retrieving visibility from it. Unfortunately it broke compatibility with other filters like `filterVisible`.
This PR moves visibilty calculation back to the DOM snapshot but makes it avoiding raising exceptions when we cannot find the target element.

Fix Selector.visible for complex selectors (closes #5002)

---

docs/articles/documentation/guides/basic-guides/select-page-elements.md

Fixing the docs example of using `testcafe-react-selectors`.
The default export declaration [changed 2 years ago](https://github.com/DevExpress/testcafe-react-selectors/commit/1172b89ef079872eb2b8c70fc73409764a273fec#diff-b19910e06a80cee27943e3eb72d8d760L4) to named export, as reflected on the [library docs](https://github.com/DevExpress/testcafe-react-selectors/blob/master/README.md#selecting-elements-by-the-component-name).

[docs] fix ReactSelector import

---

src/reporter/index.js
src/reporter/plugin-host.js
test/server/reporter-test.js

Having configuration options allows the reporter to provide additional info
Feeding options as a param to `reportTaskStart` method
#5088 (options have screenshot and video dir paths)
#3497 (screenshots/videos paths can be relativized)

Passing configuration options to reporter (closes #5088)

---

test/server/data/test-suites/typescript-defs/request-hooks.ts
test/server/data/test-suites/typescript-testcafe-scripts-defs/request-hooks.ts
ts-defs-src/test-api/request-hook.d.ts

Add type definitions for `RequestOptions` and `ResponseMock`, and update type definitions for `RequestMock.onRequestTo` and `RequestMock.respond` accordingly.
- Copied text/types from https://devexpress.github.io/testcafe/documentation/reference/test-api/requestmock/respond.html#requestoptions
- Also took a look at the src:
- RequestOptions: https://github.com/DevExpress/testcafe-hammerhead/blob/master/src/request-pipeline/request-options.ts
- ResponseMock: https://github.com/DevExpress/testcafe-hammerhead/blob/master/src/request-pipeline/request-hooks/response-mock.ts
- Not entirely sure how to test these in any feasible way. I confirmed they worked by modifying the .d.ts in node_modules of an existing project with the above changes, and confirming that auto-completion works, but not …

Add type definitions for RequestOptions and ResponseMock (closes #5108)

---

.travis.yml
Gulpfile.js
appveyor.yml
azure-pipelines.yml

Changes:
* add `RETRY_FAILED_TESTS` environment variable to CI config files (Appveyor, Travis, Azure Pipelines) that turn on rerun of the failed tests. Locally, the tests don't rerun.
* Rewrite `travis.yml` according validator messages (https://config.travis-ci.com/explore). Now, chrome and firefox browsers are installed only for those tasks where they are necessary.

Turn on rerun failed tests on CI

---

Gulpfile.js
package.json
test/functional/fixtures/api/es-next/assertions/test.js

See the custom reporter description - https://github.com/miherlosev/mocha-reporter-spec-with-retries#mocha-reporter-spec-with-retries.
https://dev.azure.com/DevExpressTestCafe/testcafebuildbot-testcafe/_build/results?buildId=5747&view=logs&j=12f1170f-54f2-53f3-20dd-22fc7dff55f9&t=35f53584-79fc-539f-463c-6471d0663a3a

Display unstable tests in the test reporter

---

src/client/automation/playback/type/index.js
test/client/fixtures/automation/type-test.js

As shown in #4881, 'change' events don't trigger if the last keypress was prevented, thus not saving the entire element value.
Added changePrepared property that sets to true before calling _keypress() if element value changed but the 'change' event has not been called.
The value of changePrepared is then checked in _typeChar() and the elementEditingWatcher is reset if it's false.
#4881

Change event on prevented keypress (closes #4881)

---

docs/articles/documentation/reference/test-api/testcontroller/expect/noteql.md

Fix argument name for `.notEql`

Fix argument name for .notEql

---

docs/articles/documentation/recipes/README.md

Adding link to @testcafe-community/axe for integration with axe-core.
The axe-testcafe project has been dormant on github for quite some time.  As such I decided to fork that library and modernize it, fixing some bugs and adding a more streamlined API that is based on modern testcafe. (using clientScripts for example)
https://github.com/testcafe-community/axe

[doc] Add  link to @testcafe-community/axe

---

docs/README.md
docs/articles/documentation/recipes/README.md
docs/articles/documentation/recipes/integrations/test-websites-that-use-recaptcha.md
docs/nav/nav-menu.yml

fixes https://github.com/DevExpress/testcafe/issues/5072

[docs] Add a reCAPTCHA article

---

src/api/test-controller/index.js
src/client-functions/types.ts
src/errors/create-stack-filter.js
src/notifications/warning-message.js
test/functional/fixtures/api/es-next/assertions/test.js
test/functional/fixtures/api/es-next/assertions/testcafe-fixtures/assertions-test.js
test/server/compiler-test.js

Users often want to assert that the selected element exists or that the returned value of ClientFunction meets a specific criteria.
I created an addAssertionWarning function that checks if the "actual" expected value is a function and if its builder object is SelectorBuilder/ClientFunctionBuilder. If this condition is met, I print a corresponding warning.
Part of #5087

Add warning messages when trying to assert Selector/ClientFunction instances

---

docs/articles/documentation/guides/concepts/typescript-and-coffeescript.md

[docs] Fix a wrong mention of TS compiler's 'paths' option

---

.publishrc
package.json

1. The vulnerable dependencies check is temporarly disabled (`lodash` vulnerability).

Turn off the vulnerable dependencies check

---

test/functional/fixtures/regression/hammerhead/gh-2350/pages/change-value.html
test/functional/fixtures/regression/hammerhead/gh-2350/test.js
test/functional/fixtures/regression/hammerhead/gh-2350/testcafe-fixtures/index.js

```html
<head>
<title>Test page title 1</title>
<script>
var log = [];
log.push('head:after-first-title: ' + String(document.title));
```
Related to https://github.com/DevExpress/testcafe-hammerhead/issues/2374

The functional test for changing title into the first script after <title> tag

---

Gulpfile.js
src/api/test-controller/index.js
src/browser/connection/index.ts
src/client/driver/driver-link/messages.js
src/client/driver/driver-link/window/child.js
src/client/driver/driver-link/window/parent.js
src/client/driver/driver.js
src/errors/test-run/child-window-error-factory.js
src/errors/test-run/index.js
src/errors/test-run/templates.js
src/errors/types.js
src/test-run/commands/actions.js
src/test-run/commands/type.js
src/test-run/index.js
test/functional/fixtures/run-options/allow-multiple-windows/pages/api/child-1.html
test/functional/fixtures/run-options/allow-multiple-windows/pages/api/child-2.html
test/functional/fixtures/run-options/allow-multiple-windows/pages/api/parent.html
test/functional/fixtures/run-options/allow-multiple-windows/test.js
test/functional/fixtures/run-options/allow-multiple-windows/testcafe-fixtures/api/api-test.js
test/server/data/expected-test-run-errors/parent-window-not-found-error
test/server/data/expected-test-run-errors/recent-window-not-found-error
test/server/data/expected-test-run-errors/switch-to-window-predicate-error
test/server/data/test-controller-reporter-expected/index.js
test/server/test-controller-events-test.js
test/server/test-run-error-formatting-test.js

We need to resolve current driver task after the command is executed in one of the windows, so I pass the `finalizePendingCommand` arg in the `_switchToParentWindow` method. Otherwise, drivers of all windows will get duplicated command.
The predicate params:
```JS
(w => {
return 
w.title === 'Title'
w.location.href === fullUrl &&
w.location.protocol === 'http:' &&
w.location.host === 'localhost:3000' &&
w.location.port === '3000' &&
w.location.query === '/fixtures/run-options/allow-multiple-windows/pages/api/parent.html';
}, { dependencies: { fullUrl } });
```

Multiple windows api (part 2) - SwitchToParentWindow, SwitchToWindow (by predicate), SwitchToRecentWindow

---

src/client/driver/driver-link/messages.js
src/client/driver/driver.js
test/functional/fixtures/run-options/allow-multiple-windows/test.js
test/functional/fixtures/run-options/allow-multiple-windows/testcafe-fixtures/api/api-test.js

We can be sure that window is closed only inside the `_ensureClosedChildWindowWatcher` method's interval.
However, in this method we do not know if the window was closed itself (not from TestCafe) or via the `closeWindow` method.
In the case of the `closeWindow` method we do not need to call `setCurrentWindowAsMaster` method. The only case when we need to change master in API call is only when we close the current window via API. In all other cases we need to leave the master window as is.
So I handle CHILD_WINDOW_CLOSED_EVENT inside API call and set flag childWindowClosedEventArgs.setWindowAsMaster to prevent the call to `_setCurrentWindowAsMaster` method

`t.closeWindow` method makes parent window of target window active(closes #5296)

---

package.json
test/server/compiler-test.js

The latest version (`0.5.2`) of the `@types/source-map-support` module references the `@source-map@^0.6.0` module without exporting typings. The types export was added to `source-map` module from the `0.7.0` version (https://github.com/mozilla/source-map/commit/7cc0c9dad9c358e956258389436bdd95c50354af).
I fixed the `@types/source-map-support` module version until it will be fixed.

Fix server tests

---

src/client/driver/driver-link/window/child.js
src/client/driver/driver.js
test/functional/fixtures/run-options/allow-multiple-windows/pages/api/child-3.html
test/functional/fixtures/run-options/allow-multiple-windows/test.js
test/functional/fixtures/run-options/allow-multiple-windows/testcafe-fixtures/api/api-test.js

1. We need to send command result for `openWindow` command only after the page is loaded and is set as master. In other case, the `switchToRecentWindow` method will not work as expected.
Since `openWindow` calls `setAsMaster`, we need to set result inside the `setAsMaster`.
2. The other problem is that we have special `_waitForEmptyCommand` method inside the `_switchToChildWindow` method. The `_waitForEmptyCommand` is not required when we use API, since here cannot be other executing commands

wait new window page is loaded completely (closes #5303)

---

src/browser/connection/index.ts
src/browser/provider/built-in/remote.js
src/browser/provider/index.ts
src/notifications/warning-log.js
src/notifications/warning-message.js
test/server/browser-provider-test.js
test/server/warning-log-test.js

When used WSL2 or connected browser as a remote to a headless Linux container (no X11, no Xvfb), TestCafe cannot handle errors thrown by `find-window`.
DevExpress#4742

Handle errors when cannot find a browser window

---

src/browser/connection/index.ts
src/browser/provider/built-in/dedicated/base.js
src/browser/provider/built-in/remote.js
src/browser/provider/index.ts
src/browser/provider/plugin-host.js
src/browser/provider/pool.js
src/errors/runtime/templates.js
src/errors/types.js
src/runner/bootstrapper.ts
src/utils/detect-display.ts
test/functional/fixtures/browser-provider/job-reporting/test.js
test/functional/fixtures/runner/test.js
test/functional/fixtures/runner/testcafe-fixtures/basic-test.js
test/functional/setup.js
test/server/bootstrapper-test.js
test/server/runner-test.js

Emit an error when trying to run tests on Linux without the graphics subsystem.
Check that ```DISPLAY``` environment variable is set. If it's not, then throw an error when trying to run tests on local and non-headless browser.
DevExpress/testcafe#4461

Emit an error when runned on Linux without GUI

---

docs/articles/documentation/reference/test-api/testcontroller/setnativedialoghandler.md

The header should be `setNativeDailogHandler` instead of `setNativeDailogueHandler`.

[docs] Fix misprint in the setNativeDailogHandler reference

---

src/browser/provider/built-in/locally-installed.js
src/errors/test-run/templates.js
test/functional/fixtures/api/es-next/multiple-windows/test.js
test/server/browser-provider-test.js
test/server/data/expected-test-run-errors/multiple-windows-mode-is-not-available-in-remote-browser-error

To disable multiwindow mode for all browsers except Chrome(Chromium, Edge 84+) and Firefox, we should disable multiwindow mode for all locally installed installed browsers, since Chrome and Firefox use separate providers and have separate implementations that enable the multiwindow functionality.

Enable multiwindow only for Chromium-based and Firefox

---

test/server/data/test-suites/typescript-defs/window-management.ts
test/server/data/test-suites/typescript-testcafe-scripts-defs/window-management.ts
ts-defs-src/test-api/test-controller.d.ts

Add definitions for the multiwindow API. Descriptions are taken from the pending PR to the docs: #5363.

Add TS defs for the window management  API

---

docs/articles/documentation/guides/advanced-guides/test-https-features-and-http2-websites.md

[docs] Update HTTPS guide

---

.travis.yml
Gulpfile.js
docker/is-docker-daemon-running.js
test/server/bootstrapper-test.js
test/server/helpers/is-alpine.js
test/server/runner-test.js

`chrome` is now required for some of our server tests. Since we use Alpine for our Docker image, we can't use Chrome here, only Chromium. Tried to mock this, but it was painful. So I added Alpine detection (looking with `fs` for a specific file), and now server tests should use Chromium for Alpine, Chrome otherwise.

Fix docker tests

---

package.json
src/notifications/warning-message.js
test/functional/fixtures/api/es-next/assertions/test.js

Remove the braces from the warning about passing a ClientFunction to `t.expect`.

Rephrase the assertion warning for ClientFunction; Bump version (v1.9.0-rc.2)

---

.publishrc
package.json
src/errors/test-run/formattable-adapter.js
test/server/test-run-error-formatting-test.js

Added a check to error formatter in case an unknown decorator is specified.

Added a check to error formatter. Bump version (v1.9.1-rc.1). Bump hammerhead (v17.1.13)

---

README.md

https://github.com/testingbot/testcafe-browser-provider-testingbot

Add the testingbot provider to the plugin list

---

src/errors/runtime/index.js
src/errors/runtime/templates.js
src/errors/types.js
src/reporter/index.js
src/reporter/interfaces.ts
src/reporter/plugin-methods.ts
src/runner/bootstrapper.ts
src/runner/index.js
src/runner/task.ts
src/utils/async-event-emitter.ts
src/utils/reporter.ts
src/utils/types.ts
test/functional/fixtures/reporter/test.js
test/server/reporter-test.js

The exceptions which may be thrown by the methods of a reporter plugin leads to hanging of TestCafe. Moreover, Task event listeners in `Reporter` don't have any exception handling.
* `AsyncEventEmitter` refactored:
- `once` method worked incorrectly: resolve of a rejected promise could happen;
- uncatched promise rejections from async event listeners should lead to emitting an `error` event. We need to handle this in our code, because [this](https://nodejs.org/api/events.html#events_capture_rejections_of_promises) thing is still experimental and emittery doesn't provide it.
* `Task` listeners/handlers are placed in separate methods of `Reporter`. 
#5135

Add exception handling in Reporter

---

package.json
src/api/test-controller/index.js
src/api/test-run-tracker.d.ts
src/api/wrap-test-function.ts
src/client-functions/selectors/add-api.js
src/notifications/add-rendered-warning.ts
src/notifications/warning-message.js
src/services/compiler/test-run-proxy.ts
src/test-run/observed-callsites-storage.ts
test/functional/fixtures/api/es-next/assertions/data/expected-missing-await-on-snapshot-callsite
test/functional/fixtures/api/es-next/assertions/data/expected-selector-property-awaited-callsite
test/functional/fixtures/api/es-next/assertions/test.js
test/functional/fixtures/api/es-next/assertions/testcafe-fixtures/assertions-test.js

Add a warning message when trying to get a snapshot property value without calling await (which returns a Promise).
Saving a callsite when accessing the snapshot property, deleting the callsite in `.then` (if the property is awaited). If there are callsites left after the test finishes, printing a warning
Part of #5087

Add warnings for missing await when trying to get a snapshot property value

---

Gulpfile.js

Corrected `execa.command` that expects to pass arguments and command via a single string to regular `execa`.

[docs] Fix website building

---

ts-defs-src/test-api/assertions.d.ts

#5446 Added null to the list of types avaliable for the checking

---

package.json

Restrict using the `new Date()` and `Date.now()`  expression in the client code.
Connected with https://github.com/DevExpress/testcafe/commit/78cd2632593806e20ea915c7634fb523e5163f3c

Update eslint-plugin-hammerhead plugin

---

docs/articles/documentation/guides/basic-guides/run-tests.md

Concurrency is not support in the Legacy Edge only, its fine in the Chromium-based version.

[docs] Mention Edge Legacy in the concurrency note

---

test/server/data/test-suites/typescript-defs/request-hooks.ts
test/server/data/test-suites/typescript-testcafe-scripts-defs/request-hooks.ts
ts-defs-src/test-api/request-hook.d.ts

Closes #5529 
Fixes typescript types for requestmocks and responsemocks. The `object` type is difficult to use and recommended linting configurations now prevent you from using it. See https://github.com/microsoft/TypeScript/issues/21732
uses a more accurate type for headers and other fields
#5529

Fixes header types for request and response mocks (#5529)

---

src/client-functions/selectors/add-api.js
test/functional/fixtures/api/es-next/assertions/data/expected-missing-await-on-snapshot-callsite
test/functional/fixtures/api/es-next/assertions/data/expected-missing-await-on-snapshot-callsite/console-log
test/functional/fixtures/api/es-next/assertions/data/expected-missing-await-on-snapshot-callsite/template-expansion
test/functional/fixtures/api/es-next/assertions/test.js
test/functional/fixtures/api/es-next/assertions/testcafe-fixtures/assertions-test.js

Now a "missing await for a snapshot property" is created only when:
- It is converted to a primitive value (arithmetic operators, template expansions, string concatenation) (overrided `Symbol.toPromitive`)
- `console.log` or `util.inspect` are invoked (overrided `util.inspect.custom`)

Fix excessive "missing await" warnings (closes #5534)

---

.publishrc
package.json

- `RequestMock`\`s type definitions was fixed to allow setting custom headers (https://github.com/DevExpress/testcafe/issues/5529)
- Eliminated "You used a DOM snapshot property without \'await\'. " warning when a snapshot property was saved to a variable but not used in a test (https://github.com/DevExpress/testcafe/issues/5534)
- Consecutive  `document.getElementsByTagName('body')` calls now produce correct results even if a first call was made before a document's body was completely parsed (#5322)

Bump version (v1.9.3)

---

package.json
test/functional/fixtures/regression/hammerhead/gh-2350/pages/iframes/iframe.html
test/functional/fixtures/regression/hammerhead/gh-2350/pages/iframes/index.html
test/functional/fixtures/regression/hammerhead/gh-2350/test.js
test/functional/fixtures/regression/hammerhead/gh-2350/testcafe-fixtures/iframes.js

Changes: 
* add test for fixed case 'proxy document.title in iframes'.

Fix proxing document.title  in iframes (tests), bump version

---

src/client/automation/cursor.js
src/client/automation/get-element.js
src/client/automation/playback/move/index.js
src/client/automation/playback/press/index.js
src/client/automation/playback/scroll.js
src/client/automation/utils/utils.js
src/client/driver/command-executors/browser-manipulation/index.js
src/client/ui/status-bar/index.js
src/utils/is-window-in-iframe.ts
test/client/fixtures/automation/type-test.js
test/functional/fixtures/regression/gh-4793/pages/iframe.html
test/functional/fixtures/regression/gh-4793/pages/index.html
test/functional/fixtures/regression/gh-4793/test.js
test/functional/fixtures/regression/gh-4793/testcafe-fixtures/index-test.js

[Safari 13](https://developer.apple.com/documentation/safari-release-notes/safari-13-release-notes) does not allow focusing elements inside of cross-domain iframes before the iframe itself is focused.
We can focus the iframe before trying to focus the inner element. This should not have side-effects as we focus the element afterwards anyway.
We can't focus the iframe from inside of its context so we need to send a message to the parent context, so that we can focus the iframe there,  and wait for the response.
Possible considerations:
- Make this logic Safari-exclusive as other browsers work without it
Closes #4793

Fix cross-domain iframe focus in Safari

---

src/client/automation/playback/click/index.js
test/client/fixtures/automation/click-test.js

We need to support the case when the `preventDefault` method is called on the touch event listener to prevent click and mouse events as [stated](https://w3c.github.io/touch-events/#mouse-events) in the W3C specification:
>  If touchstart, touchmove, or touchend are canceled, the user agent should not dispatch any mouse event that would be a consequential result of the prevented touch event.
WIP
#5380

Do not fire mouse events when touch events has been cancelled (close #5380)

---

src/client/driver/driver-link/messages.js
src/client/driver/driver-link/window/child.js
src/client/driver/driver-link/window/parent.js
src/client/driver/driver.js
src/errors/test-run/templates.js
src/errors/types.js
src/shared/errors/index.js
test/functional/fixtures/multiple-windows/test.js
test/functional/fixtures/multiple-windows/testcafe-fixtures/api/api-test.js
test/server/data/expected-test-run-errors/cannot-restore-child-window-error
test/server/test-run-error-formatting-test.js

The cause:
If the page is reloaded it loses all its childLinks and parent links.
The approach:
Parent link is restorable easily since we have the `window.opener` property.
It is more difficult to restore child links since we do not have parent-child relationship.
So, I handle the `beforeunload` event and send a command to all child windows to start to ping parents.
Child windows get the command and start sending messages to parent. The child will repeat the sending until the parent does not confirm. So while the parent is reloading, the child is sending a message and do not get the confirmation. After the parent is reloaded, the new parent driver gets the message and send a confirmation. When the new parent gets the message it can restore the child window links.

fix issues with window search (closes #5463, #5597)

---

.github/stale.yml

Add config for the Stale bot that closes outdated/stale issues.
The bot will clean up the repository from outdated/stale issues.
[https://github.com/marketplace/stale](https://github.com/marketplace/stale)
No need for tests as it is a non-technical PR.

[docs] Add config for the Stale bot

---

package.json
src/errors/create-stack-filter.js
src/errors/process-test-fn-error.js
test/server/helpers/assert-runtime-error.js

Node.js v15 adds a prefix to builtin module filenames in stacktraces: [src: use node:moduleName as builtin module filename](https://github.com/nodejs/node/pull/35498).
We need to take into account this change by adding one more case to our filtering logic of filenames in stacktraces.

Fix server tests in Node v15

---

test/server/execute-async-expression-test.js

Test for "debug" method of the test controller doesn't properly stub the stdout stream, which causes the method's code to interfere with mocha's spec reporter's output. As a result, we see broken output after the `gulp test-server` command is executed.
before:
after:

fix(server-tests): test doesn't properly stub stdout

---

src/client/driver/driver-link/messages.js
src/client/driver/driver-link/window/parent.js
src/client/driver/driver.js
src/client/driver/iframe-driver.js
test/functional/fixtures/multiple-windows/pages/frame/child.html
test/functional/fixtures/multiple-windows/pages/frame/frame.html
test/functional/fixtures/multiple-windows/pages/frame/parent.html
test/functional/fixtures/multiple-windows/test.js
test/functional/fixtures/multiple-windows/testcafe-fixtures/iframe.js

The cause of the issue is that the child window is opened in an iframe.
We need to handle this situation.
My approach:
- information about the child window is stored in the main window, not in the iframe. It allows us to iterate through windows hierarchy without considering iframes
- in the main window we need somehow to wait until the child window is fully loaded in the iframe. The problem is that in the main window we do not know when the window is opened. So, when the child window starts to open in the iframe, I send the message to the main window, that it should wait. Then, when the child window is fully loaded, I send the message from the child window to the main window to stop waiting and switch to the child window.

fix multiple windows + iframes (closes #5033)

---

docs/articles/documentation/guides/continuous-integration/circleci.md
docs/articles/documentation/reference/test-api/testcontroller/typetext.md

[docs] Add code example for formatted input fields (typeText)

---

.dockerignore
.gitignore
Gulpfile.js
gulp/helpers/domain.js

I assume that Gulp's domain error handlers started to catch the unhandled promise rejections (placed in the tests for a reason) and interrupt test execution after "[Unhandled rejections become errors on the domain](https://github.com/nodejs/node/pull/36082)" functionality shipped in Node 15.3.0. So, we need to bypass Gulp's error domains (using @AndreyBelym's [hack](https://github.com/DevExpress/generator-testcafe-reporter/blob/a79d29a6b0c835171cc7018831bf6f7737383cc8/Gulpfile.js#L54)).

fix(server-tests): errored tests after Node 15.3.0 update

---

.travis.yml

The new Travis CI backend uses the GitHub Checks API to notify GitHub about build status. Unfortunately, it seems that this API cannot change a build status to "pending" for a build that was previously completed once. It means GitHub cannot update a build status for a restarted build until it finishes. To overcome this inconvenience, the build bot can receive build notifications directly from Travis CI.

Add a webhook for Travis CI

---

Gulpfile.js
gulp/helpers/get-timeout.js
test/server/browser-provider-test.js
test/server/live-test.js
test/server/reporter-test.js
test/server/runner-test.js
test/server/test-run-request-handler-test.js

Server tests are run with a specifed Mocha "timeout" option, which should be equal to "Infinity" when tests are executed under the debugger and 2000 ms otherwise. But the [condition](https://github.com/DevExpress/testcafe/blob/6e7a44d9cdc2bbb8927c4a89cf69816ec0862016/Gulpfile.js#L383) that is supposed to implement this logic actually always returns `true`, and so the timeout is always being set to "Infinity". This condition doesn't properly detect debug mode because `typeof v8debug` always returns `undefined` in node versions >= 7 and `process.debugPort` is always set.
Checking that `typeof v8debug !=== undefined` and [process.execArgv](https://nodejs.org/api/process.html#process_process_execargv) contains "debug" or "inspect" strings. This probably doesn't cover every case, because seems …

fix(tests): mocha timeout is always set to Infinity

---

@types/time-limit-promise/index.d.ts
src/browser/connection/index.ts
src/errors/runtime/index.js
src/utils/browser-connection-timeouts.js
test/functional/fixtures/browser-provider/browser-reconnect/test.js
test/functional/fixtures/browser-provider/browser-reconnect/testcafe-fixtures/index-test.js

We need to restart the browser even if the `_closeBrowser` method hangs for some reason. So we wrap `_closeBrowser` with time-limited promised and BROWSER_CLOSE_TIMEOUT.

continue browser restart if close browser hangs (closes #5238)

---

Gulpfile.js
gulp/docker/run-functional-test-via-command-line.js
package.json

Changes:
* force docker image removing after publish
* change format of the mounted directory for docker functional tests.
`//C/Users/losev.mikhail..` -> C:/Users/losev.mikhail
* change version to make sure that docker publish process was fixed

Fix docker related problems in gulpfile.js

---

test/server/data/test-suites/typescript-defs/test-controller.ts
test/server/data/test-suites/typescript-testcafe-scripts-defs/test-controller.ts
ts-defs-src/test-api/test-controller.d.ts

Fixes the problem with coercion `unknown -> void` and preserves interfaces' inheritance. Better test ideas are welcomed.

Fix BC in test action result definitions

---

package.json
src/compiler/babel/load-libs.js
src/compiler/compile-client-function.js
test/functional/fixtures/api/es-next/client-function/test.js
test/functional/fixtures/api/es-next/client-function/testcafe-fixtures/client-fn-test.js
test/functional/fixtures/reporter/test.js
test/server/data/client-fn-compilation/basic/expected.js
test/server/data/client-fn-compilation/gh1279/expected.js
test/server/data/client-fn-compilation/typeof/expected-node10.js
test/server/data/client-fn-compilation/typeof/expected.js
test/server/data/test-controller-reporter-expected/index.js

Babel 7 injects helpers in a different way than Babel 6. As a result, ClientFunctions cannot be compiled if Babel injects some helper:
```
var selector = (function() {
return function firstHelper () {
}
function secondHelper () {
}
(function () {
return someElement;
});
})();
```
I changed the wrapper to allow declaring Babel helpers and return the ClientFunction body.

Fix compiling client functions with for-of

---

docs/articles/faq/README.md

[docs] Add a note about testing websites served over a VPN

---

.travis.yml
Gulpfile.js
src/browser/provider/built-in/dedicated/base.js
src/browser/provider/built-in/dedicated/chrome/index.js
src/browser/provider/built-in/dedicated/firefox/index.js
src/browser/provider/built-in/dedicated/firefox/marionette-client/commands.js
src/browser/provider/built-in/dedicated/firefox/marionette-client/index.js
src/browser/provider/index.ts
test/functional/fixtures/multiple-windows/test.js
test/functional/fixtures/multiple-windows/testcafe-fixtures/api/api-test.js

1. Firefox now should support resizing multiple windows using browser-tools. For this, I moved the code from 'chrome' provider to /dedicated/base provider.
2. Firefox should support resizing multiple windows in headless mode by marionette protocol. Before every action in marionette (i.e. resizing) TestCafe finds the activeWindow (by runtimeInfo.activeWindowId) and switches to this window using marionette.
It is required to switch to window in order to make screenshots. ASFAIU we cannot resize specific window by parameter, we need to switch to this window and resize current window.
3. I added FF to `multiple-windows` gulp task, but I add { only: chrome } for most of tests, since these tests are not stable in FF unfortunately. Now only resizing (local and headless) is tested in FF.

resize multiple window in local firefox

---

test/server/bootstrapper-test.js
test/server/configuration-test.js

Sometimes, these test failed by timeout in WebStorm the Gulp run task console.
I changed the default timeout (2000 ms) up to 3000 ms.

Increase test timeouts

---

.publishrc
package.json
src/compiler/babel/get-base-babel-options.ts
src/compiler/compile-client-function.js
src/compiler/test-file/formats/es-next/compiler.js

Problem: the Babel 7 [config file](https://babeljs.io/docs/en/options#configfile) at the project root is applied to the internal TestCafe babel config. Sometimes it causes the babel plugins loading problems.
The problem is reproduced only on the first TestCafe loading.
I cannot add a functional test to our test infrastructure because we reuse the Runner instance. Babel caches the config files and created in runtime configuration files is not applied.
I cannot add a server test because I have not found a public API to emulate the first TestCafe loading (clear configuration cache or something else).
I can create a test using a separate `Travis` task, but I cannot do this.
Fix: add the `configFile: false` option to the internal TestCafe config.

fix 'Error: [BABEL] unknown: Preset' (close #5808)

---

docs/articles/documentation/guides/advanced-guides/screenshots-and-videos.md
docs/articles/documentation/guides/concepts/browsers.md
test/website/test.js

[docs] Add a note that cdpPort is required when you override the user dir

---

src/browser/provider/built-in/dedicated/chrome/browser-client.ts
test/functional/fixtures/browser-provider/custom-profile/testcafe-fixtures/index-test.js

I wrap the `createClient` function in try/catch block, since that's possible when cdp argument is undefined or incorrect. In this case `createClient` should return `null`. This approach will work since we already have required null checks.

fix cdp when cdpPort is not set

---

docs/articles/documentation/why-testcafe/README.md
docs/nav/docs-top-menu.yml

As I presume, Why TestCafe should replace How It Works, so we had to modify the navbar and configure redirects from the old URL.

[docs] Fix Why TestCafe once more

---

README.md

The main page (README.MD) has a mention of the outdated nodejs version (version 6) which is unsupported by the current TestCafe version (1.10.1).
Let's recommend that the Current or Active LTS versions are preferable.
https://github.com/nodejs/Release#release-phases
All's good.

[docs] Fix the required nodejs version on the main page

---

src/client/driver/driver.js
test/functional/fixtures/multiple-windows/test.js
test/functional/fixtures/multiple-windows/testcafe-fixtures/features/screenshots.js

The child window can become master during the preceding async requests in this case we do not need to call the `_startInternal` method again since it was called during the `_handleSetAsMasterMessage` method.
It's difficult to emulate similar behavior in test, but in theory this fix should prevent flacky tests in the `multiple-windows` travis task

Prevent multiple `sendStatus` requests in multiple windows + tests for screenshots in FF

---

src/client/driver/command-executors/client-functions/eval-function.js
test/functional/fixtures/regression/gh-5886/pages/index.html
test/functional/fixtures/regression/gh-5886/test.js
test/functional/fixtures/regression/gh-5886/testcafe-fixtures/index.js

Selector.withText method can't find existing element in the rewritten iframe because [this](https://github.com/DevExpress/testcafe/blob/faec4a93682d51a6f51909514b437236899b08c1/src/client-functions/selectors/selector-text-filter.js#L21) condition fails: `RegExp` is local to the iframe window context, but the `textFilter` instance was created with the global `RegExp` (created by the replicator). All that because check with the `instanceof` operator has special behavior in different contexts: [instanceof and multiple context (e.g. frames or windows)](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/instanceof#instanceof_and_multiple_context_e.g._frames_or_windows). 
The regression is originated from [this](https://github.com/DevExpress/testcafe/pull/4915#discussion …

fix(selectors): withText can't find existing element

---

src/client/automation/playback/type/type-text.js
test/functional/fixtures/regression/gh-5921/pages/index.html
test/functional/fixtures/regression/gh-5921/test.js
test/functional/fixtures/regression/gh-5921/testcafe-fixtures/index.js

Fix the issue in tyepText that it doesn't replace the old value when the old value fits input maxlength.
Following the support from @AlexKamaev in #5921
By fixing if condition which compare the maxlength with element value.
#5921

Fix typeText replacing issue (fix #5921)

---

package.json
src/test-run/index.js
test/functional/fixtures/run-options/request-timeout/test.js

The test's request timeout options should override the test run's request timeout options.

Fix wrong request timeout options overriding

---

package.json
test/functional/fixtures/api/es-next/request-hooks/pages/api/request-filter-rule-async-predicate.html
test/functional/fixtures/api/es-next/request-hooks/test.js
test/functional/fixtures/api/es-next/request-hooks/testcafe-fixtures/api/request-filter-rule-async-predicate.js
test/functional/fixtures/regression/gh-3049/test.js
test/functional/fixtures/regression/gh-3456/test.js
test/functional/fixtures/regression/gh-3929/test.js
test/functional/fixtures/regression/gh-5239/test.js
test/functional/fixtures/regression/gh-5239/testcafe-fixtures/index.js
test/functional/fixtures/regression/gh-5549/test.js
test/functional/fixtures/regression/hammerhead/gh-863/test.js
test/functional/fixtures/regression/hammerhead/gh-863/testcafe-fixtures/index.js

Changes:
1) Now, the predicate can be asynchronous.
https://devexpress.github.io/testcafe/documentation/reference/test-api/requesthook/constructor.html#filter-with-a-predicate
```js
const logger = RequestLogger(request => {
return request.body === '{ test: true }' &&
request.headers['content-type'] === 'application/json';
});
->
const logger = RequestLogger(async request => {
return await someFn();
});
```
2) Rewrite `testcafe.close()` calls because it's asynchronous method.
3) Fix unstable tests: use the free port calculation instead of fixed value because the  `1340` port sometimes can be busy.

Async predicate for request filter rules

---

@types/map-reverse/index.d.ts
src/api/test-run-tracker.d.ts
src/index.js
src/runner/index.js
src/runner/interfaces.ts
src/services/compiler/host.ts
src/services/compiler/protocol.ts
src/services/compiler/service.ts
src/services/compiler/test-run-proxy.ts
src/services/process-title.ts
src/services/serialization/prepare-options.ts
src/services/serialization/test-structure.ts
src/services/utils/ipc/proxy.ts
test/functional/fixtures/compiler-service/test.js
test/functional/fixtures/compiler-service/testcafe-fixtures/client-function-in-assertions.js

Changes:
* processes have clear titles (for debug purposes)
* ReExecutablePromise (ClientFunction and Selector results) executed into the service process
* typings and refactoring

[compiler service process] Support client function in assertions

---

.publishrc
package.json
src/client/driver/driver.js
test/client/before-test.js
test/client/data/dom-utils/iframe.html
test/client/data/focus-blur-change/iframe.html
test/client/data/runner/iframe.html
test/client/fixtures/core/request-barrier-test.js
test/client/legacy-fixtures/cross-domain/in-iframe-test.js
test/client/legacy-fixtures/cross-domain/run-test.js
test/client/legacy-fixtures/runner-base-test.js
test/client/legacy-fixtures/runner-test.js

* update testcafe version to 1.12.1-alpha.1
* update hammerhead version to 19.4.2
* get rid of the `hammerhead.get` method usage in tests

chore: bump 1.12.1-alpha.1

---

CHANGELOG.md
docs/articles/blog/2021-03-03-testcafe-v1-12-0-released.md
docs/articles/blog/2021-2-15-testcafe-v1-11-0-released.md
docs/articles/documentation/reference/command-line-interface.md
docs/articles/documentation/reference/configuration-file.md
docs/articles/documentation/reference/testcafe-api/global/createtestcafe.md
docs/articles/documentation/reference/testcafe-api/runner/run.md

moves `cache` and `retryTestPages` options description from `runner.run` to `createTestCafe`

[docs] Move options from runner.run to createTestCafe

---

package.json

* Support Edge on Linux (DevExpress/testcafe-browser-tools#210)
* Disable Occlusion Tracking for Chromium using the `--disable-backgrounding-occluded-windows` flag (DevExpress/testcafe-browser-tools#211)

chore: bump testcafe-browser-tools@2.0.15

---

src/client/ui/styles.less

Transforming the main document element is a rare and mostly synthetic scenario.
However, we should protect the root element of our Shadow UI subsystem from transformation.
I make it similar to the `transition` CSS property.

fix 'documentElement.transform.translate moves the TestCafe UI ' (close #5606)

---

src/client-functions/selectors/add-api.js
src/test-run/debug-log.js
test/functional/fixtures/api/es-next/assertions/test.js
test/functional/fixtures/api/es-next/assertions/testcafe-fixtures/assertions-test.js

We should throw a warning in any case when we get into the `createPrimitiveGetterWrapper` function. We can get into it in two cases:
- console.log() - internally uses util.inspect
- type conversion, such as `${a}`
If we are inside the wrapper, this means that we should add a warning.
However, there is a specific moment, that TestCafe uses `inspect` internally and in this case we should not add any warning, so I added the `isTestCafeInspect` parameter into TestCafe inspect call.

Do not supress missing await warnings (closes #5554)

---

package.json
src/live/bootstrapper.js
src/live/test-runner.js
src/runner/bootstrapper.ts
src/runner/browser-job.ts
src/runner/index.js
src/runner/interfaces.ts
src/runner/task/index.ts
src/runner/test-run-controller.ts
src/services/compiler/service.ts
src/services/compiler/test-run-proxy.ts
src/services/interfaces.ts
src/test-run/index.js
src/testcafe.js
test/functional/fixtures/live/test.js
test/server/bootstrapper-test.js
test/server/browser-job-test.js
test/server/capturer-test.js
test/server/compiler-test.js
test/server/configuration-test.js
test/server/error-handle-test.js
test/server/execute-async-expression-test.js
test/server/live-test.js
test/server/multiple-windows-test.js
test/server/reporter-test.js
test/server/runner-test.js
test/server/test-controller-events-test.js
test/server/test-controller-test.js
test/server/test-run-request-handler-test.js
test/server/test-run-tracker-test.js

Changes:
* Combine multiple constructor parameters to a single object for `Bootstrapper`, `BrowserJob`, `Runner`, and etc. classes.
* Pass `compilerService` to the `TestRun` class.

Combine multiple constructor parameters

---

package.json
src/api/request-hooks/hook.ts
src/api/request-hooks/interfaces.ts
src/api/request-hooks/request-logger.ts
src/api/request-hooks/request-mock.ts
src/runner/index.js
src/test-run/index.js
test/server/custom-client-scripts-test.js
test/server/request-hooks-test.js

Changes:
* use the `RequestFilterRuleInit` class from the `testcafe-hammerhead` module
* refactor request hooks initialization

Refactor request hooks

---

@types/replicator/index.d.ts
src/services/serialization/replicator/create-replicator.ts
src/services/serialization/replicator/custom-error-transform.ts
src/services/utils/ipc/message.ts
src/services/utils/ipc/proxy.ts
test/server/data/ipc-proxy/transport.js
test/server/ipc-message-test.js

Changes:
* use `replicator` to decode/encode data between processes.
* create transformer for custom errors. The built-in errors are processed by the built-in replicator's transfromer.
* add typings to the `replicator` module

Improve data serialization between processes (main and service)

---

package.json
src/api/request-hooks/hook.ts
src/api/request-hooks/request-mock.ts
src/custom-client-scripts/client-script-init.ts
src/custom-client-scripts/client-script.ts

Changes:
* use `RequestFilterRule.id` inside of `RequestMock` class
* correct typings

Use rule.id in request mock

---

src/client/rollup.config.js

Fixes these nasty warnings: https://travis-ci.com/github/DevExpress/testcafe/jobs/494041508#L282

fix: eliminate rollup warnings about parsing TypeScript code

---

package.json
src/api/request-hooks/hook.ts
src/api/request-hooks/request-mock.ts
test/functional/fixtures/api/es-next/request-hooks/testcafe-fixtures/request-logger/api.js

Changes:
* `RequestEvent.setMock`, `RequestHook._onConfigureResponse` methods became asynchronous.
*  Remove one assertion from the `Request Logger -> API` test because in some environments browser responds with `200` HTTP status code instead of `304`. I do this to avoid conditional logic for the expected result. The test checks the API of the RequestLogger and doesn't connect with HTTP status codes.

`RequestEvent.setMock' method becomes asynchronous

---

src/api/test-controller/index.js
src/client/automation/index.js
src/client/automation/playback/dispatch-event.js
src/client/automation/playback/dispatch-event.ts
src/client/driver/command-executors/execute-action.js
src/test-run/commands/actions.js
src/test-run/commands/type.js
test/functional/fixtures/api/es-next/dispatch-event/pages/drag.html
test/functional/fixtures/api/es-next/dispatch-event/pages/index.html
test/functional/fixtures/api/es-next/dispatch-event/test.js
test/functional/fixtures/api/es-next/dispatch-event/testcafe-fixtures/index.js
test/server/data/test-controller-reporter-expected/index.js
test/server/test-controller-events-test.js
ts-defs-src/test-api/test-controller.d.ts

**t.dispatchEvent method**
Dispatches an event over a specified webpage element.
Has the following params:
- selector - Identifies the EventTarget element. (required)
- eventName - The name of the event to be dispatched on the DOM element. (required)
- options - The options which will be passed to EventConstructor. (optional)
For mouse/drag events - MouseEvent constructor is called
For input events (beforeinput, input) - InputEvent constructor is called
For keayboard events - KeyboardEvent constructor is called
For focus events - FocusEvent constructor is called
For pointer events - PointerEvent constructor is called
For any other events the `CustomEvent` constructor is called.
If the `eventConstructor` property is passed throuth the options, then the `eventConstructor` Ctor is called.
By …

t.dispatchEvent method

---

Gulpfile.js
test/functional/fixtures/compiler-service/test.js
test/functional/fixtures/compiler-service/testcafe-fixtures/basic-test.js
test/functional/fixtures/compiler-service/testcafe-fixtures/error-test.js

We will add tests to the `MIGRATE_ALL_TESTS_TO_COMPILER_SERVICE_GLOB` as soon the corresponding part of functionality will be supported for the `compiler service` mode.
We will drop this glob after all tests are moved to compiler service.
TestCafe instance is created on the first test run. At this moment the current `process.env` is copied to the spawn service process.
Respectively, the `process.env.TESTCAFE_PID` should be created before the first executed test it is passed to the service process. So, the `test/functional/fixtures/compiler-service` should be run before all tests to the `await t.expect(String(process.ppid)).eql(process.env.TESTCAFE_PID);` is passed. I remove this condition to get rid of the fixed test execution order.

Migrate tests to compiler service mode (close #6050)

---

package.json
src/api/request-hooks/request-mock.ts
src/services/compiler/host.ts
src/services/compiler/protocol.ts
src/services/compiler/service.ts
src/services/compiler/test-run-proxy.ts
src/test-run/index.js
test/functional/fixtures/api/es-next/request-hooks/pages/api/change-remove-response-headers.html
test/functional/fixtures/api/es-next/request-hooks/test.js
test/functional/fixtures/api/es-next/request-hooks/testcafe-fixtures/api/change-remove-response-headers.js
test/functional/fixtures/compiler-service/test.js
test/functional/site/server.js

Changes:
* support `ConfigureResponseEvent.setHeader`, `ConfigureResponseEvent.removeHeader` methods
* refactor usage of the `ConfigureResponseEvent.opts`

Support of the RequestHook._onConfigureResponse event (final)

---

Gulpfile.js
test/server/test-run-commands-test.js

Close https://github.com/DevExpress/testcafe/issues/6162.

Fix server tests with Node.js v16

---

package.json
test/functional/fixtures/api/es-next/iframe-switching/pages/index.html
test/functional/fixtures/api/es-next/iframe-switching/test.js
test/functional/fixtures/api/es-next/iframe-switching/testcafe-fixtures/iframe-switching-test.js

Switching to an iframe with the srcdoc attribute works incorrectly. After switch to such iframe, the following error occurs: `Content of the iframe in which the test is currently operating did not load.`. This error can be avoided by adding timeout, but switching won't happen actually (and because of that the element inside the iframe is shown as invisible in #6033).
Add the functional test for the fix on hammerhead side (https://github.com/DevExpress/testcafe-hammerhead/pull/2618)
fixes #6033

fix: switching to an iframe with the srcdoc attr

---

ts-defs-src/runner-api/runner-api.d.ts

Fix bug
Correction of an error when passing a parameter disableScreenshots 
Closes #5735

fix: added disableScreenshots in RunOptions interface

---

src/runner/browser-job.ts
test/functional/fixtures/regression/gh-5207/pages/index.html
test/functional/fixtures/regression/gh-5207/test.js
test/functional/fixtures/regression/gh-5207/testcafe-fixtures/index.js

if we have `disablePageReloads` enabled and the next test is from next fixture, then we need to wait until all reporters finished to prevent redirecting to the `idle` page

fix TestCafe hangs during TestCafe Studio tests (closes #5207)

---

src/compiler/babel/load-libs.js
src/compiler/test-file/formats/es-next/compiler.js
test/server/compiler-test.js
test/server/runner-test.js

Some issues with the server tests occurred after Babel updated to v7.14.0 (2021-04-29).
Related change with the updated error message ("Missing semicolon.", additional dot at the end) - https://github.com/babel/babel/pull/13130
Related change with the warning about using the 'loose' option - https://github.com/babel/babel/pull/13091

test: fix server tests after Babel update

---

test/functional/fixtures/regression/gh-3904/test.js

This is attempt to fix 3904 flaky test. The cause of the issue is unclear. 
I remember, that I added timeout intentionally to emulate real scenario. However, it looks like that the test is still correct if remove timeout and add button click. Thus, the test will fail if I remove hammerhead changes, a it passes with hammerhead changes.
So I think, it will be enough to modify the tests a bit.
**UPD**
We decided to skip this test

attemp to fix flaky gh-3904 test

---

package.json
src/client/automation/index.js.wrapper.mustache
src/client/core/index.js.wrapper.mustache
src/client/driver/index.js.wrapper.mustache
src/client/ui/index.js.wrapper.mustache
test/functional/fixtures/api/es-next/hooks/test.js
test/functional/fixtures/api/es-next/scroll/test.js
test/functional/fixtures/hammerhead/gh-2622/pages/iframe.html
test/functional/fixtures/hammerhead/gh-2622/pages/index.html
test/functional/fixtures/hammerhead/gh-2622/test.js
test/functional/fixtures/hammerhead/gh-2622/testcafe-fixtures/index.js

Related to https://github.com/DevExpress/testcafe-hammerhead/pull/2623.
Remove injected `script-hammerhead-shadow-ui` head scripts from DOM.

Remove injected head scripts

---

src/errors/is-internal-stack-frame.ts
test/functional/fixtures/api/es-next/assertions/test.js
test/functional/fixtures/regression/gh-6205/test.js
test/functional/fixtures/regression/gh-6205/testcafe-fixtures/source-map-support/index.js
test/functional/fixtures/regression/gh-6205/testcafe-fixtures/testcafe-hammerhead/index.js

After migration to GH Actions, the functional test in HH started to fail constantly (the test named "Should raise multiple warnings when awaiting multiple selector properties in one assertion"). It started to fail because the path to the test on CI looks like
> /home/runner/work/testcafe-hammerhead/testcafe/test/functional/**/*/assertions-test.js
Because the path contains "testcafe-hammerhead" and we're filtering stack traces containing such substring, stack traces in the warning messages were filtered, and they became identical. When adding a warning to the warning log we remove duplicates. So, the test showed only one warning instead of two and failed.
Check that filename in a stack trace contains the full path to the "testcafe-hammerhead" or "source-map-support" packages.
Part of #6205

fix: incorrect stack trace filtering for internal packages

---

Gulpfile.js
gulp/helpers/promisify-stream.js
src/api/request-hooks/hook.ts
src/api/request-hooks/request-logger.ts
src/runner/test-run-controller.ts
src/services/compiler/host.ts
src/services/compiler/protocol.ts
src/services/compiler/service.ts
src/services/compiler/test-run-proxy.ts
src/services/interfaces.ts
src/test-run/index.js
test/functional/fixtures/api/es-next/request-hooks/testcafe-fixtures/api/add-remove-request-hook.js
test/functional/fixtures/compiler-service/test.js
test/server/capturer-test.js

Changes:
* support `t.addRequestHook` and `t.removeRequestHook` methods
* move the `promisifyStream` function from the `Gulpfile.js`

feat: support request hooks (final)

---

src/client/driver/driver.js
src/configuration/types.ts
src/reporter/command/command-formatter.ts
src/reporter/command/interfaces.ts
src/test-run/commands/actions.js
src/test-run/commands/options.js
src/test-run/commands/service.js
src/test-run/commands/type.js
src/test-run/index.js
src/tsconfig.json
src/utils/is-password-input.ts
test/functional/fixtures/reporter/pages/index.html
test/functional/fixtures/reporter/reporter.js
test/functional/fixtures/reporter/test.js
test/functional/fixtures/reporter/testcafe-fixtures/index-test.js
test/server/test-run-commands-test.js
ts-defs-src/test-api/action-options.d.ts
ts-defs-src/test-api/test-controller.d.ts

Values typed into input[type=password] should be replaced by a placeholder before sending action logs with these values to a reporter. Also the `pressKey` and the `typeText` actions have the `confidential` flag. If it set to 'true', then any typed text & pressed keys would be replaced by a placeholder in action logs.
Detect what is the target element (either specified in the `typeText` action or current active element for the `pressKey` action). If it's the input which type is 'password' or the `confidential` flag is set to true, then replace info with a placeholder.
Closes #6014

feat: mask values typed into input[type=password] in a reporter

---

Gulpfile.js
gulp/constants/functional-test-globs.js
gulp/helpers/test-functional.js
package.json
src/reporter/index.ts
src/services/compiler/host.ts
src/services/compiler/protocol.ts
src/services/compiler/service.ts
src/services/compiler/test-run-proxy.ts
src/test-run/index.js
test/functional/config.js
test/functional/fixtures/compiler-service/test.js
test/functional/fixtures/concurrency/common/timeline.js
test/functional/fixtures/concurrency/test.js
test/functional/fixtures/concurrency/testcafe-fixtures/concurrent-test.js
test/functional/fixtures/concurrency/testcafe-fixtures/multibrowser-concurrent-test.js
test/functional/fixtures/concurrency/testcafe-fixtures/sequential-test.js

Changes:
* Gulpfile.js: move the `testFunctional` function to the separate file.
* Rewrite the `src/reporter/index.ts` file to TypeScript.
* Rewrite the `concurrent-test.js` tests to make them work in the compiler service mode.
* Support fixture before/after in the compiler service mode.

refactor: support fixture before/after in the compiler service mode

---

src/browser/provider/built-in/dedicated/firefox/create-temp-profile.ts
test/functional/fixtures/regression/gh-3127/pages/dummy.xml
test/functional/fixtures/regression/gh-3127/pages/index.html
test/functional/fixtures/regression/gh-3127/test.js
test/functional/fixtures/regression/gh-3127/testcafe-fixtures/index-test.js
test/functional/site/server.js

A dialogue box appears each time the test runs downloading XML.
Need to find reasons and resolve the problem.
- added browser.download.viewableInternally.typeWasRegistered.<type> params for user.js
- added creating handlers.json in user profile
- added new XML file and test downloading one
Part of https://github.com/DevExpress/testcafe/issues/5892

feat: added settings for downloading files in firefox without dialogue box

---

test/functional/fixtures/api/es-next/scroll/pages/event-properties.html
test/functional/fixtures/api/es-next/scroll/testcafe-fixtures/event-properties.js

The previous version of the test was flaky due to a scroll lag (most likely). Moreover, it didn't test events initiated by the scroll action, since the cursor wasn't properly positioned and all events in the tests were actually raised by the `MouseMove` action. 
I forced the vertical cursor alignment by using an additional first step and the `offsetX` option. It should fix both issues.

test: rewrite the "Events initiated by scroll should have valid properties" test

---

src/cli/argument-parser.ts
src/errors/runtime/templates.js
src/runner/index.js
src/utils/get-options/quarantine.ts
test/server/cli-argument-parser-test.js
test/server/runner-test.js
ts-defs-src/runner-api/runner-api.d.ts

Fix parsing CLI issue: `testcafe -q chrome test.js`, `testcafe chrome -q test.js`.
Modifying CLI arguments before parsing. Additional changes: added quarantine option validation to non-CLI interfaces.

fix: fixed a parsing issue that caused by empty quarantine mode arguments (closes #6231)

---

src/client/automation/playback/press/utils.js
src/client/core/utils/dom.js
test/functional/fixtures/regression/gh-4848/pages/index.html
test/functional/fixtures/regression/gh-4848/test.js
test/functional/fixtures/regression/gh-4848/testcafe-fixtures/index.js

This PR fixes special case when the current active element has `tabIndex` < 0.
In this case we should not sort all possible focus targets by tabIndex, but just need to focus next/previous sibling.
There is a specific case if the element with `tabIndex` < 0 is last element of all focusable elements. In this case we need to focus first element which does not have specified tabIndex.

fix focus if activeElement has negative tabIndex (closes #4848)

---

README.md

Add new contributors:
https://github.com/Aleksey28
https://github.com/kisrefod
https://github.com/rob4629 - https://github.com/DevExpress/testcafe/pull/6073
Edit text file

[docs] Add New Contributors to readme

---

src/runner/index.js

Fix error when running on MacOs. The error occurs when trying to run the browser check.
Change context for calling _hasLocalBrowsers in _checkRequiredPermissions
https://github.com/DevExpress/testcafe/issues/6244

fix: changed context for calling _hasLocalBrowsers in _checkRequiredPermissions

---

package.json
src/cli/argument-parser.ts
test/server/cli-argument-parser-test.js

Changes:
* remove `experimental` options group
* mark the `--disable-multiple-windows` option as regular because it is described as regular in the [documentation](https://testcafe.io/documentation/402639/reference/command-line-interface#--disable-multiple-windows).
We used the `experimental` options group to hide them from the `testcafe --help` command. The `commander` module has a problem with parsing `experimental` options. We fix the problem using another approach to hide `experimental` options from help - `Option.hideHelp()` method. The test is not necessary since we remove the code that causes the problem.

fix: experimental option parsing in cli

---

src/compiler/compile-client-function.js
test/server/compiler-test.js
test/server/data/client-fn-compilation/performance/index.js

Based on https://github.com/DevExpress/testcafe/pull/6290
Changes:
* load babel configuration for the `compileClientFunction` function only 1 time.
* add a performance test (before it takes 15 sec, after - 3 sec).

perf: speed up Babel compilation (close #6284)

---

test/functional/assertion-helper.js
test/functional/fixtures/video-recording/test.js

Changes:
* fix glob pattern for the recorded videos (connected to https://github.com/DevExpress/testcafe/pull/6321)
* fix expected values in the case when tests run during the `test-functional-local` task.

Fix video recording tests under Windows

---

src/client/driver/driver-link/iframe/parent.js
src/client/driver/driver-link/messages.js
src/client/driver/driver.js
src/client/driver/iframe-driver.js
src/utils/in-cross-domain-iframe.ts
test/functional/fixtures/regression/gh-4232/pages/cross-domain-page.html
test/functional/fixtures/regression/gh-4232/pages/iframe.html
test/functional/fixtures/regression/gh-4232/pages/index.html
test/functional/fixtures/regression/gh-4232/test.js
test/functional/fixtures/regression/gh-4232/testcafe-fixtures/index-test.js

TestCafe hangs when click in an iframe redirects to a page on a different domain. It occurs due to the cross-origin iframe's driver not able to read the pending actions from the `ContextStorage` of its parent and because of that the driver doesn't send the "ready" driver status and TestCafe hangs.
In the cross-domain iframe we should check that the parent doesn't have pending actions as well. Because the iframe and its parent with different origins doesn't share a common `sessionStorage` (its used under the hood of `ContextStorage`), we should send the message to check if there're some pending actions in the parent's driver.
Fixes #4232

fix: hangs in an iframe when it redirects to a cross-domain site

---

src/client/core/utils/dom.js
test/client/fixtures/automation/press-test.js

for some reason `getAttribute('tabIndex')` does not work for svg elements in Chrome/FF (without TestCafe as well).
However, if we change `tabIndex` to `tabindex` it works as expected.
This case can be reproduced only if the `tabIndex` attribute is set declaratively in HTML markup.
In we set attribute using the `setAttribute` method, then `getAttribute('tabIndex')` works as well.
APPROACH:
change `getAttribute('tabIndex')` to `getAttribute('tabindex')`
In tests I create svg element using the `innerHTML` property of parent div element intentionally, because of the problem I described above.
NOTE:
IE11 does not allow to focus SVG even with tabIndex

fix focusing of svg element with tabIndex

---

test/functional/fixtures/regression/gh-4472/pages/index.html
test/functional/fixtures/regression/gh-4472/test.js
test/functional/fixtures/regression/gh-4472/testcafe-fixtures/index.js

The DX Lookup search field loses focus and stays empty because the `focus` method is called on a not focusable element and HH sends an extra `blur` event to an active element (input).
Add functional test for the fix on HH side (https://github.com/DevExpress/testcafe-hammerhead/pull/2635)
#4472

test: typeText should work with the DX Lookup search field

---

src/client/automation/playback/press/utils.js
src/client/core/utils/dom.js
test/client/fixtures/automation/tab-emulation-test.js
test/functional/fixtures/regression/gh-4988/pages/frame1.html
test/functional/fixtures/regression/gh-4988/pages/frame2.html
test/functional/fixtures/regression/gh-4988/pages/index.html
test/functional/fixtures/regression/gh-4988/test.js
test/functional/fixtures/regression/gh-4988/testcafe-fixtures/index.js

- support of shadow dom elements.
- modification of the elements sorting algorithm
- fix focusing elements inside the iframes
I build the tree of focusable elements, where child nodes are grouped by tabIndex.
See the `buildFocusableTree` and the `flattenFocusableTree` methods.
I completely removed the `sortElementsByFocusingIndex` method, because the focusable tree approach does not need this.
I added client test for focusing shadow dom elements.
Moreover, I added functional test for focusing iframe elements. It looks like this case did not work and unfortunatelly we do not have enough tests to test iframe focusing.

support focus for elements inside shadowDom (closes #4988)

---

package.json
src/notifications/warning-message.ts
src/test-run/index.ts
src/test-run/phase.ts
test/functional/fixtures/api/es-next/assertions/test.js
test/functional/fixtures/regression/gh-4613/common/method-with-failed-assertion.js
test/functional/fixtures/regression/gh-4613/executed-test-info.js
test/functional/fixtures/regression/gh-4613/test.js
test/functional/fixtures/regression/gh-4613/testcafe-fixtures/first.js
test/functional/fixtures/regression/gh-4613/testcafe-fixtures/last.js
test/functional/fixtures/regression/gh-4613/testcafe-fixtures/middle.js

Changes:
* don't raise an error if it occurred after test function execution.
* add a warning message about assertion placed into the unawaited method

fix: ExternalAssertionLibraryError when assertion gets failed in testcafe (close #4613)

---

src/client-functions/selectors/add-api.js
test/functional/fixtures/api/es-next/selector/test.js
test/functional/fixtures/api/es-next/selector/testcafe-fixtures/selector-test.js
ts-defs-src/test-api/node-snapshot.d.ts
ts-defs-src/test-api/selector.d.ts

Our `getAttribute`'s returned value is not consistent with [`Element.getAttribute()`](https://developer.mozilla.org/en-US/docs/Web/API/Element/getAttribute).
Return `null` for nonexistent attributes due to 
https://developer.mozilla.org/en-US/docs/Web/API/Element/getAttribute#non-existing_attributes,
https://dom.spec.whatwg.org/#dom-element-getattribute.

fix: fixed getAttribute return value (closes #5984)

---

gulp/constants/functional-test-globs.js
src/api/test-controller/index.js
src/api/test-run-tracker.ts
src/client/driver/driver.js
src/runner/bootstrapper.ts
src/services/compiler/host.ts
src/services/compiler/interfaces.ts
src/services/compiler/protocol.ts
src/services/compiler/service.ts
src/services/compiler/test-run-proxy.ts
src/services/interfaces.ts
src/services/serialization/prepare-options.ts
src/services/serialization/replicator/create-replicator.ts
src/services/serialization/replicator/transforms/command-base-trasform/command-constructors.ts
src/services/serialization/replicator/transforms/url-transform.ts
src/test-run/commands/actions.d.ts
src/test-run/commands/actions.js
src/test-run/index.ts
src/utils/async-filter.ts
src/utils/parse-file-list.js
test/functional/fixtures/regression/gh-2846/pages/index.html
test/functional/fixtures/regression/gh-2846/testcafe-fixtures/index.js

Changes:
* improve serialization of `URL` class
* rename `SwitchToWindowByPredicateCommand.findWindow` -> `SwitchToWindowByPredicateCommand.checkWindow`
* add `asyncFilter` function
* other refactorings

refactor: partial support of multiple windows tests in compiler service

---

src/cli/argument-parser.ts
test/server/cli-argument-parser-test.js

[closes DevExpress/testcafe#6426]
Add allowing unknown options in the CLI
1. Add a test with the setting an unknown option in CLI
2. Call method allowUnknownOption
https://github.com/DevExpress/testcafe/issues/6426

fix: added allowing unknown options

---

src/configuration/testcafe-configuration.ts
src/runner/index.js
test/server/configuration-test.js
test/server/runner-test.js

[closes DevExpress/testcafe#6420]
Fixed overwriting the quarantine mode if the config file is used
1. Add a test with setting the quarantine mode and creating the config file
2. Remove a repeat config initialization
https://github.com/DevExpress/testcafe/issues/6420

fix: fixed overwriting the quarantine mode if the config file is used

---

package.json
src/compiler/compilers.js
src/compiler/index.js
src/compiler/test-file/api-based.js
src/compiler/test-file/formats/typescript/compiler.ts
src/configuration/typescript-configuration.ts
src/services/compiler/host.ts
src/services/compiler/service-loader.ts
src/services/compiler/service.ts
test/functional/fixtures/regression/gh-6205/test.js

The purpose: prevent renaming of imported variables by babel/typescript.
Approach: using the esm module: https://www.npmjs.com/package/esm
The problem is that the esm module is set only in the following way:
```
require = require("esm")(module/*, options*/)
module.exports = require("./main.js")
```
However, we need to rewrite default nodejs `require` function, and this leads to incorrect esm module work.
The entry point for review is: https://github.com/DevExpress/testcafe/pull/6384/files#diff-c8bc3b8eb8e44f049d51dd2956f8651d8d6dd3511a676d5933713627c9e1a9f4
In addidion, I needed to modify Typescript compiler to correctly process `require` with esm module

attempt to integrate esm module for compiler service

---

.github/workflows/deploy-to-artifacts.yml
.github/workflows/test-functional-local-debug.yml
Gulpfile.js
gulp/constants/functional-test-globs.js
gulp/helpers/test-functional.js
src/cli/argument-parser.ts
src/cli/cli.js
src/configuration/option-names.ts
src/testcafe.js
test/functional/fixtures/multiple-windows/test.js
test/functional/fixtures/multiple-windows/testcafe-fixtures/features/screenshots.js
test/functional/setup.js
test/server/cli-argument-parser-test.js

Closes https://github.com/DevExpress/testcafe/issues/6390
Changes:
* fix tests
* rename `--experimental-compiler-service` to `--experimental-debug`

refactor: fix multiple windows test in the compiler service mode

---

src/configuration/testcafe-configuration.ts
src/errors/runtime/templates.js
src/errors/types.js
test/server/configuration-test.js
test/server/create-testcafe-test.js

[closes DevExpress/testcafe#6337]
Show an error if the explicitly configuration file doesn't exist
1. Add a test with getting an error
2. Add a new error type
3. Add a condition for the existence of the configuration file
https://github.com/DevExpress/testcafe/issues/6337

feat: added verification of the existence of the configuration file

---

src/browser/provider/pool.js
test/server/browser-provider-test.js

[closes DevExpress/testcafe#6456]
Fix processing the option 'browsers' with value 'all'
1. Add test
2. Add fix
https://github.com/DevExpress/testcafe/issues/6456

fix: fixed processing the option 'browsers' with value 'all'

---

Gulpfile.js
src/runner/bootstrapper.ts
test/server/runner-test.js
ts-defs-src/runner-api/options.d.ts

I need to have freedom in using both, sync and async functions when filtering tests using the Runner object
use an asynchronous filter
https://github.com/DevExpress/testcafe/issues/6370

feat: async runner.filter predicate (#6370)

---

src/compiler/test-file/formats/es-next/get-test-list.js
src/compiler/test-file/formats/typescript/get-test-list.js
src/compiler/test-file/test-file-parser-base.js
test/server/data/test-suites/fixture-and-test-hooks/testfile.js
test/server/parse-fixture-test.js

I have opened an issue https://github.com/DevExpress/testcafe/issues/6238, and I was suggested to open a PR. The purpose is to add property of "isSkipped" when using getTypeScriptTestList / getTypeScriptTestListFromCode and getTestList / getTestListFromCode when I just want to do a static analysis without actually running the tests.
1) Add property "isSkipped" in Class Fixture, Class Test and formatFnData().
2) Add check if the test / fixture is skipped by a new function getSkippedInfo().
3) Pass the isSkipped property in analyze() for fixture and test.
_Provide a link to the existing issue(s), …

Add ability to get skipped tests when using getTestList for static analysis

---

bin/testcafe-with-v8-flag-filter.js
src/cli/argument-parser.ts
src/cli/node-arguments-filter.ts
src/configuration/option-names.ts
src/services/compiler/host.ts
src/testcafe.js
test/server/cli-argument-parser-test.js
test/server/test/server/node-arguments-filter-test.js

Closes https://github.com/DevExpress/testcafe/issues/3811.
Changes:
* pass raw v8 flags to the `lib/cli` if the `--experimental-debug` option is specified
* merge internal and passed flag before running the service process
Based on https://github.com/DevExpress/testcafe/pull/3826/.

refactor: pass v8 flags to the compiler process

---

src/configuration/default-values.ts
src/configuration/screenshot-option-names.ts
src/configuration/testcafe-configuration.ts
src/configuration/types.ts
src/runner/index.js
src/runner/task/index.ts
src/screenshots/capturer.js
src/screenshots/index.js
src/test-run/browser-manipulation-queue.js
src/test-run/commands/browser-manipulation.js
test/functional/fixtures/api/es-next/take-screenshot/test.js
test/functional/fixtures/api/es-next/take-screenshot/testcafe-fixtures/take-screenshot.js
test/server/configuration-test.js
test/server/data/test-controller-reporter-expected/index.js

Make thumbnails generation customizable when taking screenshots.
(By default, thumbnails are not generated when taking screenshots.)
- Added thumbnails to Screenshot Options for the -s (--screenshots) command line flag. (e.g. `-s thumbnails=true`)
- Added the thumbnails parameter of the screenshots API method. (e.g. `takeScreenshot({thumbnails: true})`)
resolved #1550

Don't create thumbnails by default

---

src/runner/fixture-hook-controller.ts
src/runner/task/index.ts
src/services/compiler/host.ts
src/services/compiler/interfaces.ts
src/services/compiler/protocol.ts
src/services/compiler/service.ts
src/test-run/index.ts

Changes:
* remove `testRun` from service state of compiler service at the end of the `testRun` execution in the main process.
* remove `fixtureCtx` from service state after the `fixture.after` method execution.

refactor: decrease memory usage for the debug mode

---

src/configuration/configuration-base.ts
src/configuration/testcafe-configuration.ts
src/configuration/typescript-configuration.ts
test/server/configuration-test.js

Fix reading config files
1. Add test 'Should read JS config file if JSON and JS default files exist'
2. Fix using filePath while reading configuration files
https://github.com/DevExpress/testcafe/issues/6501

fix: fixed reading config files

---

src/configuration/configuration-base.ts
src/configuration/testcafe-configuration.ts
src/configuration/typescript-configuration.ts
src/utils/get-filter-fn.js
test/server/configuration-test.js

To leave filter function from the js config without changes
1. Add test 'Shouldn't change filter option with a function'
2. Add skip changes condition for filter with any function
https://github.com/DevExpress/testcafe/issues/6501
https://teams.microsoft.com/l/message/19:ece0830172fd4073b11b897657443889@thread.skype/1630066293120?tenantId=e4d60396-9352-4ae8-b84c-e69244584fa4&groupId=c3abb0f3-231c-4d87-b5a3-44925dc1d075&parentMessageId=1630066293120&teamName=TestCafe&channelName=Support%20(Daily)&createdTime=1630066293120

fix: added condition if filter equals a function it should return the same function

---

src/cli/cli.js
src/services/compiler/host.ts

PR allows to set the port for debugging in experimental mode.
Examples:
`testcafe --inspect-brk chrome test.js` - takes free port
`testcafe --inspect chrome test.js` - takes free port
`testcafe --inspect-brk=62125 chrome test.js` - takes 62125 port
`testcafe --inspect=127.0.0.23:62125 chrome test.js` - takes 62125 port but ignores hostname
To debug testcafe internal code and experimental compiler service at the same time do the following:
`node --inspect-brk bin/testcafe chrome test.js --inspect-brk=62125`

add port argument support for experimental debug (closes #6522)

---

src/services/compiler/service.ts
test/functional/fixtures/api/coffeescript/smoke/test.js
test/functional/fixtures/api/es-next/roles/test.js
test/functional/fixtures/api/es-next/test-controller/test.js
test/functional/fixtures/api/typescript/smoke/test.js
test/functional/fixtures/regression/gh-1311/test.js
test/functional/fixtures/run-options/disable-page-caching/test.js

The main change is https://github.com/DevExpress/testcafe/pull/6542/files#diff-1f8383a36bf02f58356a4c61f8897a4d5d3349c273e565e7e2c0761435c45634R96

refactor: hack for supporting 'import { t } from testcafe' in the experimental debug mode.

---

test/functional/fixtures/api/es-next/test-structure/test.js
test/functional/fixtures/api/es-next/test-structure/testcafe-test-structure/test-structure-test.js

According to the ES modules standard, the `import attachedTest from './attached-test';` expression requires `./attached-test';` file has a default export. If it doesn't have it, we get an error message about the absence of the default export.
The module transpiler plugin of the Babel compiler is more tolerant than the ES modules standard.
So, we need just to rewrite the import statement according to the standard.

chore: fix importing tests in debug mode

---

.publishrc
package.json

Closes https://github.com/DevExpress/testcafe/issues/6561.

release: bumped version, added missing @babel/plugin-proposal-private-methods package

---

src/reporter/index.ts
test/server/reporter-test.js

[closes DevExpress/testcafe#6461]
Pass test's startTime to reporter plugin's reportTestStart
1. Add the tests for feature
2. Add sending a startTime to reporter plugin's reportTestStart
https://github.com/DevExpress/testcafe/issues/6461

feat: added test's startTime to reporter plugin's reportTestStart

---

src/runner/browser-job.ts
src/video-recorder/interfaces.ts
src/video-recorder/recorder.js
src/video-recorder/test-run-video-recorder.js
src/video-recorder/videos.ts
test/functional/fixtures/video-recording/test.js
test/server/video-recorder-test.js

JFI: TestCafe is recording video in real time. This means that we can just use Date.now() to get correct timecode.

add times codes for attempts to video in quarantine mode (closes #6478)

---

src/test-run/index.ts
test/functional/fixtures/regression/gh-2846/testcafe-fixtures/index.js

The `_enqueueSetBreakpointCommand` method is called from multiple places, so it's not suitable for emitting a warning. I moved the warning to the `_internalExecuteCommand` method.

Fix multiple debug in headless mode warnings (closes #6605)

---

src/compiler/interfaces.ts
src/live/bootstrapper.js
src/reporter/index.ts
src/runner/bootstrapper.ts
src/runner/fixture-hook-controller.ts
src/runner/index.js
src/services/compiler/host.ts
src/services/compiler/interfaces.ts
src/services/compiler/protocol.ts
src/services/compiler/service.ts
src/test-run/index.ts

Changes:
* add an `id` for a runnable configuration and remove appropriate units from service state by runnable configuration id.
* small refactoring

Improve performance of the debug mode (part 1)

---

src/runner/fixture-hook-controller.ts
src/runner/index.js
src/services/compiler/host.ts
src/services/compiler/interfaces.ts
src/services/compiler/protocol.ts
src/services/compiler/service.ts

Changes:
In some cases (browser restart, stop task on first fail, etc.), the fixture contexts may not be deleted.
We remove all fixture context at the end of test execution to clean forgotten contexts.

Debug mode optimization (part 2)

---

src/test-run/index.ts
test/functional/fixtures/regression/gh-6646/pages/index.html
test/functional/fixtures/regression/gh-6646/test.js
test/functional/fixtures/regression/gh-6646/testcafe-fixtures/index.js
test/server/test-run-error-formatting-test.js

We have two actions where we need to pass errors:
`reportTestActionDone` and `reportTestDone`.
The problem is that the error is the same in both cases, but wrapper (TestRunFormattableAdapter) is different, because we create different adapters for each of these events.
So, the approach is add to an error the `error.id` property which will be shared between different error adapters.

add error-id to formattable-adapter (closes #6646)

---

package.json
src/cli/argument-parser.ts
src/cli/cli.js
src/configuration/option-names.ts
src/reporter/index.ts
src/reporter/interfaces.ts
src/runner/index.js
src/utils/get-options/dashboard.ts
src/utils/get-options/index.ts
test/server/cli-argument-parser-test.js
test/server/configuration-test.js
test/server/runner-test.js

Integrate testcafe-reporter-dashboard with TestCafe. Develop an API.
Pass options object to the reporter via plugin constructor aguments
https://github.com/DevExpress/testcafe/issues/6657

feat: Integrate dashboard reporter (closes #6657)

---

ts-defs-src/runner-api/options.d.ts

[closes DevExpress/testcafe#6713]
Fix definitions for the testExecutionTimeout and runExecutionTimeout
Add definitions
https://github.com/DevExpress/testcafe/issues/6713

fix: added definitions for the testExecutionTimeout and runExecutionTimeout

---

src/browser/provider/built-in/dedicated/chrome/index.js
src/browser/provider/built-in/dedicated/chrome/local-chrome.js

[closes DevExpress/testcafe#6436]
Fix the error of start chromium under the docker
Create new tab after start chromium and before init
https://github.com/DevExpress/testcafe/issues/6436

fix: fixed the error of start chromium under the docker

---

src/custom-client-scripts/client-script.ts
src/errors/runtime/templates.js
src/live/test-runner.js
test/server/custom-client-scripts-test.js

Before fix
After fix
I didn't write any test because the current behavior is not good: the bootstrapping error handled by [process.on('unhandledRejection')](https://github.com/DevExpress/testcafe/blob/8815cb929ec9eb784e36c7be77df5cfd01312961/src/utils/handle-errors.js#L65) handler. The `ClientScript` error raising refactoring is a separate task. So, I just fix the error message now.

fix '"Cannot read property 'tests' of null" when using client scripts ' (close #6305)

---

src/api/test-run-tracker.ts
src/test-run/execute-js-expression/index.js
test/functional/fixtures/api/raw/code-steps/test.js
test/functional/fixtures/api/raw/code-steps/testcafe-fixtures/eval.testcafe

fix 'The t.eval() method does not work in the 'execute-async-expression' script' (close #4562)

---

src/configuration/configuration-base.ts
src/configuration/default-values.ts
src/configuration/option-source.ts
src/configuration/testcafe-configuration.ts
test/server/configuration-test.js

fix 'Testcafe wrongly shows "filter" warning' (close #6620)

---

src/browser/connection/index.ts
src/browser/provider/built-in/dedicated/chrome/index.js
src/browser/provider/index.ts

It looks like a Chrome bug. If smth deletes Chrome temp profile folders when multiple Chrome instances are running, it breaks Chrome cache and leads to ERR_CACHE_READ_FAILURE.
I found a hint here: https://stackoverflow.com/questions/36741489/err-cache-read-failure-in-google-chrome
The solution: do not remove temp profile directories when browser is restarting.
All these temp direcotries will be removed when TestCafe finishes

do not dispose temp profile on browser restart (closes #4554)

---

src/client/automation/index.js
src/client/automation/shared-adapter-initializer.ts
src/client/driver/driver-link/messages.js
src/client/driver/driver.js
src/client/driver/iframe-driver.js
test/functional/fixtures/multiple-windows/pages/i6085/iframe.html
test/functional/fixtures/multiple-windows/pages/i6085/index.html
test/functional/fixtures/multiple-windows/pages/i6085/window.html
test/functional/fixtures/multiple-windows/test.js
test/functional/fixtures/multiple-windows/testcafe-fixtures/i6085.js

solution:
If we switch to the new window from an iframe we should call `stopInternal` not in the iframe driver but parent driver

fix browser hanging when the test switches between windows after switching to iframe (closes #6085)

---

src/role/role.ts
src/test-run/bookmark.ts
test/functional/fixtures/concurrency/pages/first-page.html
test/functional/fixtures/concurrency/pages/second-page.html
test/functional/fixtures/concurrency/test-info.js
test/functional/fixtures/concurrency/test.js
test/functional/fixtures/concurrency/testcafe-fixtures/concurrent-test.js
test/functional/fixtures/concurrency/testcafe-fixtures/multibrowser-concurrent-test.js
test/functional/fixtures/concurrency/testcafe-fixtures/role-test.js
test/functional/fixtures/concurrency/testcafe-fixtures/sequential-test.js
test/functional/fixtures/concurrency/timeline.js
test/server/ipc-serialization-test.js

[closes DevExpress/testcafe#6041]
Fix the incorrect URL of the page visited when running tests in parallel in the same file with the role. 
This is because right now one role can only store one `redirectUrl`. And when we use one role in two and more tests with concurrency mode `redirectUrl` is rewritten in one test before the redirect occurs in another one.
1. Add the tests to fix
2. Add keeping redirect URL in the Role for each test
https://github.com/DevExpress/testcafe/issues/6041

fix: fixed incorrect Page URL visited when running tests in parallel in one file with Role

---

src/client/ui/select-element.js
test/functional/fixtures/regression/gh-5616/pages/index.html
test/functional/fixtures/regression/gh-5616/test.js
test/functional/fixtures/regression/gh-5616/testcafe-fixtures/index.js

[closes DevExpress/testcafe#5616]
The ability to describe requests hooks for all tests.
1. Add the tests to fix
2. Add conditions for not expanding disabled select
https://github.com/DevExpress/testcafe/issues/5616

fix: fixed expanding disabled select

---

src/client/core/utils/shared/types.d.ts
src/client/core/utils/shared/visibility.ts
test/functional/fixtures/regression/gh-3495/pages/index.html
test/functional/fixtures/regression/gh-3495/test.js
test/functional/fixtures/regression/gh-3495/testcafe-fixtures/index.js

[closes DevExpress/testcafe#3495]
SVG elements without visibility properties should be checked correctly depending on parent elements.
1. Add the tests to fix
2. Add checking parent elements of the SVG
https://github.com/DevExpress/testcafe/issues/3495

fix: fixed incorrect check visibility of an SVG element in a hidden element

---

gulp/constants/functional-test-globs.js
gulp/helpers/test-functional.js

Now, the screenshot tests run in both tasks (`test-functional-local-debug-1`, `test-functional-local-debug-2`)

Run screenshot tests only for the 'test-functional-local-debug-1' task

---

src/browser/provider/built-in/dedicated/chrome/local-chrome.js
src/compiler/test-file/test-file-parser-base.js
test/server/parse-fixture-test.js

We try to get a tabs list of the browser until errors are disappeared. But errors are appearing while the browser isn't ready. After that, the browser in docker doesn't have enough time to get the list of tabs.
Try to get the list of the tabs while it is empty.
Additionally refactored tests with checking parsed files with tests because babel added a new property 'index' for parsed files.
https://teams.microsoft.com/l/message/19:5eb4e942f0f946188ab14b3d8bf960f3@thread.skype/1641979833965?tenantId=e4d60396-9352-4ae8-b84c-e69244584fa4&groupId=f74b7d18-34a4-4c78-b7d5-b56e55ce3236&parentMessageId=1641979833965&teamName=Teams%20Collaborations&channelName=TestCafe&createdTime=1641979833965

fix: added condition to repeat getting tab list while it is empty

---

gulp/constants/client-test-settings.js
test/client/fixtures/automation/automations-test.js
test/client/fixtures/automation/click-test.js
test/client/fixtures/automation/content-editable/api-actions-content-editable-test/index-test.js
test/client/fixtures/automation/content-editable/select-and-type-content-editable-test/index-test.js
test/client/fixtures/automation/drag-test.js
test/client/fixtures/automation/select-element-test.js
test/client/fixtures/automation/select-test/index-test.js
test/client/fixtures/automation/type-test.js

Closes https://github.com/DevExpress/testcafe/issues/6736
Changes:
* turn off few tests
* increase test timeouts (iPhone emulator is very slowly)
* change assertion to prevent unclear error messages

Update Safari versions for client tests

---

.publishrc
package.json

fix: preserve output to stderr and stdout when spinner is active

---

test/functional/fixtures/api/es-next/cookies/test.js
test/functional/fixtures/api/es-next/cookies/testcafe-fixtures/cookies-test.js

Implement synchronization of changing cookies with the client
Only add tests for synchronization changed cookies with the client and adapt the old one. The functionality itself has been implemented in the hammerhead.
[First part](https://github.com/DevExpress/testcafe/pull/6841)
[Corresponding PR in the hammerhead](https://github.com/DevExpress/testcafe-hammerhead/pull/2741)

feat: added cookies API (2 part)

---

src/configuration/configuration-base.ts
src/testcafe.js
test/server/configuration-test.js

[closes DevExpress/testcafe#6945]
Global request loggers are cloned with configuration during the creating runner. It is the reason why we can't get any results from the global loggers in tests.
1. Add tests for the cloning testcafe configuration
2. Add recovering the hooks after the cloning configuration during the creating runner
https://github.com/DevExpress/testcafe/issues/6945

fix: fixed working of the global request logger 

---

src/browser/connection/gateway.ts
src/browser/connection/index.ts
src/browser/provider/built-in/dedicated/base.js
src/browser/provider/built-in/dedicated/chrome/cdp-client/index.ts
src/browser/provider/index.ts
src/browser/provider/plugin-host.js
src/client/browser/index.js
src/client/driver/driver.js
src/client/test-run/index.js.mustache
src/test-run/index.ts
test/functional/fixtures/multiple-windows/test.js
test/functional/fixtures/multiple-windows/testcafe-fixtures/i6037.js

fix: avoid browser hanging on close window while video is recording (closes #6037)

---

src/client/automation/playback/click/click-command.js
test/functional/fixtures/regression/gh-6949/pages/with-button.html
test/functional/fixtures/regression/gh-6949/pages/with-div.html
test/functional/fixtures/regression/gh-6949/pages/with-link-without-href.html
test/functional/fixtures/regression/gh-6949/pages/with-link.html
test/functional/fixtures/regression/gh-6949/test.js
test/functional/fixtures/regression/gh-6949/testcafe-fixtures/with-button.js
test/functional/fixtures/regression/gh-6949/testcafe-fixtures/with-div.js
test/functional/fixtures/regression/gh-6949/testcafe-fixtures/with-link-without-href.js
test/functional/fixtures/regression/gh-6949/testcafe-fixtures/with-link.js

Previously, we were forced to change the checked state of a checkbox when clicking on a label in the Chrome browser due to the following issue: https://github.com/DevExpress/testcafe/issues/3348
As a result, the checked state changes even if the link or button inside the label is clicked(https://github.com/DevExpress/testcafe/issues/6949). This behavior differs from the native behavior of the browser.
Add element tag checking.
https://github.com/DevExpress/testcafe/issues/6949
https://github.com/DevExpress/testcafe/issues/3348

Prevent chrome from changing checkbox checked state when button or link located inside the label is clicked(closes #6949)

---

src/client/automation/playback/click/click-command.js
test/functional/fixtures/regression/gh-6949/pages/with-disabled-checkbox.html
test/functional/fixtures/regression/gh-6949/test.js
test/functional/fixtures/regression/gh-6949/testcafe-fixtures/with-disabled-checkbox.js

The same as in the following PR: [6950](https://github.com/DevExpress/testcafe/pull/6950). But in this case, we should prevent the **disabled** checkbox from changing the checked state.
Add checkbox disabled state checking.
https://github.com/DevExpress/testcafe/issues/6949
https://github.com/DevExpress/testcafe/pull/6950

Prevent chrome from changing checkbox checked state when disabled checkbox label is clicked(closes #6949)

---

package.json

Resolves https://snyk.io/vuln/SNYK-JS-MOMENT-2440688
moment.js' latest updates resolve this issue
[_Provide a link to the existing issue(s), if any._](https://github.com/moment/moment/security/advisories/GHSA-8hfj-j24r-96c4)
Unable to fully verify that tests are still passing. I run TestCafe in a arm64 Linux VM under a M1 macbook and `chrome:headless` is not available for it.  
Other tests that run are still passing. Hoping a CI would pick up anything wrong.

Updated moment.js to resolve https://snyk.io/vuln/SNYK-JS-MOMENT-2440688

---

src/test-run/index.ts
test/functional/fixtures/api/es-next/global-hooks/data/execution-flow-config.js
test/functional/fixtures/api/es-next/global-hooks/test.js
test/functional/fixtures/api/es-next/global-hooks/testcafe-fixtures/flow-info-test.js
test/functional/fixtures/api/es-next/global-hooks/utils/flow-info-storage.js
test/functional/fixtures/api/es-next/hooks/test.js
test/functional/utils/file-storage.js

Changes:
* change execution order of the `localTestAfter` and `globalTestAfter` hooks.
* move all tests to the root `describe('Global hooks')` function.

feat: Change execution order of global hooks (close #7005)

---

src/errors/test-run/index.js
src/errors/test-run/templates.js
src/test-run/commands/validations/argument.js
test/server/compiler-test.js
test/server/data/expected-test-run-errors/action-cookie-argument-error
test/server/data/expected-test-run-errors/action-cookie-arguments-error
test/server/data/expected-test-run-errors/action-date-option-error
test/server/data/expected-test-run-errors/action-number-option-error
test/server/data/expected-test-run-errors/action-required-cookie-arguments
test/server/data/expected-test-run-errors/action-string-option-error
test/server/data/expected-test-run-errors/action-url-cookie-argument-error
test/server/data/expected-test-run-errors/action-urls-cookie-argument-error
test/server/test-run-commands-test.js
test/server/test-run-error-formatting-test.js
ts-defs-src/test-api/action-options.d.ts
ts-defs-src/test-api/test-controller.d.ts

Add definitions of the Cookies API functionality.
1. Add interfaces for the Cookies API functionality.
2. Fix test
3. Refactor errors messages
[actionRequiredCookieArguments](https://github.com/DevExpress/testcafe/blob/e00140550089bd5ad29cdec174709720dd772590/src/errors/test-run/templates.js#L133)
[actionCookieArgumentError](https://github.com/DevExpress/testcafe/blob/e00140550089bd5ad29cdec174709720dd772590/src/errors/test-run/templates.js#L137)
[actionCookieArgumentsError](https://github.com/DevExpress/testcafe/blob/e00140550089bd5ad29cdec174709720dd772590/src/errors/test-run/templates.js#L141)
[actionUrlCookieArgumentError
](https://github.com/DevExpress/testcafe/blob/e00140550089bd5ad29cdec174709720dd772590/src/errors/test-run/templates.js#L145)[actionUrlsCookieArgumentError](https://g …

feat: added cookies API definitions

---

src/runner/index.js
test/functional/fixtures/reporter/test.js
test/functional/fixtures/run-options/stop-on-first-fail/testcafe-fixtures/stop-on-first-fail-test.js
test/server/runner-test.js

Add new conditions for showing the advertisement:
1. Add new tests and refactor previous
2. Implement conditions from purpose before showing the advertisement.
Closes https://github.com/DevExpress/testcafe-marketing/issues/392

refactor: make dashboards ads more selective

---

src/dashboard/config-storage.ts
src/runner/index.js
test/server/runner-test.js

We should send reports to the dashboard when it is not disabled explicitly. This means we should not add the dashboard reporter only if `sendReport` is strictly equal to `false`.

fix: send reports to dashboard by default

---

src/test-run/index.ts
test/functional/fixtures/api/es-next/global-hooks/test.js
test/functional/fixtures/api/es-next/global-hooks/testcafe-fixtures/flow-info-test.js
test/functional/fixtures/api/es-next/hooks/test.js

[closes DevExpress/testcafe#7049]
Fix order of the after hooks for tests. The order should be as follows:
1. If `test.after` exists run it
2. Else if `fixture.afterEach` exists run it
3. Run `global.test.after`  in any case
1. Add tests
2. Change order of the hooks
https://github.com/DevExpress/testcafe/issues/7049

release: fixed after hooks order for test

---

src/client/core/utils/position.js
src/client/core/utils/shared/visibility.ts
src/client/driver/command-executors/client-functions/adapter/initializer.ts
src/client/driver/command-executors/client-functions/selector-executor/utils.ts
src/client/driver/command-executors/client-functions/types.d.ts
src/client/driver/driver-link/iframe/child.js
src/client/driver/driver.js
src/client/proxyless/client-fn-adapter-initializer.ts
src/client/proxyless/utils/dom.ts
test/functional/fixtures/api/es-next/iframe-switching/pages/index.html
test/functional/fixtures/regression/gh-4558/pages/iframePage.html
test/functional/fixtures/regression/gh-4558/pages/index.html
test/functional/fixtures/regression/gh-4558/pages/innerIframePage.html
test/functional/fixtures/regression/gh-4558/test.js
test/functional/fixtures/regression/gh-4558/testcafe-fixtures/index.js

Some sites use invisible iframes to perform some util logic. For example: [Studio issue](https://github.com/DevExpress/testcafe-studio/issues/2881)
Remove dimensions check when switching to iframe.
Closes [#4558](https://github.com/DevExpress/testcafe/issues/4558)

Allow switching to an invisible iframe(closes #4558)

---

src/configuration/types.ts
src/runner/index.js
src/runner/task/index.ts
src/screenshots/capturer.js
src/screenshots/index.js
src/utils/create-safe-listener.ts
src/video-recorder/recorder.js
test/functional/fixtures/api/es-next/take-screenshot/test.js
test/functional/fixtures/screenshots-on-fails/test.js
test/server/capturer-test.js
test/server/runner-test.js

[closes DevExpress/testcafe-marketing#401]
To send screenshots with errors to the dashboard reporter every time.
1. Add test
2. Save screenshots to the temp directory
3. Reed screenshots from the temp directory
4. Send buffer with data to the method reporterTestDone
5. Save screenshots to the `screenshotPath` if the options `takeOnFails` was turned on
https://github.com/DevExpress/testcafe-marketing/issues/401
https://github.com/DevExpress/testcafe-reporter-dashboard/pull/90

feat: added permanent sending screenshots with errors to the dashboard reporter independent on users options

---

src/runner/index.js
test/server/runner-test.js

[closes DevExpress/testcafe#7090]
Made merging dashboard options in the correct priority
1. Added tests
2. Get storage options
3. Get config options
4. Get environment options
5. Merge options in the following order: storage options -> config options -> environment options
https://github.com/DevExpress/testcafe/issues/7090

fix: fixed merging dashboard options

---

src/runner/browser-job.ts
test/functional/fixtures/concurrency/test.js

[closes DevExpress/testcafe#7062]
Don't run tests until a task starts running.
1. Add test
2. Add waiting until a task starts running 
https://github.com/DevExpress/testcafe/issues/7062

fix: fixed start test before task starting finishes

---

README.md

Change the repo link for gherkin-testcafe in TestCafe's documentation: as referenced [here](https://github.com/kiwigrid/gherkin-testcafe) this package is now maintained [there](https://github.com/Arthy000/gherkin-testcafe)
I'm affraid that some users will stop looking into gherkin-testcafe as soon as they see "This repository has been archived by the owner. It is now read-only."
⚠️ __documentation change only__ ⚠️

update gherkin-testcafe link in documentation

---

src/client-functions/selectors/selector-builder.js
src/client/driver/driver.js
src/shared/errors/selector-error-ctor-callback.ts
src/shared/utils/elements-retriever.ts
src/test-run/commands/actions.js
src/test-run/commands/observation.d.ts
src/test-run/commands/observation.js
src/test-run/commands/validations/initializers.js
src/test-run/index.ts
test/functional/fixtures/api/es-next/type/test.js
test/functional/fixtures/api/es-next/type/testcafe-fixtures/type-test.js
test/server/test-run-commands-test.js

[closes DevExpress/testcafe#6623]
Prevent executing selector twice when it isn't available for the `typeText` command.
1. Add test
2. Skip typing text if the selector wasn't available during inspection.
https://github.com/DevExpress/testcafe/issues/6623

fix: prevented waiting element in the second time if an error was raised in the first 

---

src/reporter/index.ts
src/runner/bootstrapper.ts
test/functional/fixtures/concurrency/test.js

When running tests in concurrency mode:
- Only the last opened session link is passed to all the report errors.
- Also, only the last opened session link is passed to the report task start handler.
Previously we used the same reference of the "browserInfo" object in all the "browserConnection" objects. As a result, the browserMetaInfo was rewritten in all the "browserConnections".
After fix: Different "browserInfo" references are passed to different "browserConnections".
[Show all links to all cloud test sessions in concurrency mode #4346](https://github.com/DevExpress/testcafe/issues/4346)

Fix: Incorrect cloud provider links are shown in report errors when running test in concurrency mode(closes #4346)

---

src/screenshots/capturer.js
src/test-run/browser-manipulation-queue.js
src/test-run/commands/browser-manipulation.js
src/test-run/index.ts
test/functional/fixtures/api/es-next/take-screenshot/test.js
test/functional/fixtures/reporter/test.js
test/functional/fixtures/reporter/testcafe-fixtures/index-test.js
test/server/capturer-test.js

[closes DevExpress/testcafe#7094]
Add `actionId` to the screenshot information that helps to math screenshots and actions in the dashboard. 
1. Add test 
2. Pass `actionId` to the screenshot information
3. In the error case passe  `actionId` from original action
https://github.com/DevExpress/testcafe/issues/7094

feat: added `actionId` to the screenshot information

---

src/reporter/index.ts
test/server/reporter-test.js

[closes DevExpress/testcafe#7118]
Pass the 'fixture' object that contains `id`, `name`, `path` and `meta` to the reporter.reportTestDone method.
1. Add the `fixture` option to the `testRunInfo`
2. Fix tests
https://github.com/DevExpress/testcafe/issues/7118

feat: added the `fixture` option to the `testRunInfo` of the `reportTestDone` method

---

.publishrc
package.json
src/compiler/test-file/formats/dev-tools/compiler.ts
test/functional/fixtures/api/json/test.js
test/functional/fixtures/api/json/testcafe-fixtures/json-without-test.json

skip JSON files if they do not contain 'steps' statement

ignore json files which do not contain test/fixtures

---

src/browser/provider/built-in/dedicated/chrome/cdp-client/index.ts
src/browser/provider/built-in/dedicated/chrome/index.js
src/browser/provider/index.ts
src/browser/provider/plugin-host.js
src/video-recorder/process.js

Closes https://github.com/DevExpress/testcafe/issues/7188
Fixes:
* memory leak on running more than 11 tests
* next test contains the last video frame of the previous test

fix: 'Memory leak on running more than 11 tests' (close #7188)

---

src/errors/test-run/utils.js
test/server/util-test.js

Based on https://github.com/DevExpress/testcafe-studio/pull/4278#issuecomment-1211885391
When researching the bug, I found out that its cause is in the incorrect behavior of the `markup` utility: https://github.com/DevExpress/testcafe/blob/83ea14c7a70719c846071486632466638be03a63/src/errors/test-run/utils.js#L73
The `markup` utility does not work correctly due to the missing definition of `SUBTITLES[TEST_RUN_PHASE.pendingFinalization]`. As a result, the utility might return something like this:
```
undefined<div class="message">AssertionError: expected false to be truthy</div>
<strong>Browser:</strong> <span class="user-agent">Chrome 104.0.5112.81 / Windows 10</span>
0
```

fix: added definition for SUBTITLES[TEST_RUN_PHASE.pendingFinalization]

---

src/errors/test-run/utils.js
test/server/util-test.js

In addition to https://github.com/DevExpress/testcafe/pull/7227.
Reason: we need to make sure that the definitions for the various phases are not forgotten in the future.

test: SUBTITLES should contains defenitions of all test run phases

---

src/screenshots/index.js

Fixed studio hanging. Delete unnecessary disposing of a temp directory for screenshots, because it already happens [there ](https://github.com/DevExpress/testcafe/blob/431f048c4f6569ceb061f566863e88f740697cf9/src/utils/temp-directory/cleanup-process/worker.js#L64). If we try to remove it again process hangs of waiting response.
1. Research problem
2. Fix removing temp dir for screenshots

fix: removed unnecessary disposing a temp directory for screenshots

---

package.json
src/compiler/test-file/formats/typescript/compiler.ts
src/errors/test-run/templates.js
test/server/data/expected-test-run-errors/uncaught-js-error-on-page
ts-defs-src/test-api/test-controller.d.ts

Fix skipJsErrors API, fix TS warnings

---

src/errors/process-test-fn-error.js
src/errors/runtime/index.js
src/reporter/index.ts
test/server/reporter-test.js

Changes:
* additional logic with the `debug` module
* safe `error.stack` creation

fix: more tolerant error handling for errors raised into reporter plugin methods

---

src/browser/provider/built-in/dedicated/chrome/cdp-client/index.ts
src/video-recorder/process.js

The main idea - call the `client.Page.screencastFrameAck` method for last saved frame only 1 time.

fix video recording in concurrency mode (closes #7218)

---

src/runner/browser-set.ts

Closes [#7188](https://github.com/DevExpress/testcafe/issues/7188).
Test on the farm will be very unstable due to high concurrency level (>= 7).

fix warning for high concurrency level (closes #7188)

---

src/video-recorder/process.js

[closes #7216]
Fix an error when running tests with video records on Unix systems. It throws the error that screencast files have invalid format data. 
1. Research the problem
2. Force input and output formats because sometimes `ffmpeg` recognize wrong formats and cannot read data.
https://github.com/DevExpress/testcafe/issues/7216

fix: forced stdin and stdout formats for ffmpeg

---

src/compiler/test-file/formats/raw.js
src/utils/raw-command-callsite-record.ts
test/functional/fixtures/api/raw/test-controller/test.js
test/functional/fixtures/api/raw/test-controller/testcafe-fixtures/hooks-test.testcafe

[closes #7089]
`actionId` for hooks in raw-tests has a prefix, that is why it is impossible to parse it as Integer and impossible to create a callsite. It needs to use `actionId` without parsing.
1. Add test for error in hooks
2. Fix using actionId
https://github.com/DevExpress/testcafe/issues/7089

fix: create correct raw-callsite for hooks 

---

package.json
src/runner/index.js
test/server/runner-test.js

Make testcafe compatible with TestCafe Dashboard Alpha

fix: `getReportUrl` method doesn't exist for testcafe-reporter-dashboard alpha version

---

test/server/runner-test.js

The previous token was ok, but it's better to generate a token on the fly. This way it's clear that we do not use a real production token.

release: get rid of pregenerated token

---

gulp/constants/functional-test-globs.js
src/browser/connection/gateway.ts
src/browser/connection/index.ts
src/browser/connection/service-routes.ts
src/browser/provider/built-in/dedicated/chrome/index.js
src/browser/provider/index.ts
src/client/browser/idle-page/index.html.mustache
src/client/browser/idle-page/index.js
src/client/browser/index.js
src/client/driver/driver.js
src/client/driver/iframe-driver.js
src/client/test-run/index.js.mustache
src/proxyless/cdp-utils.ts
src/proxyless/resource-injector.ts
src/runner/browser-job.ts
src/shared/types.d.ts
src/test-run/index.ts
test/functional/fixtures/api/es-next/cookies/test.js
test/functional/fixtures/api/es-next/disable-reloads/test.js
test/functional/fixtures/api/es-next/disable-reloads/testcafe-fixtures/helpers.js
test/functional/fixtures/api/es-next/request/test.js
test/functional/fixtures/api/es-next/take-screenshot/test.js
test/functional/fixtures/api/es-next/type/test.js
test/functional/fixtures/browser-provider/browser-reconnect/test.js
test/functional/fixtures/browser-provider/chrome-emulation/test.js
test/functional/fixtures/concurrency/test.js
test/functional/fixtures/ui/test.js
test/functional/utils/skip-in-proxyless.js
test/server/browser-connection-test.js

[Closes DevExpress/testcafe-private#19]
Changes:
* support file protocol in `proxyless` mode.
* support the `disablePageReloads` option in `proxyless` mode.
* move service routes to the separate file and use in necessary places.
* refactoring

Proxyless: support file protocol, 'disablePageReloads' option

---

src/utils/make-reg-exp.js
test/functional/fixtures/page-js-errors/test.js
test/functional/fixtures/page-js-errors/testcafe-fixtures/test-controller.js

RegExp parsed incorrectly when passing it via CLI or as a string argument. After parsing the string into source and flags, we pass the source to a function that escapes all characters associated with the RegExp. We should escape characters only if the user sets a non-regex value.
Do not escape chars in the string if it is a regular expression string.
[#7301](https://github.com/DevExpress/testcafe/issues/7301)

fix: SkipJsErrors RegExp parsed incorrectly if it is passed through CLI(closes #7301)

---

src/client/automation/visible-element-automation.ts
src/client/driver/command-executors/action-executor/index.ts
src/test-run/commands/options.d.ts
src/test-run/commands/options.js
test/client/fixtures/automation/click-test.js
test/functional/fixtures/api/es-next/click/pages/index.html
test/functional/fixtures/api/es-next/click/test.js
test/functional/fixtures/api/es-next/click/testcafe-fixtures/click-test.js
test/server/test-run-command-options-test.js

[closes #7309]
Click on the available point of the element.
1. Research ways to find uncovered and visible points of the element
2. Add tests
3. Add a searching available point of the element if the element is partly covered or hidden
4. Replace the default click offset with available
https://github.com/DevExpress/testcafe/issues/7309

feat: upgraded click mechanism on element if offset options isn't set and center isn't available

---

package.json

`npm audit` and some installation warnings are fixed in new `testcafe-reporter-dashboard` version

deps: update testcafe-reporter-dashboard v0.2.7

---

gulp/constants/functional-test-globs.js
package.json
src/browser/connection/gateway.ts
src/client/driver/driver.js
src/client/test-run/index.js.mustache
src/proxyless/request-hooks/event-provider.ts
src/proxyless/request-pipeline/index.ts
src/proxyless/utils/cdp.ts
src/proxyless/utils/headers.ts
src/test-run/index.ts
test/functional/fixtures/api/es-next/request-hooks/common/mock-routes.js
test/functional/fixtures/api/es-next/request-hooks/pages/request-logger/mocked-requests.html
test/functional/fixtures/api/es-next/request-hooks/test.js
test/functional/fixtures/api/es-next/request-hooks/testcafe-fixtures/request-logger/mocked-requests.js
test/functional/fixtures/api/es-next/roles/test.js

Changes:
* support redirects
* support `t.getBrowserConsoleMessages`
* support preflight requests
* handle failed requests

proxyless: more fixes

---

src/configuration/testcafe-configuration.ts
src/utils/is-localhost.ts
src/utils/localhost-names.ts
test/server/configuration-test.js

Set hostname to 'locahost' if experminetalProxyless mode is enabled to prevent block-mixed-content error.

Configuration: proxyless + hostname

---

src/notifications/add-rendered-warning.ts
src/test-run/index.ts
test/functional/fixtures/api/es-next/click/test.js

[closes #7386 ]
Add `callsite` to the warning with the overlapping element.
1. Add `callsite` to warning
2. Fix test
https://github.com/DevExpress/testcafe/issues/7386

feat: added `callsite` to the warning with the overlapping element

---

src/client/ui/status-bar/index.js
test/functional/fixtures/ui/pages/hiding.html
test/functional/fixtures/ui/test.js
test/functional/fixtures/ui/testcafe-fixtures/status-bar-test.js

When the document body is hidden (with `display: none`) during the page initialization, the status bar cannot correctly calculate its height. Later this calculated height is used to determine if the bar should hide or not when the mouse is moving. When the height is not calculated correctly, the bar will never hide.
The status bar height is recalculated on each mouse move.
Closes #7384.

fix: calculate the status bar reactively (closes #7384)

---

src/configuration/types.ts
ts-defs-src/test-api/test-controller.d.ts

TestController.customActions property doesn't have types definitions. 
https://github.com/DevExpress/testcafe/pull/7393

add types for TestController.customActions property

---

gulp/constants/functional-test-globs.js
package.json
src/client/driver/driver.js
src/client/driver/iframe-driver.js
src/client/driver/native-dialog-tracker/iframe.js
src/client/driver/native-dialog-tracker/index.js
src/client/driver/storage.js
src/client/test-run/iframe.js.mustache
src/proxyless/api-base.ts
src/proxyless/index.ts
src/proxyless/native-dialogs/index.ts
src/proxyless/request-pipeline/index.ts
src/proxyless/resource-injector.ts
src/proxyless/session-storage/index.ts
src/proxyless/types.ts
src/test-run/index.ts
test/functional/fixtures/api/es-next/native-dialogs-handling/test.js
test/functional/fixtures/api/es-next/native-dialogs-handling/testcafe-fixtures/native-dialogs-test.js

We solve two problems here:
1. The `beforeunload` dialog for some reason cannot be handled through CDP.
For some reason it starts working if we make some fake mouse action via CDP:
```JS
public async fixMissingBeforeUnloadHandling (): Promise<void> {
// NOTE: do fake mouse event to make cdp handle the `beforeunload` event.
// the `beforeunload` event is not handled without this click.
await this._client.Input.dispatchMouseEvent({
type:   'mousePressed',
...
});
}
```
2. Commands are still stored in the ContextStorage (which is sessionStorage actually). In proxy mode we use hammerhead and the sessionStorage is preserved between different domain page navigations. In the proxyless mode the sessionStorage is not preserved between different domain page navigations, so the …

proxyless handle native dialogs

---

src/client/core/utils/position.ts
test/functional/fixtures/regression/gh-7454/pages/index.html
test/functional/fixtures/regression/gh-7454/test.js
test/functional/fixtures/regression/gh-7454/testcafe-fixtures/index.js

[closed #7454]
Fix the possibility to click on SVG element inside `shadowRoot`. Skip visibility check for `shadowRoot`.
1. Add test
2. Update HH
3. Skip visibility check for shadowRoot
https://github.com/DevExpress/testcafe-hammerhead/pull/2837
https://github.com/DevExpress/testcafe/issues/7454

fix: fixed click on SVG inside `shadowRoot`

---

gulp/constants/functional-test-globs.js
src/api/test-controller/index.js
src/proxyless/request-pipeline/index.ts
src/proxyless/request-pipeline/resendAuthRequest.ts
src/proxyless/utils/cdp.ts
src/test-run/request/send.ts
test/functional/fixtures/api/es-next/auth/test.js

- only HTTP Basic auth
- Enter credentials only on failed request with 401 status (as in HH version)
**why?**
we cannot use [Fetch.authRequired](https://chromedevtools.github.io/devtools-protocol/tot/Fetch/#event-authRequired) event, since in this case Chrome will store credentials inside the user profile. We cannot reset credentials in this case without reopening browser.
Moreover, we cannot sent Authorization header on every request, since in this case other target websites can get access to the Authorization header + this leads to unexpected errors in browser (but I did not research these problems).
For making request, I use the method which was used in the Request API.
We handle the `requestPaused` event on the response stage. We check responseStatus. If responseStatus === 401, we are …

Basic Http-auth in proxyless mode

---

gulp/constants/functional-test-globs.js
package.json
src/custom-client-scripts/get-code.ts
src/custom-client-scripts/routing.ts
src/proxyless/request-hooks/event-factory/frame-navigated-event-based.ts
src/proxyless/request-hooks/event-factory/request-paused-event-based.ts
src/proxyless/request-hooks/event-provider.ts
src/proxyless/request-pipeline/context-info.ts
src/proxyless/request-pipeline/index.ts
src/proxyless/request-pipeline/test-run-bridge.ts
src/proxyless/resource-injector.ts
src/proxyless/types.ts
src/proxyless/utils/cdp.ts
src/runner/task/index.ts
src/test-run/index.ts

Changes:
* create request pipeline context for each request
* add two event factories for `RequestPausedEvent` and `FrameNavigatedEvent` events
* move all `TestRun` related code to the `TestRunBridge` class.

proxyless: support client scripts

---

gulp/constants/functional-test-globs.js
src/client/browser/index.js
src/client/driver/driver.js
src/proxyless/request-pipeline/index.ts
src/proxyless/resource-injector.ts
src/shared/utils/is-file-protocol.ts

1. Make the `isFileProtocol` condition less strong, since it's very common to write file URI with just two slashes like `file://blabla` instead of `file:///blabla`.
2. Add contextStorage restoring to the blank page to complete executing function (COMMAND_EXECUTING_FLAG)
3. Use CDP redirect in the navigateTo command in case of the proxyless mode and file protocol usage.

fix navigate to `about:blank/file://` page in the CDP mode

---

src/live/test-runner.js
src/runner/index.js
test/functional/fixtures/live/test.js
test/functional/fixtures/live/testcafe-fixtures/selector-inspector.js

The Selector Inspector could not evaluate the selector in live mode because the request handler on the server could not get the TestRun instance.
The reason was that the LiveModeTestRunner was calling `this._messageBus.clearListeners()` too late, and this resulted in the removal of the handler by which the BrowserConnection instance received the actual TestRun.
1. Run Selector Inspector in live mode.
2. Enter the selector in the appropriate input - the match indicator should show the correct number of elements.

fix(Selector Inspector): selector is parsed correctly in life mode

---

src/reporter/index.ts
src/runner/index.js
test/functional/fixtures/browser-provider/browser-reconnect/run-log-error-on-disconnect-test.js
test/functional/fixtures/browser-provider/browser-reconnect/test.js
test/server/reporter-test.js

Currently, reportTaskDone event is not raised if the browser has been disconnected. As a result, the reporters that do not write data on the fly, but create structures (html, xml, etc.) and write them to a file at the very end - do not create reports.
Raise reportTaskDone event if an error occurred that is not handled on the testrun level.

fix: raise reporter reportTaskDone event if browser has been disconnected

---

src/api/test-controller/execution-context.js
src/test-run/execute-js-expression/index.js
test/functional/fixtures/ui/test.js
test/functional/fixtures/ui/testcafe-fixtures/selector-inspector-test.js

In experimental debug mode, the TestRun instance has a `controller` field of `null`. Because of this, it was impossible to get the context in which the selector is executed.
1. Run Selector Inspector in experimental debug mode.
2. Enter selector in css format - the match indicator should show the correct number of elements.
3. Enter selector in TestCafe format - the match indicator should show the correct number of elements.

fix(Selector Inspector): selectors parsing in experimental debug mode

---

src/client/automation/playback/click/index.ts
src/client/automation/playback/press/get-key-info.ts
src/client/automation/playback/press/index.js
src/client/automation/playback/press/key-press-simulator.js
src/client/automation/visible-element-automation.ts
src/client/core/utils/array.js
src/client/driver/command-executors/action-executor/actions-initializer.ts
src/proxyless/client/input.ts
src/proxyless/client/key-press/utils.ts
src/proxyless/client/utils.ts
src/proxyless/types.ts
src/proxyless/utils/cdp.ts
test/client/fixtures/automation/key-press-simulation-test.js
test/functional/fixtures/api/es-next/press-key/common/utils.js
test/functional/fixtures/api/es-next/press-key/pages/various-keys.html
test/functional/fixtures/api/es-next/press-key/test.js
test/functional/fixtures/api/es-next/press-key/testcafe-fixtures/press-key-test.js
test/functional/fixtures/api/es-next/press-key/testcafe-fixtures/press-various-keys-test.js
test/functional/fixtures/multiple-windows/test.js

Changes:
* rename `ProxylessEventSimulator` -> `ProxylessInput`
* refactor the code related to getting pressed key information
* implement basic `keyPress` simulation using CDP API

proxyless: implement 'keyPress' action

---

gulp/constants/functional-test-globs.js
test/functional/fixtures/browser-provider/job-reporting/test.js

Job Reporting tests do not work in proxyless
Pass proxyless settings to the browserProvider mock

fix: job reporting tests in proxyless

---

.github/workflows/test-client-desktop.yml
.github/workflows/test-client-mobile.yml
.github/workflows/test-functional-docker.yml
.github/workflows/test-functional-local-chrome.yml
.github/workflows/test-functional-local-esm.yml
.github/workflows/test-functional-local-headed-browsers.yml
.github/workflows/test-functional-local-multiple-windows.yml
.github/workflows/test-functional-local-proxyless.yml
.github/workflows/test-functional-remote-macos.yml
.github/workflows/test-functional-remote-mobile.yml
.github/workflows/test-server-docker.yml
.github/workflows/test-server-lts.yml
Gulpfile.js
gulp/constants/functional-test-globs.js

We have only one task that runs tests in headed mode(multiple-windows). We need an additional task that can be used for tests that need to run in headed mode.
Add the additional task "headed-browsers"

add a separate headed browsers task for tests that cannot be run in headless mode

---

Gemfile

@AlexKamaev If I understand correctly, we don't need Jekyll anymore.
So I removed Gemfile to not deal with vulnerabilities in the redundant dependencies.

fix: vulnerabilities in Jekyll dependencies

---

src/client/automation/playback/press/index.js
src/client/automation/playback/type/index.js
src/proxyless/client/event-descriptor.ts
src/proxyless/client/input.ts

*Run a simple test 50 times.*
```js
import { ClientFunction } from 'testcafe';
fixture `TypeText speed up test suite`
.page('https://devexpress.github.io/testcafe/example/');
const prepareInput = ClientFunction(() => {
const input = document.getElementById('developer-name');
input.value = 'Peter Parker';
input.focus();
});
for (let i = 0; i < 50; i++) {
test('test', async t => {
await prepareInput();
await t.pressKey('ctrl+a delete p e t e r p a r k e r');
});
}
```
*Execution time (from fastest):*
* improved proxyless mode (this PR) - 41s.
* regular mode - 1m 01s. 
* current proxyless mode (master) - (1m 03s).

proxyless: speed up 'pressKey' action

---

gulp/constants/functional-test-globs.js
test/functional/fixtures/run-options/request-timeout/test.js

We have {pageRequestTimeout, ajaxRequestTimeout} props on different levels. CDP doesn't support request timeouts out of the box. 
skipInProxyless
We decided not to manually implement such functionality until it is supported in the CDP, in order not to complicate the code and not create potential bugs.

skip request timeout tests in proxyless until native timeout support is implemented

---

gulp/constants/functional-test-globs.js
test/functional/fixtures/run-options/disable-page-caching/test.js

This test suit tests localStorage synchronisation between windows. We didn't support multiple windows in CDP yet.
We need to turn on these tests and implement cache-control response header in proxyless once multiple windows are supported.
To implement this see the following:
https://github.com/DevExpress/testcafe-hammerhead/blob/master/src/request-pipeline/context/index.ts#L474
https://github.com/DevExpress/testcafe-hammerhead/blob/master/src/request-pipeline/header-transforms/index.ts#L98
skipInProxyless

skip disablePageCaching tests in proxyless until multiple windows support

---

src/client/automation/move.ts
src/client/automation/playback/click/index.ts
src/client/automation/playback/hover.js
src/client/automation/types.d.ts
src/client/automation/visible-element-automation.ts
src/client/driver/command-executors/action-executor/actions-initializer.ts
src/client/driver/command-executors/action-executor/index.ts
src/client/driver/driver-link/iframe/child.js
src/client/driver/driver-link/messages.js
src/client/driver/driver.js
src/client/driver/iframe-driver.js
src/proxyless/client/event-descriptor.ts
src/proxyless/client/input.ts
test/functional/fixtures/regression/gh-7557/pages/frame.html
test/functional/fixtures/regression/gh-7557/pages/index.html
test/functional/fixtures/regression/gh-7557/pages/nested-frame.html
test/functional/fixtures/regression/gh-7557/test.js
test/functional/fixtures/regression/gh-7557/testcafe-fixtures/index.js

calculate leftTopPoint on demand before making request to the cdp route
remove leftTopPoint passing from all other places
this PR fixes the #7557 issue only partially because, there is another problem with fixed header + iframes + proxyless, which is specific to the DevExtreme website

fix scroll position for cdp events

---

src/browser/connection/index.ts
src/reporter/index.ts
src/utils/get-browser.ts
src/utils/parse-user-agent.ts
test/functional/fixtures/api/es-next/browser-info/testcafe-fixtures/browser-info-test.js
test/functional/fixtures/api/es-next/take-screenshot/testcafe-fixtures/take-screenshot.js
test/server/reporter-test.js

https://github.com/DevExpress/testcafe-private/issues/147
Both the browserConnection.connectionInfo and browserConnection.userAgent are prettyUserAgent string. The only difference is in osInfo. In the case of userAgent it is calculated from the browser and usually it is incorrect. 
Calculate osInfo in userAgent using the provider getOSInfo method. 
https://github.com/DevExpress/testcafe-private/issues/147

fix: use calculated osInfo in userAgent

---

src/client/automation/playback/press/index.js
test/client/fixtures/automation/key-press-simulation-test.js
test/client/fixtures/automation/press-shortcuts-test.js

Old Firefox prevented backspace, tab, etc. keys via preventDefault([B254435](https://supportcenter.devexpress.com/internal/ticket/details/B254435)). 
Now this behavior is the same as in other modern browsers. So we don't need to prevent such key pressing.
Remove firefox check
#4115

fix: firefox keypress event doesn't work with backspace, tab, etc, if preventDefault called

---

src/test-run/request/create-request-options.ts
test/functional/fixtures/api/es-next/request/test.js
test/functional/fixtures/api/es-next/request/testcafe-fixtures/request-test.js
test/functional/site/api.js

Request action returns bad request if request method is specified in lowercase. The issue is only in native automation mode, because the request is not fully handled by hammerhead.  
Use uppercase
#7609

fix: request action returns bad request if request method is specified in lowercase in native automation(closes #7609)

---

Gulpfile.js
test/docker/Dockerfile
test/server/live-test.js

Changes:
* rewrite `Gulpfile.js` and `test/docker/Dockerfile` files to avoid the https://github.com/lovell/sharp/issues/3641 issue.
* fix server tests on docker.

fix docker server tests

---

src/custom-client-scripts/client-script.ts

FIPS doesn't allow for MD5, so replace it with SHA256.
Replaces MD5 usage with SHA256, in order to be FIPS/StateRAMP-compliant.
See the Purpose section.
https://github.com/DevExpress/testcafe/issues/5864

FIPS compliance (#5864)

---

src/configuration/interfaces.ts
ts-defs-src/test-api/skip-js-errors-options.d.ts

When a non-`Error` exception is thrown in the client, the object received by the `skipJsErrors` callback will not contain the `message` field. Adjust the typings to reflect this.
Closes issue #7627

fix: adjust typing of `SkipJsErrorsCallback`

---

src/cli/argument-parser/index.ts
src/cli/utils/should-move-option-to-end.ts
src/utils/get-options/boolean-or-object-option.ts
src/utils/get-options/quarantine.ts
src/utils/get-options/skip-js-errors.ts
test/server/cli-argument-parser-test.js

You cannot set the quarantine or skipJsErrors value to false via CLI. This should be allowed in order to have an ability to override the config file value

fix: quarantine and skipJsErrors CLI option value cannot be set to false(closes #7077)

---

src/browser/provider/built-in/dedicated/chrome/cdp-client/index.ts
src/browser/provider/built-in/dedicated/chrome/index.js

Fix a case when browser or electron window is opened with DevTools. Make it possible to inherit Chrome browser provider.

test: Fix for electron or studio tests with native automation mode

---

src/test-run/commands/actions.js
test/functional/fixtures/page-js-errors/testcafe-fixtures/test-controller.js

Calling skipJsErrors action without arguments should be equak .skipJsErrors(true), but actually it .skipJsErrors(false)
Specify default value for action and fix test
#7648

fix: skipJsErrors action without arguments doesn't skip errors(closes #7648)

---

src/client/automation/move.ts
src/native-automation/client/input.ts
test/functional/fixtures/api/es-next/hover/pages/index.html
test/functional/fixtures/api/es-next/hover/testcafe-fixtures/hover-test.js

The CDP 'mouseMoved' event does not have the "modifiers" option.
Add the 'modifiers' property to the 'mouseMoved' event.
https://github.com/DevExpress/testcafe/issues/7676

fix: Native Automation - Support modifier keys for the hover action (closes #7676)

---

src/native-automation/client/event-descriptor.ts
test/functional/fixtures/api/es-next/press-key/test.js
test/functional/fixtures/api/es-next/press-key/testcafe-fixtures/press-various-keys-test.js

For example, the `await t.pressKey('Ctrl+s')` action produces the 's' char in the input field. This behavior is incorrect.
Do not produce a char when a modified Ctrl or Alt is enabled.

fix: Native automation - Do not generate a char for hotkey combinations (closes #7680)

---

src/utils/parse-user-agent.ts
test/server/util-test.js

fix 'Incorrect browser alias is displayed while running Edge in headless mode' (close #7647)

---

src/native-automation/request-pipeline/index.ts
src/native-automation/request-pipeline/safe-api.ts
src/native-automation/request-pipeline/special-handlers.ts
src/native-automation/resource-injector.ts
src/native-automation/types.ts
src/native-automation/utils/cdp.ts

this should fix #7640 issue with request interception
- implement the `attachedToTarget` event for iframes
- call Fetch.enable for iframes
- add the `Runtime.runIfWaitingForDebugger` call just to make this thing work (playwright does the same trick).
- ignore typing errors for sessionId argument (https://github.com/cyrus-and/chrome-remote-interface/issues/534)
- I did not manage to create a test due to its complexity and unknown cause

attempt to fix missing requests (#7640)

---

test/docker/Dockerfile

The https://github.com/lovell/sharp/issues/3641 has been fixed. So, we can remove a hack for it.

remove hack for the docker server tests

---

src/test-run/commands/utils.js
test/server/helpers/base-test-run-mock.js
test/server/test-run-driver-task-queue-test.js

The t.addRequestHooks action crashes the TestCafe Studio recorder.
Specify that the addRequestHooks command should be executed only on the server side. This will make the recorder work.
https://github.com/DevExpress/testcafe-studio/issues/4350

fix: TestCafe Studio recorder stops working after a request hook is added

---

src/client/automation/playback/press/key-press-simulator.js
test/functional/fixtures/regression/gh-6969/pages/index.html
test/functional/fixtures/regression/gh-6969/test.js
test/functional/fixtures/regression/gh-6969/testcafe-fixtures/index.js

#6969 
We emulate the click event in some browsers on space pressing. Previously we didn't emulate it in Firefox. Now, we need to emulate it for Firefox as well.   
emulate click
#6969

fix: keyPress with space doesn't change the checkbox state(closes #6969)

---

src/reporter/index.ts
src/reporter/plugin-host.ts
test/functional/fixtures/reporter/test.js

Remove unused function
Remove context since it can break internal logic
https://github.com/DevExpress/testcafe-private/issues/196

refactor: remove unused code from onBeforeWrite hook and remove context binding

---

src/custom-client-scripts/client-script.ts
src/custom-client-scripts/get-url.ts
src/custom-client-scripts/routing.ts
src/runner/test-run-controller.ts
src/test-run/index.ts
test/server/custom-client-scripts-test.js

There are two issues:
* the cached tested web page can request the client script URL from a previous test run
* in parallel execution, the client script can be unregistered before its usage.
Solution - make a unique client script URL for each test run.

fix unstable client scripts test on remote browsers

---

src/client/driver/native-dialog-tracker/index.js
test/functional/fixtures/api/es-next/native-dialogs-handling/pages/index.html
test/functional/fixtures/api/es-next/native-dialogs-handling/pages/page-load.html
test/functional/fixtures/api/es-next/native-dialogs-handling/test.js
test/functional/fixtures/api/es-next/native-dialogs-handling/testcafe-fixtures/native-dialogs-test.js
test/functional/fixtures/api/es-next/native-dialogs-handling/testcafe-fixtures/page-load-test.js

The native print dialog cannot be handled and page hangs
Handle it as other dialogs
#2331 
```js
await t
.setNativeDialogHandler((type, text, url) => {
// type = 'print'
// text = undefined
// url  = pageUrl
})
```

fix: native print dialog is not handled(closes #2331)

---

.github/workflows/test-functional-local-native-automation.yml
src/native-automation/request-pipeline/index.ts
test/functional/fixtures/regression/gh-7640-iframe/pages/dynamic-oopif.html
test/functional/fixtures/regression/gh-7640-iframe/pages/frame.html
test/functional/fixtures/regression/gh-7640-iframe/test.js
test/functional/fixtures/regression/gh-7640-iframe/testcafe-fixtures/index.js
test/functional/fixtures/regression/gh-7770/pages/frame.html
test/functional/fixtures/regression/gh-7770/pages/index.html
test/functional/fixtures/regression/gh-7770/pages/worker.js
test/functional/fixtures/regression/gh-7770/test.js
test/functional/fixtures/regression/gh-7770/testcafe-fixtures/index.js

Tests fail now, because the Native Automation task is in non-graphic mode.
Tests should pass after merge.

add missing functional tests for #7770 and #7640

---

src/errors/runtime/index.js
test/server/configuration-test.js
test/server/data/configuration/module-not-found/config.js
test/server/data/configuration/module-not-found/module.js
test/server/runner-test.js

fix: unexpected error is thrown if config file imports non-existing module

---

package.json
src/api/request-hooks/request-logger.ts
src/native-automation/request-hooks/event-factory/request-paused-event-based.ts
src/native-automation/request-pipeline/index.ts
src/utils/lowercase-object-keys.ts
test/functional/fixtures/api/es-next/request-hooks/test.js
test/functional/fixtures/api/es-next/request-hooks/testcafe-fixtures/api/header-names.js
test/functional/fixtures/regression/gh-7640/testcafe-fixtures/index.js
test/functional/fixtures/regression/gh-7748/test.js
test/functional/fixtures/regression/gh-7764/testcafe-fixtures/index.js
test/functional/fixtures/regression/gh-7787/test.js

Changes:
* lowercase header names for all RequestHooks (not only for the `RequestLogger` class)
* move `statusCode` calculation for the custom respond function into `testcafe-hammerhead`
* add change tracking for `RequestOptions` class
Connected PR in the `testcafe-hammerhead` repository - https://github.com/DevExpress/testcafe-hammerhead/pull/2909.

native automation: header names should be lowercased

---

test/functional/assertion-helper.js
test/functional/fixtures/regression/gh-3456/test.js

At last time, the `3456` test became stable. However, I added additional logging to it.

chore: add more logging for the 3456 functional test

---

package.json

#7752 
Revert old linux binaries and add more logging
#7752 
https://github.com/DevExpress/testcafe-browser-tools/pull/229

fix: testcafe-browser-tools works incorrectly on linux(closes #7752)

---

src/reporter/index.ts
test/functional/fixtures/reporter/test.js
test/functional/fixtures/reporter/testcafe-fixtures/skipped-tests.js

#7731
Set the durationMs value to 0 for skipped tests
#7731

fix: durationMs value is incorrect for skipped tests(closes #7731)

---

.github/workflows/test-functional-remote-mobile.yml
.github/workflows/test-functional.yml

Increase BrowserStack runners count for remote tests
Currently, we use only 2 self-hosted runners to execute remote tests. These runners don't use all runners in the BrowserStack. Find out the way to use all BrowserStack runners.
https://github.com/DevExpress/testcafe-private/issues/202

github-actions: added running remote tests via the github host

---

package.json
test/functional/fixtures/regression/gh-7833/pages/index.html
test/functional/fixtures/regression/gh-7833/test.js
test/functional/fixtures/regression/gh-7833/testcafe-fixtures/index.js
test/functional/fixtures/regression/hammerhead/gh-2350/test.js
test/functional/fixtures/regression/hammerhead/gh-2350/testcafe-fixtures/iframes.js

Regression after disabling overrides(https://github.com/DevExpress/testcafe-hammerhead/pull/2877). 
Remove extra overridings from hammerhead(https://github.com/DevExpress/testcafe-hammerhead/pull/2919)
#7833 
https://github.com/DevExpress/testcafe-hammerhead/pull/2919

fix: title node textContent returns incorrect value in native automation mode(closes #7833)

---

src/native-automation/request-pipeline/index.ts
src/test-run/request/interfaces.ts
test/functional/fixtures/api/es-next/auth/test.js
test/functional/fixtures/api/es-next/auth/testcafe-fixtures/basic-auth-with-correct-credentials-test.js
test/functional/site/basic-auth-server.js

[closes #7852]
Fix regression on basic http authentication
1. Research issue. TestCafe in NA mode won't redirect if the authorization request returns redirection. It happens because headers from the response don't affect the result. 
2. Add a test.
3. Inherit headers from the response to the `fulfillInfo`

fix: fixed regression on basic http authentication

---

test/functional/fixtures/multiple-windows/test.js

[closes DevExpress/testcafe-private#206]
Stabilize multiple tests
Some times test `Should switch to parent and close window if the file was downloaded in separate window` isn't executed correctly in Firefox. Something happens on the client side and the server doesn't get the done result. It reproduces only on the GitHub host. 
I made the test run only in Chrome.

test: fixed blinking multiple test

---

test/functional/fixtures/regression/gh-856/test.js

Skip these flaky tests until we completely decide what should be done with them.

skip flaky gh-856 test

---

src/reporter/index.ts
src/runner/browser-job.ts
src/test-run/index.ts
test/functional/fixtures/concurrency/test.js
test/functional/fixtures/concurrency/testcafe-fixtures/duration-test.js

The duration is calculated incorrectly because it was calculated at the moment when testrun-done event is raised. We cannot change the order of the testCompletionQueue, but we can calculate the correct duration.
https://github.com/DevExpress/testcafe/issues/1816
Calculate the finish time at the moment when TestRun is finished instead of the moment when the corresponding event has been raised.
https://github.com/DevExpress/testcafe/issues/1816

fix: duration is calculated incorrectly in concurrency mode(closes #1816)

---

src/api/exportable-lib/index.js
src/cli/argument-parser/index.ts
src/index.js
src/reporter/index.ts
src/reporter/plugin-host.ts
src/utils/debug-loggers.ts
src/utils/get-testcafe-version.ts
test/functional/fixtures/reporter/test.js
test/server/compiler-test.js
test/server/data/test-suites/basic/testfile4.js
test/server/data/test-suites/typescript-defs/version.ts
test/server/parse-fixture-test.js
test/server/runner-test.js
ts-defs-src/helpers/test-api-exports.d.ts

Add version logging on TestCafe start.
export DEBUG="testcafe:version"
Add ability to check version in reporter: #6591 
Add logging
Add version export
```ts
// Any script file:
import {version} from 'testcafe';
console.log(version);
```
```js
//reporter method:
{
init (testcafeVersion) { 
this.write(`Using TestCafe v${testcafeVersion}`).newline()
}
}
```

feat: add testcafe version logging, add version export(closes #6591)

---

src/client/driver/native-dialog-tracker/index.js
test/functional/fixtures/api/es-next/native-dialogs-handling/pages/index.html
test/functional/fixtures/api/es-next/native-dialogs-handling/pages/page-load.html
test/functional/fixtures/api/es-next/native-dialogs-handling/test.js
test/functional/fixtures/api/es-next/native-dialogs-handling/testcafe-fixtures/native-dialogs-test.js
test/functional/fixtures/api/es-next/native-dialogs-handling/testcafe-fixtures/page-load-test.js

#3224
In some cases, you need to handle access geolocation dialog and provide a corresponding result.
The geolocation window can be invoked when the user call [window.navigator.geolocation.getCurrentPosition](https://developer.mozilla.org/en-US/docs/Web/API/Geolocation/getCurrentPosition) or watchPosition.
We cannot emulate watchPosition method because it invokes callbacks on changing user geolocation. So, this PR only handles getCurrentPosition method. When this method is called on the page for the first time, the Geolocation access dialog must be shown. All subsequent calls will lead to returning geolocation in the case when the user allowed access, or an error in the case when the user denied access. 
This handler allows you to return a geolocation or an error when calling …

feat: add possibility to handle access geolocation dialog(closes #3224)

---

package.json
test/functional/fixtures/api/es-next/iframe-switching/test.js
test/functional/fixtures/regression/gh-5992/pages/page1.html
test/functional/fixtures/regression/gh-5992/pages/page2.html
test/functional/fixtures/regression/gh-5992/test.js
test/functional/fixtures/regression/gh-5992/testcafe-fixtures/index.js

Connected [PR](https://github.com/DevExpress/testcafe-hammerhead/pull/2923) in the `testcafe-hammerhead` repository.

fix 'Local storage is cleared on every t.navigateTo in Safari'

---

src/client/driver/native-dialog-tracker/index.js
test/functional/fixtures/api/es-next/native-dialogs-handling/pages/geolocation-overrided.html
test/functional/fixtures/api/es-next/native-dialogs-handling/test.js
test/functional/fixtures/api/es-next/native-dialogs-handling/testcafe-fixtures/native-dialogs-test.js

If the user mocks the geolocation dialog via page/client-scripts/client-function we will override it with default native dialog handler. That will lead to unexpected behavior. 
This PR also handles the case when the user "promisified" the getCurrentPosition method which may lead to test hanging.
Do not override the getCurrentPosition method in case when it is already overridden.
https://github.com/DevExpress/testcafe/pull/7791

fix: support custom geolocation dialog mocks

---

package.json

Closes https://github.com/DevExpress/testcafe/issues/7918
Closes https://github.com/DevExpress/testcafe/issues/7918 so that more dependencies of testcafe have better defined licenses using SPDX identifiers (before this commit, the `stackframe` dependency has `SEE LICENSE IN LICENSE`, and after it has license: MIT)
Well, there's not much to explain. I just updated the dependency so the dependency chain has permissive licenses defined SPDX identifiers.
Closes https://github.com/DevExpress/testcafe/issues/7918

chore: update error-stack-parser to avoid licensing issues

---

Gulpfile.js
test/functional/fixtures/browser-provider/browser-reconnect/test.js

This test hangs on CI. Locally it works as expected. We need to temporarily skip.
skip test for safari

skip: should rais reportTaskDone handler if browser disconnects for safari

---

test/client/legacy-fixtures/api/click-test.js
test/client/legacy-fixtures/api/drag-test.js
test/client/legacy-fixtures/api/press-test.js
test/client/legacy-fixtures/api/select-test/index-test.js

refactor: removed IE and MS Edge Legacy leftovers from test\client\legacy-fixtures\api

---

test/client/fixtures/core/array-utils-test.js
test/client/fixtures/core/dom-utils-test.js
test/client/fixtures/driver/script-execution-barrier-test.js

refactor: removed IE and MS Edge Legacy leftovers from test\client\fixtures

---

src/errors/runtime/templates.js
src/errors/types.js
src/runner/bootstrapper.ts
test/functional/fixtures/regression/gh-7925/pages/index.html
test/functional/fixtures/regression/gh-7925/test.js
test/functional/fixtures/regression/gh-7925/testcafe-fixtures/index.js
test/server/bootstrapper-test.js

We decided to not support the `userProfile` option in Native Automation mode.
Native Automation mode clears all cookies and local storages between test runs. If we use `:userProfile` the Native Automation mode will clear all cookies in current user profile.

Browsers with "userProfile" option in Native Automation (closes #7925)

---

src/errors/runtime/templates.js
test/functional/fixtures/regression/gh-7925/test.js
test/server/bootstrapper-test.js

fix error message for `:userProfile`

---

test/functional/fixtures/browser-provider/browser-reconnect/test.js
test/functional/fixtures/browser-provider/custom-profile/test.js
test/functional/fixtures/browser-provider/job-reporting/test.js
test/functional/fixtures/driver/script-execution-barrier/pages/index.html
test/functional/fixtures/hammerhead/gh-2622/pages/iframe.html
test/functional/fixtures/hammerhead/gh-2622/pages/index.html
test/functional/fixtures/hammerhead/worker/test.js
test/functional/fixtures/page-js-errors/test.js
test/functional/fixtures/ui/test.js
test/functional/setup.js

refactor: removed IE leftovers from test\functional\fixtures

---

src/api/request-hooks/request-logger.ts
src/native-automation/request-hooks/event-factory/request-paused-event-based.ts
test/functional/fixtures/regression/gh-7977/pages/index.html
test/functional/fixtures/regression/gh-7977/test.js
test/functional/fixtures/regression/gh-7977/testcafe-fixtures/index.js
test/functional/fixtures/regression/gh-7977/testcafe-fixtures/requestCounter.js

Using only requestId for the key is not enough, since in concurrent tests the keys can be the same. I added the `sessionId` (testRunId) to the key.

should log concurrent requests (closes #7977)

---

.github/ISSUE_TEMPLATE.md
.github/ISSUE_TEMPLATE/bug_report.yaml
gulp/constants/client-test-settings.js

refactor: removed IE leftovers from .github and gulp/constants

---

src/client/core/barriers/page-unload-barrier.ts

refactor: removed IE leftovers from src\client\core\barriers

---

src/client/core/utils/array.js
src/client/core/utils/content-editable.js
src/client/core/utils/event-emitter.ts
src/client/core/utils/event.js

refactor: removed IE leftovers from src\client\core\utils (part 1)

---

src/browser/connection/index.ts
test/functional/fixtures/browser-provider/browser-reconnect/test.js
test/functional/fixtures/browser-provider/browser-reconnect/testcafe-fixtures/index-test.js

If development mode turned on, the heartbeat continues to work and _waitHeartBeat doesn't assign promises responsible for reloading. 
HeartBeat responsible for fast stopping application when pressed ctr + c

disabled restart browser in devmode

---

src/compiler/test-file/formats/typescript/compiler.ts

TypeScript compilation fails when using Yarn PnP
Added file's path normalization for typescript test.
Couldn't add test due to OS specificity
[7412](https://github.com/DevExpress/testcafe/issues/7412)

update typescript compiler

---

.github/workflows/test-client-mobile.yml
.github/workflows/test-client.yml
gulp/constants/client-test-settings.js

The Test Client (Mobile) tests task fails for android
Updated workflow and client test settings
Last settings for mobile browser on android fails on Saucelabs server. This has been confirmed by Saucelab support.
For solve took settings from testcafe-hammerhead and added variable in workflow.
[issue 329](https://github.com/DevExpress/testcafe-private/issues/329)

fix The Test Client (Mobile)

---

src/client/ui/selector-inspector-panel/descriptors.js
src/client/ui/selector-inspector-panel/hide-button.js
src/client/ui/styles.less
test/functional/fixtures/ui/utils/selector-inspector.js

`input` tag with type button used for Hide Picker button rendering

fix: `Hide Picker` button fixed for Mac

---

src/runner/browser-job.ts
test/functional/fixtures/regression/gh-8087/pages/index.html
test/functional/fixtures/regression/gh-8087/test.js
test/functional/fixtures/regression/gh-8087/testcafe-fixtures/index.js

Disabling concurrency with quarantine mode led to unexpected behavior.
Updated method `_onTestRunRestart` in browser job.
Previously, we added a quarantine test to the general queue. Now we change the queue, if before this the test was executed in a fixture with the `disable concurrency` flag.
#8087

fix: disableConcurrency with quarantine mode (closes #8087)

---

src/client/automation/playback/upload.js
src/client/driver/command-executors/action-executor/actions-initializer.ts
test/functional/fixtures/api/es-next/upload/pages/index.html
test/functional/fixtures/api/es-next/upload/test.js
test/functional/fixtures/api/es-next/upload/testcafe-fixtures/upload-test.js

UploadAutomation is fixed in order to upload required inputs in Native Automation mode. 
Remove the required attribute from the file input before uploading. 
Initialize the addInternalEventAfterListener on inputs form 'submit' event for returning the required attributes back.
closes https://github.com/DevExpress/testcafe/issues/8079

fix: upload files with required inputs in native automation

---

src/runner/fixture-hook-controller.ts
src/runner/test-run-controller.ts
test/functional/fixtures/concurrency/test.js
test/functional/fixtures/concurrency/testcafe-fixtures/concurrent-fixture-before-test.js
test/server/capturer-test.js

Fixed the bug when the concurrent tests did not wait until the finish of the fixture and global before hook.
Updated the method runFixtureBeforeHookIfNecessary in src/runner/fixture-hook-controller.ts. Now we store the promises of hooks in item from _getFixtureMapItem and await them in concurrent tests.
closes https://github.com/DevExpress/testcafe/issues/6999

fix: In concurrent test run fixed awaiting of fixture before hook

---

package.json
test/functional/fixtures/regression/gh-8091/imports/script.js
test/functional/fixtures/regression/gh-8091/test.js
test/functional/fixtures/regression/gh-8091/testcafe-fixtures/index.ts

Error in compilation typescript test files.
Set Babel dependancies to a 7.23.3 version
Closes #8091

build: Set @babel/plugin-transform-runtime to a 7.23.3 version

---

.github/workflows/test-client.yml
src/cli/argument-parser/index.ts
src/configuration/option-names.ts
src/configuration/screenshot-option-names.ts
src/configuration/types.ts
src/runner/index.js
src/runner/task/index.ts
src/screenshots/index.js
src/utils/path-pattern.js
test/functional/fixtures/screenshots-on-fails/test.js
test/functional/setup.js
test/server/runner-test.js

- added support new configuration screenshot option
[issue 7014](https://github.com/DevExpress/testcafe/issues/7014)

feat: Added path-pattern-on-fails for screenshots (closes #7014)

---

src/api/skip-js-errors/index.ts
src/api/test-controller/index.js
src/client-functions/client-function-builder.js
src/client-functions/selectors/selector-builder.js
src/client/driver/command-executors/action-executor/elements-retriever.ts
src/client/driver/command-executors/client-functions/client-function-executor.ts
src/client/driver/command-executors/client-functions/selector-executor/index.ts
src/client/driver/driver.js
src/client/ui/selector-inspector-panel/index.js
src/client/ui/selector-inspector-panel/selector-input-container.js
src/client/ui/selector-inspector-panel/utils/cast-array.js
src/client/ui/selector-inspector-panel/utils/get-elements-by-selector.js
src/reporter/command/command-formatter.ts
src/shared/types.d.ts
src/test-run/bookmark.ts
src/test-run/commands/actions.d.ts
src/test-run/commands/actions.js
src/test-run/commands/base.d.ts
src/test-run/commands/execute-client-function.d.ts
src/test-run/commands/execute-client-function.js
src/test-run/commands/observation.d.ts
src/test-run/commands/observation.js
src/test-run/commands/service.js
src/test-run/commands/validations/initializers.js
src/test-run/index.ts
test/functional/fixtures/ui/test.js
test/functional/fixtures/ui/testcafe-fixtures/selector-inspector-test.js
test/server/compiler-test.js
test/server/data/test-controller-reporter-expected/index.js

The purpose of this PR is to allow passing selector to a t.debug call. Something like this t.debug(Selector). Then the selector will be shown in debug mode and highlighted.
So overall, the main goal was to pass the selector argument from server-side debug call to client-side selector-input-contaner. 
1) src/test-run/index.ts Inside this file we have _internalExecuteCommand method. There is debug command type handling block. Inside of it we call _enqueueSetBreakpointCommand to which we pass command.selector as a second argument. This way we transfer Selector from debugCommand to breakpointCommand.
2) After the breakpointCommand is added to driverTaskQueue we can work with it on client-side.
3) On client-side we pass selector to _debugSelector  method of SelectorInputContainer class.
4) In …

feat: debug with selector option added

---

src/browser/provider/built-in/dedicated/chrome/index.js
test/functional/config.js
test/functional/fixtures/regression/gh-8117/pages/index.html
test/functional/fixtures/regression/gh-8117/test.js
test/functional/fixtures/regression/gh-8117/testcafe-fixtures/maximize.js
test/functional/fixtures/regression/gh-8117/testcafe-fixtures/resize.js

fix: resize and maximize window with `disableMultipleWindows` option in NA mode

---

package-lock.json
package.json

Remove vulnerable lodash pick that was used by gulp-less version 4.
Updated version of gulp-less from version 4 to 5
https://github.com/DevExpress/testcafe/security/dependabot/24

chore: update gulp-less from v4 to v5

---

Gulpfile.js
package-lock.json
package.json

Removed npm-auditor package and the corresponding gulp task in order to get rid of ip package vulnerability.
Deleted gulp task and npm uninstall npm-auditor package
https://github.com/orgs/DevExpress/projects/11/views/1?pane=issue&itemId=52847042

chores: removed npm-auditor package and the corresponding gulp task

---

src/compiler/compilers.js
src/compiler/esm-loader.ts
src/compiler/index.js

Starting from Node version 20 Hooks like `load` run in a separate thread, isolated from the main thread.
https://nodejs.org/docs/latest-v20.x/api/module.html#hooks.
Our current implementation relies on main thread in `getTestFileCompilers`.
Because the `load` hook is now running in a separate thread the `testFileCompilers` was never initialized before, and `getTestFileCompilers` calls `initTestFileCompilers` with no parameters. That is why the `esm` flag is lost in Node version 20 and above.
Pass the `esm` flag from `load` hook to getTestFileCompilers` in order to initialize the correct compilers.
The test 'Should import ESM without errors in ESM mode' also works for this fix in node 20 and above.
closes [#8132](https://github.com/DevExpress/testcafe/issues/8132)

fix: esm loader fix

---

Gulpfile.js
src/browser/provider/built-in/dedicated/chrome/build-chrome-args.js
src/browser/provider/built-in/dedicated/chrome/local-chrome.js
test/functional/fixtures/api/es-next/maximize-window/testcafe-fixtures/maximize-window-test.js
test/functional/fixtures/api/es-next/request-hooks/common/mock-routes.js
test/functional/fixtures/api/es-next/request-hooks/testcafe-fixtures/request-mock/basic.js
test/functional/fixtures/api/es-next/request-hooks/testcafe-fixtures/request-mock/respond-error.js
test/functional/fixtures/regression/gh-3456/test.js

closes https://github.com/DevExpress/testcafe-private/issues/225

testing test-functional-docker workflow

---

src/api/test-controller/index.js
src/browser/connection/index.ts
src/browser/provider/built-in/dedicated/chrome/index.js
src/browser/provider/index.ts
src/browser/provider/plugin-host.js
src/test-run/commands/actions.d.ts
src/test-run/commands/actions.js
src/test-run/commands/type.js
src/test-run/index.ts
test/functional/fixtures/api/es-next/get-current-cdp-session/pages/child.html
test/functional/fixtures/api/es-next/get-current-cdp-session/pages/index.html
test/functional/fixtures/api/es-next/get-current-cdp-session/test.js
test/functional/fixtures/api/es-next/get-current-cdp-session/testcafe-fixtures/index.js
test/server/data/test-controller-reporter-expected/index.js
test/server/test-controller-events-test.js
ts-defs-src/test-api/test-controller.d.ts

closes Devexpress/testcafe-private/issues/479

feat: add method which return current cdp

---

src/screenshots/constants.js
test/server/crop-test.js

#8154 addresses the issue, where screenshots are not cropped on macOS (14) Safari.
The problem is, that the screenshot mark can not be found.
This is because part of the mark is not visible because of the rounded corners in macOS.
The solution is to increase `MARK_RIGHT_MARGIN` in `src/screenshots/constants.js`.
I found that `25` is the lowest value that works for all resolutions I was able to test.
* In order for the tests to work I parametrized the tests to depend on `MARK_RIGHT_MARGIN`.
* ~~I enabled the screenshot-tests that were skipped in the safari browser~~
* ~~fix tests~~
* ~~retina aware~~
* ~~color-profile aware~~
#8154

Fix Screenshots in macOS Safari - adapt to rounded corners

---

.publishrc
package-lock.json
package.json

Version **5.0.2** of babel-plugin-module-resolver has glob version **^9.3.3** with vulnerability. 
By fixing to version **5.0.0** babel-plugin-module-resolver we avoid vulnerability with glob version **^8.0.3**.
[Link to discussion](https://teams.microsoft.com/l/message/19:5eb4e942f0f946188ab14b3d8bf960f3@thread.skype/1717393430400?tenantId=e4d60396-9352-4ae8-b84c-e69244584fa4&groupId=f74b7d18-34a4-4c78-b7d5-b56e55ce3236&parentMessageId=1717393430400&teamName=Teams%20Collaborations&channelName=TestCafe&createdTime=1717393430400)

fix babel-plugin-module-resolver version to 5.0.0

---

bin/testcafe-with-v8-flag-filter.js
src/compiler/test-file/api-based.js
ts-defs-src/runner-api/options.d.ts

close https://github.com/DevExpress/testcafe/issues/8213

add: option to run esm from runner and config file

---

src/browser/provider/built-in/dedicated/chrome/build-chrome-args.js

fix: add --disable-search-engine-choice-screen to default arguments

---

src/test-run/index.ts
test/functional/fixtures/api/es-next/request-hooks/test.js
test/functional/fixtures/api/es-next/request-hooks/testcafe-fixtures/api/8229.js

Request hooks are initialized even though the test is skipped
check if test is skipped before initialization
closes https://github.com/DevExpress/testcafe/issues/8229

fix: skip request hooks initialization for skiped tests

---

ts-defs-src/test-api/test-controller.d.ts

feat: change ts-defs

---

src/browser/provider/built-in/dedicated/chrome/cdp-client/utils.ts

When requesting active tabs in Chrome 130.0.6723.6, a chrome-extension tab is included in the list. A CDP client is created based on this tab, but the tab gets closed, which results in the error.
Excluded tabs with `^chrome-extension` URLs from the list of tabs.
closes #8286

fix: The 'WebSocket connection closed' error on Chrome 130

---

package-lock.json
package.json

closes https://github.com/DevExpress/testcafe/issues/8221
hammerhead PR: https://github.com/DevExpress/testcafe-hammerhead/pull/3026

bump: update testcafe-hammerhead to 31.7.4

---

src/client/automation/playback/drag/base.js
src/client/automation/playback/drag/to-element.js
test/functional/fixtures/regression/gh-8250/pages/index.html
test/functional/fixtures/regression/gh-8250/test.js
test/functional/fixtures/regression/gh-8250/testcafe-fixtures/index.js

closes https://github.com/DevExpress/testcafe/issues/8250

fix: drag and click

---

src/browser/provider/built-in/dedicated/chrome/cdp-client/index.ts
test/functional/fixtures/api/es-next/resize-window/test.js
test/functional/fixtures/api/es-next/resize-window/testcafe-fixtures/resize-window-test.js

Window did not maximize properly after resizing. 
Remove redundant use of _setDeviceMetricsOverride in resize window using CDP.
closes https://github.com/DevExpress/testcafe/issues/8360

Fix maximizeWindow after resize

---

.github/workflows/test-functional.yml

https://github.com/actions/upload-artifact?tab=readme-ov-file#breaking-changes
v4 upload-artifact breaks with same named Artifact

fix: workflow artifact upload updated to have different names

---

src/errors/test-run/templates.js
test/functional/fixtures/page-error/test.js
test/server/data/expected-test-run-errors/page-load-error

closes https://github.com/DevExpress/testcafe-private/issues/548

update: pageLoadError url updated
